// ===== deck-guides.js =====
'use strict';
var MTG = globalThis.MTG || (globalThis.MTG = {});
(function () {
  MTG.DECK_GUIDE_ROUTES = Object.freeze({
    goWide: [
      { label: 'Early game', title: 'Seed the board', text: 'Develop mana and cheap bodies. Your small pieces matter more as a group than alone.' },
      { label: 'Midgame', title: 'Multiply the army', text: 'Layer token makers and payoffs, but keep enough material back to recover from a wipe.' },
      { label: 'Endgame', title: 'Turn width into damage', text: 'Choose the turn where one attack or sacrifice chain converts the whole board into a finish.' },
    ],
    artifacts: [
      { label: 'Early game', title: 'Assemble the engine', text: 'Play mana and low-cost artifacts first so every later synergy arrives ahead of curve.' },
      { label: 'Midgame', title: 'Stack the payoffs', text: 'Add counters, copies, or card draw while protecting the piece that makes the engine compound.' },
      { label: 'Endgame', title: 'Convert the machine', text: 'Turn accumulated artifacts and counters into a lethal board, a huge spell, or an alternate win.' },
    ],
    spells: [
      { label: 'Early game', title: 'Prepare the turn', text: 'Develop mana and a value creature before spending the cheap spells that make the deck snowball.' },
      { label: 'Midgame', title: 'Chain with purpose', text: 'Sequence draw, interaction, and copy effects so each spell improves the next one.' },
      { label: 'Endgame', title: 'Explode in one window', text: 'Wait for an opening, then turn stored cards and mana into a decisive multi-spell turn.' },
    ],
    groupSlug: [
      { label: 'Early game', title: 'Install the taxes', text: 'Deploy repeatable life-loss pieces before opponents can freely build their engines.' },
      { label: 'Midgame', title: 'Squeeze every action', text: 'Keep the board moving while making draws, spells, and attacks cost the table life.' },
      { label: 'Endgame', title: 'Close the furnace', text: 'Use a burst of damage or a punisher payoff before the whole table can turn on you.' },
    ],
    defenders: [
      { label: 'Early game', title: 'Fortify and ramp', text: 'Play high-toughness defenders and mana creatures until attacking you becomes inefficient.' },
      { label: 'Midgame', title: 'Turn the corner', text: 'Land the effects that let toughness become pressure while your walls still guard your life total.' },
      { label: 'Endgame', title: 'Crush behind the shield', text: 'Commit to combat once your defensive board becomes an oversized attacking force.' },
    ],
    politics: [
      { label: 'Early game', title: 'Develop quietly', text: 'Build resources without looking like the player the rest of the table must stop first.' },
      { label: 'Midgame', title: 'Redirect the table', text: 'Use votes, incentives, and selective interaction to point the strongest boards at one another.' },
      { label: 'Endgame', title: 'Cash in the opening', text: 'Break parity when opponents are depleted and convert the political advantage into a win.' },
    ],
    counters: [
      { label: 'Early game', title: 'Plant the first counters', text: 'Start with mana and creatures that reward every future counter placement.' },
      { label: 'Midgame', title: 'Scale the board', text: 'Proliferate or spread counters across several threats so one removal spell cannot reset you.' },
      { label: 'Endgame', title: 'Make one huge swing', text: 'Use evasion, trample, or a counter payoff to turn stored growth into lethal combat.' },
    ],
    graveyard: [
      { label: 'Early game', title: 'Stock the graveyard', text: 'Mill and trade creatures while developing mana. The graveyard is a second hand, not a loss.' },
      { label: 'Midgame', title: 'Reuse the best pieces', text: 'Reanimate value creatures and recur answers while opponents spend real cards to keep up.' },
      { label: 'Endgame', title: 'Rebuild at full scale', text: 'Resolve a mass-return or graveyard payoff that turns all the setup into one overwhelming board.' },
    ],
    lands: [
      { label: 'Early game', title: 'Put lands to work', text: 'Ramp, mill, and sacrifice lands only when the exchange advances both mana and graveyard setup.' },
      { label: 'Midgame', title: 'Profit from every move', text: 'Use landfall and sacrifice payoffs so normal development also makes cards, tokens, or damage.' },
      { label: 'Endgame', title: 'Bring the world back', text: 'Return a full graveyard of lands and let the resulting triggers bury the table in value.' },
    ],
    equipment: [
      { label: 'Early game', title: 'Find the weapons', text: 'Develop mana, cheap Equipment, and creatures that lower equip costs or reward modifications.' },
      { label: 'Midgame', title: 'Connect safely', text: 'Move the best Equipment to the attacker most likely to survive and generate another advantage.' },
      { label: 'Endgame', title: 'Break the limit', text: 'Stack protection and power on one decisive threat, then finish with combat or an Equipment payoff.' },
    ],
    typal: [
      { label: 'Early game', title: 'Recruit the core', text: 'Curve out with mana and the creatures that make every later member of the team stronger.' },
      { label: 'Midgame', title: 'Layer team synergies', text: 'Add lords, engines, and protection while spreading value across more than one permanent.' },
      { label: 'Endgame', title: 'Rally the table', text: 'Use the commander or a finisher to turn the assembled team into a decisive attack.' },
    ],
    bigCreatures: [
      { label: 'Early game', title: 'Ramp without drifting', text: 'Prioritize mana development and cost reduction. The deck starts when its large threats arrive on time.' },
      { label: 'Midgame', title: 'Deploy must-answer threats', text: 'Present one powerful creature at a time and keep the next threat ready if the board is cleared.' },
      { label: 'Endgame', title: 'Own the combat step', text: 'Use haste, evasion, and attack triggers to end the game before opponents can stabilize.' },
    ],
  });

  MTG.DECK_GUIDES = Object.freeze({
    'Abzan Armor': {
      route: 'defenders', pace: 'FORTRESS MIDRANGE', complexity: 'Approachable',
      theme: 'A living fortress where walls stop early attacks, then hit with their toughness.',
      plan: 'Build an untouchable defensive board, use defenders as mana and cards, then let Felothar turn toughness into combat power. The deck wins by changing roles faster than the table expects.',
      mulligan: 'Keep two or three lands, an early defender, and either ramp or a card-advantage piece.',
      tip: 'Do not expose every payoff at once. A few walls already discourage attacks; save the card that turns them aggressive for the turn you can use it.',
      keys: ['Betor, Ancestor\'s Voice', 'Baldin, Century Herdmaster', 'Blight Pile'],
    },
    'Animated Army': {
      route: 'bigCreatures', pace: 'STOMPY MIDRANGE', complexity: 'Approachable',
      theme: 'Bello wakes up harmless artifacts and enchantments as a charging 4/4 army.',
      plan: 'Ramp into mana value four artifacts and enchantments, then use Bello to animate them with haste. Your support pieces become attackers without giving up their normal engine text.',
      mulligan: 'Keep reliable green mana, one ramp spell, and at least one four-mana permanent for Bello to animate.',
      tip: 'Cast Bello after the engine pieces when possible. That gives opponents less time to remove him before the animated army attacks.',
      keys: ['Kodama of the East Tree', 'Etali, Primal Storm', 'Ghalta, Primal Hunger'],
    },
    'Avengers Assemble': {
      route: 'typal', pace: 'HEROIC MIDRANGE', complexity: 'Intermediate',
      theme: 'A Hero team-up deck that rewards assembling named threats instead of one lone attacker.',
      plan: 'Curve out with Heroes, grow the team through shared counters and triggers, and use Captain America to turn a broad cast into focused pressure. The deck is strongest when each new Hero improves the entire battlefield.',
      mulligan: 'Keep three colors of mana or fixing, an early Hero, and a payoff that rewards the team entering or attacking.',
      tip: 'Spread counters and Equipment before loading one creature. Your best turns come from preserving several relevant Heroes through removal.',
      keys: ['Iron Man, Armored Avenger', 'Captain Marvel, Apex Avenger', 'Falcon and Redwing'],
    },
    'Blight Curse': {
      route: 'counters', pace: 'ATTRITION CONTROL', complexity: 'Advanced',
      theme: 'Wither and -1/-1 counters shrink opposing boards while your own payoffs multiply.',
      plan: 'Place counters surgically, profit from creatures dying or being weakened, and let Auntie Ool keep the curse moving. The deck wins by turning removal into creatures, cards, and a board opponents cannot rebuild through.',
      mulligan: 'Keep black and green mana, an early counter source, and one payoff such as Hapatra or a death-value engine.',
      tip: 'A single counter can disable utility creatures and unlock your synergies. Save mass counter placement for the board that actually threatens you.',
      keys: ['Hapatra, Vizier of Poisons', 'Carnifex Demon', 'Necroskitter'],
    },
    'Counter Intelligence': {
      route: 'artifacts', pace: 'ARTIFACT ENGINE', complexity: 'Advanced',
      theme: 'A spacecraft command center that charges artifacts until ordinary pieces become win conditions.',
      plan: 'Develop cheap artifacts, place and proliferate counters, then use Inspirit to station a growing engine. You can win through a giant artifact board or by protecting an alternate-win counter piece.',
      mulligan: 'Keep three lands or two plus a mana rock, a cheap artifact, and one way to add or multiply counters.',
      tip: 'Count the counters you can create before choosing a line. Proliferate is strongest after several different permanents are already charged.',
      keys: ['Coretapper', 'Deepglow Skate', 'Darksteel Reactor'],
    },
    'Deep Clue Sea': {
      route: 'artifacts', pace: 'VALUE ENGINE', complexity: 'Advanced',
      theme: 'Every investigation becomes evidence, life, cards, and eventually a tidal wave of tokens.',
      plan: 'Make Clues early, multiply them with token doublers, and crack them when the draw also triggers another payoff. Morska turns patient investigation into a huge, evasive finisher.',
      mulligan: 'Keep fixing, an investigate source, and either a token multiplier or a payoff for drawing the second card.',
      tip: 'Uncracked Clues are stored choices. Do not cash them all in until the extra draws, token copies, or life gain matter.',
      keys: ['Academy Manufactor', 'Adrix and Nev, Twincasters', 'Esix, Fractal Bloom'],
    },
    'Doom Prevails': {
      route: 'graveyard', pace: 'VILLAIN CONTROL', complexity: 'Advanced',
      theme: 'Doctor Doom turns a cast of scheming Villains into connive, theft, and graveyard leverage.',
      plan: 'Loot away cards that are useful from the graveyard, disrupt the strongest rival, and use Villain triggers to keep resources flowing. Doom rewards precise sequencing more than raw speed.',
      mulligan: 'Keep blue, black, and red access, an early Villain, and either draw/connive or interaction.',
      tip: 'Choose what to discard as carefully as what to cast. Many of your best turns begin with placing the right card in the graveyard.',
      keys: ['Kang, Temporal Tyrant', 'Baron Strucker, HYDRA Overlord', 'Living Laser'],
    },
    'Elven Council': {
      route: 'politics', pace: 'POLITICAL VALUE', complexity: 'Intermediate',
      theme: 'An Elf council where public votes produce cards, creatures, and shifting alliances.',
      plan: 'Develop Elf mana, invite votes that are good for you in either outcome, and use the table\'s decisions to grow Galadriel\'s board. Your strongest position often looks helpful until it becomes lethal.',
      mulligan: 'Keep green mana, a one- or two-mana Elf, and a card that creates or rewards a council vote.',
      tip: 'Read what each opponent needs before calling the vote. The same options produce very different politics depending on who is behind.',
      keys: ['Elrond of the White Council', 'Erestor of the Council', 'Elvish Warmaster'],
    },
    'Endless Punishment': {
      route: 'groupSlug', pace: 'PUNISHER PRESSURE', complexity: 'Intermediate',
      theme: 'A haunted pressure cooker that makes every normal game action hurt.',
      plan: 'Install repeatable life-loss pieces, keep everyone playing into them, and grow Valgavoth from the damage. You are the clock, so finish before three opponents can combine their answers.',
      mulligan: 'Keep black and red mana, an early punisher permanent, and a draw or removal spell.',
      tip: 'Avoid dealing equal damage for no gain. Point interaction at the player who can remove your engine or race your clock.',
      keys: ['Blood Artist', 'Braids, Arisen Nightmare', 'Kaervek the Merciless'],
    },
    'Family Matters': {
      route: 'goWide', pace: 'AIRBORNE TOKENS', complexity: 'Intermediate',
      theme: 'Zinnia gives creatures offspring, creating smaller copies with the same useful abilities.',
      plan: 'Cast creatures whose enter-the-battlefield text is worth copying, pay offspring when the curve allows it, and fill the skies with value. The deck turns one good creature into two engines or two attackers.',
      mulligan: 'Keep all three colors or fixing, an early creature, and one creature whose ability is worth copying later.',
      tip: 'Offspring is optional. Skip the extra cost when it delays Zinnia or a more important engine, then double the premium creature later.',
      keys: ['Cloudblazer', 'Combat Celebrant', 'Inferno Titan'],
    },
    'Mardu Surge': {
      route: 'goWide', pace: 'AGGRESSIVE TOKENS', complexity: 'Intermediate',
      theme: 'Zurgo leads fresh waves of attackers that keep generating value as combat spreads around the table.',
      plan: 'Build token producers, attack where blocks are weakest, and multiply attack triggers across different defenders. The deck wants repeated profitable combats, not one reckless all-in swing.',
      mulligan: 'Keep three colors or strong fixing, an early token maker, and a payoff that rewards attacking with a team.',
      tip: 'Assign each attacker deliberately. Splitting combat can trigger more effects and deny one defender the chance to block everything.',
      keys: ['Adeline, Resplendent Cathar', 'Hero of Bladehold', 'Grenzo, Havoc Raiser'],
    },
    'Most Wanted': {
      route: 'politics', pace: 'TREASURE HEIST', complexity: 'Intermediate',
      theme: 'Olivia\'s Outlaws rob the open player, stockpile Treasure, and spend it on the next heist.',
      plan: 'Connect with evasive Outlaws, turn combat into Treasure, and use that burst of mana for theft or a powerful follow-up. Politics helps keep a safe target available without becoming passive.',
      mulligan: 'Keep Mardu fixing, a cheap evasive Outlaw, and either a Treasure payoff or interaction.',
      tip: 'Treasure is tempo, not decoration. Spend it when it creates another hit, steals the best permanent, or protects your lead.',
      keys: ['Academy Manufactor', 'Captain Lannery Storm', 'Breena, the Demagogue'],
    },
    'Prismari Artistry': {
      route: 'spells', pace: 'BIG-SPELL ENGINE', complexity: 'Advanced',
      theme: 'Prismari turns expressive instants and sorceries into copies, mana, and enormous Elementals.',
      plan: 'Build a creature-based spell engine, bank Treasures and cards, then cast and copy one spectacular spell. Rootha can rebuy the exact spell that makes the turn worth staging.',
      mulligan: 'Keep blue and red mana, a ramp or cost-reduction piece, and one spell-payoff creature.',
      tip: 'The largest spell is not always the best spell. Count every copy trigger and leave mana for the decision that protects the chain.',
      keys: ['Archmage Emeritus', 'Goldspan Dragon', 'Manaform Hellkite'],
    },
    'Quick Draw': {
      route: 'spells', pace: 'FAST SPELLSLINGER', complexity: 'Advanced',
      theme: 'Stella Lee rewards the second and third spell, turning cheap cantrips into explosive copy turns.',
      plan: 'Develop a payoff creature, use cheap spells to cross Stella\'s thresholds, and copy the spell that matters most. Patience turns a hand of small effects into one oversized turn.',
      mulligan: 'Keep two or three lands, one mana reducer or payoff creature, and at least two cheap spells.',
      tip: 'Sequence from least important to most important. Your copied spell should be the payoff, not the cantrip used to unlock it.',
      keys: ['Archmage Emeritus', 'Storm-Kiln Artist', 'Niv-Mizzet, Parun'],
    },
    'Squirreled Away': {
      route: 'goWide', pace: 'TOKEN ENGINE', complexity: 'Intermediate',
      theme: 'A woodland value engine where Food and Squirrels become mana, material, or damage.',
      plan: 'Build tokens without spending them too early, double the best token with Hazel, and convert sacrifices into table-wide pressure. Every token can change jobs as the game changes.',
      mulligan: 'Keep two or three lands, a ramp piece, and either a token maker or a sacrifice payoff.',
      tip: 'Treat Food as a flexible bank. It can stabilize life, fuel Hazel, or become an extra Squirrel and drain trigger at the right moment.',
      keys: ['Chatterfang, Squirrel General', 'Academy Manufactor', 'Nadier\'s Nightblade'],
    },
    'The Fantastic Four': {
      route: 'spells', pace: 'COMBO MIDRANGE', complexity: 'Advanced',
      theme: 'Marvel\'s first family turns every noncreature spell into another coordinated superpower.',
      plan: 'Assemble family members with complementary triggers, protect the engine, and cast noncreature spells in the order that produces the most value. The deck can pivot from control to a sudden combo finish.',
      mulligan: 'Keep four-color access or fixing, a low-cost family member, and a noncreature spell that advances the board.',
      tip: 'Resolve triggers in the order that preserves options. One small spell can create several abilities, targets, and copy decisions.',
      keys: ['Human Torch', 'Mister Fantastic', 'Galactus, Devourer of Worlds'],
    },
    'Turtle Power': {
      route: 'counters', pace: 'FIVE-COLOR TEAM-UP', complexity: 'Advanced',
      theme: 'The Turtles and their allies share counters, mutate the team, and attack as one five-color crew.',
      plan: 'Fix all five colors, choose the commander pair that supports the hand, and grow several Mutants through counters and combat triggers. The deck rewards coordinated attacks more than a single giant creature.',
      mulligan: 'Keep three colors plus fixing, an early Turtle or Mutant, and a source of counters or token growth.',
      tip: 'Your mana is the first puzzle. Prioritize color access before flashy plays, then choose attacks that advance multiple team triggers.',
      keys: ['Leonardo, the Balance', 'Michelangelo, the Heart', 'Donatello, the Brains'],
    },
    'Wakanda Forever': {
      route: 'artifacts', pace: 'MONARCH MIDRANGE', complexity: 'Intermediate',
      theme: 'Vibranium artifacts and the Monarch crown turn Wakanda into an accumulating resource advantage.',
      plan: 'Develop artifacts, claim or protect the Monarch, and let T\'Challa convert material into pressure. Equipment and artifact bodies give you both a defended throne and a powerful attack.',
      mulligan: 'Keep green and white mana, early artifact development, and a creature that can defend or reclaim the crown.',
      tip: 'Do not take the Monarch unless you can defend it. A delayed crown that draws two cards is better than gifting three cards around the table.',
      keys: ['Bast, Panther Goddess', 'Palace Jailer', 'Metalwork Colossus'],
    },
    'Scions & Spellcraft': {
      route: 'spells', pace: 'SPELL-DRAIN CONTROL', complexity: 'Advanced',
      theme: 'The Scions turn substantial noncreature spells into cards, life swings, and a patient table-wide drain.',
      plan: 'Build mana and card flow, land Y\'shtola when you can protect her, then cast mana value three-or-greater spells across several turns. The deck wins while answering threats, not by abandoning interaction.',
      mulligan: 'Keep Esper fixing, a mana rock or value permanent, and at least one meaningful noncreature spell.',
      tip: 'Use opponents\' turns. Instants can trigger Y\'shtola while preserving your own main phase for development and protection.',
      keys: ['Alisaie Leveilleur', 'Alphinaud Leveilleur', 'Archmage Emeritus'],
    },
    'Coven Counters': {
      route: 'counters', pace: 'CREATURE MIDRANGE', complexity: 'Approachable',
      theme: 'A growing Human fellowship where different power values unlock Coven and shared counters.',
      plan: 'Curve out with creatures of different sizes, spread +1/+1 counters, and trigger Coven without making every body identical. Leinore keeps the cards flowing while the team grows into combat.',
      mulligan: 'Keep green and white mana, two creatures at different points on the curve, and a counter source.',
      tip: 'Coven cares about three different powers. Place counters where they preserve that pattern instead of automatically growing the largest creature.',
      keys: ['Kyler, Sigardian Emissary', 'Mikaeus, the Lunarch', 'Verdurous Gearhulk'],
    },
    'Quandrix Unlimited': {
      route: 'counters', pace: 'X-SPELL ENGINE', complexity: 'Advanced',
      theme: 'Zimone turns extra lands and variable X spells into a rapidly expanding mathematical engine.',
      plan: 'Ramp and trigger landfall, use Zimone to reduce or reward the first X spell, and distribute counters where they create the best next turn. The deck scales from efficient setup to enormous Fractals and Hydras.',
      mulligan: 'Keep three lands or two plus ramp, a landfall/value piece, and an X spell that remains useful at several sizes.',
      tip: 'Plan the first X spell before tapping mana. The discount and counter triggers can change which X value is actually optimal.',
      keys: ['Zimone, Quandrix Prodigy', 'Hydroid Krasis', 'Primordial Hydra'],
    },
    'Dance of the Elements': {
      route: 'graveyard', pace: 'FIVE-COLOR REANIMATOR', complexity: 'Advanced',
      theme: 'Ashling conducts five-color Elementals through the battlefield and graveyard in one final dance.',
      plan: 'Fix colors with Elemental mana, fill the graveyard through trades and evoke effects, then recur the creatures whose enter/leave triggers matter most. Your graveyard becomes a second cast of characters.',
      mulligan: 'Keep green mana, color fixing, an early Elemental, and either self-mill or a recursion payoff.',
      tip: 'Track which Elementals are best to reuse, not just which are largest. Evoke can be setup when the death and graveyard placement both help.',
      keys: ['Risen Reef', 'Omnath, Locus of the Roil', 'Horde of Notions'],
    },
    'World Shaper': {
      route: 'lands', pace: 'LANDFALL ENGINE', complexity: 'Advanced',
      theme: 'A living worldship sacrifices lands for value, then returns them all in one tectonic turn.',
      plan: 'Develop mana while stocking lands in the graveyard, collect payoffs for sacrificing and replaying them, and use mass land return to trigger the whole engine at once. Hearthhull turns the setup into a threat of its own.',
      mulligan: 'Keep three lands, a ramp or self-mill piece, and one payoff for landfall or sacrifice.',
      tip: 'Do not sacrifice lands without a return path. The strongest lines gain a resource now and set up several landfall triggers later.',
      keys: ['Aftermath Analyst', 'Tireless Tracker', 'Mayhem Devil'],
    },
    'Limit Break': {
      route: 'equipment', pace: 'EQUIPMENT AGGRO', complexity: 'Intermediate',
      theme: 'Cloud equips a Final Fantasy party, turning modified heroes into a focused combat squad.',
      plan: 'Deploy cheap Equipment and equip-cost support, connect with modified creatures, and move the best gear to the attacker that creates the safest advantage. Cloud converts preparation into a decisive Limit Break.',
      mulligan: 'Keep Naya fixing, one cheap Equipment, and a creature or support piece that reduces equip friction.',
      tip: 'Equipment survives creature removal. Build the armory first, then commit it to the hero most likely to connect this turn.',
      keys: ['Puresteel Paladin', 'Zack Fair', 'Red XIII, Proud Warrior'],
    },
    'Temur Roar': {
      route: 'bigCreatures', pace: 'DRAGON RAMP', complexity: 'Approachable',
      theme: 'Temur ramp opens the skies for hasty Dragons and punishing attack triggers.',
      plan: 'Accelerate mana and reduce Dragon costs, deploy one threat that demands an answer, then let Ureni find more Dragons as combat begins. Haste keeps the deck from giving the table a full turn to prepare.',
      mulligan: 'Keep green mana, a ramp or cost-reduction spell, and one Dragon you can realistically cast on curve.',
      tip: 'Do not fill the hand with only seven-drops. One early reducer often deals more eventual damage than another spectacular Dragon.',
      keys: ['Sarkhan, Soul Aflame', 'Lathliss, Dragon Queen', 'Dragonlord Atarka'],
    },
    'Sultai Arisen': {
      route: 'graveyard', pace: 'GRAVEYARD VALUE', complexity: 'Advanced',
      theme: 'Teval turns self-mill and fallen creatures into a deep, reusable Sultai resource pool.',
      plan: 'Mill deliberately, trade creatures for value, and recur the exact answer or threat the table demands. The deck wins long games because its spent cards keep returning in stronger combinations.',
      mulligan: 'Keep all three colors or fixing, self-mill, and a recursion or payoff card that can use the stocked graveyard.',
      tip: 'Know what can be recovered before milling aggressively. Protect the recursion spell that turns a full graveyard into a real board.',
      keys: ['Meren of Clan Nel Toth', 'Living Death', 'Lord of Extinction'],
    },
    'Jeskai Striker': {
      route: 'spells', pace: 'PROWESS TEMPO', complexity: 'Advanced',
      theme: 'Shiko and Narset make the second spell each turn the center of a precise Jeskai tempo engine.',
      plan: 'Develop a token or prowess payoff, cast the first spell to set the turn, and make the second spell the one worth copying or rewarding. Playing on multiple turns keeps the engine producing without emptying your hand.',
      mulligan: 'Keep Jeskai fixing, a cheap payoff creature, and two low-cost spells with different jobs.',
      tip: 'Count spells separately on every turn. A cheap instant on an opponent\'s turn can create another full second-spell reward cycle.',
      keys: ['Monastery Mentor', 'Veyran, Voice of Duality', 'Archmage Emeritus'],
    },
  });
})();
