// ===== deck-guides.js =====
'use strict';
var MTG = globalThis.MTG || (globalThis.MTG = {});
(function () {
  MTG.DECK_GUIDE_ROUTES = Object.freeze({
    exile: [
      {label:'Early game',title:'Build mana',text:'Develop lands and mana rocks so you can afford cards exiled by your spells.'},
      {label:'Midgame',title:'Play from exile',text:'Use Prosper and temporary exile permissions to generate Treasures while developing your board.'},
      {label:'Endgame',title:'Spend the reserves',text:'Convert accumulated Treasures into a decisive sequence of threats and removal.'},
    ],
    enchantments: [
      {label:'Early game',title:'Enchant your mana',text:'Develop lands and mana Auras, then add an enchantment payoff before committing your planeswalker.'},
      {label:'Midgame',title:'Protect your engines',text:'Use Masks and defensive enchantments while drawing cards from each new enchantment.'},
      {label:'Endgame',title:'Rebuild and overwhelm',text:'Return enchantments from your graveyard and turn protected creatures or tokens into a finishing attack.'},
    ],
    fliers: [
      {label:'Early game',title:'Develop your air force',text:'Build mana and play inexpensive fliers while keeping enough blockers to protect your life total.'},
      {label:'Midgame',title:'Keep the skies open',text:'Use card draw and timely answers to keep flying attackers ahead of opposing defenses.'},
      {label:'Endgame',title:'Finish above the ground',text:'Protect your strongest fliers and choose an attack that leaves a safe defense against the remaining players.'},
    ],
    dragons: [
      {label:'Early game',title:'Ramp toward Dragons',text:'Develop green mana and acceleration so expensive Dragons arrive while you can still defend yourself.'},
      {label:'Midgame',title:'Build a threatening flight',text:'Choose Dragons whose entry and attack triggers improve the board immediately.'},
      {label:'Endgame',title:'Attack with double strike',text:'Land Atarka before declaring attackers, then use flying and double strike to turn the Dragon army into a finish.'},
    ],
    goWide: [
      { label: 'Early game', title: 'Seed the board', text: 'Develop mana and cheap bodies. Your small pieces matter more as a group than alone.' },
      { label: 'Midgame', title: 'Multiply the army', text: 'Layer token makers and payoffs, but keep enough material back to recover from a wipe.' },
      { label: 'Endgame', title: 'Turn width into damage', text: 'Choose the turn where one attack or sacrifice chain converts the whole board into a finish.' },
    ],
    artifacts: [
      { label: 'Early game', title: 'Assemble the engine', text: 'Play mana and low-cost artifacts first so every later synergy arrives ahead of curve.' },
      { label: 'Midgame', title: 'Stack the payoffs', text: 'Add counters, copies, or card draw while protecting the piece that makes the engine compound.' },
      { label: 'Endgame', title: 'Convert the machine', text: 'Turn accumulated artifacts and counters into a lethal board, a huge spell, or an alternate win.' },
    ],
    spells: [
      { label: 'Early game', title: 'Prepare the turn', text: 'Develop mana and a value creature before spending the cheap spells that make the deck snowball.' },
      { label: 'Midgame', title: 'Chain with purpose', text: 'Sequence draw, interaction, and copy effects so each spell improves the next one.' },
      { label: 'Endgame', title: 'Explode in one window', text: 'Wait for an opening, then turn stored cards and mana into a decisive multi-spell turn.' },
    ],
    groupSlug: [
      { label: 'Early game', title: 'Install the taxes', text: 'Deploy repeatable life-loss pieces before opponents can freely build their engines.' },
      { label: 'Midgame', title: 'Squeeze every action', text: 'Keep the board moving while making draws, spells, and attacks cost the table life.' },
      { label: 'Endgame', title: 'Close the furnace', text: 'Use a burst of damage or a punisher payoff before the whole table can turn on you.' },
    ],
    defenders: [
      { label: 'Early game', title: 'Fortify and ramp', text: 'Play high-toughness defenders and mana creatures until attacking you becomes inefficient.' },
      { label: 'Midgame', title: 'Turn the corner', text: 'Land the effects that let toughness become pressure while your walls still guard your life total.' },
      { label: 'Endgame', title: 'Crush behind the shield', text: 'Commit to combat once your defensive board becomes an oversized attacking force.' },
    ],
    politics: [
      { label: 'Early game', title: 'Develop quietly', text: 'Build resources without looking like the player the rest of the table must stop first.' },
      { label: 'Midgame', title: 'Redirect the table', text: 'Use votes, incentives, and selective interaction to point the strongest boards at one another.' },
      { label: 'Endgame', title: 'Cash in the opening', text: 'Break parity when opponents are depleted and convert the political advantage into a win.' },
    ],
    counters: [
      { label: 'Early game', title: 'Plant the first counters', text: 'Start with mana and creatures that reward every future counter placement.' },
      { label: 'Midgame', title: 'Scale the board', text: 'Proliferate or spread counters across several threats so one removal spell cannot reset you.' },
      { label: 'Endgame', title: 'Make one huge swing', text: 'Use evasion, trample, or a counter payoff to turn stored growth into lethal combat.' },
    ],
    graveyard: [
      { label: 'Early game', title: 'Stock the graveyard', text: 'Mill and trade creatures while developing mana. The graveyard is a second hand, not a loss.' },
      { label: 'Midgame', title: 'Reuse the best pieces', text: 'Reanimate value creatures and recur answers while opponents spend real cards to keep up.' },
      { label: 'Endgame', title: 'Rebuild at full scale', text: 'Resolve a mass-return or graveyard payoff that turns all the setup into one overwhelming board.' },
    ],
    lands: [
      { label: 'Early game', title: 'Put lands to work', text: 'Ramp, mill, and sacrifice lands only when the exchange advances both mana and graveyard setup.' },
      { label: 'Midgame', title: 'Profit from every move', text: 'Use landfall and sacrifice payoffs so normal development also makes cards, tokens, or damage.' },
      { label: 'Endgame', title: 'Bring the world back', text: 'Return a full graveyard of lands and let the resulting triggers bury the table in value.' },
    ],
    equipment: [
      { label: 'Early game', title: 'Find the weapons', text: 'Develop mana, cheap Equipment, and creatures that lower equip costs or reward modifications.' },
      { label: 'Midgame', title: 'Connect safely', text: 'Move the best Equipment to the attacker most likely to survive and generate another advantage.' },
      { label: 'Endgame', title: 'Break the limit', text: 'Stack protection and power on one decisive threat, then finish with combat or an Equipment payoff.' },
    ],
    typal: [
      { label: 'Early game', title: 'Recruit the core', text: 'Curve out with mana and the creatures that make every later member of the team stronger.' },
      { label: 'Midgame', title: 'Layer team synergies', text: 'Add lords, engines, and protection while spreading value across more than one permanent.' },
      { label: 'Endgame', title: 'Rally the table', text: 'Use the commander or a finisher to turn the assembled team into a decisive attack.' },
    ],
    bigCreatures: [
      { label: 'Early game', title: 'Ramp without drifting', text: 'Prioritize mana development and cost reduction. The deck starts when its large threats arrive on time.' },
      { label: 'Midgame', title: 'Deploy must-answer threats', text: 'Present one powerful creature at a time and keep the next threat ready if the board is cleared.' },
      { label: 'Endgame', title: 'Own the combat step', text: 'Use haste, evasion, and attack triggers to end the game before opponents can stabilize.' },
    ],
  });

  MTG.DECK_GUIDES = Object.freeze({
    "Land's Wrath": {"route": "lands", "pace": "LANDFALL AND COUNTERS", "complexity": "Intermediate", "theme": "Obuun grows your creatures with landfall and animates a land for combat.", "plan": "Ramp, make repeated land drops, and put counters on Obuun before animating a land.", "mulligan": "Keep three lands, early ramp, and a landfall payoff.", "tip": "Obuun uses his power when the combat trigger resolves. A land that becomes a creature can still tap for mana.", "keys": ["Emeria Shepherd", "Trove Warden", "Geode Rager"]},
    "Arm for Battle": {"route": "equipment", "pace": "EQUIPMENT AND CARD DRAW", "complexity": "Intermediate", "theme": "Wyleth turns each attached Aura and Equipment into a card whenever he attacks.", "plan": "Equip Wyleth, protect him through combat, and use each attack to refill your hand.", "mulligan": "Keep two or three lands, a cheap Equipment, and a protection spell.", "tip": "Wyleth draws when he attacks; he does not need to deal combat damage.", "keys": ["Timely Ward", "Blazing Sunsteel", "Sunforger"]},
    "Reap the Tides": {"route": "bigCreatures", "pace": "LAND RAMP AND SEA MONSTERS", "complexity": "Intermediate", "theme": "Aesi allows an extra land each turn and draws a card whenever your land enters.", "plan": "Build your mana with extra lands, then deploy sea monsters and bounce opposing creatures.", "mulligan": "Keep three lands and early ramp or an inexpensive creature that replaces itself.", "tip": "Aesi permits one additional land play; lands put onto the battlefield by effects do not use that allowance.", "keys": ["Trench Behemoth", "Stumpsquall Hydra", "Whelming Wave"]},
    "Phantom Premonition": {"route": "fliers", "pace": "FORETELL AND BLINK", "complexity": "Intermediate", "theme": "Ranar discounts your first foretell action each turn and creates Spirits from qualifying exile events.", "plan": "Set aside foretell spells, reuse creature entry abilities, and build a flying Spirit army.", "mulligan": "Keep two or three lands, a mana rock, and a foretell or blink play.", "tip": "Foretelling sets a card aside; it may be cast for its foretell cost only after that turn ends.", "keys": ["Ethereal Valkyrie", "Cosmic Intervention", "Soulherder"]},
    "Elven Empire": {"route": "typal", "pace": "ELVES AND LIFE DRAIN", "complexity": "Intermediate", "theme": "Lathril makes Elf Warriors from combat damage and taps an Elf army to drain the table.", "plan": "Develop mana Elves, attack with Lathril, and preserve enough untapped Elves for her drain ability.", "mulligan": "Keep two or three lands, a mana Elf, and an Elf payoff or card draw spell.", "tip": "Lathril taps herself plus ten other untapped Elves. The ten supporting Elves may have summoning sickness.", "keys": ["Marwyn, the Nurturer", "Pact of the Serpent", "Serpent's Soul-Jar"]},
    "Undead Unleashed": {"route": "typal", "pace": "ZOMBIES AND SACRIFICE", "complexity": "Intermediate", "theme": "Wilhelt replaces other Zombies without decayed that die with decayed Zombies.", "plan": "Build a Zombie army, sacrifice creatures for cards and value, then use tribal payoffs to close the game.", "mulligan": "Keep two or three lands, an inexpensive Zombie, and draw or ramp.", "tip": "Decayed Zombies cannot block. Once they attack, they are sacrificed at the end of combat.", "keys": ["Cleaver Skaab", "Hordewing Skaab", "Crowded Crypt"]},
    "Dungeons of Death": {"route": "graveyard", "pace": "VENTURE AND REANIMATION", "complexity": "Intermediate", "theme": "Sefris ventures when creature cards enter your graveyard and reanimates after a dungeon.", "plan": "Put creatures in your graveyard, finish dungeons, and return impactful creatures with Sefris.", "mulligan": "Keep three lands, a way to draw or discard, and a venture or reanimation enabler.", "tip": "Sefris can venture only once each turn, including opponents’ turns. Completing a dungeon gives a separate targeted reanimation trigger.", "keys": ["Radiant Solar", "Hama Pashar, Ruin Seeker", "Midnight Pathlighter"]},
    "Aura of Courage": {"route": "equipment", "pace": "AURAS AND EQUIPMENT", "complexity": "Intermediate", "theme": "Galea casts Auras and Equipment from the top of your library.", "plan": "Establish a protected attacker, improve it with Auras and Equipment, and use Galea to keep cards flowing.", "mulligan": "Keep two or three lands, ramp, and an inexpensive Aura or Equipment.", "tip": "Equipment cast from the top with Galea gains an entry trigger that attaches it to a creature you control.", "keys": ["Mantle of the Ancients", "Holy Avenger", "Storvald, Frost Giant Jarl"]},
    "Draconic Rage": {"route": "bigCreatures", "pace": "DICE AND DRAGONS", "complexity": "Intermediate", "theme": "Vrondiss creates Dragon Spirits when dealt damage.", "plan": "Ramp into Dragons, use dice to trigger Vrondiss, and attack with the growing army.", "mulligan": "Keep three lands, ramp, and an affordable creature or dice effect.", "tip": "Vrondiss can deal 1 damage to himself whenever you roll dice; his Dragon Spirits are sacrificed after dealing damage.", "keys": ["Wulfgar of Icewind Dale", "Barbarian Class", "Klauth, Unrivaled Ancient"]},
    "Planar Portal": {"route": "exile", "pace": "EXILE AND TREASURE", "complexity": "Intermediate", "theme": "Prosper turns cards played from exile into Treasures.", "plan": "Build mana with Treasures, play exiled cards before permissions expire, and spend the extra resources on interaction.", "mulligan": "Keep two or three lands, early ramp, and a spell that exiles cards to play.", "tip": "Prosper lets you play his exiled card through the end of your next turn; normal timing and land limits still apply.", "keys": ["Wild-Magic Sorcerer", "Grim Hireling", "Fevered Suspicion"]},

    "Mystic Intellect": {"route": "graveyard", "pace": "FLASHBACK AND SPELL COPIES", "complexity": "Advanced", "theme": "Sevinne copies your first instant or sorcery cast from the graveyard each turn.", "plan": "Develop mana, stock the graveyard and keep reusable answers available.", "mulligan": "Keep three lands, blue mana and early selection or ramp.", "tip": "Sevinne copies only the first qualifying graveyard spell each turn, even if he entered after an earlier one.", "keys": ["Increasing Vengeance", "Backdraft Hellkite", "Dockside Extortionist"]},
    "Faceless Menace": {"route": "bigCreatures", "pace": "MORPH AND HIDDEN CREATURES", "complexity": "Advanced", "theme": "Kadena discounts your first face-down creature spell each turn and draws when a face-down creature enters.", "plan": "Build a board of hidden creatures, then keep mana open to turn the right creature face up.", "mulligan": "Keep three lands, all three colors and an early morph creature.", "tip": "Turning a creature face up is a special action. Its triggered ability still uses the Stack.", "keys": ["Kadena's Silencer", "Vesuvan Shapeshifter", "Trail of Mystery"]},
    "Timeless Wisdom": {"route": "spells", "pace": "CYCLING AND TOKEN VALUE", "complexity": "Advanced", "theme": "Gavi makes your first cycling cost each turn free and rewards your second draw with a Dinosaur Cat.", "plan": "Cycle selectively, build tokens and save cycling interaction for opposing turns.", "mulligan": "Keep three lands, a cheap cycling card and early mana development.", "tip": "Your first cycling action counts even if Gavi was not on the battlefield. Free cycling still discards the card.", "keys": ["Astral Drift", "New Perspectives", "Zenith Flare"]},
    "Enhanced Evolution": {"route": "bigCreatures", "pace": "MUTATE AND CREATURE RECURSION", "complexity": "Advanced", "theme": "Otrimi combines mutate abilities with trample and returns mutate creatures after a combat hit.", "plan": "Develop a non-Human creature, stack useful mutation triggers and protect the resulting threat.", "mulligan": "Keep three lands, a cheap non-Human and a mutate creature or ramp.", "tip": "Mutate targets a non-Human creature you own. A successful merge keeps the existing permanent and does not trigger entry abilities.", "keys": ["Auspicious Starrix", "Migratory Greathorn", "Mindleecher"]},
    "Ruthless Regiment": {"route": "typal", "pace": "HUMANS AND ATTACK PRESSURE", "complexity": "Intermediate", "theme": "Jirina recruits Humans based on her command-zone casts and gives your other Humans +2/+0.", "plan": "Build a Human army, protect key pieces and rebuild with Jirina after removal.", "mulligan": "Keep three lands, early Humans and removal or protection.", "tip": "Jirina counts actual casts from the command zone. Reanimation and blinking do not increase that count.", "keys": ["Xathrid Necromancer", "Call the Coppercoats", "Frontline Medic"]},
    "Arcane Maelstrom": {"route": "spells", "pace": "INSTANTS AND SPELL COPIES", "complexity": "Advanced", "theme": "A tapped Kalamax copies your first instant each turn and grows whenever you copy an instant.", "plan": "Develop mana, tap Kalamax through combat or a cost and save instants for several turns around the table.", "mulligan": "Keep three lands, green ramp and an inexpensive instant.", "tip": "Kalamax must be tapped when the first instant is cast. Twinning Staff adds one copy to each copying instruction.", "keys": ["Twinning Staff", "Deflecting Swat", "Wort, the Raidmother"]},
    "Symbiotic Swarm": {"route": "counters", "pace": "GRAVEYARD AND KEYWORD COUNTERS", "complexity": "Advanced", "theme": "Kathril turns creature keywords in your graveyard into counters and grows for the counters actually placed.", "plan": "Fill the graveyard with useful keywords, develop creatures and make a protected threat with Kathril.", "mulligan": "Keep three lands, graveyard setup and an early creature or ramp spell.", "tip": "Keyword counters remain after Kathril leaves. Removing or moving counters can enable Tayam or strengthen a different threat.", "keys": ["Tayam, Luminous Enigma", "Slippery Bogbonder", "Soulflayer"]},
    "Sneak Attack": {"route": "typal", "pace": "ROGUES AND COMBAT MILLING", "complexity": "Intermediate", "theme": "Anowon boosts other Rogues and turns Rogue combat damage into milling and potential card draw.", "plan": "Deploy evasive Rogues, attack open opponents and use stolen or reanimated cards to keep resources flowing.", "mulligan": "Keep two or three lands, an evasive Rogue and interaction or draw.", "tip": "Anowon mills for the Rogue damage dealt to each player and draws once for that player if a creature card was milled.", "keys": ["Notorious Throng", "Whispersteel Dagger", "Enigma Thief"]},

    "Draconic Domination": {"route": "dragons", "pace": "DRAGONS AND EMINENCE", "complexity": "Intermediate", "theme": "The Ur-Dragon reduces Dragon costs from the command zone and rewards a full flight with cards and a free permanent.", "plan": "Fix all five colors, ramp and deploy Dragons before committing your expensive commander.", "mulligan": "Keep three lands, green mana and a ramp or fixing spell.", "tip": "Eminence reduces other Dragon spells by one generic mana. The attack ability counts all your attacking Dragons.", "keys": ["Dragon Tempest", "Kindred Discovery", "Scion of the Ur-Dragon"]},
    "Vampiric Bloodlust": {"route": "goWide", "pace": "VAMPIRE SWARM", "complexity": "Intermediate", "theme": "Edgar creates a Vampire for each other Vampire spell, then grows the whole tribe when he attacks.", "plan": "Build a wide board with inexpensive Vampires, drain life and protect an attack that grows your army.", "mulligan": "Keep two or three lands and several early Vampires.", "tip": "Edgar can create tokens while in the command zone. The token trigger resolves before the Vampire spell.", "keys": ["Captivating Vampire", "Bloodline Necromancer", "New Blood"]},
    "Feline Ferocity": {"route": "bigCreatures", "pace": "CATS AND EQUIPMENT", "complexity": "Intermediate", "theme": "Arahbo boosts a Cat before combat and can turn another attacking Cat into a trampling threat.", "plan": "Develop a Cat and Equipment, use the free combat boost and hold mana for the attack payment.", "mulligan": "Keep three lands, an early Cat and Equipment or ramp.", "tip": "The command-zone boost targets another Cat. Arahbo must be on the battlefield to offer the paid attack boost.", "keys": ["Hammer of Nazahn", "Nazahn, Revered Bladesmith", "Raksha Golden Cub"]},
    "Arcane Wizardry": {"route": "spells", "pace": "WIZARDS AND COPIES", "complexity": "Advanced", "theme": "Inalla offers temporary Wizard copies whose entry abilities build value and whose bodies can attack immediately.", "plan": "Develop mana and cast Wizards with useful entry abilities while reserving one mana for each copy.", "mulligan": "Keep three lands, fixing and an inexpensive Wizard or draw spell.", "tip": "The copy gains haste and is exiled at the next end step. Inalla can offer copies from the command zone.", "keys": ["Galecaster Colossus", "Kindred Dominance", "Bloodline Necromancer"]},
    "Exquisite Invention": {"route": "artifacts", "pace": "ARTIFACT ENGINES", "complexity": "Advanced", "theme": "Saheeli creates Servos and gives the next spell a discount based on your artifact count.", "plan": "Build artifact mana and tokens, protect Saheeli and turn spare machines into large threats or copied armies.", "mulligan": "Keep three lands, an artifact mana source and an early artifact.", "tip": "Choose between making a Servo and discounting your next spell. Each planeswalker normally activates once per turn.", "keys": ["Saheeli's Directive", "Brudiclad, Telchor Engineer", "Thopter Spy Network"]},
    "Subjective Reality": {"route": "spells", "pace": "TOP-DECK AND BLINK", "complexity": "Advanced", "theme": "Aminatou sets up the top of your library and blinks owned permanents to reuse their entry abilities.", "plan": "Develop mana, arrange useful top cards and reuse entry effects while protecting your planeswalker.", "mulligan": "Keep three lands, both early colors and a selection or defensive spell.", "tip": "The blink ability targets another permanent you own, even if someone else currently controls it.", "keys": ["Aminatou's Augury", "Yennett, Cryptic Sovereign", "Ponder"]},
    "Nature's Vengeance": {"route": "graveyard", "pace": "LANDS AND RECURSION", "complexity": "Intermediate", "theme": "Lord Windgrace turns discarded lands into extra cards and brings lands back from the graveyard.", "plan": "Develop lands, trade spare lands for cards and reuse sacrificed lands to keep large threats coming.", "mulligan": "Keep three lands, green ramp and a draw or recursion play.", "tip": "Discarding a land to the plus ability draws two cards. Returning lands does not use your land play for the turn.", "keys": ["Avenger of Zendikar", "Nesting Dragon", "Harrow"]},
    "Adaptive Enchantment": {"route": "enchantments", "pace": "AURAS AND ENCHANTMENTS", "complexity": "Advanced", "theme": "Estrid protects permanents with Masks, untaps enchanted permanents and rebuilds enchantments from the graveyard.", "plan": "Enchant useful mana sources, protect Estrid and grow a board that can recover from removal.", "mulligan": "Keep three lands, a mana Aura and an early enchantment payoff.", "tip": "A Mask can enchant another permanent. Umbra armor replaces destruction, including lethal damage, but does not stop sacrifice or exile.", "keys": ["Estrid's Invocation", "Tuvasa the Sunlit", "Enchantress's Presence"]},
    "Merciless Rage": {"route": "graveyard", "pace": "MADNESS AND DISCARD", "complexity": "Advanced", "theme": "Anje discards and draws at speed, untapping whenever you discard a card with madness.", "plan": "Use Anje to improve your hand, cast madness spells from exile and return discarded creatures to the battlefield.", "mulligan": "Keep three lands, both colors and a madness card or removal spell.", "tip": "Madness first exiles the discarded card. Its trigger then offers the madness cost, even outside normal sorcery timing.", "keys": ["Bone Miser", "Chainer, Nightmare Adept", "Archfiend of Spite"]},
    "Primal Genesis": {"route": "goWide", "pace": "POPULATE AND ATTACK", "complexity": "Intermediate", "theme": "Ghired brings a trampling Rhino and populates an attacking token every time he attacks.", "plan": "Ramp into large tokens, protect Ghired and turn each attack into another substantial threat.", "mulligan": "Keep three lands, green ramp and a token maker or defensive creature.", "tip": "Populate copies a creature token you control. Ghired puts the copy into combat tapped and attacking.", "keys": ["Garruk, Primal Hunter", "Ghired's Belligerence", "Desolation Twin"]},

      "Call the Spirits": {"route":"goWide","pace":"ENCHANTMENT TOKENS","complexity":"Intermediate","theme":"Daxos turns each enchantment spell into lasting experience and an army of growing Spirits.","plan":"Develop mana and protective enchantments, build experience, then create Spirits while leaving mana for interaction.","mulligan":"Keep three lands, a mana rock and an inexpensive enchantment.","tip":"Experience counters stay with you when Daxos leaves. Spirit size follows their controller’s experience total.","keys":["Mesa Enchantress","Grasp of Fate","Doomwake Giant"]},
      "Seize Control": {"route":"spells","pace":"SPELLS AND EXPERIENCE","complexity":"Advanced","theme":"Mizzix makes large instants and sorceries affordable as your experience grows.","plan":"Cast increasingly large spells, protect Mizzix and turn card draw into a decisive chain of damage and copies.","mulligan":"Keep three lands, early interaction and a draw spell or mana rock.","tip":"Experience reduces generic mana only. Choose X before paying; the spell’s mana value includes X on the Stack.","keys":["Mizzix's Mastery","Melek, Izzet Paragon","Blue Sun's Zenith"]},
      "Plunder the Graves": {"route":"graveyard","pace":"CREATURE RECURSION","complexity":"Intermediate","theme":"Meren builds experience from fallen creatures and brings them back at your end step.","plan":"Trade creatures for value, reuse their entry abilities and let experience turn end-step returns into battlefield advantage.","mulligan":"Keep three lands, an early creature and ramp or a sacrifice outlet.","tip":"Meren returns a creature directly only when its mana value is no greater than your experience. Otherwise it returns to hand.","keys":["Sakura-Tribe Elder","Skullwinder","Victimize"]},
      "Wade into Battle": {"route":"bigCreatures","pace":"GIANTS AND EQUIPMENT","complexity":"Intermediate","theme":"Kalemne gains experience from expensive creatures and becomes a vigilant double-strike threat.","plan":"Ramp into large creatures, keep blockers while Kalemne attacks and use Equipment or removal to clear a finishing swing.","mulligan":"Keep three lands, a mana rock and a creature you can cast before the late game.","tip":"A creature spell with mana value five or more earns experience even if that spell is countered.","keys":["Blade of Selves","Urza's Incubator","Thundercloud Shaman"]},
      "Swell the Host": {"route":"counters","pace":"SMALL CREATURES, BIG COUNTERS","complexity":"Intermediate","theme":"Ezuri rewards small creatures, then places your accumulated experience on another creature before combat.","plan":"Build a board of low-power creatures, protect Ezuri and put counters where evasion or other abilities make them matter.","mulligan":"Keep two or three lands, early creatures and a draw or protection spell.","tip":"Ezuri’s combat trigger must target another creature. It uses your experience total when it resolves.","keys":["Cold-Eyed Selkie","Kaseto, Orochi Archmage","Great Oak Guardian"]},
      "Entropic Uprising": {"route":"spells","pace":"COMBAT INTO CASCADE","complexity":"Advanced","theme":"Yidris turns a successful combat hit into cascade for spells you cast from your hand that turn.","plan":"Fix all four colors, connect with Yidris and cast from hand in your second main phase to collect cascade value.","mulligan":"Keep three lands with several colors, a fixing spell and an early play.","tip":"Yidris must deal combat damage to a player first. The cascade grant applies to later hand casts that turn.","keys":["Bloodbraid Elf","Whispering Madness","Cruel Entertainment"]},
      "Open Hostility": {"route":"bigCreatures","pace":"FOUR-COLOR AGGRESSION","complexity":"Intermediate","theme":"Saskia chooses a player as she enters and sends extra creature damage toward that player.","plan":"Fix your colors, build an attacking board and choose the player you want to pressure through attacks on the rest of the table.","mulligan":"Keep three lands, fixing and two early creatures.","tip":"Saskia’s extra damage is dealt by the original creature and is not combat damage. The chosen player may also be the original defender.","keys":["Brutal Hordechief","Tymna the Weaver","Crackling Doom"]},
      "Stalwart Unity": {"route":"politics","pace":"SHARED RESOURCES AND DEFENSE","complexity":"Advanced","theme":"Kynaios and Tiro help every player develop while your defenses buy time to use the extra resources.","plan":"Fix your colors, encourage development and protect yourself with taxes and selective removal before committing finishers.","mulligan":"Keep three lands, color fixing and a defensive or draw engine.","tip":"You always draw first at your end step. Each opponent who declines to put a land onto the battlefield draws afterward.","keys":["Rites of Flourishing","Sphere of Safety","Reverse the Sands"]},
      "Breed Lethality": {"route":"counters","pace":"COUNTERS AND PROLIFERATE","complexity":"Intermediate","theme":"Atraxa proliferates at your end step while the deck spreads counters across an expanding board.","plan":"Fix four colors, put counters on useful creatures and protect your board so each end step adds lasting growth.","mulligan":"Keep three lands, early fixing and a creature or engine that starts with counters.","tip":"Proliferate adds one counter of each kind already present on each chosen permanent or player. Choose carefully.","keys":["Reyhan, Last of the Abzan","Corpsejack Menace","Deepglow Skate"]},
      "Invent Superiority": {"route":"artifacts","pace":"ARTIFACT SACRIFICE AND REUSE","complexity":"Advanced","theme":"Breya makes Thopters and converts spare artifacts into damage, removal or life.","plan":"Develop artifact mana, protect your useful machines and recycle expendable artifacts into Breya activations or graveyard returns.","mulligan":"Keep three lands, a mana artifact and an inexpensive artifact or recursion spell.","tip":"Breya’s ability costs two mana and two artifacts. Tokens can pay the sacrifice cost, and Breya can sacrifice herself.","keys":["Silas Renn, Seeker Adept","Daretti, Scrap Savant","Open the Vaults"]},
    "Forged in Stone": {"route":"artifacts","pace":"EQUIPMENT MIDRANGE","complexity":"Intermediate","theme":"Nahiri forges Equipment, raises Kor Soldiers, and rebuilds a resilient white army.","plan":"Develop mana and Equipment, then use Nahiri to create defenders and recover your strongest relics. Protect loyalty with a growing army and finish with an equipped threat.","mulligan":"Keep three lands, an early mana rock, and a creature or Equipment.","tip":"Nahiri can put an Equipment from either hand or graveyard onto the battlefield. Her first ability can attach Equipment without paying its equip cost.","keys":["Kemba, Kha Regent","Sun Titan","Skullclamp"]},
    "Peer Through Time": {"route":"bigCreatures","pace":"BLUE CONTROL","complexity":"Advanced","theme":"Teferi untaps powerful mana sources and uses blue card advantage to keep large threats coming.","plan":"Build mana rocks, hold interaction, and use Teferi to untap your most productive permanents. Turn card selection, morph creatures and large fliers into a sustained advantage.","mulligan":"Keep three Islands, a mana rock, and an early play or card-draw spell.","tip":"Teferi can untap up to four permanents, including mana rocks. Each planeswalker still has only one loyalty activation per turn after his emblem.","keys":["Thran Dynamo","Brine Elemental","Sphinx of Uthuun"]},
    "Sworn to Darkness": {"route":"graveyard","pace":"BLACK ATTRITION","complexity":"Intermediate","theme":"Ob Nixilis builds a Demon army while black mana engines, sacrifice and life drain wear down the table.","plan":"Develop Swamps and mana multipliers, then stabilize with removal and large Demons. Sacrifice creatures for value, reanimate threats, and use life drain to close the game.","mulligan":"Keep three Swamps, a mana rock or draw spell, and a useful removal spell.","tip":"Abyssal Persecutor stops your opponents from losing while you control it. Keep a sacrifice outlet or removal spell ready before the finishing blow.","keys":["Crypt Ghast","Ghoulcaller Gisa","Gray Merchant of Asphodel"]},
    "Built from Scratch": {"route":"artifacts","pace":"ARTIFACT REANIMATION","complexity":"Advanced","theme":"Daretti turns discarded machines into battlefield threats and rebuilds after every exchange.","plan":"Use inexpensive artifacts for mana and cards, discard expensive machines, and return them with Daretti or Goblin Welder. Save Scrap Mastery to rebuild a decisive artifact board.","mulligan":"Keep three lands, an early artifact mana source, and an artifact to discard or sacrifice.","tip":"Daretti’s minus ability targets an artifact card in your graveyard before you sacrifice anything. The sacrificed artifact cannot be that ability’s return target.","keys":["Goblin Welder","Wurmcoil Engine","Scrap Mastery"]},
    "Guided by Nature": {"route":"goWide","pace":"ELF RAMP","complexity":"Intermediate","theme":"Freyalise grows an Elf mana engine that turns into a large army and powerful green finishers.","plan":"Develop Elves and lands, protect Freyalise, and convert extra mana into creatures and cards. Build enough bodies for an overrun effect or attack through blockers with Siege Behemoth.","mulligan":"Keep two or three Forests, an early mana Elf, and a card-draw or creature payoff.","tip":"Freyalise’s Elf Druids need haste or a full turn under your control before tapping for mana. Her ultimate counts green creatures when it resolves.","keys":["Elvish Archdruid","Overwhelming Stampede","Siege Behemoth"]},
    "Lorehold Legacies": {"route":"artifacts","pace":"ARTIFACT RECURSION","complexity":"Advanced","theme":"Osgir rebuilds fallen artifacts as pairs of tokens, turning discarded relics into mana and massive constructs.","plan":"Develop mana rocks, stock the graveyard, and use Osgir to create two copies of a valuable artifact. Preserve a way to rebuild after removal and turn artifact tokens into a decisive board.","mulligan":"Keep three lands with both colors, a mana rock, and an artifact to cast or discard.","tip":"Osgir’s copy ability costs the artifact’s mana value, taps him, and exiles the card as a cost. Activate it only during your main phase with an empty stack.","keys":["Daretti, Scrap Savant","Scrap Trawler","Triplicate Titan"]},
    "Prismari Performance": {"route":"spells","pace":"BIG SPELLS","complexity":"Advanced","theme":"Zaffai rewards large instants, sorceries, and copies with Elementals and bursts of damage.","plan":"Build mana and establish spell payoffs before casting large instants and sorceries. Chain draw and copy effects to create Constructs and Elementals while keeping interaction available.","mulligan":"Keep three lands, both colors, an early mana rock, and card draw.","tip":"Zaffai triggers for copies as well as casts. A spell with mana value five makes an Elemental; mana value ten also deals ten damage to a random opponent.","keys":["Metallurgic Summonings","Pyromancer's Goggles","Apex of Power"]},
    "Quantum Quandrix": {"route":"goWide","pace":"TOKEN MULTIPLICATION","complexity":"Intermediate","theme":"Adrix and Nev double token production, building Fractals, copies, and growing armies.","plan":"Ramp into Adrix and Nev, then multiply token makers and creature copies. Spread counters across your threats and protect the board before a large attack.","mulligan":"Keep green mana, three lands, ramp, and a token maker or card-draw engine.","tip":"Token copies copy the printed or copied characteristics, not counters already on the original. Fractal makers place counters on each token they create.","keys":["Master Biomancer","Paradox Zone","Ezuri's Predation"]},
    "Silverquill Statement": {"route":"politics","pace":"POLITICAL MIDRANGE","complexity":"Intermediate","theme":"Breena rewards carefully chosen attacks with cards and counters while protective threats discourage retaliation.","plan":"Develop mana and let Breena reward attacks at players with more life. Grow evasive threats, redirect pressure through incentives, and keep protection for the closing turns.","mulligan":"Keep both colors, three lands, an early creature or mana rock, and an answer.","tip":"Breena’s trigger compares the attacked player’s life with another of your opponents. Plan attacks and counter placements before committing your strongest creature.","keys":["Felisa, Fang of Silverquill","Nils, Discipline Enforcer","Inkshield"]},
    "Witherbloom Witchcraft": {"route":"counters","pace":"LIFE AND COUNTERS","complexity":"Intermediate","theme":"Willowdusk converts life gained or lost into counters, backed by Food, lifelink, and graveyard recovery.","plan":"Build mana and repeatable life gain, then use Willowdusk to grow a creature after gaining or losing life. Turn lifelink attacks into larger future threats and recover key creatures from the graveyard.","mulligan":"Keep both colors, three lands, an early creature, and a life-gain or ramp play.","tip":"Willowdusk uses whichever is greater: life gained or life lost during the current turn. The ability can target any other creature and follows sorcery timing.","keys":["Gyome, Master Chef","Tivash, Gloom Summoner","Revival Experiment"]},
    'First Flight': {
      route:'fliers',pace:'FLYING MIDRANGE',complexity:'Approachable',
      theme:'A flying fleet backed by Isperia’s defensive card draw.',
      plan:'Develop mana and small fliers, then land Isperia while keeping an answer available. Attack through the air and use sweepers when the ground gets crowded.',
      mulligan:'Keep three lands with both colors, a mana rock or early flier, and an answer.',
      tip:'Isperia draws once for each creature attacking you or your planeswalker. Leave flying blockers when you need that deterrent.',
      keys:['Sephara, Sky\'s Blade','Thunderclap Wyvern','Windreader Sphinx'],
    },
    'Grave Danger': {
      route:'graveyard',pace:'ZOMBIE RECURSION',complexity:'Intermediate',
      theme:'Gisa and Geralf turn fallen Zombies into another turn of development.',
      plan:'Build mana, mill cards, and cast a Zombie from your graveyard on each of your turns. Use tribal boosts and mass reanimation to rebuild after removal.',
      mulligan:'Keep both colors, an early Zombie or mana rock, and a way to draw or fill the graveyard.',
      tip:'Gisa and Geralf allow one Zombie creature cast during each of your turns. You still pay its cost and follow normal timing.',
      keys:['Diregraf Captain','Grimoire of the Dead','Army of the Damned'],
    },
    'Chaos Incarnate': {
      route:'groupSlug',pace:'COMBAT AND SACRIFICE',complexity:'Intermediate',
      theme:'Kardur encourages opponents to attack each other while your finishers drain the table.',
      plan:'Develop mana and defensive creatures, then cast Kardur when opposing boards are ready to attack. Follow the trades with sacrifice effects, reanimation, and large flying threats.',
      mulligan:'Keep black and red mana, an early play or mana rock, and interaction.',
      tip:'Kardur’s attack requirement lasts until your next turn and also affects creatures opponents play during that time.',
      keys:['Archfiend of Depravity','Rakshasa Debaser','Fiery Confluence'],
    },
    'Draconic Destruction': {
      route:'dragons',pace:'DRAGON RAMP',complexity:'Approachable',
      theme:'Ramp into Dragons and turn Atarka’s double strike into decisive flying attacks.',
      plan:'Prioritize green mana and ramp, then cast Dragons with useful entry or attack triggers. Protect the board long enough for Atarka to give attacking Dragons double strike.',
      mulligan:'Keep three lands, green mana, ramp, and a Dragon you can cast after developing.',
      tip:'Atarka must be on the battlefield when a Dragon attacks to trigger. Savage Ventmaw’s attack mana remains available through your second main phase.',
      keys:['Savage Ventmaw','Drakuseth, Maw of Flames','Dragon Tempest'],
    },
    'Token Triumph': {
      route:'goWide',pace:'TOKENS AND CONVOKE',complexity:'Approachable',
      theme:'Emmara turns tapping into Soldiers, supported by convoke and team boosts.',
      plan:'Develop mana and token makers, tap Emmara for attacks or convoke, and build several bodies before using a team boost. Keep enough cards to rebuild after a sweeper.',
      mulligan:'Keep green and white mana, an early creature or token maker, and a payoff for a wide board.',
      tip:'Convoke can tap a creature with summoning sickness. Tapping Emmara this way still creates a lifelink Soldier.',
      keys:['Trostani Discordant','Felidar Retreat','Slate of Ancestry'],
    },
    'Abzan Armor': {
      route: 'defenders', pace: 'FORTRESS MIDRANGE', complexity: 'Approachable',
      theme: 'A living fortress where walls stop early attacks, then hit with their toughness.',
      plan: 'Build an untouchable defensive board, use defenders as mana and cards, then let Felothar turn toughness into combat power. The deck wins by changing roles faster than the table expects.',
      mulligan: 'Keep two or three lands, an early defender, and either ramp or a card-advantage piece.',
      tip: 'Do not expose every payoff at once. A few walls already discourage attacks; save the card that turns them aggressive for the turn you can use it.',
      keys: ['Betor, Ancestor\'s Voice', 'Baldin, Century Herdmaster', 'Blight Pile'],
    },
    'Animated Army': {
      route: 'bigCreatures', pace: 'STOMPY MIDRANGE', complexity: 'Approachable',
      theme: 'Bello wakes up harmless artifacts and enchantments as a charging 4/4 army.',
      plan: 'Ramp into mana value four artifacts and enchantments, then use Bello to animate them with haste. Your support pieces become attackers without giving up their normal engine text.',
      mulligan: 'Keep reliable green mana, one ramp spell, and at least one four-mana permanent for Bello to animate.',
      tip: 'Cast Bello after the engine pieces when possible. That gives opponents less time to remove him before the animated army attacks.',
      keys: ['Kodama of the East Tree', 'Etali, Primal Storm', 'Ghalta, Primal Hunger'],
    },
    'Avengers Assemble': {
      route: 'typal', pace: 'HEROIC MIDRANGE', complexity: 'Intermediate',
      theme: 'A Hero team-up deck that rewards assembling named threats instead of one lone attacker.',
      plan: 'Curve out with Heroes, grow the team through shared counters and triggers, and use Captain America to turn a broad cast into focused pressure. The deck is strongest when each new Hero improves the entire battlefield.',
      mulligan: 'Keep three colors of mana or fixing, an early Hero, and a payoff that rewards the team entering or attacking.',
      tip: 'Spread counters and Equipment before loading one creature. Your best turns come from preserving several relevant Heroes through removal.',
      keys: ['Iron Man, Armored Avenger', 'Captain Marvel, Apex Avenger', 'Falcon and Redwing'],
    },
    'Blight Curse': {
      route: 'counters', pace: 'ATTRITION CONTROL', complexity: 'Advanced',
      theme: 'Wither and -1/-1 counters shrink opposing boards while your own payoffs multiply.',
      plan: 'Place counters surgically, profit from creatures dying or being weakened, and let Auntie Ool keep the curse moving. The deck wins by turning removal into creatures, cards, and a board opponents cannot rebuild through.',
      mulligan: 'Keep black and green mana, an early counter source, and one payoff such as Hapatra or a death-value engine.',
      tip: 'A single counter can disable utility creatures and unlock your synergies. Save mass counter placement for the board that actually threatens you.',
      keys: ['Hapatra, Vizier of Poisons', 'Carnifex Demon', 'Necroskitter'],
    },
    'Counter Intelligence': {
      route: 'artifacts', pace: 'ARTIFACT ENGINE', complexity: 'Advanced',
      theme: 'A spacecraft command center that charges artifacts until ordinary pieces become win conditions.',
      plan: 'Develop cheap artifacts, place and proliferate counters, then use Inspirit to station a growing engine. You can win through a giant artifact board or by protecting an alternate-win counter piece.',
      mulligan: 'Keep three lands or two plus a mana rock, a cheap artifact, and one way to add or multiply counters.',
      tip: 'Count the counters you can create before choosing a line. Proliferate is strongest after several different permanents are already charged.',
      keys: ['Coretapper', 'Deepglow Skate', 'Darksteel Reactor'],
    },
    'Deep Clue Sea': {
      route: 'artifacts', pace: 'VALUE ENGINE', complexity: 'Advanced',
      theme: 'Every investigation becomes evidence, life, cards, and eventually a tidal wave of tokens.',
      plan: 'Make Clues early, multiply them with token doublers, and crack them when the draw also triggers another payoff. Morska turns patient investigation into a huge, evasive finisher.',
      mulligan: 'Keep fixing, an investigate source, and either a token multiplier or a payoff for drawing the second card.',
      tip: 'Uncracked Clues are stored choices. Do not cash them all in until the extra draws, token copies, or life gain matter.',
      keys: ['Academy Manufactor', 'Adrix and Nev, Twincasters', 'Esix, Fractal Bloom'],
    },
    'Doom Prevails': {
      route: 'graveyard', pace: 'VILLAIN CONTROL', complexity: 'Advanced',
      theme: 'Doctor Doom turns a cast of scheming Villains into connive, theft, and graveyard leverage.',
      plan: 'Loot away cards that are useful from the graveyard, disrupt the strongest rival, and use Villain triggers to keep resources flowing. Doom rewards precise sequencing more than raw speed.',
      mulligan: 'Keep blue, black, and red access, an early Villain, and either draw/connive or interaction.',
      tip: 'Choose what to discard as carefully as what to cast. Many of your best turns begin with placing the right card in the graveyard.',
      keys: ['Kang, Temporal Tyrant', 'Baron Strucker, HYDRA Overlord', 'Living Laser'],
    },
    'Elven Council': {
      route: 'politics', pace: 'POLITICAL VALUE', complexity: 'Intermediate',
      theme: 'An Elf council where public votes produce cards, creatures, and shifting alliances.',
      plan: 'Develop Elf mana, invite votes that are good for you in either outcome, and use the table\'s decisions to grow Galadriel\'s board. Your strongest position often looks helpful until it becomes lethal.',
      mulligan: 'Keep green mana, a one- or two-mana Elf, and a card that creates or rewards a council vote.',
      tip: 'Read what each opponent needs before calling the vote. The same options produce very different politics depending on who is behind.',
      keys: ['Elrond of the White Council', 'Erestor of the Council', 'Elvish Warmaster'],
    },
    'Endless Punishment': {
      route: 'groupSlug', pace: 'PUNISHER PRESSURE', complexity: 'Intermediate',
      theme: 'A haunted pressure cooker that makes every normal game action hurt.',
      plan: 'Install repeatable life-loss pieces, keep everyone playing into them, and grow Valgavoth from the damage. You are the clock, so finish before three opponents can combine their answers.',
      mulligan: 'Keep black and red mana, an early punisher permanent, and a draw or removal spell.',
      tip: 'Avoid dealing equal damage for no gain. Point interaction at the player who can remove your engine or race your clock.',
      keys: ['Blood Artist', 'Braids, Arisen Nightmare', 'Kaervek the Merciless'],
    },
    'Family Matters': {
      route: 'goWide', pace: 'AIRBORNE TOKENS', complexity: 'Intermediate',
      theme: 'Zinnia gives creatures offspring, creating smaller copies with the same useful abilities.',
      plan: 'Cast creatures whose enter-the-battlefield text is worth copying, pay offspring when the curve allows it, and fill the skies with value. The deck turns one good creature into two engines or two attackers.',
      mulligan: 'Keep all three colors or fixing, an early creature, and one creature whose ability is worth copying later.',
      tip: 'Offspring is optional. Skip the extra cost when it delays Zinnia or a more important engine, then double the premium creature later.',
      keys: ['Cloudblazer', 'Combat Celebrant', 'Inferno Titan'],
    },
    'Mardu Surge': {
      route: 'goWide', pace: 'AGGRESSIVE TOKENS', complexity: 'Intermediate',
      theme: 'Zurgo leads fresh waves of attackers that keep generating value as combat spreads around the table.',
      plan: 'Build token producers, attack where blocks are weakest, and multiply attack triggers across different defenders. The deck wants repeated profitable combats, not one reckless all-in swing.',
      mulligan: 'Keep three colors or strong fixing, an early token maker, and a payoff that rewards attacking with a team.',
      tip: 'Assign each attacker deliberately. Splitting combat can trigger more effects and deny one defender the chance to block everything.',
      keys: ['Adeline, Resplendent Cathar', 'Hero of Bladehold', 'Grenzo, Havoc Raiser'],
    },
    'Most Wanted': {
      route: 'politics', pace: 'TREASURE HEIST', complexity: 'Intermediate',
      theme: 'Olivia\'s Outlaws rob the open player, stockpile Treasure, and spend it on the next heist.',
      plan: 'Connect with evasive Outlaws, turn combat into Treasure, and use that burst of mana for theft or a powerful follow-up. Politics helps keep a safe target available without becoming passive.',
      mulligan: 'Keep Mardu fixing, a cheap evasive Outlaw, and either a Treasure payoff or interaction.',
      tip: 'Treasure is tempo, not decoration. Spend it when it creates another hit, steals the best permanent, or protects your lead.',
      keys: ['Academy Manufactor', 'Captain Lannery Storm', 'Breena, the Demagogue'],
    },
    'Prismari Artistry': {
      route: 'spells', pace: 'BIG-SPELL ENGINE', complexity: 'Advanced',
      theme: 'Prismari turns expressive instants and sorceries into copies, mana, and enormous Elementals.',
      plan: 'Build a creature-based spell engine, bank Treasures and cards, then cast and copy one spectacular spell. Rootha can rebuy the exact spell that makes the turn worth staging.',
      mulligan: 'Keep blue and red mana, a ramp or cost-reduction piece, and one spell-payoff creature.',
      tip: 'The largest spell is not always the best spell. Count every copy trigger and leave mana for the decision that protects the chain.',
      keys: ['Archmage Emeritus', 'Goldspan Dragon', 'Manaform Hellkite'],
    },
    'Quick Draw': {
      route: 'spells', pace: 'FAST SPELLSLINGER', complexity: 'Advanced',
      theme: 'Stella Lee rewards the second and third spell, turning cheap cantrips into explosive copy turns.',
      plan: 'Develop a payoff creature, use cheap spells to cross Stella\'s thresholds, and copy the spell that matters most. Patience turns a hand of small effects into one oversized turn.',
      mulligan: 'Keep two or three lands, one mana reducer or payoff creature, and at least two cheap spells.',
      tip: 'Sequence from least important to most important. Your copied spell should be the payoff, not the cantrip used to unlock it.',
      keys: ['Archmage Emeritus', 'Storm-Kiln Artist', 'Niv-Mizzet, Parun'],
    },
    'Squirreled Away': {
      route: 'goWide', pace: 'TOKEN ENGINE', complexity: 'Intermediate',
      theme: 'A woodland value engine where Food and Squirrels become mana, material, or damage.',
      plan: 'Build tokens without spending them too early, double the best token with Hazel, and convert sacrifices into table-wide pressure. Every token can change jobs as the game changes.',
      mulligan: 'Keep two or three lands, a ramp piece, and either a token maker or a sacrifice payoff.',
      tip: 'Treat Food as a flexible bank. It can stabilize life, fuel Hazel, or become an extra Squirrel and drain trigger at the right moment.',
      keys: ['Chatterfang, Squirrel General', 'Academy Manufactor', 'Nadier\'s Nightblade'],
    },
    'The Fantastic Four': {
      route: 'spells', pace: 'COMBO MIDRANGE', complexity: 'Advanced',
      theme: 'Marvel\'s first family turns every noncreature spell into another coordinated superpower.',
      plan: 'Assemble family members with complementary triggers, protect the engine, and cast noncreature spells in the order that produces the most value. The deck can pivot from control to a sudden combo finish.',
      mulligan: 'Keep four-color access or fixing, a low-cost family member, and a noncreature spell that advances the board.',
      tip: 'Resolve triggers in the order that preserves options. One small spell can create several abilities, targets, and copy decisions.',
      keys: ['Human Torch', 'Mister Fantastic', 'Galactus, Devourer of Worlds'],
    },
    'Turtle Power': {
      route: 'counters', pace: 'FIVE-COLOR TEAM-UP', complexity: 'Advanced',
      theme: 'The Turtles and their allies share counters, mutate the team, and attack as one five-color crew.',
      plan: 'Fix all five colors, choose the commander pair that supports the hand, and grow several Mutants through counters and combat triggers. The deck rewards coordinated attacks more than a single giant creature.',
      mulligan: 'Keep three colors plus fixing, an early Turtle or Mutant, and a source of counters or token growth.',
      tip: 'Your mana is the first puzzle. Prioritize color access before flashy plays, then choose attacks that advance multiple team triggers.',
      keys: ['Leonardo, the Balance', 'Michelangelo, the Heart', 'Donatello, the Brains'],
    },
    'Wakanda Forever': {
      route: 'artifacts', pace: 'MONARCH MIDRANGE', complexity: 'Intermediate',
      theme: 'Vibranium artifacts and the Monarch crown turn Wakanda into an accumulating resource advantage.',
      plan: 'Develop artifacts, claim or protect the Monarch, and let T\'Challa convert material into pressure. Equipment and artifact bodies give you both a defended throne and a powerful attack.',
      mulligan: 'Keep green and white mana, early artifact development, and a creature that can defend or reclaim the crown.',
      tip: 'Do not take the Monarch unless you can defend it. A delayed crown that draws two cards is better than gifting three cards around the table.',
      keys: ['Bast, Panther Goddess', 'Palace Jailer', 'Metalwork Colossus'],
    },
    'Scions & Spellcraft': {
      route: 'spells', pace: 'SPELL-DRAIN CONTROL', complexity: 'Advanced',
      theme: 'The Scions turn substantial noncreature spells into cards, life swings, and a patient table-wide drain.',
      plan: 'Build mana and card flow, land Y\'shtola when you can protect her, then cast mana value three-or-greater spells across several turns. The deck wins while answering threats, not by abandoning interaction.',
      mulligan: 'Keep Esper fixing, a mana rock or value permanent, and at least one meaningful noncreature spell.',
      tip: 'Use opponents\' turns. Instants can trigger Y\'shtola while preserving your own main phase for development and protection.',
      keys: ['Alisaie Leveilleur', 'Alphinaud Leveilleur', 'Archmage Emeritus'],
    },
    'Coven Counters': {
      route: 'counters', pace: 'CREATURE MIDRANGE', complexity: 'Approachable',
      theme: 'A growing Human fellowship where different power values unlock Coven and shared counters.',
      plan: 'Curve out with creatures of different sizes, spread +1/+1 counters, and trigger Coven without making every body identical. Leinore keeps the cards flowing while the team grows into combat.',
      mulligan: 'Keep green and white mana, two creatures at different points on the curve, and a counter source.',
      tip: 'Coven cares about three different powers. Place counters where they preserve that pattern instead of automatically growing the largest creature.',
      keys: ['Kyler, Sigardian Emissary', 'Mikaeus, the Lunarch', 'Verdurous Gearhulk'],
    },
    'Quandrix Unlimited': {
      route: 'counters', pace: 'X-SPELL ENGINE', complexity: 'Advanced',
      theme: 'Zimone turns extra lands and variable X spells into a rapidly expanding mathematical engine.',
      plan: 'Ramp and trigger landfall, use Zimone to reduce or reward the first X spell, and distribute counters where they create the best next turn. The deck scales from efficient setup to enormous Fractals and Hydras.',
      mulligan: 'Keep three lands or two plus ramp, a landfall/value piece, and an X spell that remains useful at several sizes.',
      tip: 'Plan the first X spell before tapping mana. The discount and counter triggers can change which X value is actually optimal.',
      keys: ['Zimone, Quandrix Prodigy', 'Hydroid Krasis', 'Primordial Hydra'],
    },
    'Dance of the Elements': {
      route: 'graveyard', pace: 'FIVE-COLOR REANIMATOR', complexity: 'Advanced',
      theme: 'Ashling conducts five-color Elementals through the battlefield and graveyard in one final dance.',
      plan: 'Fix colors with Elemental mana, fill the graveyard through trades and evoke effects, then recur the creatures whose enter/leave triggers matter most. Your graveyard becomes a second cast of characters.',
      mulligan: 'Keep green mana, color fixing, an early Elemental, and either self-mill or a recursion payoff.',
      tip: 'Track which Elementals are best to reuse, not just which are largest. Evoke can be setup when the death and graveyard placement both help.',
      keys: ['Risen Reef', 'Omnath, Locus of the Roil', 'Horde of Notions'],
    },
    'World Shaper': {
      route: 'lands', pace: 'LANDFALL ENGINE', complexity: 'Advanced',
      theme: 'A living worldship sacrifices lands for value, then returns them all in one tectonic turn.',
      plan: 'Develop mana while stocking lands in the graveyard, collect payoffs for sacrificing and replaying them, and use mass land return to trigger the whole engine at once. Hearthhull turns the setup into a threat of its own.',
      mulligan: 'Keep three lands, a ramp or self-mill piece, and one payoff for landfall or sacrifice.',
      tip: 'Do not sacrifice lands without a return path. The strongest lines gain a resource now and set up several landfall triggers later.',
      keys: ['Aftermath Analyst', 'Tireless Tracker', 'Mayhem Devil'],
    },
    'Limit Break': {
      route: 'equipment', pace: 'EQUIPMENT AGGRO', complexity: 'Intermediate',
      theme: 'Cloud equips a Final Fantasy party, turning modified heroes into a focused combat squad.',
      plan: 'Deploy cheap Equipment and equip-cost support, connect with modified creatures, and move the best gear to the attacker that creates the safest advantage. Cloud converts preparation into a decisive Limit Break.',
      mulligan: 'Keep Naya fixing, one cheap Equipment, and a creature or support piece that reduces equip friction.',
      tip: 'Equipment survives creature removal. Build the armory first, then commit it to the hero most likely to connect this turn.',
      keys: ['Puresteel Paladin', 'Zack Fair', 'Red XIII, Proud Warrior'],
    },
    'Temur Roar': {
      route: 'bigCreatures', pace: 'DRAGON RAMP', complexity: 'Approachable',
      theme: 'Temur ramp opens the skies for hasty Dragons and punishing attack triggers.',
      plan: 'Accelerate mana and reduce Dragon costs, deploy one threat that demands an answer, then let Ureni find more Dragons as combat begins. Haste keeps the deck from giving the table a full turn to prepare.',
      mulligan: 'Keep green mana, a ramp or cost-reduction spell, and one Dragon you can realistically cast on curve.',
      tip: 'Do not fill the hand with only seven-drops. One early reducer often deals more eventual damage than another spectacular Dragon.',
      keys: ['Sarkhan, Soul Aflame', 'Lathliss, Dragon Queen', 'Dragonlord Atarka'],
    },
    'Sultai Arisen': {
      route: 'graveyard', pace: 'GRAVEYARD VALUE', complexity: 'Advanced',
      theme: 'Teval turns self-mill and fallen creatures into a deep, reusable Sultai resource pool.',
      plan: 'Mill deliberately, trade creatures for value, and recur the exact answer or threat the table demands. The deck wins long games because its spent cards keep returning in stronger combinations.',
      mulligan: 'Keep all three colors or fixing, self-mill, and a recursion or payoff card that can use the stocked graveyard.',
      tip: 'Know what can be recovered before milling aggressively. Protect the recursion spell that turns a full graveyard into a real board.',
      keys: ['Meren of Clan Nel Toth', 'Living Death', 'Lord of Extinction'],
    },
    'Jeskai Striker': {
      route: 'spells', pace: 'PROWESS TEMPO', complexity: 'Advanced',
      theme: 'Shiko and Narset make the second spell each turn the center of a precise Jeskai tempo engine.',
      plan: 'Develop a token or prowess payoff, cast the first spell to set the turn, and make the second spell the one worth copying or rewarding. Playing on multiple turns keeps the engine producing without emptying your hand.',
      mulligan: 'Keep Jeskai fixing, a cheap payoff creature, and two low-cost spells with different jobs.',
      tip: 'Count spells separately on every turn. A cheap instant on an opponent\'s turn can create another full second-spell reward cycle.',
      keys: ['Monastery Mentor', 'Veyran, Voice of Duality', 'Archmage Emeritus'],
    },
  });
})();
