import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,play,activate,settle,fuel} from './helpers/afc-mic-fixtures.mjs';
const target=(f,c)=>{f.decide=(p,q)=>q.type==='chooseTargets'?[c]:undefined;};
for(const role of ['human','ai']){
 test(role+': Galea casts top Equipment and attaches on entry',async()=>{const f=setup(role),g=await play(f,'Galea, Kindler of Hope'),s=card(f,'Sword of Hours','library');target(f,g);const e=f.game.castableList(f.a).find(e=>e.card===s);assert.ok(e);await play(f,s.name,{card:s,alt:e.alt});assert.equal(s.attachedTo,g.iid);});
 test(role+': Minimus turns a creature into a Treasure with only its granted mana ability',async()=>{const f=setup(role),e=card(f,'Llanowar Elves','battlefield',f.b);target(f,e);await play(f,'Minimus Containment');assert.equal(e.is('Creature'),false);assert.equal(e.is('Artifact'),true);assert.equal(e.hasSub('Treasure'),true);assert.deepEqual([...e.colors],['G']);const sources=f.game.manaSources(f.b).filter(s=>s.card===e);assert.equal(sources.length,1);assert.equal(sources[0].m.cost.sacSelf,true);});
 test(role+': Imprisoned in the Moon is a colorless land and loses abilities',async()=>{const f=setup(role),e=card(f,'Llanowar Elves','battlefield',f.b);target(f,e);await play(f,'Imprisoned in the Moon');assert.equal(e.is('Creature'),false);assert.equal(e.is('Land'),true);assert.deepEqual([...e.colors],[]);const sources=f.game.manaSources(f.b).filter(s=>s.card===e);assert.equal(sources.length,1);assert.deepEqual(JSON.parse(JSON.stringify(sources[0].produce)),[{C:1}]);});
 test(role+': Utopia Sprawl grants the chosen color in addition to Forest mana',async()=>{const f=setup(role),l=card(f,'Forest');f.decide=(p,q)=>q.type==='chooseTargets'?[l]:q.type==='chooseOption'&&q.options.some(o=>o.key==='U')?'U':undefined;await play(f,'Utopia Sprawl');for(const k in f.a.pool)f.a.pool[k]=0;const s=f.game.manaSources(f.a).find(s=>s.card===l);await f.game.activateManaSource(f.a,s,s.produce[0]);assert.equal(f.a.pool.G,1);assert.equal(f.a.pool.U,1);});
 test(role+': Midnight Pathlighter allows only legendary blockers',async()=>{const f=setup(role);await play(f,'Midnight Pathlighter');const a=card(f,'Grizzly Bears'),b=card(f,'Grizzly Bears','battlefield',f.b),l=card(f,'Nihiloor','battlefield',f.b);assert.equal(f.game.canBlock(b,a),false);assert.equal(f.game.canBlock(l,a),true);});
 test(role+': Crowded Crypt counts dead creatures then creates that many decayed Zombies',async()=>{const f=setup(role),c=await play(f,'Crowded Crypt'),b=card(f,'Grizzly Bears');await f.game.sacrifice(f.a,b);await settle(f.game);assert.equal(c.counters.corpse,1);await activate(f,c);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.kw('decayed')).length,1);});
 test(role+': Cleaver Skaab cannot sacrifice itself and makes two copies of another Zombie',async()=>{const f=setup(role),c=await play(f,'Cleaver Skaab'),z=card(f,'Tomb Tyrant');c.sick=false;f.decide=(p,q)=>q.type==='chooseCards'&&q.from.includes(z)?[z]:undefined;await activate(f,c);assert.equal(c.zone,'battlefield');assert.equal(z.zone,'graveyard');const made=f.game.creatures(f.a).filter(c=>c.isToken&&c.name==='Tomb Tyrant');assert.equal(made.length,2);assert.equal(made[0].def.afcGorex,undefined);});
 test(role+': Grim Hireling creates two Treasures per player hit by a combat damage event',async()=>{const f=setup(role,2);await play(f,'Grim Hireling');const a=card(f,'Grizzly Bears'),b=card(f,'Grizzly Bears');await f.game.damageBatch([{src:a,target:f.b,n:2,opts:{combat:true}},{src:b,target:f.b,n:2,opts:{combat:true}},{src:b,target:f.others[1],n:1,opts:{combat:true}}]);await settle(f.game);assert.equal(f.game.bf().filter(c=>c.hasSub('Treasure')).length,4);});
 test(role+': Hordewing loots once for the number of opponents damaged',async()=>{const f=setup(role,2);await play(f,'Hordewing Skaab');const a=card(f,'Wilhelt, the Rotcleaver'),b=card(f,'Tomb Tyrant'),h=f.a.hand.length;f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await f.game.damageBatch([{src:a,target:f.b,n:2,opts:{combat:true}},{src:b,target:f.others[1],n:2,opts:{combat:true}}]);await settle(f.game);assert.equal(f.a.turnState.drewThisTurn,2);assert.equal(f.a.hand.length,h);});
 test(role+': Wulfgar doubles a controlled attack trigger',async()=>{const f=setup(role);await play(f,'Wulfgar of Icewind Dale');const c=card(f,'Chaos Channeler');await f.game.emit('attacks',{card:c,player:f.a,defender:f.b});assert.equal(f.game.pendingTriggers.filter(t=>t.src===c).length,2);});
 test(role+': Minn creates an Illusion on the second draw only and returns a small permanent on death',async()=>{const f=setup(role);await play(f,'Minn, Wily Illusionist');await f.game.draw(f.a,3);await settle(f.game);const t=f.game.creatures(f.a).find(c=>c.isToken&&c.hasSub('Illusion'));assert.ok(t);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken).length,1);const e=card(f,'Llanowar Elves','hand');f.decide=(p,q)=>q.type==='chooseCards'&&q.from.includes(e)?[e]:undefined;await f.game.sacrifice(f.a,t);await settle(f.game);assert.equal(e.zone,'battlefield');});
 test(role+': Ghouls Night Out adds black Zombie and decayed before entry',async()=>{const f=setup(role),a=card(f,'Grizzly Bears','graveyard'),b=card(f,'Llanowar Elves','graveyard',f.b);await play(f,"Ghouls' Night Out");for(const c of [a,b]){assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);assert.equal(c.hasSub('Zombie'),true);assert.equal(c.colors.includes('B'),true);assert.equal(c.colors.includes('G'),true);assert.equal(c.kw('decayed'),true);}});
 test(role+': Hour of Eternity exiles exactly X creatures and creates 4/4 black Zombie copies',async()=>{const f=setup(role),a=card(f,'Grizzly Bears','graveyard');target(f,a);await play(f,'Hour of Eternity',{xVal:1});assert.equal(a.zone,'exile');const t=f.game.creatures(f.a).find(c=>c.isToken);assert.ok(t);assert.equal(t.power,4);assert.deepEqual([...t.colors],['B']);assert.deepEqual([...t.cur.subtypes],['Zombie']);});
 test(role+': Shadow Kin mills each player and copies a chosen creature retaining the upkeep ability',async()=>{const f=setup(role),s=await play(f,'Shadow Kin'),a=card(f,'Grizzly Bears','library');f.decide=(p,q)=>q.type==='chooseCards'&&q.from.includes(a)?[a]:undefined;await f.game.emit('upkeep',{player:f.a});await settle(f.game);assert.equal(a.zone,'exile');assert.equal(s.name,'Grizzly Bears');assert.equal(s.power,2);assert.ok(s.def.triggers.some(t=>t.on==='upkeep'));});
 test(role+': Nihiloor takes a creature while controlled, then gives it back on departure',async()=>{const f=setup(role),b=card(f,'Grizzly Bears','battlefield',f.b),mine=card(f,'Grizzly Bears');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Nihiloor:')?(q.from.includes(mine)?[mine]:[]):q.type==='chooseTargets'?[b]:undefined;const n=await play(f,'Nihiloor');assert.equal(b.ctrl,f.a);assert.equal(mine.tapped,true);await f.game.move(n,'graveyard');assert.equal(b.ctrl,f.b);});
 test(role+': Gryff Boon and Death Tyrant return directly from graveyard',async()=>{const f=setup(role),b=card(f,'Grizzly Bears'),a=card(f,"Gryff's Boon",'graveyard');target(f,b);fuel(f.a);let e=f.game.activatableList(f.a).find(e=>e.card===a&&e.gyAbility);assert.ok(e);await f.game.activateAbility(f.a,e);await settle(f.game);assert.equal(a.zone,'battlefield');assert.equal(a.attachedTo,b.iid);const d=card(f,'Death Tyrant','graveyard');e=f.game.activatableList(f.a).find(e=>e.card===d&&e.gyAbility);assert.ok(e);await f.game.activateAbility(f.a,e);await settle(f.game);assert.equal(d.zone,'battlefield');assert.equal(d.tapped,true);});
 test(role+': complete Tomb of Annihilation creates the legendary Atropal',async()=>{const f=setup(role);let keys=['tomb','oubliette'];f.decide=(p,q)=>q.type==='chooseOption'&&/choose a dungeon|choose the next room/.test(q.prompt)?keys.shift():undefined;for(let i=0;i<3;i++){await f.game.venture(f.a);await settle(f.game);}assert.equal(f.a.afcCompletedDungeons,1);const t=f.game.creatures(f.a).find(c=>c.name==='The Atropal');assert.ok(t);assert.equal(t.power,4);assert.equal(t.kw('deathtouch'),true);assert.equal(t.cur.super.includes('Legendary'),true);});
}
