import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,play,activate,settle,fuel} from './helpers/afc-mic-fixtures.mjs';
const pick=(f,c)=>{f.decide=(p,q)=>q.type==='chooseTargets'?q.candidates.includes(c)?[c]:[]:undefined;};
for(const role of ['human','ai']){
 test(role+': Prosper grants next-turn play and creates Treasure for exile spell and land',async()=>{const f=setup(role);await play(f,'Prosper, Tome-Bound');const c=card(f,'Grizzly Bears','library');await f.game.emit('endStep',{player:f.a});await settle(f.game);assert.equal(c.zone,'exile');assert.ok(f.game.castableList(f.a).some(e=>e.card===c));await play(f,c.name,{card:c});assert.equal(f.game.bf().filter(c=>c.hasSub('Treasure')).length,1);const land=card(f,'Forest','exile');M.AFC.playGrant({g:f.game,you:f.a},land);await f.game.playLand(f.a,land);await settle(f.game);assert.equal(f.game.bf().filter(c=>c.hasSub('Treasure')).length,2);});
 test(role+': Hostage Taker returns exact exiled object and does not exile after leaving',async()=>{const f=setup(role),b=card(f,'Grizzly Bears','battlefield',f.b);pick(f,b);const h=await play(f,'Hostage Taker');assert.equal(b.zone,'exile');await f.game.move(h,'graveyard');assert.equal(b.zone,'battlefield');assert.equal(b.ctrl,f.b);const h2=card(f,'Hostage Taker','hand');fuel(f.a);await f.game.castSpell(f.a,h2);await f.game.resolveTop();await f.game.move(h2,'graveyard');await settle(f.game);assert.equal(b.zone,'battlefield');});
 test(role+': Rooftop Storm offers zero mana and still charges commander tax',async()=>{const f=setup(role);await play(f,'Rooftop Storm');for(const k in f.a.pool)f.a.pool[k]=0;const c=card(f,'Wilhelt, the Rotcleaver','command');c.commander=true;c.cmdCasts=0;const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.afcRooftop);assert.ok(e);assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),true);await settle(f.game);await f.game.move(c,'command');c.cmdCasts=1;assert.equal(f.game.castableList(f.a).some(e=>e.card===c),false);f.a.pool.C=2;assert.equal(f.game.castableList(f.a).some(e=>e.card===c&&e.alt?.afcRooftop),true);});
 test(role+': Gorex pays an additional exile cost and later returns the linked card',async()=>{const f=setup(role),a=card(f,'Grizzly Bears','graveyard'),b=card(f,'Llanowar Elves','graveyard');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.startsWith('Gorex:')?[a,b]:undefined;fuel(f.a);const c=await play(f,'Gorex, the Tombshell');assert.equal(a.zone,'exile');assert.equal(b.zone,'exile');await f.game.emit('attacks',{card:c,player:f.a,defender:f.b});await settle(f.game);assert.equal([a,b].filter(c=>c.zone==='hand').length,1);});
 test(role+': Rod of Absorption exiles only on resolution and spends a total X budget',async()=>{const f=setup(role),r=await play(f,'Rod of Absorption');await play(f,'Ponder');assert.equal(M.AFC.linked(M.AFC.linkState(r,'afcAbsorb')).length,1);f.x=1;await activate(f,r);assert.equal(r.zone,'graveyard');assert.equal(f.a.graveyard.some(c=>c.name==='Ponder'),true);});
 test(role+': Share the Spoils permission follows the active player and refills after use',async()=>{const f=setup(role),a=card(f,'Forest','library'),b=card(f,'Grizzly Bears','library',f.b);const s=await play(f,'Share the Spoils');assert.equal(a.zone,'exile');assert.ok(f.game.playableLands(f.a).includes(a));assert.equal(f.game.castableList(f.b).some(e=>e.card===b),false);const top=card(f,'Mountain','library');await f.game.playLand(f.a,a);await settle(f.game);assert.equal(top.zone,'exile');await f.game.move(s,'graveyard');assert.equal(f.game.playableLands(f.a).includes(top),false);});
 test(role+': Lorcan adds Warlock before entry and replaces its death with exile',async()=>{const f=setup(role);await play(f,'Lorcan, Warlock Collector');const b=card(f,'Grizzly Bears','hand',f.b);f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('collect the creature')?'yes':undefined;await f.game.move(b,'graveyard');await settle(f.game);assert.equal(b.zone,'battlefield');assert.equal(b.ctrl,f.a);assert.equal(b.hasSub('Warlock'),true);assert.equal(f.a.life,38);await f.game.destroy(b);assert.equal(b.zone,'exile');});
 test(role+': Ride the Avalanche grants flash to only the next spell and captures mana value',async()=>{const f=setup(role),b=card(f,'Grizzly Bears');await play(f,'Ride the Avalanche');f.game.turnPlayer=f.b;f.game.phase='combat';const c=card(f,'Llanowar Elves','hand');assert.equal(f.game.canCastTiming(f.a,c,{}),true);pick(f,b);await play(f,c.name,{card:c});assert.equal(b.counters['+1/+1'],1);const d=card(f,'Grizzly Bears','hand');assert.equal(f.game.canCastTiming(f.a,d,{}),false);});
 test(role+': Undead Alchemist exiles each milled creature once and makes one Zombie per card',async()=>{const f=setup(role);await play(f,'Undead Alchemist');const a=card(f,'Grizzly Bears','library',f.b),b=card(f,'Llanowar Elves','library',f.b);await f.game.mill(f.b,2);await settle(f.game);assert.equal(a.zone,'exile');assert.equal(b.zone,'exile');assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Zombie')).length,2);});
}
