import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,play,activate,settle,fuel} from './helpers/afc-mic-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Barbarian Class ignores lowest dice and triggers once per group',async()=>{const f=setup(role);const b=await play(f,'Barbarian Class'),bear=card(f,'Grizzly Bears');await activate(f,b,0);let seq=[0,.9,.4],i=0;f.game.rnd=()=>seq[i++];const dice=await f.game.rollDice(f.a,6,2);assert.deepEqual([...dice],[3,6]);assert.equal(f.game.pendingTriggers.filter(t=>t.src===b).length,1);await settle(f.game);assert.equal(bear.power,4);assert.equal(bear.kw('menace'),true);});
 test(role+': natural maximum draws; ignored rolls do not trigger Puzzle-Ward',async()=>{const f=setup(role);await play(f,'Netherese Puzzle-Ward');const h=f.a.hand.length;f.game.rnd=()=>.999;await f.game.rollDice(f.a,4,2);await settle(f.game);assert.equal(f.a.hand.length,h+2);});
 test(role+': Vrondiss pays five mana and creates a 5/4 Spirit from self damage',async()=>{const f=setup(role);const c=await play(f,'Vrondiss, Rage of Ancients');await f.game.rollDice(f.a,6);await settle(f.game);const t=f.game.creatures(f.a).find(x=>x.isToken&&x.hasSub('Spirit'));assert.ok(t);assert.equal(t.power,5);assert.equal(t.toughness,4);await f.game.damageAny(t,f.b,5);await settle(f.game);assert.notEqual(t.zone,'battlefield');assert.equal(c.zone,'battlefield');});
 test(role+': Grave Endeavor returns with counters before ETB and drains the other die',async()=>{const f=setup(role);const c=card(f,'Grizzly Bears','graveyard');f.game.rnd=()=>.4;await play(f,'Grave Endeavor');assert.equal(c.zone,'battlefield');assert.equal(c.counters['+1/+1'],5);assert.equal(f.b.life,35);assert.equal(f.a.life,45);});
 test(role+': Neverwinter Hydra rolls X dice and counters are its sum',async()=>{const f=setup(role);f.game.rnd=()=>.5;const c=await play(f,'Neverwinter Hydra',{xVal:3});assert.equal(c.counters['+1/+1'],12);assert.equal(c.power,12);});
 test(role+': Clay Golem rolls as a cost, monstrosity resolves once',async()=>{const f=setup(role),c=await play(f,'Clay Golem'),b=card(f,'Grizzly Bears','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseTargets'?q.candidates.includes(b)?[b]:q.candidates.slice(0,q.max):undefined;fuel(f.a);f.game.rnd=()=>.5;const entry=f.game.activatableList(f.a).find(e=>e.card===c);await f.game.activateAbility(f.a,entry);assert.equal(c.counters['+1/+1']||0,0);assert.equal(f.game.stack.at(-1).ctx.afcDiceCost,5);await settle(f.game);assert.equal(c.counters['+1/+1'],5);assert.equal(b.zone,'graveyard');});
 test(role+': Component Pouch has no mana before a counter and spends one counter for two distinct colors',async()=>{const f=setup(role),c=await play(f,'Component Pouch');assert.equal(f.game.manaSources(f.a).some(s=>s.card===c),false);f.game.rnd=()=>.6;await activate(f,c);assert.equal(c.counters.component,2);f.game.untap(c);const sources=f.game.manaSources(f.a).filter(s=>s.card===c);assert.ok(sources.length);assert.ok(sources[0].produce.every(p=>Object.keys(p).length===2));});
 test(role+': Ebony Fly animation keeps Artifact and gains flying',async()=>{const f=setup(role),c=await play(f,'Ebony Fly');f.game.rnd=()=>.5;await activate(f,c);assert.equal(c.is('Artifact'),true);assert.equal(c.is('Creature'),true);assert.equal(c.power,4);assert.equal(c.kw('flying'),true);});
}
test('zero dice produces no roll trigger',async()=>{const f=setup();await play(f,'Vrondiss, Rage of Ancients');await f.game.rollDice(f.a,6,0);assert.equal(f.game.pendingTriggers.length,0);});
