import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,play,activate,settle,fuel} from './helpers/afc-mic-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Karazikar taps and goads the attacked player creature until your next turn',async()=>{const f=setup(role,3),k=await play(f,'Karazikar, the Eye Tyrant'),b=card(f,'Grizzly Bears','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseTargets'?[b]:undefined;await f.game.emit('attackedPlayer',{player:f.a,defender:f.b,attackers:[k]});await settle(f.game);assert.equal(b.tapped,true);assert.ok(f.game.untilEffects.some(e=>e.kind==='goadCard'&&e.iid===b.iid&&e.notPlayer===f.a&&e.expires==='untilTurnOf'&&e.whoTurn===f.a));f.game.untap(b);assert.equal(f.game.isForcedToAttack(b),true);});
 test(role+': Wild-Magic grants cascade only to the first spell from exile that turn',async()=>{const f=setup(role);await play(f,'Wild-Magic Sorcerer');const c=card(f,'Sol Ring','exile');M.AFC.playGrant({g:f.game,you:f.a},c);fuel(f.a);await f.game.castSpell(f.a,c,{from:'exile',alt:f.game.castableList(f.a).find(e=>e.card===c).alt});assert.ok([...f.game.stack,...f.game.pendingTriggers].some(t=>/Cascade/.test(t.name)));await settle(f.game);const b=card(f,'Sol Ring','exile');M.AFC.playGrant({g:f.game,you:f.a},b);await f.game.castSpell(f.a,b,{from:'exile',alt:f.game.castableList(f.a).find(e=>e.card===b).alt});assert.equal([...f.game.stack,...f.game.pendingTriggers].some(t=>/Cascade/.test(t.name)),false);});
 test(role+': Warlock Class level two puts exactly one in hand and two into graveyard',async()=>{const f=setup(role),w=await play(f,'Warlock Class'),a=card(f,'Grizzly Bears','library'),b=card(f,'Sol Ring','library'),c=card(f,'Forest','library');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Warlock Class:')?[a]:undefined;await activate(f,w);assert.equal(a.zone,'hand');assert.equal(b.zone,'graveyard');assert.equal(c.zone,'graveyard');});
 test(role+': Dead Mans Chest exiles exactly the dead creature power with continuing casting permission',async()=>{const f=setup(role),b=card(f,'Grizzly Bears','battlefield',f.b),a=card(f,'Sol Ring','library',f.b),c=card(f,'Ponder','library',f.b);f.decide=(p,q)=>q.type==='chooseTargets'?[b]:undefined;await play(f,"Dead Man's Chest");await f.game.destroy(b);await settle(f.game);assert.equal(a.zone,'exile');assert.equal(c.zone,'exile');assert.ok(f.game.castableList(f.a).some(e=>e.card===a));});
 test(role+': Curse of Unbinding reanimates the first creature and mills only the revealed remainder',async()=>{const f=setup(role),c=card(f,'Grizzly Bears','library',f.b),a=card(f,'Sol Ring','library',f.b),b=card(f,'Forest','library',f.b);f.decide=(p,q)=>q.type==='chooseTargets'?[f.b]:undefined;await play(f,'Curse of Unbinding');await f.game.emit('upkeep',{player:f.b});await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);assert.equal(a.zone,'graveyard');assert.equal(b.zone,'graveyard');});
 test(role+': Bag of Devouring links a sacrificed creature and returns it after a die roll',async()=>{const f=setup(role),bag=await play(f,'Bag of Devouring'),b=card(f,'Grizzly Bears');f.decide=(p,q)=>q.type==='chooseCards'&&q.from.includes(b)?[b]:undefined;await activate(f,bag,0);assert.equal(b.zone,'exile');f.game.untap(bag);f.game.rnd=()=>.99;await activate(f,bag,1);assert.equal(b.zone,'hand');});
 test(role+': Klauth mana persists across steps and cannot pay activated abilities',async()=>{const f=setup(role),k=await play(f,'Klauth, Unrivaled Ancient');for(const x in f.a.pool)f.a.pool[x]=0;k.attacking=f.b;f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='G')?'G':undefined;await f.game.emit('attacks',{card:k,player:f.a,defender:f.b});await settle(f.game);assert.equal(f.a.pool.G,4);f.game.emptyPool();assert.equal(f.a.pool.G,4);const c=card(f,'Grizzly Bears','hand');assert.equal(f.game.canPayMana(f.a,M.parseCost('{4}'),{card:c,castOpts:{}}),true);assert.equal(f.game.canPayMana(f.a,M.parseCost('{4}'),{card:k,isAbility:true}),false);});
 test(role+': Hellish Rebuke applies to sources already on the battlefield and sacrifices the damaging source',async()=>{const f=setup(role),b=card(f,'Grizzly Bears','battlefield',f.b);await play(f,'Hellish Rebuke');await f.game.damageAny(b,f.a,2);await settle(f.game);assert.equal(b.zone,'graveyard');assert.equal(f.b.life,38);});
 test(role+': Dark Salvation creates X Zombies then shrinks a creature by the Zombie count',async()=>{const f=setup(role),b=card(f,'Colossal Dreadmaw','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseTargets'?q.candidates.includes(f.a)?[f.a]:[b]:undefined;await play(f,'Dark Salvation',{xVal:2});assert.equal(f.game.creatures(f.a).filter(c=>c.hasSub('Zombie')).length,2);assert.equal(b.power,4);assert.equal(b.toughness,4);});
}
