import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,play,activate,settle,fuel} from './helpers/afc-mic-fixtures.mjs';
const route=(f,keys)=>{f.decide=(p,q)=>q.type==='chooseOption'&&/choose a dungeon|choose the next room/.test(q.prompt)?keys.shift():undefined;};
for(const role of ['human','ai']){
 test(role+': complete Lost Mine through legal rooms and Sefris reanimates',async()=>{const f=setup(role);await play(f,'Sefris of the Hidden Ways');const c=card(f,'Grizzly Bears','graveyard');route(f,['mine','tunnels','pool']);for(let i=0;i<4;i++){await f.game.venture(f.a);await settle(f.game);}assert.equal(f.a.afcDungeon,null);assert.equal(f.a.afcCompletedDungeons,1);assert.equal(c.zone,'battlefield');assert.ok(f.game.bf().some(c=>c.ctrl===f.a&&c.hasSub('Treasure')));});
 test(role+': Hama doubles a room ability, and dungeon state survives JSON restore',async()=>{const f=setup(role);await play(f,'Hama Pashar, Ruin Seeker');route(f,['mage']);const hp=f.a.life;await f.game.venture(f.a);assert.equal(f.game.pendingTriggers.length,2);await settle(f.game);assert.equal(f.a.life,hp+2);const state=M.captureGameState(f.game);assert.ok(state,M.gameStateSnapshotBlockers(f.game).join(', '));const next=setup();M.restoreGameState(next.game,JSON.parse(JSON.stringify(state)));assert.equal(next.a.afcDungeon.key,'mage');assert.equal(next.a.afcDungeon.room,'portal');});
 test(role+': Sefris triggers once per turn for a simultaneous graveyard batch',async()=>{const f=setup(role),s=await play(f,'Sefris of the Hidden Ways');const a=card(f,'Grizzly Bears'),b=card(f,'Llanowar Elves');route(f,['mine']);await f.game.destroyMany([a,b]);assert.equal(f.game.pendingTriggers.filter(t=>t.src===s).length,1);await settle(f.game);const c=card(f,'Grizzly Bears');await f.game.destroy(c);assert.equal(f.game.pendingTriggers.filter(t=>t.src===s).length,0);});
 test(role+': Wilhelt does not replace a dead decayed Zombie',async()=>{const f=setup(role),w=await play(f,'Wilhelt, the Rotcleaver');const z=(await f.game.makeTokens(M.AFC.zombie(),f.a))[0];await f.game.sacrifice(f.a,z);await settle(f.game);const d=f.game.creatures(f.a).find(c=>c.isToken&&c.kw('decayed'));assert.ok(d);assert.equal(d.cur.cantBlock,true);await f.game.sacrifice(f.a,d);assert.equal(f.game.pendingTriggers.filter(t=>t.src===w).length,0);});
 test(role+': Rod removes abilities until it untaps, then ventures',async()=>{const f=setup(role),rod=await play(f,'Immovable Rod'),elf=card(f,'Llanowar Elves','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseTargets'?[elf]:q.type==='chooseOption'&&q.options.some(o=>o.key==='mine')?'mine':undefined;await activate(f,rod);assert.equal(elf.cur.abilitiesDisabled,true);assert.equal(elf.cur.cantAttack,true);f.game.untap(rod);await f.game.flushRuleEvents();await settle(f.game);assert.equal(elf.cur.abilitiesDisabled,false);assert.equal(f.a.afcDungeon.key,'mine');});
}
test('save/restore keeps decayed, Dragon Spirit sacrifice ability, and empty dungeon state',async()=>{const f=setup();const [z]=await f.game.makeTokens(M.AFC.zombie(true),f.a),[s]=await f.game.makeTokens(M.TOKENS.afcDragonSpirit,f.a);const save=M.captureGameState(f.game);assert.ok(save,M.gameStateSnapshotBlockers(f.game).join(', '));const fresh=setup();M.restoreGameState(fresh.game,JSON.parse(JSON.stringify(save)));assert.equal(fresh.a.afcDungeon,null);const dz=fresh.game.byIid(z.iid),ds=fresh.game.byIid(s.iid);assert.equal(dz.kw('decayed'),true);assert.equal(dz.cur.cantBlock,true);await fresh.game.damageAny(ds,fresh.b,5);await settle(fresh.game);assert.notEqual(ds.zone,'battlefield');const invalid=structuredClone(save);invalid.players[0].afcDungeon={id:1,key:'invalid',room:'invalid'};assert.throws(()=>M.restoreGameState(fresh.game,invalid),/invalid dungeon progress/);});
test('Live view carries public dungeon progress while preserving private hands',async()=>{const f=setup();f.a.onlineSeat=0;f.b.onlineSeat=1;const privateCard=card(f,'Grizzly Bears','hand');f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='mage')?'mage':undefined;await f.game.venture(f.a);await settle(f.game);const model=new M.OnlineArenaView();model.update(JSON.parse(JSON.stringify(M.onlineGameViewFor(f.game,f.b))),1);assert.equal(model.players[0].afcDungeon.key,'mage');assert.equal(model.players[0].afcDungeon.room,'portal');assert.equal(model.players[0].hand[0].name,'Hidden card');assert.notEqual(model.players[0].hand[0].name,privateCard.name);});
test('Galea lets only its controller see the library top in Live views',async()=>{const f=setup();f.a.onlineSeat=0;f.b.onlineSeat=1;await play(f,'Galea, Kindler of Hope');const top=card(f,'Sword of Hours','library');assert.equal(M.onlineGameViewFor(f.game,f.a).players[0].libraryTop.name,top.name);assert.equal(M.onlineGameViewFor(f.game,f.b).players[0].libraryTop,null);});
