import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {M,setup,card,body,play,activate,event,settle,fuel,mana} from './helpers/c21-fixtures.mjs';
import {buildIntake} from '../scripts/import-blc-dsc-sld-drc-fic-precons.mjs';
const count=(c,k='+1/+1')=>c.counters[k]||0;
const choose=(f,fn)=>{f.decide=(p,q)=>fn(p,q);};

test('all ten original lists retain 100 cards, exact quantities and native rules',()=>{
 const intake=buildIntake(M);assert.equal(intake.decks.length,10);assert.equal(intake.newNames.length,0);
 for(const d of intake.decks){assert.equal(d.cards.reduce((n,c)=>n+c.n,0),100);assert.deepEqual(JSON.parse(JSON.stringify(M.DECKS[d.name].cards)),d.cards);for(const c of d.cards){assert.ok(M.DEFS[c.name]);assert.equal(!!M.DEFS[c.name].simplified,false);assert.equal(!!M.DEFS[c.name].autoScripted,false);}}
 const initial=JSON.parse(fs.readFileSync(new URL('../reports/decks/precon-blc-dsc-sld-drc-fic-2026-09-12/intake.json',import.meta.url)));assert.equal(initial.newCards,156);assert.equal(initial.reusedCards,559);
 for(const d of intake.decks){assert.ok(M.DECK_META[d.name].set);assert.deepEqual([...M.DECK_META[d.name].colors].sort(),[...M.CARD_CATALOG[d.commander].colorIdentity].sort());const guide=M.DECK_GUIDES[d.name];assert.ok(M.DECK_GUIDE_ROUTES[guide.route].length===3);assert.ok(guide.keys.every(k=>d.cards.some(c=>c.name===k)));assert.ok(M.DECK_AI_PROFILES[d.name]);assert.ok(M.cardImageURL(d.commander,'art').endsWith('.webp'));}
});
for(const role of ['human','ai']){
 test(role+': Falcon pays five mana to return tapped and cannot return a new graveyard incarnation',async()=>{const f=setup(role),c=card(f,'The Falcon, Airship Restored','graveyard');fuel(f.a);const entry=f.game.activatableList(f.a).find(e=>e.card===c&&e.gyAbility);assert.ok(entry);const before=mana(f.a);assert.equal(await f.game.activateAbility(f.a,entry),true);await settle(f.game);assert.equal(mana(f.a),before-5);assert.equal(c.zone,'battlefield');assert.equal(c.tapped,true);await f.game.move(c,'graveyard');const again=f.game.activatableList(f.a).find(e=>e.card===c&&e.gyAbility);assert.equal(await f.game.activateAbility(f.a,again),true);await f.game.move(c,'exile');await f.game.move(c,'graveyard');await settle(f.game);assert.equal(c.zone,'graveyard');});
 test(role+': Falcon sacrifices before its reflexive graveyard target is announced',async()=>{const f=setup(role),c=card(f,'The Falcon, Airship Restored'),target=card(f,'Grizzly Bears','graveyard');let saw=false;choose(f,(p,q)=>{if(q.type==='chooseTargets'&&q.candidates.includes(target)){saw=true;assert.equal(c.zone,'graveyard');return [target];}});await event(f,'damageToPlayer',{src:c,player:f.b,n:4,combat:true});assert.ok(saw);assert.equal(c.zone,'graveyard');assert.equal(target.zone,'battlefield');});
 test(role+': Bumbleflower draws two only on its second resolved trigger',async()=>{const f=setup(role),b=body(f);card(f,'Ms. Bumbleflower');choose(f,(p,q)=>q.type==='chooseTargets'?[q.candidates.includes(f.b)?f.b:b]:undefined);for(let i=0;i<3;i++)await play(f,'Sol Ring');assert.equal(f.a.hand.length,2);assert.equal(f.b.hand.length,3);assert.equal(count(b),3);assert.ok(b.kw('flying'));});
 test(role+': Zimone manifests on the first resolution and turns a permanent face up next',async()=>{const f=setup(role);card(f,'Zimone, Mystery Unraveler');const hit=card(f,'Sol Ring','library');choose(f,(p,q)=>q.type==='chooseCards'&&q.from.includes(hit)?[hit]:undefined);await f.game.putPermanentOntoBattlefield(card(f,'Forest','hand'),f.a);await settle(f.game);assert.ok(hit.faceDown);await f.game.putPermanentOntoBattlefield(card(f,'Forest','hand'),f.a);await settle(f.game);assert.equal(hit.faceDown,false);assert.ok(hit.is('Artifact'));});
 test(role+': Winter exiles four card types, returns a permanent with finality and loses it to exile',async()=>{const f=setup(role);card(f,'Winter, Cynical Opportunist');const c=card(f,'Grizzly Bears','graveyard'),cs=[c,card(f,'Forest','graveyard'),card(f,'Sol Ring','graveyard'),card(f,'Ponder','graveyard')];choose(f,(p,q)=>q.type==='chooseCards'?q.from.includes(c)&&c.zone==='graveyard'?cs:q.from.includes(c)?[c]:undefined:undefined);await event(f,'endStep',{player:f.a});assert.equal(c.zone,'battlefield');assert.equal(count(c,'finality'),1);await f.game.sacrifice(f.a,c);await settle(f.game);assert.equal(c.zone,'exile');});
 test(role+': Terra pays two before choosing and returning a small creature tapped',async()=>{const f=setup(role),terra=card(f,'Terra, Herald of Hope'),c=card(f,'Grizzly Bears','graveyard');fuel(f.a);const before=mana(f.a);await event(f,'damageToPlayer',{src:terra,player:f.b,n:3,combat:true});assert.equal(c.zone,'battlefield');assert.equal(c.tapped,true);assert.equal(mana(f.a),before-2);});
 test(role+': Tidus moves a counter and draws/proliferates only once each turn',async()=>{const f=setup(role),a=body(f),b=body(f);a.counters.shield=1;card(f,"Tidus, Yuna's Guardian");choose(f,(p,q)=>q.type==='chooseTargets'?[q.candidates.includes(a)?a:b]:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined);await event(f,'beginCombat',{player:f.a});assert.equal(count(a,'shield'),0);assert.equal(count(b,'shield'),1);await event(f,'damageToPlayer',{src:b,player:f.b,n:2,combat:true});const hand=f.a.hand.length;assert.equal(hand,1);await event(f,'damageToPlayer',{src:b,player:f.b,n:2,combat:true});assert.equal(f.a.hand.length,hand);});
 test(role+': Aminatou offers the first drawn enchantment for four less mana',async()=>{const f=setup(role);card(f,'Aminatou, Veil Piercer');const c=card(f,'Ghirapur Orrery','library');const enchantment=card(f,"Liliana's Contract",'library');fuel(f.a);choose(f,(p,q)=>q.type==='chooseOption'&&q.prompt.includes('Miracle')?'yes':undefined);const before=mana(f.a);await f.game.draw(f.a,1);await settle(f.game);assert.equal(enchantment.zone,'battlefield');assert.equal(mana(f.a),before-2);assert.equal(c.zone,'hand');});
 test(role+': Nissa spends exactly eight energy for a permanent and requires a live source',async()=>{const f=setup(role),nissa=card(f,'Nissa, Worldsoul Speaker'),c=card(f,'Sol Ring','hand');f.a.counters.energy=8;fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c&&r.alt?.bdfNissa);assert.ok(offer);const before=mana(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:offer.alt}),true);await settle(f.game);assert.equal(count(f.a,'energy'),0);assert.equal(mana(f.a),before);const next=card(f,'Sol Ring','hand');f.a.counters.energy=8;const stale=f.game.castableList(f.a).find(r=>r.card===next&&r.alt?.bdfNissa);await f.game.move(nissa,'exile');assert.equal(await f.game.castSpell(f.a,next,{from:'hand',alt:stale.alt}),false);assert.equal(count(f.a,'energy'),8);});
 test(role+': Rooms pay only the selected door, keep other abilities locked and reset on reentry',async()=>{const f=setup(role),b=body(f,f.b);choose(f,(p,q)=>q.type==='chooseTargets'?[b]:undefined);const c=await play(f,'Bottomless Pool // Locker Room',{alt:{bdfDoor:'left',altCostStr:'{U}'}});assert.equal(c.mv,1);assert.equal(c.name,'Bottomless Pool');assert.equal(b.zone,'hand');const a=body(f);await event(f,'damageToPlayer',{src:a,player:f.b,n:2,combat:true});assert.equal(f.a.hand.length,0);await activate(f,c,1);assert.equal(c.mv,6);await event(f,'damageToPlayer',{src:a,player:f.b,n:2,combat:true});assert.equal(f.a.hand.length,1);await f.game.move(c,'exile');await f.game.putPermanentOntoBattlefield(c,f.a);await settle(f.game);assert.equal(c.mv,0);assert.deepEqual([...c.meta.bdfUnlocked],[]);});
 test(role+': Baird taxes attacks at the player and their planeswalkers',()=>{const f=setup(role),a=body(f),b=card(f,'Baird, Steward of Argive','battlefield',f.b),w=card(f,'Tamiyo, Field Researcher','battlefield',f.b);assert.equal(f.game.c21AttackTax(a,f.b),1);assert.equal(f.game.c21AttackTax(a,w),1);b.cur.abilitiesDisabled=true;assert.equal(f.game.c21AttackTax(a,w),0);});
 test(role+': Skaab Ruinator pays three other creatures even when cast from the graveyard',async()=>{const f=setup(role),c=card(f,'Skaab Ruinator','graveyard');const cs=Array.from({length:3},()=>card(f,'Grizzly Bears','graveyard'));fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:offer.alt}),true);await settle(f.game);assert.equal(c.zone,'battlefield');assert.ok(cs.every(c=>c.zone==='exile'));});
 test(role+': Banon only permits a newly milled creature, once during your turn',async()=>{const f=setup(role);card(f,"Banon, the Returners' Leader");const old=card(f,'Grizzly Bears','graveyard'),c=card(f,'Grizzly Bears','library');await f.game.mill(f.a,1);fuel(f.a);assert.equal(f.game.castableList(f.a).some(r=>r.card===old),false);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:c.zone,alt:offer.alt}),true);await settle(f.game);const second=card(f,'Grizzly Bears','library');await f.game.mill(f.a,1);assert.equal(f.game.castableList(f.a).some(r=>r.card===second),false);});
 test(role+': Master of Keys escape exiles three other cards and still pays printed mana',async()=>{const f=setup(role);card(f,'The Master of Keys');const c=card(f,'Growing Dread','graveyard'),cs=Array.from({length:3},()=>card(f,'Forest','graveyard'));fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);const before=mana(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:c.zone,alt:offer.alt}),true);await settle(f.game);assert.ok(cs.every(c=>c.zone==='exile'));assert.equal(before-mana(f.a),2);});
 test(role+': One with the Multiverse plays the top land and casts only one free spell per turn',async()=>{const f=setup(role);card(f,'One with the Multiverse');const top=f.a.library.at(-1);assert.equal(await f.game.playLand(f.a,top),true);const c=card(f,'Grizzly Bears','hand');fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c&&r.alt?.bdfMode==='multiverse');assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:offer.alt}),true);await settle(f.game);assert.equal(f.game.castableList(f.a).some(r=>r.alt?.bdfMode==='multiverse'),false);});
 test(role+': Into the Pit requires a real nonland sacrifice in addition to mana',async()=>{const f=setup(role);const pit=card(f,'Into the Pit'),sac=body(f),c=card(f,'Sol Ring','library');choose(f,(p,q)=>q.type==='chooseCards'&&q.from.includes(sac)?[sac]:undefined);fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'library',alt:offer.alt}),true);await settle(f.game);assert.equal(sac.zone,'graveyard');assert.equal(c.zone,'battlefield');assert.equal(pit.zone,'battlefield');});
 test(role+': Rhet-Tomb grants real paid cycling and the grant ends when it leaves',async()=>{const f=setup(role),s=card(f,'Rhet-Tomb Mystic'),c=card(f,'Grizzly Bears','hand');fuel(f.a);const a=f.game.activatableList(f.a).find(e=>e.card===c&&e.cycling);assert.ok(a);const before=mana(f.a);assert.equal(await f.game.activateAbility(f.a,a),true);await settle(f.game);assert.equal(c.zone,'graveyard');assert.equal(mana(f.a),before-2);await f.game.move(s,'exile');const b=card(f,'Grizzly Bears','hand');assert.equal(f.game.activatableList(f.a).some(e=>e.card===b&&e.cycling),false);});
 test(role+': Brainstone puts exactly two chosen cards back after drawing three',async()=>{const f=setup(role),s=card(f,'Brainstone');await activate(f,s);assert.equal(s.zone,'graveyard');assert.equal(f.a.hand.length,1);assert.equal(f.a.library.length,29);});
 test(role+': Halo Fountain pays untapping as a cost before creating the Citizen',async()=>{const f=setup(role),s=card(f,'Halo Fountain'),b=body(f);assert.equal(f.game.activatableList(f.a).some(e=>e.card===s),false);b.tapped=true;await activate(f,s);assert.equal(b.tapped,false);assert.equal(s.tapped,true);assert.ok(f.game.creatures(f.a).some(c=>c.hasSub('Citizen')));});
 test(role+': Sin consumes counters during entry and doubles them',async()=>{const f=setup(role),b=body(f);b.counters['+1/+1']=2;b.counters.shield=1;choose(f,(p,q)=>q.type==='chooseCards'&&q.from.includes(b)?[b]:undefined);const sin=await play(f,'Sin, Unending Cataclysm');assert.equal(count(sin),6);assert.equal(count(b),0);assert.equal(count(b,'shield'),0);});
 test(role+': Ashaya turns only your nontoken creatures into Forest lands and counts them',async()=>{const f=setup(role),b=body(f),enemy=body(f,f.b);card(f,'Forest');const s=await play(f,'Ashaya, Soul of the Wild');assert.ok(b.is('Land'));assert.ok(b.hasSub('Forest'));assert.equal(enemy.is('Land'),false);assert.equal(s.power,3);const first=s.power;f.game.recalc();assert.equal(s.power,first);await f.game.move(s,'exile');assert.equal(b.is('Land'),false);});
 test(role+': Arcane Adaptation adds the selected type to battlefield and hand cards and spells',async()=>{const f=setup(role),b=body(f),h=card(f,'Grizzly Bears','hand');choose(f,(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='Zombie')?'Zombie':undefined);const s=await play(f,'Arcane Adaptation');assert.ok(b.hasSub('Zombie'));assert.ok(h.hasSub('Zombie'));assert.ok(f.game.castDefinition(h,{}).subtypes.includes('Zombie'));await f.game.move(s,'exile');assert.equal(h.hasSub('Zombie'),false);});
 test(role+': Amoeboid can remove Changeling’s creature types without removing land types',async()=>{const f=setup(role),s=card(f,'Amoeboid Changeling'),c=card(f,'Morophon, the Boundless');choose(f,(p,q)=>q.type==='chooseTargets'?[c]:undefined);assert.ok(c.hasSub('Zombie'));await activate(f,s,1);assert.equal(c.hasSub('Zombie'),false);assert.equal(c.hasSub('Shapeshifter'),false);});
 test(role+': Gatta prevents damage and adds equal counters, but cannot override unpreventable damage',async()=>{const f=setup(role),b=body(f),enemy=body(f,f.b);choose(f,(p,q)=>q.type==='chooseTargets'?[b]:undefined);await play(f,'Gatta and Luzzu');await f.game.damageAny(enemy,b,3);assert.equal(b.damage,0);assert.equal(count(b),3);await f.game.damageAny(enemy,b,1,{cantBePrevented:true});assert.equal(b.damage,1);assert.equal(count(b),3);});
 test(role+': Pariah redirects player damage to its enchanted creature',async()=>{const f=setup(role),b=body(f),enemy=body(f,f.b);choose(f,(p,q)=>q.type==='chooseTargets'?[b]:undefined);await play(f,'Pariah');await f.game.damageAny(enemy,f.a,1);assert.equal(f.a.life,40);assert.equal(b.damage,1);});
 test(role+': gifts are promised during casting and delivered before the effect',async()=>{const f=setup(role);card(f,'Jolly Gerbils');const a=card(f,'Sol Ring','battlefield',f.b),b=card(f,'Mind Stone','battlefield',f.b);choose(f,(p,q)=>q.type==='chooseTargets'?[a,b].filter(c=>q.candidates.includes(c)):q.type==='chooseOption'&&q.options.some(o=>o.key===String(f.b.idx))?String(f.b.idx):undefined);await play(f,'Wear Down',{alt:{bdfGift:true}});assert.equal(a.zone,'graveyard');assert.equal(b.zone,'graveyard');assert.equal(f.b.hand.length,1);assert.equal(f.a.hand.length,1);});
 test(role+': countering a gift spell gives no gift',async()=>{const f=setup(role),target=card(f,'Sol Ring','battlefield',f.b),c=card(f,'Wear Down','hand');card(f,'Mind Stone','battlefield',f.b);fuel(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:{bdfGift:true}}),true);const so=f.game.stack.find(s=>s.card===c);await f.game.counterStackObject(so,{});await settle(f.game);assert.equal(f.b.hand.length,0);assert.equal(target.zone,'battlefield');});
 test(role+': Stridehangar adds one Thopter for the entire artifact-token event',async()=>{const f=setup(role);card(f,'Stridehangar Automaton');await f.game.makeTokens(M.TOKENS.treasure,f.a,{n:3});assert.equal(f.game.bf().filter(c=>c.hasSub('Treasure')).length,3);assert.equal(f.game.bf().filter(c=>c.hasSub('Thopter')).length,1);});
 test(role+': Tromell and Curator apply counters before entry triggers see the creature',async()=>{const f=setup(role);card(f,"Tromell, Seymour's Butler");card(f,'Curator Beastie');const c=await play(f,'Solemn Simulacrum');assert.equal(count(c),3);assert.equal(c.power,5);});
 test(role+': Communal Brewing uses its resolved ingredient count on the creature spell',async()=>{const f=setup(role);choose(f,(p,q)=>q.type==='chooseTargets'&&q.candidates.includes(f.b)?[f.b]:undefined);const brewing=await play(f,'Communal Brewing');assert.equal(count(brewing,'ingredient'),2);const c=await play(f,'Grizzly Bears');assert.equal(count(c),2);});
 test(role+': Felidar Sovereign enforces the forty-life threshold',async()=>{const f=setup(role);card(f,'Felidar Sovereign');f.a.life=39;await event(f,'upkeep',{player:f.a});assert.equal(f.b.lost,false);f.a.life=40;await event(f,'upkeep',{player:f.a});assert.equal(f.b.lost,true);});
 test(role+': Biovisionary can win at an opponent’s end step',async()=>{const f=setup(role);for(let i=0;i<4;i++)card(f,'Biovisionary');await event(f,'endStep',{player:f.b});assert.equal(f.b.lost,true);});
 test(role+': Approach must have been cast earlier and the winning cast must come from hand',async()=>{const f=setup(role);const first=await play(f,'Approach of the Second Sun');assert.equal(f.a.life,47);assert.equal(f.a.library.at(-7),first);assert.equal(f.b.lost,false);await play(f,'Approach of the Second Sun');assert.equal(f.b.lost,true);});
 test(role+': Fear of Sleep Paralysis prevents removing opposing stun counters',async()=>{const f=setup(role),s=card(f,'Fear of Sleep Paralysis'),b=body(f,f.b);b.counters.stun=2;f.game.removeCounters(b,'stun',1);assert.equal(count(b,'stun'),2);await f.game.move(s,'exile');f.game.removeCounters(b,'stun',1);assert.equal(count(b,'stun'),1);});
 test(role+': The Warring Triad uses the Stack and pays its milling cost',async()=>{const f=setup(role),s=card(f,'The Warring Triad');assert.equal(s.is('Creature'),false);choose(f,(p,q)=>q.type==='chooseTargets'?[f.b]:undefined);await activate(f,s);assert.equal(f.a.graveyard.length,1);assert.equal(mana(f.b),1);});
 test(role+': Worldspine creates three Wurms and shuffles itself back after dying',async()=>{const f=setup(role),s=card(f,'Worldspine Wurm');await f.game.sacrifice(f.a,s);await settle(f.game);assert.equal(s.zone,'library');assert.equal(f.game.creatures(f.a).filter(c=>c.hasSub('Wurm')).length,3);});
 test(role+': Athreos returns a coin-marked creature under its controller',async()=>{const f=setup(role);card(f,'Athreos, Shroud-Veiled');const c=body(f,f.b);c.counters.coin=1;await f.game.sacrifice(f.b,c);await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);});
}
for(const role of ['human','ai']){
 test(role+': granted Miracle preserves X and discounts only four generic mana',async()=>{const f=setup(role);card(f,'Aminatou, Veil Piercer');const c=card(f,'The Master of Keys','library');fuel(f.a);choose(f,(p,q)=>q.type==='chooseX'?7:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined);const before=mana(f.a);await f.game.draw(f.a,1);await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(count(c),7);assert.equal(before-mana(f.a),6);});
 test(role+': Aminatou can reveal a Room and pay the discounted selected door',async()=>{const f=setup(role);card(f,'Aminatou, Veil Piercer');const c=card(f,'Bottomless Pool // Locker Room','library');fuel(f.a);choose(f,(p,q)=>q.prompt==='Choose a Miracle cost'?'1':q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined);const before=mana(f.a);await f.game.draw(f.a,1);await settle(f.game);assert.equal(c.name,'Locker Room');assert.equal(c.mv,5);assert.equal(before-mana(f.a),1);});
 test(role+': a countered granted Miracle leaves no reusable permission',async()=>{const f=setup(role);card(f,'Aminatou, Veil Piercer');const c=card(f,"Liliana's Contract",'library');fuel(f.a);choose(f,(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined);await f.game.draw(f.a,1);await f.game.flushTriggers();const trigger=f.game.stack.find(s=>s.name.includes('Miracle'));assert.ok(trigger);await f.game.counterStackObject(trigger,{});assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:{miracle:true,altCostStr:'{0}{B}{B}',speed:'instant'}}),false);assert.equal(c.zone,'hand');});
 test(role+': On Wings of Gold triggers once for a batch and again for a later departure',async()=>{const f=setup(role);card(f,'On Wings of Gold');const cs=[card(f,'Grizzly Bears','graveyard'),card(f,'Sol Ring','graveyard')];await f.game.moveGraveyardBatch(cs,'exile');await settle(f.game);assert.equal(f.game.creatures(f.a).length,1);const c=card(f,'Forest','graveyard');await f.game.move(c,'exile');await settle(f.game);assert.equal(f.game.creatures(f.a).length,2);assert.ok(f.game.creatures(f.a).every(c=>c.power===2&&c.kw('flying')));});
 test(role+': Celes grows the board only once for simultaneous graveyard arrivals',async()=>{const f=setup(role);const celes=card(f,'Celes, Rune Knight'),cs=[card(f,'Grizzly Bears','graveyard'),card(f,'Wind Drake','graveyard')];await M.BDF.enterMany({g:f.game,src:celes,you:f.a},cs);await settle(f.game);assert.equal(count(celes),1);assert.ok(cs.every(c=>count(c)===1));});
 test(role+': Gond Gate overrides tapped entry before observers see another Gate',async()=>{const f=setup(role);card(f,'Gond Gate');const c=card(f,'Azorius Guildgate','hand');await f.game.putPermanentOntoBattlefield(c,f.a,{tapped:true});await settle(f.game);assert.equal(c.tapped,false);});
 test(role+': Fisher’s Talent replaces all Fish at level three with Octopuses',async()=>{const f=setup(role),s=card(f,"Fisher's Talent");await activate(f,s,0);await activate(f,s,1);const made=await f.game.makeTokens(M.BDF.token('Fish',['Fish'],1,1,['U']),f.a,{n:2});assert.equal(made.length,2);assert.ok(made.every(c=>c.hasSub('Octopus')&&c.power===8));});
 test(role+': a copied Room spell unlocks its selected door and a battlefield copy stays locked',async()=>{const f=setup(role),c=card(f,'Bottomless Pool // Locker Room','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:{bdfDoor:'right',altCostStr:'{4}{U}'}}),true);await f.game.copySpell(f.game.stack.at(-1),f.a);await settle(f.game);const spellCopy=f.game.bf().find(x=>x!==c&&x.isToken);assert.equal(spellCopy.mv,5);const made=await f.game.copyPermanentToken(c,f.a);assert.equal(made[0].mv,0);});
 test(role+': copied gift spells retain the promised recipient without a new promise',async()=>{const f=setup(role),c=card(f,'Peerless Recycling','hand'),cs=[card(f,'Forest','graveyard'),card(f,'Sol Ring','graveyard')];fuel(f.a);choose(f,(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key===String(f.b.idx))?String(f.b.idx):q.type==='chooseTargets'?cs:undefined);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:{bdfGift:true}}),true);const so=f.game.stack.at(-1);await f.game.copySpell(so,f.a);await settle(f.game);assert.equal(f.b.hand.length,1,'copy returns both targets; the original fizzles and gives no second gift');assert.ok(cs.every(c=>c.zone==='hand'));});
 test(role+': Magus Sisters chooses its random mode before priority and uses one trigger',async()=>{const f=setup(role);body(f);f.game.rnd=()=>0;const s=card(f,'Summon: Magus Sisters');f.game.addCounters(s,'lore',1,false,f.a);await f.game.flushTriggers();assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].ctx.mode,0);assert.equal(f.game.stack[0].targets.length,1);await settle(f.game);assert.equal(f.game.creatures(f.a).reduce((n,c)=>n+count(c),0),3);});
 test(role+': Umaro’s damage mode announces a target on the combat trigger',async()=>{const f=setup(role);card(f,'Umaro, Raging Yeti');f.game.rnd=()=>0.99;choose(f,(p,q)=>q.type==='chooseTargets'?[f.b]:undefined);await f.game.emit('beginCombat',{player:f.a});await f.game.flushTriggers();assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].ctx.mode,2);assert.equal(f.game.stack[0].targets[0],f.b);await settle(f.game);assert.equal(f.b.life,35);});
 test(role+': Tamiyo draws once when one marked creature damages multiple blockers simultaneously',async()=>{const f=setup(role),s=card(f,'Tamiyo, Field Researcher'),c=body(f),a=body(f,f.b),b=body(f,f.b);s.counters.loyalty=4;choose(f,(p,q)=>q.type==='chooseTargets'?[c]:undefined);await activate(f,s);await f.game.damageBatch([{src:c,target:a,n:1},{src:c,target:b,n:1}],{combat:true});await settle(f.game);assert.equal(f.a.hand.length,1);});
 test(role+': Rikku prevents only creatures controlled by her opponents from blocking',async()=>{const f=setup(role),s=card(f,'Rikku, Resourceful Guardian'),enemy=body(f,f.b),ours=body(f);f.game.addCounters(enemy,'+1/+1',1,false,f.a);await settle(f.game);assert.equal(f.game.canBlock(ours,enemy),true);const third=body(f,f.game.players[2]);assert.equal(f.game.canBlock(third,enemy),false);});
 test(role+': Gogo copies another creature and requires both to attack this turn',async()=>{const f=setup(role),gogo=card(f,'Gogo, Mysterious Mime'),c=body(f);choose(f,(p,q)=>q.type==='chooseTargets'?[c]:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined);await event(f,'beginCombat',{player:f.a});assert.equal(gogo.power,4);assert.equal(c.power,4);assert.equal(gogo.meta.mustAttackTurn,f.game.turnNo);assert.equal(c.meta.mustAttackTurn,f.game.turnNo);});
 test(role+': Strago grants haste to a creature spell and sacrifices it at the end step',async()=>{const f=setup(role),s=card(f,'Strago and Relm'),c=card(f,'Grizzly Bears','library',f.b);choose(f,(p,q)=>q.type==='chooseTargets'?[f.b]:q.type==='chooseCards'&&q.from.includes(c)?[c]:undefined);await activate(f,s);assert.equal(c.zone,'battlefield');assert.ok(c.kw('haste'));await event(f,'endStep',{player:f.a});assert.equal(c.zone,'graveyard');});
 test(role+': Wizened Mentor notices an opposing permanent sacrificed to activate an ability',async()=>{const f=setup(role);card(f,'Wizened Mentor');const s=card(f,'Mind Stone','battlefield',f.b);fuel(f.b);await activate(f,s);assert.equal(s.zone,'graveyard');assert.equal(f.game.creatures(f.a).filter(c=>c.hasSub('Zombie')).length,2);});
 test(role+': Lord Jyscal investigates at each end step after you put a counter',async()=>{const f=setup(role);card(f,'Lord Jyscal Guado');const c=body(f);f.game.addCounters(c,'+1/+1',1,false,f.a);await settle(f.game);await event(f,'endStep',{player:f.b});assert.equal(f.game.bf().filter(c=>c.hasSub('Clue')).length,1);await event(f,'endStep',{player:f.a});assert.equal(f.game.bf().filter(c=>c.hasSub('Clue')).length,2);});
 test(role+': Perch Protection locks life, phases the board and grants the promised extra turn',async()=>{const f=setup(role),c=body(f);choose(f,(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key===String(f.b.idx))?String(f.b.idx):undefined);await play(f,'Perch Protection',{alt:{bdfGift:true}});assert.equal(c.phasedOut,true);await f.game.loseLife(f.a,8);await f.game.gainLife(f.a,8);assert.equal(f.a.life,40);assert.equal(f.game.canPayLife(f.a,1),false);});
 test(role+': Yuna’s mana creates a delayed bonus for exactly the next creature spell',async()=>{const f=setup(role),s=card(f,'Yuna, Grand Summoner');const m=f.game.manaSources(f.a).find(m=>m.card===s);assert.ok(m);assert.equal(await f.game.activateManaSource(f.a,m,m.produce[0]),true);const c=await play(f,'Grizzly Bears');assert.equal(count(c),2);const next=await play(f,'Grizzly Bears');assert.equal(count(next),0);});
 test(role+': The Bears of Littjara uses each qualifying creature as its damage source',async()=>{const f=setup(role),s=card(f,'The Bears of Littjara'),c=body(f),enemy=card(f,'Worldspine Wurm','battlefield',f.b);c.counters['+1/+1']=2;f.game.recalc();choose(f,(p,q)=>q.type==='chooseTargets'?[enemy]:undefined);s.counters.lore=2;f.game.addCounters(s,'lore',1,false,f.a);await settle(f.game);assert.equal(enemy.damage,4);assert.equal(s.zone,'graveyard');});
 test(role+': Ashaya’s type change supplies mana and contributes to other land-count creatures',async()=>{const f=setup(role);card(f,'Forest');card(f,'Ashaya, Soul of the Wild');const c=card(f,'Multani, Yavimaya’s Avatar'.replace('’',"'"));assert.equal(c.power,3);assert.ok(f.game.manaSources(f.a).some(s=>s.card===c&&s.produce.some(p=>p.G===1)));});
 test(role+': Nightmare Shepherd copies the dying creature’s last copiable characteristics',async()=>{const f=setup(role);card(f,'Nightmare Shepherd');const c=body(f);M.OracleV8Copies.applyCopy(f.game,c,M.DEFS['Wind Drake']);f.game.recalc();assert.equal(c.name,'Wind Drake');await f.game.sacrifice(f.a,c);await settle(f.game);const copy=f.game.creatures(f.a).find(c=>c.isToken);assert.equal(copy.name,'Wind Drake');assert.ok(copy.kw('flying'));assert.equal(copy.power,1);});
 test(role+': a Room rejects invented zero-mana and free alternatives',async()=>{const f=setup(role),c=card(f,'Bottomless Pool // Locker Room','hand');fuel(f.a);for(const a of [{bdfDoor:'right',altCostStr:'{0}'},{bdfDoor:'right',free:true}])assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:a}),false);assert.equal(c.zone,'hand');});
 test(role+': Polluted Cistern also counts surveil and other grouped library-to-graveyard movement',async()=>{const f=setup(role);await play(f,'Polluted Cistern // Dim Oubliette',{alt:{bdfDoor:'left',altCostStr:'{1}{B}'}});const cs=[card(f,'Grizzly Bears','library'),card(f,'Forest','library')];await f.game.withGraveyardEntryBatch(async()=>{for(const c of cs)await f.game.move(c,'graveyard');});await settle(f.game);assert.equal(f.b.life,38);});
 test(role+': Lost Monarch remembers any Zombie combat damage and triggers only in the second main phase',async()=>{const f=setup(role);card(f,'Lost Monarch of Ifnir');const z=card(f,'Wizened Mentor','battlefield',f.b);await event(f,'damageToPlayer',{src:z,player:f.a,n:1,combat:true});const n=f.a.library.length;await event(f,'postcombatMain',{player:f.a,ordinal:2});assert.equal(f.a.library.length,n-3);await event(f,'postcombatMain',{player:f.a,ordinal:3});assert.equal(f.a.library.length,n-3);});
 test(role+': declining Tidus’s Cheer preserves the option for a later combat-damage event',async()=>{const f=setup(role);card(f,"Tidus, Yuna's Guardian");const c=body(f);c.counters['+1/+1']=1;let accept=false;choose(f,(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?accept?'yes':'no':undefined);await event(f,'damageToPlayer',{src:c,player:f.b,n:1,combat:true});assert.equal(f.a.hand.length,0);accept=true;await event(f,'damageToPlayer',{src:c,player:f.b,n:1,combat:true});assert.equal(f.a.hand.length,1);await event(f,'damageToPlayer',{src:c,player:f.b,n:1,combat:true});assert.equal(f.a.hand.length,1);});
 test(role+': Approach’s prior casting and permanent Bird goad survive a JSON checkpoint',async()=>{const f=setup(role);await play(f,'Approach of the Second Sun');const src=card(f,'Rendmaw, Creaking Nest');await M.BDF.bdfBirds({g:f.game,src,you:f.a});await settle(f.game);const snap=M.captureGameState(f.game);assert.ok(snap,JSON.stringify(M.gameStateSnapshotBlockers(f.game)));const fresh=setup(role);M.restoreGameState(fresh.game,JSON.parse(JSON.stringify(snap)));assert.equal(fresh.a.bdfApproaches,1);assert.equal(fresh.game.untilEffects.filter(e=>e.kind==='goadCard'&&e.expires==='never').length,3);await play(fresh,'Approach of the Second Sun');assert.equal(fresh.b.lost,true);});
 for(const [name,kind,threshold]of [['Test of Endurance','life',50],['Helix Pinnacle','tower',100],['Triskaidekaphile','hand',13],['Revel in Riches','treasure',10]])test(role+': '+name+' checks its exact alternate-win threshold',async()=>{const f=setup(role),s=card(f,name);if(kind==='life')f.a.life=threshold-1;else if(kind==='hand')for(let i=0;i<threshold-1;i++)card(f,'Forest','hand');else if(kind==='tower')s.counters.tower=threshold-1;else await f.game.makeTokens(M.TOKENS.treasure,f.a,{n:threshold-1});await event(f,'upkeep',{player:f.a});assert.equal(f.b.lost,false);if(kind==='life')f.a.life++;else if(kind==='hand')card(f,'Forest','hand');else if(kind==='tower')s.counters.tower++;else await f.game.makeTokens(M.TOKENS.treasure,f.a);await event(f,'upkeep',{player:f.a});assert.equal(f.b.lost,true);});
}
