import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,fuel,mana,settle,target,tokens} from './helpers/c17-c19-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Arixmethes enters as a tapped land with five counters, then awakens after five spells',async()=>{const f=setup(role);await play(f,"Trostani, Selesnya's Voice");const c=await play(f,'Arixmethes, Slumbering Isle');assert.equal(c.counters.slumber,5);assert.ok(c.is('Land')&&!c.is('Creature')&&c.tapped);assert.equal(f.a.life,40);f.game.untap(c);const source=f.game.manaSources(f.a).find(s=>s.card===c);assert.ok(source);for(let i=0;i<5;i++)await play(f,'Sol Ring');assert.equal(c.counters.slumber,0);assert.ok(c.is('Creature')&&!c.is('Land'));assert.equal(c.power,12);assert.equal(c.toughness,12);});
 test(role+': Blood Tribute taps even a summoning-sick Vampire as kicker and gains actual life lost',async()=>{const f=setup(role),v=card(f,'Falkenrath Noble');v.sick=true;target(f,f.b);await play(f,'Blood Tribute');assert.equal(v.tapped,true);assert.equal(f.b.life,20);assert.equal(f.a.life,60);});
 test(role+': Blood Tribute without an untapped Vampire casts unkicked',async()=>{const f=setup(role);target(f,f.b);await play(f,'Blood Tribute');assert.equal(f.b.life,20);assert.equal(f.a.life,40);});
 test(role+': Orator reveals an actual Dragon as additional cost then draws on entry',async()=>{const f=setup(role),d=card(f,'Thundermaw Hellkite','hand');f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('additional cost')?'0':undefined;const c=await play(f,'Orator of Ojutai');assert.equal(c.castMeta.c1719DragonRevealed,true);assert.equal(d.zone,'hand');assert.equal(f.a.hand.length,2);});
 test(role+': Orator checks a Dragon controlled while casting, not one acquired afterward',async()=>{const f=setup(role),d=card(f,'Thundermaw Hellkite');const c=await play(f,'Orator of Ojutai');assert.equal(c.castMeta.c1719ControlledDragon,true);assert.equal(f.a.hand.length,1);await f.game.move(d,'graveyard');await f.game.move(c,'hand');await play(f,'Orator of Ojutai',{card:c});assert.equal(f.a.hand.length,1);});
 test(role+': Bloodlord gains its own bloodthirst and grants it to a cast Vampire through a Stack trigger',async()=>{const f=setup(role);await f.game.damagePlayer(body(f),f.b,1);const b=await play(f,'Bloodlord of Vaasgoth');assert.equal(b.plus1(),3);const c=await play(f,'Falkenrath Noble');assert.equal(c.plus1(),3);});
 test(role+': Ravenous Slime replaces an opponent death and receives power counters, without a dies trigger',async()=>{const f=setup(role),s=await play(f,'Ravenous Slime'),b=body(f,f.b);await f.game.destroy(b);await settle(f.game);assert.equal(b.zone,'exile');assert.equal(s.plus1(),2);assert.ok(s.cur.cantBeBlockedBy(f.game,body(f)));assert.equal(f.game.diedThisTurn.some(r=>r.iid===b.iid),false);});
 test(role+': Vindictive Lich assigns three modes to three distinct opponents',async()=>{const f=setup(role,3),l=await play(f,'Vindictive Lich');for(const p of f.others){body(f,p);card(f,'Island','hand',p);card(f,'Forest','hand',p);}f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('choose one or more')?'7':q.type==='chooseTargets'?[q.candidates[0]]:undefined;await f.game.destroy(l);await settle(f.game);assert.equal(f.game.creatures(f.others[0]).length,0);assert.equal(f.others[1].hand.length,0);assert.equal(f.others[2].life,35);});
}
test('Blood Tribute rejects a stale tapped kicker choice before spending mana',async()=>{const f=setup(),v=card(f,'Falkenrath Noble'),s=card(f,'Blood Tribute','hand');fuel(f.a);const before=mana(f.a);f.decide=(p,q)=>{if(q.type==='chooseCards'&&q.prompt.includes('tap an untapped Vampire')){v.tapped=true;return[v];}if(q.type==='chooseTargets')return[f.b];};assert.equal(await f.game.castSpell(f.a,s,{from:'hand'}),false);assert.equal(mana(f.a),before);assert.equal(s.zone,'hand');});
test('A copied Orator spell keeps revealed cost but does not acquire controlled-Dragon cast history',async()=>{for(const revealed of [true,false]){const f=setup();card(f,'Thundermaw Hellkite',revealed?'hand':'battlefield');f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('additional cost')?'0':undefined;const c=card(f,'Orator of Ojutai','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:'hand'}),true);await f.game.copySpell(f.game.stack.at(-1),f.a);await settle(f.game);assert.equal(f.a.hand.length,revealed?3:1);}});
test('Tawnos copies an artifact triggered ability',async()=>{const f=setup(),t=await play(f,"Tawnos, Urza's Apprentice"),s=card(f,'Solemn Simulacrum','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,s,{from:'hand'}),true);await f.game.resolveTop();await f.game.flushTriggers();const trigger=f.game.stack.at(-1);assert.equal(trigger.kind,'trigger');target(f,trigger);await activate(f,t);assert.equal(f.game.lands(f.a).length,2);});
