import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,fuel,mana,settle,target,tokens} from './helpers/c17-c19-fixtures.mjs';
const castGrant=async(f,c,p=f.a)=>{fuel(p);const e=f.game.castableList(p).find(e=>e.card===c&&e.alt?.starterPermission==='c1719');assert.ok(e,c.name+' granted cast');assert.equal(await f.game.castSpell(p,c,{from:e.from,alt:e.alt}),true);await settle(f.game);return e;};
for(const role of ['human','ai']){
 test(role+': Kess casts one graveyard spell during its controller turn and exiles it on leaving the Stack',async()=>{const f=setup(role);await play(f,'Kess, Dissident Mage');const c=card(f,'Cultivate','graveyard'),d=card(f,'Sol Ring','graveyard'),e=card(f,'Ponder','graveyard');await castGrant(f,c);assert.equal(c.zone,'exile');assert.equal(f.game.castableList(f.a).some(e=>e.card===d),false);assert.equal(f.game.castableList(f.a).some(r=>r.card===e),false);});
 test(role+': Chainer discards as an activation cost, grants one graveyard creature cast and gives haste',async()=>{const f=setup(role),c=await play(f,'Chainer, Nightmare Adept'),discard=card(f,'Island','hand'),b=card(f,'Grizzly Bears','graveyard'),second=card(f,'Serra Angel','graveyard');await activate(f,c);assert.equal(discard.zone,'graveyard');await castGrant(f,b);assert.ok(b.kw('haste'));assert.equal(f.game.castableList(f.a).some(e=>e.card===second),false);assert.equal(f.game.activatableList(f.a).some(e=>e.card===c&&e.ability),false);});
 test(role+': Daxos grants the exiled nonland spell with any-color mana and gains its mana value',async()=>{const f=setup(role),c=await play(f,'Daxos of Meletis'),s=card(f,'Grizzly Bears','library',f.b);await f.game.damagePlayer(c,f.b,1,{combat:true});await settle(f.game);assert.equal(s.zone,'exile');assert.equal(f.a.life,42);for(const k of Object.keys(f.a.pool))f.a.pool[k]=0;f.a.pool.R=2;const e=f.game.castableList(f.a).find(e=>e.card===s);assert.ok(e);assert.equal(await f.game.castSpell(f.a,s,{from:e.from,alt:e.alt}),true);await settle(f.game);assert.equal(s.ctrl,f.a);});
 test(role+': Hedonist Trove permits lands and one exiled spell each turn, with permissions following its controller',async()=>{const f=setup(role),s=card(f,'Sol Ring','graveyard',f.b),d=card(f,'Grizzly Bears','graveyard',f.b),land=card(f,'Island','graveyard',f.b);target(f,f.b);const t=await play(f,"Hedonist's Trove");assert.equal(s.zone,'exile');assert.ok(f.game.playableLands(f.a).includes(land));assert.equal(await f.game.playLand(f.a,land),true);await castGrant(f,s);assert.equal(f.game.castableList(f.a).some(e=>e.card===d),false);M.OracleV8Control.gain(f.game,t,f.others[1]);f.game.recalc();f.game.turnPlayer=f.others[1];await castGrant(f,d,f.others[1]);assert.equal(d.ctrl,f.others[1]);});
 test(role+': Intet pays for a face-down exile, grants free play and expires on a new Intet object',async()=>{const f=setup(role),i=await play(f,'Intet, the Dreamer'),s=card(f,'Sol Ring','library');fuel(f.a);await f.game.damagePlayer(i,f.b,1,{combat:true});await settle(f.game);assert.equal(s.zone,'exile');assert.equal(s.faceDown,true);await castGrant(f,s);assert.equal(s.zone,'battlefield');const b=card(f,'Grizzly Bears','library');await f.game.damagePlayer(i,f.b,1,{combat:true});await settle(f.game);await f.game.move(i,'exile');await f.game.putPermanentOntoBattlefield(i,f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===b),false);});
 test(role+': Kheru exiles the opponent chosen card and makes it playable from exile',async()=>{const f=setup(role),k=await play(f,'Kheru Mind-Eater'),s=card(f,'Sol Ring','hand',f.b);await f.game.damagePlayer(k,f.b,1,{combat:true});await settle(f.game);assert.equal(s.zone,'exile');assert.equal(s.faceDown,true);await castGrant(f,s);assert.equal(s.ctrl,f.a);});
 test(role+': Magus of the Mind sacrifices itself and grants a spell-count cohort for free until turn end',async()=>{const f=setup(role),m=await play(f,'Magus of the Mind');m.sick=false;const expected=1+f.game.players.reduce((n,p)=>n+p.turnState.spellsCast,0);await activate(f,m);assert.equal(m.zone,'graveyard');assert.equal(f.a.exile.length,expected);assert.ok(f.a.exile.every(c=>M.C1719.playRecords(f.game,f.a,c,true).length));f.game.turnNo++;assert.equal(f.game.playableLands(f.a).length,0);});
 test(role+': Djinn reveals and casts its top spell within an ability, paying a wish counter and four mana',async()=>{const f=setup(role),d=await play(f,'Djinn of Wishes'),s=card(f,'Sol Ring','library');await activate(f,d);assert.equal(d.counters.wish,2);assert.equal(s.zone,'battlefield');});
 test(role+': Djinn plays a top land during its own combat, respecting the land limit',async()=>{const f=setup(role),d=await play(f,'Djinn of Wishes'),land=card(f,'Island','library');f.game.phase='combat';await activate(f,d);assert.equal(land.zone,'battlefield');assert.equal(f.a.landsPlayed,1);const second=card(f,'Forest','library');await activate(f,d);assert.equal(second.zone,'exile');});
 test(role+': Geode Golem casts a commander for free but still pays commander tax',async()=>{const f=setup(role),g=await play(f,'Geode Golem'),c=card(f,'Ghired, Conclave Exile','command');c.commander=true;c.cmdCasts=2;fuel(f.a);const before=mana(f.a);await f.game.damagePlayer(g,f.b,1,{combat:true});await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(before-mana(f.a),4);assert.equal(c.cmdCasts,3);});
 test(role+': Augury puts a land onto the battlefield and permits one free spell of each chosen type',async()=>{const f=setup(role),s=card(f,'Sol Ring','library'),t=card(f,'Scrabbling Claws','library'),b=card(f,'Grizzly Bears','library');await play(f,"Aminatou's Augury");assert.equal(f.game.lands(f.a).length,1);await castGrant(f,s);assert.equal(f.game.castableList(f.a).some(e=>e.card===t),false);await castGrant(f,b);assert.equal(b.zone,'battlefield');});
 test(role+': Primordial Mist exiles a face-down permanent as its cost and grants normal play this turn',async()=>{const f=setup(role),m=await play(f,'Primordial Mist'),s=card(f,'Sol Ring','library');await f.game.manifestCard(f.a,s);await activate(f,m);assert.equal(s.zone,'exile');assert.equal(s.faceDown,false);await castGrant(f,s);assert.equal(s.name,'Sol Ring');assert.equal(s.zone,'battlefield');});
 test(role+': Fist of Suns provides and pays its five-color alternative with commander tax',async()=>{const f=setup(role);await play(f,'Fist of Suns');const c=card(f,'The Ur-Dragon','command');c.commander=true;c.cmdCasts=1;fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.c1719Id==='fist');assert.ok(e);const before=mana(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),true);assert.equal(before-mana(f.a),7);await settle(f.game);assert.equal(c.zone,'battlefield');});
}
test('Fist of Suns combines with a paid graveyard permission, consumes Kess and rejects a stale Fist',async()=>{const f=setup(),fist=await play(f,'Fist of Suns');await play(f,'Kess, Dissident Mage');const c=card(f,'Decree of Pain','graveyard');fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.c1719Fist);assert.ok(e);const n=mana(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),true);assert.equal(n-mana(f.a),5);await settle(f.game);assert.equal(c.zone,'exile');const other=card(f,'Cultivate','graveyard');assert.equal(f.game.castableList(f.a).some(e=>e.card===other),false);});
test('Fist of Suns preserves exile permission lifetime and never grants a new zone permission',async()=>{const f=setup(),fist=await play(f,'Fist of Suns'),c=card(f,'Cultivate','exile');fuel(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===c),false);M.C1719.playGrant({g:f.game,you:f.a},c,{turn:f.game.turnNo});const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.c1719Fist);assert.ok(e);await f.game.move(fist,'hand');assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),false);assert.equal(c.zone,'exile');});
