import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,fuel,mana,settle,target,tokens} from './helpers/c17-c19-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Aeon Engine pays its tap and exile cost and reverses turn and priority order',async()=>{const f=setup(role,3),c=await play(f,'Aeon Engine');assert.ok(c.tapped);f.game.untap(c);await activate(f,c);assert.equal(c.zone,'exile');assert.equal(f.game.nextPlayer(f.a),f.others[2]);assert.deepEqual(Array.from(f.game.apnapFrom(f.a),p=>p.idx),[0,3,2,1]);f.game.advanceTurnPlayer(f.a);assert.equal(f.game.turnPlayer,f.others[2]);});
 for(const [name,keyword]of [['Cloudform','hexproof'],['Lightform','lifelink']])test(role+': '+name+' manifests its top card, becomes an Aura and grants the correct abilities',async()=>{const f=setup(role),b=card(f,'Grizzly Bears','library'),c=await play(f,name);assert.equal(b.zone,'battlefield');assert.equal(b.faceDown,true);assert.equal(b.power,2);assert.ok(c.hasSub('Aura'));assert.equal(c.attachedTo,b.iid);assert.ok(b.kw('flying')&&b.kw(keyword));assert.equal(c.zone,'battlefield');});
 test(role+': Yuriko commander ninjutsu pays UB, returns an unblocked attacker and avoids commander tax',async()=>{const f=setup(role),b=body(f),y=card(f,"Yuriko, the Tiger's Shadow",'command');y.commander=true;y.cmdCasts=3;b.attacking=f.b;f.game.phase='combat';f.game.step='blockers';f.game.combat={attackers:[b],blockers:[]};fuel(f.a);const before=mana(f.a),entry=f.game.activatableList(f.a).find(e=>e.card===y&&e.ninjutsu);assert.ok(entry);assert.equal(await f.game.activateAbility(f.a,entry),true);assert.equal(before-mana(f.a),2);await settle(f.game);assert.equal(b.zone,'hand');assert.equal(y.zone,'battlefield');assert.equal(y.attacking,f.b);assert.equal(y.cmdCasts,3);const top=card(f,'Cultivate','library');await f.game.damagePlayer(y,f.b,1,{combat:true});await settle(f.game);assert.equal(top.zone,'hand');assert.equal(f.b.life,36);assert.equal(f.others[1].life,37);});
 test(role+': Taigam Sidisi skips the entire draw step and exchanges the top three at upkeep',async()=>{const f=setup(role);const c=await play(f,"Taigam, Sidisi's Hand"),one=card(f,'Sol Ring','library'),two=card(f,'Grizzly Bears','library'),three=card(f,'Cultivate','library');let drawSteps=0;const original=f.game.emit;f.game.emit=function(n,d){if(n==='drawStep')drawSteps++;return original.call(this,n,d);};f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Taigam: choose')?[three]:undefined;f.game.mainPhase=async()=>{};f.game.combatPhase=async()=>{};f.game.priorityRound=()=>settle(f.game);await f.game.runTurn();assert.equal(drawSteps,0);assert.equal(three.zone,'hand');assert.equal(one.zone,'graveyard');assert.equal(two.zone,'graveyard');const b=body(f,f.b);f.decide=(p,q)=>q.type==='chooseX'?2:q.type==='chooseTargets'?[b]:undefined;await activate(f,c);assert.equal(one.zone,'exile');assert.equal(two.zone,'exile');assert.equal(b.zone,'graveyard');});
 test(role+': Taigam Ojutai protects Dragon spells and grants rebound to a spell cast after attacking',async()=>{const f=setup(role),t=await play(f,'Taigam, Ojutai Master');await event(f,'attacks',{card:t,player:f.a,defender:f.b});const spell=card(f,'Cultivate','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,spell,{from:'hand'}),true);assert.ok(t.def.uncounterableSpells(f.game,t,f.game.stack[0]));await settle(f.game);assert.equal(spell.zone,'exile');await event(f,'upkeep',{player:f.a});assert.equal(spell.zone,'graveyard');});
 test(role+': Seht Tiger protects its controller from selected-color damage, targets and Auras',async()=>{const f=setup(role);f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('protection color')?'R':undefined;await play(f,"Seht's Tiger");const red=card(f,'Lightning Bolt','hand',f.b),blue=card(f,'Ponder','hand',f.b);assert.ok(f.game.isProtectedFrom(f.a,red));assert.equal(f.game.isProtectedFrom(f.a,blue),false);await f.game.damagePlayer(red,f.a,3);assert.equal(f.a.life,40);assert.equal(f.game.legalTargets(M.T.player(),red,f.b).includes(f.a),false);});
 test(role+': Teferi Protection phases permanents, locks life and life payments and ends before the next untap',async()=>{const f=setup(role),b=body(f),spell=await play(f,"Teferi's Protection");assert.equal(spell.zone,'exile');assert.ok(b.phasedOut);assert.equal(f.game.bf().length,0);await f.game.loseLife(f.a,8,'test');await f.game.gainLife(f.a,8);assert.equal(f.a.life,40);assert.equal(f.game.canPayLife(f.a,2),false);for(const k of Object.keys(f.a.pool))f.a.pool[k]=0;assert.equal(f.game.canPayMana(f.a,M.parseCost('{B/P}')),false);assert.equal(f.game.isProtectedFrom(f.a,card(f,'Ponder','hand',f.b)),true);f.game.mainPhase=async()=>{};f.game.combatPhase=async()=>{};await f.game.runTurn();assert.equal(b.phasedOut,false);assert.equal(f.game.canPayLife(f.a,2),true);});
}
test('Ravenous Slime replaces token deaths and only the affected player chosen exile replacement receives counters',async()=>{const f=setup(),a=await play(f,'Ravenous Slime'),b=card(f,'Ravenous Slime');const [t]=await f.game.makeTokens(M.C1719.token('Beast',['Beast'],3,3,['G']),f.b);await f.game.destroy(t);await settle(f.game);assert.equal(t.zone,'ceased');assert.equal(a.plus1()+b.plus1(),3);});
test('Teferi life lock permits ordinary mana and rejects life payments from both planning and payment',async()=>{const f=setup();await play(f,"Teferi's Protection");fuel(f.a);const n=mana(f.a);assert.equal(f.game.canPayMana(f.a,M.parseCost('{2}{U}')),true);assert.equal(await f.game.payMana(f.a,M.parseCost('{2}{U}')),true);assert.equal(n-mana(f.a),3);assert.equal(await f.game.payMana(f.a,M.parseCost('{0}'),null,{reservedLife:2}),false);assert.equal(f.a.life,40);});
