import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,fuel,mana,settle,target,tokens} from './helpers/c17-c19-fixtures.mjs';
async function blood(f,c,type){const v=card(f,'Falkenrath Noble');f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key===type)?type:q.type==='chooseTargets'?[c]:q.type==='chooseCards'&&q.prompt.includes('tap an untapped Vampire')?[v]:undefined;await play(f,'New Blood');return v;}
for(const role of ['human','ai']){
 test(role+': New Blood taps a Vampire, gains control and changes both creature type and the native tribal ability',async()=>{const f=setup(role),a=card(f,'Arahbo, Roar of the World','battlefield',f.b),v=await blood(f,a,'Cat');assert.ok(v.tapped);assert.equal(a.ctrl,f.a);assert.ok(a.hasSub('Vampire')&&!a.hasSub('Cat'));const cat=card(f,'Ajani\'s Pridemate'),vampire=card(f,'Falkenrath Noble');f.decide=(p,q)=>q.type==='chooseTargets'?[vampire]:undefined;await event(f,'beginCombat',{player:f.a});assert.equal(vampire.power,5);assert.equal(cat.power,2);});
 test(role+': New Blood modifies native tribal rules while leaving unrelated cards and later copies unchanged',async()=>{const f=setup(role),lord=card(f,'Elvish Archdruid','battlefield',f.b);await blood(f,lord,'Elf');const elf=card(f,'Llanowar Elves'),vamp=card(f,'Falkenrath Noble');assert.equal(elf.power,1);assert.equal(vamp.power,3);lord.sick=false;const [copy]=await M.C1719.copy({g:f.game,src:lord,you:f.a},lord);assert.ok(copy.hasSub('Elf')&&!copy.hasSub('Vampire'));assert.equal(elf.power,2);await f.game.move(lord,'hand');assert.ok(lord.hasSub('Elf'));});
 test(role+': New Blood cannot be cast without an untapped Vampire and rejects a stale tap cost atomically',async()=>{const f=setup(role),b=body(f,f.b),s=card(f,'New Blood','hand');fuel(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===s),false);const v=card(f,'Falkenrath Noble'),before=mana(f.a);f.decide=(p,q)=>q.type==='chooseTargets'?[b]:q.type==='chooseCards'&&q.prompt.includes('tap an untapped Vampire')?(v.tapped=true,[v]):undefined;assert.equal(await f.game.castSpell(f.a,s,{from:'hand'}),false);assert.equal(s.zone,'hand');assert.equal(mana(f.a),before);});
 test(role+': Leonin Arbiter stops searches while each player can independently pay its special action',async()=>{const f=setup(role),a=await play(f,'Leonin Arbiter');await play(f,'Cultivate');assert.equal(f.game.lands(f.a).length,0);assert.equal(f.a.hand.length,0);fuel(f.a);const entry=f.game.activatableList(f.a).find(e=>e.c1719IgnoreArbiter);assert.ok(entry);const before=mana(f.a);assert.equal(await f.game.activateAbility(f.a,entry),true);assert.equal(before-mana(f.a),2);assert.equal(f.game.stack.length,0);assert.equal(f.game.canSearchLibrary(f.a),true);assert.equal(f.game.canSearchLibrary(f.b),false);await play(f,'Cultivate');assert.equal(f.game.lands(f.a).length,1);assert.equal(f.a.hand.length,1);});
 test(role+': Multiple Leonin Arbiters require separate payments and their restriction does not stop top-card inspection',async()=>{const f=setup(role);await play(f,'Leonin Arbiter');await play(f,'Leonin Arbiter');fuel(f.a);const entries=f.game.activatableList(f.a).filter(e=>e.c1719IgnoreArbiter);assert.equal(entries.length,2);await f.game.activateAbility(f.a,entries[0]);assert.equal(f.game.canSearchLibrary(f.a),false);await f.game.activateAbility(f.a,entries[1]);assert.equal(f.game.canSearchLibrary(f.a),true);f.game.turnNo++;assert.equal(f.game.canSearchLibrary(f.a),false);await play(f,'Ponder');assert.equal(f.a.hand.length,1);});
}

test('New Blood recompiles Oracle creature-type descriptors and preserves unrelated tribal sources',async()=>{const f=setup(),c=card(f,'Elvish Champion','battlefield',f.b);assert.ok(c.def.oracleImplementation.length);await blood(f,c,'Elf');const elf=card(f,'Llanowar Elves'),vamp=card(f,'Falkenrath Noble');assert.equal(elf.power,1);assert.equal(vamp.power,3);assert.ok(vamp.kw('forestwalk'));assert.equal(elf.kw('forestwalk'),false);});
test('New Blood changes tokens created by native abilities but does not rewrite chosen-type values',async()=>{const f=setup(),c=card(f,"Freyalise, Llanowar's Fury");c.meta.c1719TextChanges=[{from:'Elf',to:'Vampire'}];f.game.recalc();await activate(f,c,0);const t=tokens(f)[0];assert.ok(t.hasSub('Vampire')&&!t.hasSub('Elf'));const lord=card(f,'Metallic Mimic');lord.meta.chosenType='Elf';lord.meta.c1719TextChanges=[{from:'Elf',to:'Vampire'}];f.game.recalc();assert.equal(lord.meta.chosenType,'Elf');assert.ok(lord.hasSub('Elf'));const elf=await play(f,'Llanowar Elves');assert.equal(elf.plus1(),1);});
test('local AI pays the Arbiter special action before casting its search spell and does not pay without a search',async()=>{const f=setup('ai');card(f,'Leonin Arbiter','battlefield',f.b);const s=card(f,'Cultivate','hand');fuel(f.a);let q={type:'main',player:f.a,casts:f.game.castableList(f.a),acts:f.game.activatableList(f.a),lands:[],phase:'main1'};const answer=await f.a.controller.decide(f.game,q);assert.equal(answer.kind,'activate');assert.ok(answer.entry.c1719IgnoreArbiter);assert.equal(await f.game.performAction(f.a,answer),true);assert.equal(f.game.canSearchLibrary(f.a),true);await f.game.move(s,'graveyard');f.game.turnNo++;q={...q,casts:[],acts:f.game.activatableList(f.a)};const idle=await f.a.controller.decide(f.game,q);assert.equal(idle.kind,'done');});
