import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,fuel,mana,settle,target,tokens} from './helpers/c17-c19-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Predict chooses a name before milling and draws two only for a correctly named milled card',async()=>{const f=setup(role),b=card(f,'Forest','library',f.b);f.decide=(p,q)=>q.type==='chooseOption'&&q.searchableChoices?'Forest':q.type==='chooseTargets'?[f.b]:undefined;await play(f,'Predict');assert.equal(b.zone,'graveyard');assert.equal(f.a.hand.length,2);});
 test(role+': Conundrum Sphinx collects all names before revealing top cards and bottoms mismatches',async()=>{const f=setup(role),s=await play(f,'Conundrum Sphinx'),a=card(f,'Forest','library'),b=card(f,'Island','library',f.b);f.decide=(p,q)=>q.type==='chooseOption'&&q.searchableChoices?'Forest':undefined;await event(f,'attacks',{card:s,player:f.a,defender:f.b});assert.equal(a.zone,'hand');assert.equal(f.b.library[0],b);});
 test(role+': Krrik pays black symbols with life for both spells and abilities and gains cast counters',async()=>{const f=setup(role),k=await play(f,"K'rrik, Son of Yawgmoth"),n=card(f,'Nightshade Assassin','hand');for(const key of Object.keys(f.a.pool))f.a.pool[key]=0;f.a.pool.C=2;assert.equal(await f.game.castSpell(f.a,n,{from:'hand'}),true);await settle(f.game);assert.equal(f.a.life,36);assert.equal(k.plus1(),1);const v=card(f,'Vein Drinker');v.sick=false;const e=card(f,'Mairsil, the Pretender');const p=M.parseCost('{B}{B}');assert.equal(await f.game.payMana(f.a,p,{card:e,isAbility:true}),true);assert.equal(f.a.life,32);});
 test(role+': Marisi blocks opposing combat casting and goads the damaged player creatures',async()=>{const f=setup(role),m=await play(f,'Marisi, Breaker of the Coil'),b=body(f,f.b),bolt=card(f,'Lightning Bolt','hand',f.b);f.game.phase='combat';assert.equal(f.game.canCastTiming(f.b,bolt),false);await f.game.damagePlayer(m,f.b,1,{combat:true});await settle(f.game);assert.equal(f.game.isGoaded(b),true);});
 test(role+': Mathas grants a bounty death ability independent of Mathas remaining in play',async()=>{const f=setup(role),m=await play(f,'Mathas, Fiend Seeker'),b=body(f,f.b);target(f,b);await event(f,'endStep',{player:f.a});assert.equal(b.counters.bounty,1);await f.game.move(m,'graveyard');await f.game.destroy(b);await settle(f.game);assert.equal(f.a.hand.length,1);assert.equal(f.a.life,42);assert.equal(f.others[1].life,42);assert.equal(f.b.life,40);});
 test(role+': Mirri enforces per-defender attack and per-opponent blocking caps',async()=>{const f=setup(role),m=await play(f,'Mirri, Weatherlight Duelist'),a=body(f,f.b),b=body(f,f.b);m.tapped=true;f.game.recalc();a.attacking=f.a;b.attacking=f.a;assert.equal(f.game.attackGroupLegal([a,b]),false);b.attacking=f.others[1];assert.equal(f.game.attackGroupLegal([a,b]),true);await event(f,'attacks',{card:m,player:f.a,defender:f.b});const other=body(f);assert.equal(f.game.blockDeclarationLegal([m,other],[{blocker:a,attacker:m},{blocker:b,attacker:other}]),false);});
 test(role+': O-Kagachi targets only the damaged player nonlands when that player attacked its controller last turn',async()=>{const f=setup(role),o=await play(f,'O-Kagachi, Vengeful Kami'),b=body(f,f.b);f.b.c1719PreviousTurnAttacks=[f.a.idx];target(f,b);await f.game.damagePlayer(o,f.b,1,{combat:true});await settle(f.game);assert.equal(b.zone,'exile');});
 test(role+': Portal Mage reselects an attacker defender during declare attackers without attack triggers',async()=>{const f=setup(role),b=body(f,f.b);b.attacking=f.a;f.game.phase='combat';f.game.step='attackers';f.game.combat={attackers:[b],blockers:[]};f.decide=(p,q)=>q.type==='chooseTargets'?[b]:q.type==='chooseOption'&&q.prompt.includes('new defender')?'1':undefined;await play(f,'Portal Mage');assert.equal(b.attacking,f.others[1]);});
 test(role+': Tahngarth joins an opponent attack and its control expires at end of combat',async()=>{const f=setup(role),t=await play(f,'Tahngarth, First Mate'),b=body(f,f.b);t.tapped=true;b.attacking=f.others[1];f.game.phase='combat';f.game.combat={attackers:[b],blockers:[]};await event(f,'attackersDeclared',{player:f.b,attackers:[b]});assert.equal(t.ctrl,f.b);assert.equal(t.attacking,f.others[1]);assert.equal(f.game.blockerBounds(t).max,1);f.game.untilEffects=f.game.untilEffects.filter(e=>e.expires!=='combat');f.game.recalc();assert.equal(t.ctrl,f.a);});
 test(role+': Varchild creates restricted Survivors for the damaged player and gains them when leaving',async()=>{const f=setup(role),v=await play(f,'Varchild, Betrayer of Kjeldor');await f.game.damagePlayer(v,f.b,2,{combat:true});await settle(f.game);const made=tokens(f,f.b);assert.equal(made.length,2);assert.ok(made.every(c=>c.cur.cantBlock));assert.equal(f.game.canAttackTarget(made[0],f.a),false);await f.game.move(v,'graveyard');await settle(f.game);assert.ok(made.every(c=>c.ctrl===f.a));});
 test(role+': Jeskai Infiltrator manifests itself and its top card with new hidden object identifiers',async()=>{const f=setup(role),j=await play(f,'Jeskai Infiltrator'),top=card(f,'Sol Ring','library'),old=j.iid;assert.ok(j.cur.unblockable);await f.game.damagePlayer(j,f.b,1,{combat:true});await settle(f.game);assert.ok(j.faceDown&&top.faceDown);assert.equal(j.zone,'battlefield');assert.notEqual(j.iid,old);assert.equal(f.game.creatures(f.a).length,2);});
 test(role+': Dark Impostor pays six, exiles a creature and gains its activated abilities',async()=>{const f=setup(role),d=await play(f,'Dark Impostor'),m=card(f,'Mercurial Chemister','battlefield',f.b);target(f,m);await activate(f,d);assert.equal(m.zone,'exile');assert.equal(d.plus1(),1);d.sick=false;await activate(f,d,e=>e.ability?.label==='Draw two cards');assert.equal(f.a.hand.length,2);});
 test(role+': Mairsil cages a card and allows each gained ability only once per turn',async()=>{const f=setup(role),c=card(f,'Mercurial Chemister','hand'),m=await play(f,'Mairsil, the Pretender');assert.equal(c.zone,'exile');assert.equal(c.counters.cage,1);m.sick=false;await activate(f,m,e=>e.ability?.label==='Draw two cards');f.game.untap(m);assert.equal(f.a.hand.length,2);assert.equal(f.game.activatableList(f.a).some(e=>e.card===m&&e.ability?.label==='Draw two cards'),false);});
 test(role+': Budoka flips after its tenth land and Dokai makes a land-count Elemental; a token copy starts unflipped',async()=>{const f=setup(role),b=await play(f,'Budoka Gardener');b.sick=false;for(let i=0;i<9;i++)card(f,'Forest');const l=card(f,'Island','hand');await activate(f,b);assert.equal(l.zone,'battlefield');assert.equal(b.name,'Dokai, Weaver of Life');assert.equal(b.power,3);assert.equal(b.mv,2);f.game.untap(b);await activate(f,b);assert.equal(tokens(f)[0].power,10);const [copy]=await M.C1719.copy({g:f.game,src:b,you:f.a},b);assert.equal(copy.name,'Budoka Gardener');await f.game.move(b,'hand');assert.equal(b.name,'Budoka Gardener');});
 test(role+': Emissary reveals its secret as a once-only cost and retargets the chosen opponent spell',async()=>{const f=setup(role);f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('secretly')?String(f.b.idx):undefined;const e=await play(f,'Emissary of Grudges'),s=card(f,'Lightning Bolt','hand',f.b);fuel(f.b);target(f,f.a);assert.equal(await f.game.castSpell(f.b,s,{from:'hand'}),true);const so=f.game.stack.at(-1);f.decide=(p,q)=>q.type==='chooseTargets'?q.candidates.includes(so)?[so]:[f.b]:undefined;await activate(f,e);assert.equal(f.b.life,37);assert.equal(f.a.life,40);assert.equal(f.game.activatableList(f.a).some(x=>x.card===e&&x.ability),false);});
}
