import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,tokens,settle,fuel,event,mana} from './helpers/c19-c20-fixtures.mjs';
const cycle=async(f,c,match=e=>true,resolve=true)=>{const e=f.game.activatableList(f.a).find(e=>e.card===c&&e.cycling&&match(e));assert.ok(e,c.name+' cycling offered');assert.equal(await f.game.activateAbility(f.a,e),true);if(resolve)await settle(f.game);return e;};
for(const role of ['human','ai']){
 test(role+': Gavi offers zero only for the first cycling and second draw creates exactly one token',async()=>{const f=setup(role);card(f,'Gavi, Nest Warden');const a=card(f,'Tranquil Thicket','hand'),b=card(f,'Forgotten Cave','hand');await f.game.draw(f.a,1);const n=mana(f.a);await cycle(f,a);assert.equal(mana(f.a),n);assert.equal(tokens(f).length,1);assert.deepEqual(Array.from(tokens(f)[0].colors),['R','W']);assert.equal(f.game.activatableList(f.a).some(e=>e.card===b&&e.label.includes('{0}')),false);fuel(f.a);await cycle(f,b);assert.equal(tokens(f).length,1);});
 test(role+': Gavi and Valiant consider cycling before they entered and reset on every turn',async()=>{const f=setup(role),a=card(f,'Tranquil Thicket','hand');fuel(f.a);await cycle(f,a);card(f,'Gavi, Nest Warden');card(f,'Valiant Rescuer');const b=card(f,'Forgotten Cave','hand');assert.equal(f.game.activatableList(f.a).some(e=>e.card===b&&e.label.includes('{0}')),false);await cycle(f,b);assert.equal(tokens(f).length,1,'Gavi second draw only');f.a.turnState=f.a.freshTurnState();const c=card(f,'Tranquil Thicket','hand');await cycle(f,c);assert.equal(tokens(f).length,2,'Valiant first cycle on a new turn');});
 test(role+': New Perspectives draws three and free cycling checks seven before discarding',async()=>{const f=setup(role);for(let i=0;i<3;i++)card(f,'Island','hand');await play(f,'New Perspectives');const c=card(f,'Tranquil Thicket','hand');assert.equal(f.a.hand.length,7);for(const k of Object.keys(f.a.pool))f.a.pool[k]=0;await cycle(f,c,e=>e.label.includes('{0}'),false);assert.equal(f.a.hand.length,6);const d=card(f,'Forgotten Cave','hand');await f.game.move(f.a.hand.find(x=>x!==d),'graveyard');assert.equal(f.game.activatableList(f.a).some(e=>e.card===d),false);await settle(f.game);assert.ok(f.game.activatableList(f.a).some(e=>e.card===d&&e.label.includes('{0}')));});
 test(role+': Tectonic grants a second cycling option to lands and loses it when removed',async()=>{const f=setup(role),s=card(f,'Tectonic Reformation'),a=card(f,'Tranquil Thicket','hand'),b=card(f,'Island','hand');fuel(f.a);assert.equal(f.game.activatableList(f.a).filter(e=>e.card===a&&e.cycling).length,2);const stale=f.game.activatableList(f.a).find(e=>e.card===b&&e.cycling);assert.ok(stale);await f.game.move(s,'graveyard');assert.equal(await f.game.activateAbility(f.a,stale),false);await f.game.putPermanentOntoBattlefield(s,f.a);await cycle(f,b,e=>e.label.includes('{R}'));assert.equal(b.zone,'graveyard');assert.equal(b.def.cycling,undefined);});
 test(role+': Gavi zero cycling sets an X cycling cost to zero without changing paid cycling',async()=>{const f=setup(role);card(f,'Gavi, Nest Warden');const c=card(f,'Shark Typhoon','hand');fuel(f.a);await cycle(f,c,e=>e.label.includes('{0}'));assert.equal(tokens(f).filter(c=>c.hasSub('Shark')).length,0);assert.equal(f.a.turnState.c1920Cycled,1);});
 test(role+': Sarcophagus keeps cycled cards, casts them at normal cost, then exiles them',async()=>{const f=setup(role);card(f,'Abandoned Sarcophagus');const c=card(f,'Curator of Mysteries','hand');fuel(f.a);await cycle(f,c);assert.equal(c.zone,'graveyard');const e=f.game.castableList(f.a).find(e=>e.card===c);assert.ok(e);assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),true);await settle(f.game);assert.equal(c.zone,'battlefield');await f.game.destroy(c);assert.equal(c.zone,'exile');});
 test(role+': Sarcophagus exiles discarded and milled cycling cards including Tectonic lands',async()=>{const f=setup(role);card(f,'Abandoned Sarcophagus');card(f,'Tectonic Reformation');const c=card(f,'Curator of Mysteries','hand'),land=card(f,'Island','hand'),mill=card(f,'Curator of Mysteries','library');await f.game.discard(f.a,[c,land]);await f.game.mill(f.a,1);assert.equal(c.zone,'exile');assert.equal(land.zone,'exile');assert.equal(mill.zone,'exile');const own=card(f,'Curator of Mysteries','hand',f.b);await f.game.discard(f.b,[own]);assert.equal(own.zone,'graveyard');});
 test(role+': Astral Drift cycling exiles now and returns only its exact exiled object next end step',async()=>{const f=setup(role),c=body(f,f.b),s=card(f,'Astral Drift','hand');target(f,c);fuel(f.a);await cycle(f,s);assert.equal(c.zone,'exile');await event(f,'endStep',{player:f.b});assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.b);});
 test(role+': Astral Drift on the battlefield reacts to another card cycling',async()=>{const f=setup(role);card(f,'Astral Drift');const c=body(f,f.b),s=card(f,'Tranquil Thicket','hand');target(f,c);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':prior(p,q);fuel(f.a);await cycle(f,s);assert.equal(c.zone,'exile');await f.game.move(c,'hand');await f.game.move(c,'exile');await event(f,'endStep',{player:f.a});assert.equal(c.zone,'exile');});
 test(role+': Nimble cycling counters an opposing ability independently from the cycling draw',async()=>{const f=setup(role),source=body(f,f.b),so={kind:'ability',ctrl:f.b,srcCard:source,name:'Opposing draw',targets:[],run:ctx=>ctx.g.draw(ctx.you,5)};f.game.stack.push(so);const c=card(f,'Nimble Obstructionist','hand');target(f,so);fuel(f.a);const before=f.b.hand.length;await cycle(f,c);assert.equal(f.b.hand.length,before);assert.equal(f.a.hand.length,1);});
 test(role+': Rooting Moloch grants a cycling land until the next own turn and Herald reanimates cycling permanents',async()=>{const f=setup(role),land=card(f,'Tranquil Thicket','graveyard');target(f,land);await play(f,'Rooting Moloch');assert.equal(land.zone,'exile');assert.ok(f.game.playableLands(f.a).includes(land));const a=card(f,'Curator of Mysteries','graveyard'),b=card(f,'Astral Drift','graveyard');target(f,a,b);await play(f,'Herald of the Forgotten');assert.equal(a.zone,'battlefield');assert.equal(b.zone,'battlefield');});
 test(role+': Spellpyre returns a cycling instant at entry and itself after two cycles',async()=>{const f=setup(role),c=card(f,'Decree of Pain','graveyard');target(f,c);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':prior(p,q);const s=await play(f,'Spellpyre Phoenix');assert.equal(c.zone,'hand');await f.game.move(s,'graveyard');fuel(f.a);await cycle(f,card(f,'Tranquil Thicket','hand'));await cycle(f,card(f,'Forgotten Cave','hand'));await event(f,'endStep',{player:f.b});assert.equal(s.zone,'hand');});
}
test('Free cycling replaces a life or sacrifice cycling cost but still discards the card',async()=>{const f=setup();card(f,'Gavi, Nest Warden');const c=card(f,'Street Wraith','hand');const life=f.a.life;await cycle(f,c,e=>e.label.includes('{0}'));assert.equal(f.a.life,life);assert.equal(c.zone,'graveyard');});
test('A stale free cycling action and an invented free option cannot pay for a second card',async()=>{const f=setup();card(f,'Gavi, Nest Warden');const c=card(f,'Tranquil Thicket','hand'),d=card(f,'Forgotten Cave','hand'),stale=f.game.activatableList(f.a).find(e=>e.card===d);await cycle(f,c);assert.equal(await f.game.activateAbility(f.a,stale),false);assert.equal(await f.game.activateAbility(f.a,{card:d,cycling:true,cyclingId:'invented'}),false);assert.equal(d.zone,'hand');});
