import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,settle,fuel,event} from './helpers/c19-c20-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Sanctuary Blade chooses on each new attachment and changes the host’s protection',async()=>{const f=setup(role),s=card(f,'Sanctuary Blade'),a=body(f),b=body(f),red=card(f,'Lightning Bolt','hand',f.b),blue=card(f,'Urban Evolution','hand',f.b);let color='R',choices=0;f.decide=(p,q)=>{if(q.type==='chooseOption'&&q.options?.some(o=>o.key==='R')){choices++;return color;}};await f.game.attach(s,a);assert.equal(a.power,4);assert.equal(f.game.isProtectedFrom(a,red),true);await f.game.attach(s,a);assert.equal(choices,1);color='U';await f.game.attach(s,b);assert.equal(a.power,2);assert.equal(f.game.isProtectedFrom(a,red),false);assert.equal(f.game.isProtectedFrom(b,blue),true);assert.equal(f.game.isProtectedFrom(b,red),false);});
 test(role+': Prismatic Strands prevents damage from a chosen color to every kind of recipient',async()=>{const f=setup(role),red=card(f,'Fireflux Squad','battlefield',f.b),blue=card(f,'Curator of Mysteries','battlefield',f.b),a=body(f);f.decide=(p,q)=>q.type==='chooseOption'&&q.options?.some(o=>o.key==='R')?'R':undefined;await play(f,'Prismatic Strands');const life=f.a.life;await f.game.damagePlayer(red,f.a,3);await f.game.damageAny(red,a,3);assert.equal(f.a.life,life);assert.equal(a.damage,0);await f.game.damageAny(blue,a,1);assert.equal(a.damage,1);await f.game.damagePlayer(red,f.a,1,{cantBePrevented:true});assert.equal(f.a.life,life-1);});
 test(role+': Prismatic Strands flashback taps an untapped white creature and exiles the spell',async()=>{const f=setup(role),s=card(f,'Prismatic Strands','graveyard');fuel(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===s),false);const white=card(f,'Valiant Rescuer');const e=f.game.castableList(f.a).find(e=>e.card===s);assert.ok(e?.alt.flashback);assert.equal(await f.game.castSpell(f.a,s,{from:e.from,alt:e.alt}),true);assert.equal(white.tapped,true);await settle(f.game);assert.equal(s.zone,'exile');});
 test(role+': Prismatic Strands refuses forged or stale zero-cost flashback',async()=>{const f=setup(role),s=card(f,'Prismatic Strands','graveyard'),c=card(f,'Valiant Rescuer');fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===s);assert.equal(await f.game.castSpell(f.a,s,{from:'graveyard',alt:{flashback:true,altCostStr:'{0}'}}),false);c.tapped=true;assert.equal(await f.game.castSpell(f.a,s,{from:e.from,alt:e.alt}),false);assert.equal(s.zone,'graveyard');});
 test(role+': Eon Frolicker grants an extra turn and protects only the player and planeswalkers present at resolution',async()=>{const f=setup(role),pw=card(f,'Ajani Unyielding'),enemy=body(f,f.b);pw.counters.loyalty=10;target(f,f.b);let extra;f.game.scheduleExtraTurn=p=>{extra=p;};await play(f,'Eon Frolicker');assert.equal(extra,f.b);assert.equal(f.game.isProtectedFrom(f.a,enemy),true);assert.equal(f.game.isProtectedFrom(pw,enemy),true);const next=card(f,'Jace, Architect of Thought');assert.equal(f.game.isProtectedFrom(next,enemy),false);const before=f.a.life;await f.game.damagePlayer(enemy,f.a,8);assert.equal(f.a.life,before);});
 test(role+': Soulflayer and Kathril recognize printed keyword lines that also contain protection',async()=>{const f=setup(role),a=card(f,'Sphinx of the Steel Wind','graveyard');assert.equal(a.kw('flying'),true);assert.equal(a.kw('lifelink'),true);f.decide=(p,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='delve'?[a]:undefined;const s=await play(f,'Soulflayer');assert.equal(s.kw('flying'),true);assert.equal(s.kw('lifelink'),true);const b=card(f,'Akroma, Angel of Wrath','graveyard');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.includes('Kathril')?[s]:undefined;await play(f,'Kathril, Aspect Warper');assert.equal(s.counters['flying'],1);assert.equal(s.counters['first strike'],1);});
}
