import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,target,tokens,settle,fuel,event} from './helpers/c19-c20-fixtures.mjs';
const down=(f,name)=>play(f,name,{alt:{faceDownCast:'morph'}});
const up=async(f,c)=>{fuel(f.a);const e=f.game.activatableList(f.a).find(e=>e.card===c&&e.turnFaceUp);assert.ok(e,c.meta.faceDownDef.name+' face-up action');assert.equal(await f.game.activateAbility(f.a,e),true);await settle(f.game);};
const yes=f=>{const previous=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':previous?.(p,q);};
for(const role of ['human','ai']){
 test(role+': Chromeshell Crab exchanges both selected creatures after morph',async()=>{const f=setup(role),a=body(f),b=body(f,f.b),c=await down(f,'Chromeshell Crab');target(f,a,b);yes(f);await up(f,c);assert.equal(a.ctrl,f.b);assert.equal(b.ctrl,f.a);assert.equal(c.ctrl,f.a);});
 test(role+': Deathmist Raptor returns from the graveyard when another permanent turns face up',async()=>{const f=setup(role),r=card(f,'Deathmist Raptor','graveyard'),c=await down(f,'Hooded Hydra');yes(f);await up(f,c);assert.equal(r.zone,'battlefield');});
 test(role+': Deathmist Raptor can return face down and later pays its megamorph cost',async()=>{const f=setup(role),r=card(f,'Deathmist Raptor','graveyard'),c=await down(f,'Hooded Hydra');f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='down')?'down':q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':undefined;await up(f,c);assert.equal(r.faceDown,true);await up(f,r);assert.equal(r.name,'Deathmist Raptor');assert.equal(r.counters['+1/+1'],1);});
 test(role+': Kadena’s Silencer counters opposing abilities and leaves spells alone',async()=>{const f=setup(role),c=await down(f,"Kadena's Silencer"),ornament=card(f,"Bonder's Ornament",'battlefield',f.b);fuel(f.b);const e=f.game.activatableList(f.b).find(e=>e.card===ornament);assert.ok(e);await f.game.activateAbility(f.b,e);const spell=card(f,'Brainstorm','hand',f.b);await f.game.castSpell(f.b,spell);const n=f.b.hand.length;await up(f,c);assert.equal(c.counters['+1/+1'],1);assert.equal(f.b.hand.length,n+1);assert.equal(spell.zone,'graveyard');});
 test(role+': Kheru Spellsnatcher counters into exile and its permission survives the source leaving',async()=>{const f=setup(role),c=await down(f,'Kheru Spellsnatcher'),s=card(f,'Brainstorm','hand',f.b);fuel(f.b);assert.equal(await f.game.castSpell(f.b,s),true);const so=f.game.stack.find(so=>so.card===s);target(f,so);await up(f,c);assert.equal(s.zone,'exile');await f.game.move(c,'graveyard');const e=f.game.castableList(f.a).find(e=>e.card===s);assert.ok(e?.alt.free);assert.equal(await f.game.castSpell(f.a,s,{from:e.from,alt:e.alt}),true);await settle(f.game);assert.equal(s.zone,'graveyard');});
 test(role+': Silumgar Assassin destroys a small creature and uses its current power for blocking',async()=>{const f=setup(role),small=body(f,f.b),large=card(f,'Colossal Dreadmaw','battlefield',f.b),c=await down(f,'Silumgar Assassin');target(f,small);await up(f,c);assert.equal(c.power,3);assert.equal(small.zone,'graveyard');c.attacking=f.b;assert.equal(f.game.canBlock(large,c),false);M.E.pumpUntilEOT(f.game,c,4,4);assert.equal(f.game.canBlock(large,c),true);});
 test(role+': Hooded Hydra gets five counters before state actions and creates five Snakes when it dies',async()=>{const f=setup(role),c=await down(f,'Hooded Hydra');assert.equal(c.power,2);await up(f,c);assert.equal(c.zone,'battlefield');assert.equal(c.counters['+1/+1'],5);await f.game.sacrifice(f.a,c);await settle(f.game);assert.equal(tokens(f).length,5);});
 test(role+': Gift of Doom sacrifices another creature as a morph cost and attaches without targeting',async()=>{const f=setup(role),sac=body(f),host=card(f,'Colossal Dreadmaw'),c=await down(f,'Gift of Doom');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.startsWith('Gift of Doom: attach')?[host]:q.type==='chooseCards'&&q.from.includes(sac)&&q.aiHint?.kind==='sacrifice'?[sac]:undefined;await up(f,c);assert.equal(c.is('Creature'),false);assert.equal(c.attachedTo,host.iid);assert.ok(host.kw('indestructible')&&host.kw('deathtouch'));assert.ok([sac,host].some(c=>c.zone==='graveyard'));});
 test(role+': Gift of Doom cannot turn face up with itself as the only creature',async()=>{const f=setup(role),c=await down(f,'Gift of Doom');fuel(f.a);assert.equal(f.game.activatableList(f.a).some(e=>e.card===c&&e.turnFaceUp),false);assert.equal(await f.game.turnFaceUp(f.a,c,'{0}','morph'),false);assert.equal(c.faceDown,true);});
 test(role+': Vesuvan Shapeshifter copies, turns face down in place and can copy again',async()=>{const f=setup(role),a=card(f,'Colossal Dreadmaw');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.startsWith('Vesuvan Shapeshifter:')?[a]:q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':undefined;const c=await play(f,'Vesuvan Shapeshifter'),v=c.zoneVersion;assert.equal(c.name,'Colossal Dreadmaw');assert.equal(c.power,6);await event(f,'upkeep',{player:f.a});assert.equal(c.faceDown,true);assert.equal(c.zoneVersion,v);assert.equal(c.meta.faceDownDef.name,'Vesuvan Shapeshifter');await up(f,c);assert.equal(c.name,'Colossal Dreadmaw');assert.equal(c.power,6);});
 test(role+': Scroll of Fate manifests a chosen hand card without casting it',async()=>{const f=setup(role),c=card(f,'Scroll of Fate'),h=card(f,'Colossal Dreadmaw','hand');await activate(f,c);assert.equal(h.zone,'battlefield');assert.equal(h.faceDown,true);assert.equal(h.power,2);await up(f,h);assert.equal(h.name,'Colossal Dreadmaw');assert.equal(h.power,6);});
 test(role+': Thieving Amalgam manifests another owner’s top card and drains when it dies',async()=>{const f=setup(role),c=card(f,'Thieving Amalgam'),h=card(f,'Island','library',f.b),a=f.a.life,b=f.b.life;await event(f,'upkeep',{player:f.b});assert.equal(h.owner,f.b);assert.equal(h.ctrl,f.a);assert.equal(h.faceDown,true);await f.game.sacrifice(f.a,h);await settle(f.game);assert.equal(h.zone,'graveyard');assert.equal(f.a.life,a+2);assert.equal(f.b.life,b-2);});
 test(role+': Trail of Mystery searches on face-down entry and pumps only the turned creature',async()=>{const f=setup(role);card(f,'Trail of Mystery');const land=card(f,'Forest','library'),before=f.a.hand.length;yes(f);const c=await down(f,'Hooded Hydra');assert.equal(f.a.hand.length,before+1);await up(f,c);assert.equal(c.power,7);});
 test(role+': Predatory Impetus supplies goad and a blocking requirement while attached',async()=>{const f=setup(role),c=body(f,f.b);target(f,c);const a=await play(f,'Predatory Impetus');assert.equal(c.power,5);assert.ok(c.cur.goadedBy.includes(f.a));assert.ok(c.cur.mustBeBlocked);await f.game.move(a,'graveyard');assert.equal(c.power,2);assert.equal(!!c.cur.mustBeBlocked,false);});
 test(role+': Psychic Impetus scries for its controller when the enchanted enemy attacks',async()=>{const f=setup(role),c=body(f,f.b);target(f,c);await play(f,'Psychic Impetus');let scries=0;const base=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=async(g,q)=>{if(q.type==='scry')scries++;return base(g,q);};await event(f,'attacks',{card:c,player:f.b,defender:f.a});assert.equal(scries,1);assert.equal(c.power,4);});
}
