import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,tokens,settle,fuel} from './helpers/c19-c20-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Blood Curdle destroys then chooses a non-target recipient for a menace counter',async()=>{const f=setup(role),ours=body(f),victim=body(f,f.b);target(f,victim);await play(f,'Blood Curdle');assert.equal(victim.zone,'graveyard');assert.equal(ours.counters.menace,1);assert.ok(ours.kw('menace'));});
 test(role+': Call the Coppercoats counts all selected opposing creatures',async()=>{const f=setup(role,3);body(f,f.b);body(f,f.b);const p=f.game.players[2];body(f,p);target(f,f.b,p);await play(f,'Call the Coppercoats');assert.equal(tokens(f).length,3);assert.ok(tokens(f).every(c=>c.hasSub('Human')&&c.hasSub('Soldier')&&c.power===1));});
 test(role+': Curious Herd counts artifacts once, including artifact creatures',async()=>{const f=setup(role);card(f,'Sol Ring','battlefield',f.b);card(f,'Ornithopter','battlefield',f.b);body(f,f.b);target(f,f.b);await play(f,'Curious Herd');assert.equal(tokens(f).length,2);assert.ok(tokens(f).every(c=>c.power===3&&c.hasSub('Beast')));});
 test(role+': Ever After returns two creatures with added Zombie type and goes to the library bottom',async()=>{const f=setup(role),a=card(f,'Grizzly Bears','graveyard'),b=card(f,'Llanowar Elves','graveyard');target(f,a,b);const s=await play(f,'Ever After');assert.equal(a.zone,'battlefield');assert.equal(b.zone,'battlefield');assert.ok(a.hasSub('Bear')&&a.hasSub('Zombie'));assert.ok(a.colors.includes('G')&&a.colors.includes('B'));assert.equal(f.a.library[0],s);});
 test(role+': Extract from Darkness can reanimate a creature milled during resolution',async()=>{const f=setup(role);const c=card(f,'Grizzly Bears','library',f.b);card(f,'Island','library',f.a);await play(f,'Extract from Darkness');assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);assert.equal(c.owner,f.b);});
 test(role+': Fated Return grants indestructible to the returned incarnation only',async()=>{const f=setup(role),c=card(f,'Grizzly Bears','graveyard',f.b);target(f,c);await play(f,'Fated Return');assert.equal(c.ctrl,f.a);assert.ok(c.kw('indestructible'));await f.game.move(c,'exile');await f.game.putPermanentOntoBattlefield(c,f.b);assert.equal(c.kw('indestructible'),false);});
 test(role+': both Find and Finality have distinct costs and effects',async()=>{const f=setup(role),a=card(f,'Grizzly Bears','graveyard'),b=card(f,'Llanowar Elves','graveyard');target(f,a,b);await play(f,'Find // Finality',{alt:{splitHalf:'find',altCostStr:'{B/G}{B/G}',name:'Find'}});assert.equal(a.zone,'hand');assert.equal(b.zone,'hand');const big=card(f,'Colossal Dreadmaw'),small=body(f,f.b);await play(f,'Find // Finality',{alt:{splitHalf:'finality',altCostStr:'{4}{B}{G}',name:'Finality'}});assert.equal(small.zone,'graveyard');assert.equal(big.zone,'battlefield');assert.ok(big.power>=2);});
 test(role+': Leadership Vacuum moves every controlled commander and draws',async()=>{const f=setup(role),c=body(f,f.b);c.commander=true;target(f,f.b);const before=f.a.hand.length;await play(f,'Leadership Vacuum');assert.equal(c.zone,'command');assert.equal(f.a.hand.length,before+1);});
 test(role+': Strength of the Tajuru gives every paid target X counters',async()=>{const f=setup(role),a=body(f),b=body(f),c=body(f);target(f,a,b,c);const choose=f.decide;f.decide=(p,q)=>q.type==='chooseX'&&q.prompt?.startsWith('Multikicker')?Math.min(2,q.max):choose(p,q);await play(f,'Strength of the Tajuru',{xVal:3});assert.ok(a.counters['+1/+1']>0);assert.equal(b.counters['+1/+1'],a.counters['+1/+1']);assert.equal(c.counters['+1/+1'],a.counters['+1/+1']);});
 test(role+': Surreal Memoir returns only an instant and establishes rebound',async()=>{const f=setup(role),c=card(f,'Brainstorm','graveyard'),other=card(f,'Cultivate','graveyard');const s=await play(f,'Surreal Memoir');assert.equal(c.zone,'hand');assert.equal(other.zone,'graveyard');assert.equal(s.zone,'exile');assert.ok(f.game.delayed.length);});
 test(role+': Unbreakable Bond enters with a real lifelink counter',async()=>{const f=setup(role),c=card(f,'Grizzly Bears','graveyard');target(f,c);await play(f,'Unbreakable Bond');assert.equal(c.counters.lifelink,1);assert.ok(c.kw('lifelink'));});
 test(role+': Unexpectedly Absent places the permanent under exactly X cards',async()=>{const f=setup(role),c=body(f,f.b);for(let n=0;n<5;n++)card(f,'Island','library',f.b);target(f,c);f.x=2;await play(f,'Unexpectedly Absent',{xVal:2});assert.equal(c.zone,'library');assert.equal(f.b.library.indexOf(c),f.b.library.length-3);});
 test(role+': Urban Evolution draws three and grants one additional land play',async()=>{const f=setup(role),before=f.a.hand.length,limit=f.game.landPlayLimit(f.a);await play(f,'Urban Evolution');assert.equal(f.a.hand.length,before+3);assert.equal(f.game.landPlayLimit(f.a),limit+1);});
 test(role+': Zenith Flare counts cycling cards and gains its resolved amount',async()=>{const f=setup(role);card(f,'Tranquil Thicket','graveyard');card(f,'Forgotten Cave','graveyard');card(f,'Island','graveyard');target(f,f.b);const a=f.a.life,b=f.b.life;await play(f,'Zenith Flare');assert.equal(f.a.life,a+2);assert.equal(f.b.life,b-2);});
 test(role+': Open into Wonder gives combat-damage draw triggers and unblockability',async()=>{const f=setup(role),c=body(f);f.x=1;target(f,c);await play(f,'Open into Wonder');assert.ok(c.cur.unblockable);const before=f.a.hand.length;await f.game.damagePlayer(c,f.b,2,{combat:true});await settle(f.game);assert.equal(f.a.hand.length,before+1);});
 test(role+': Mass Diminish sets base stats before counters and leaves later entrants unchanged',async()=>{const f=setup(role),c=card(f,'Colossal Dreadmaw','battlefield',f.b);f.game.addCounters(c,'+1/+1',2);target(f,f.b);await play(f,'Mass Diminish');assert.equal(c.power,3);assert.equal(c.toughness,3);assert.equal(c.kw('trample'),true);const later=body(f,f.b);assert.equal(later.power,2);});
 test(role+': Runic Repetition returns a flashback card from exile',async()=>{const f=setup(role),c=card(f,'Mass Diminish','exile');target(f,c);await play(f,'Runic Repetition');assert.equal(c.zone,'hand');});
}
test('Commander ban status is an import warning while semantic and deck structure gates remain errors',()=>{const catalog=M.CARD_CATALOG['Sol Ring'],old=catalog.commanderLegality;catalog.commanderLegality='banned';try{const parsed=M.parseDeckText('Commander\n1 Ashling, the Limitless\nDeck\n1 Sol Ring\n98 Wastes');const v=M.validateImportedDeck(parsed);assert.equal(v.ok,true,JSON.stringify(v.errors));assert.ok(v.warnings.some(w=>w.code==='commander-legality'&&w.card==='Sol Ring'));catalog.deckImportEligible=false;const unsupported=M.validateImportedDeck(parsed);assert.equal(unsupported.ok,false);assert.ok(unsupported.errors.some(e=>e.code==='engine-unsupported'));}finally{catalog.commanderLegality=old;catalog.deckImportEligible=true;}});
