import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,target,tokens,settle,event,fuel} from './helpers/c19-c20-fixtures.mjs';
const walker=async(f,name)=>{const c=await play(f,name,{xVal:4});c.counters.loyalty=20;f.game.recalc();return c;};
for(const role of ['human','ai']){
 test(role+': Ajani +2 takes all revealed nonland permanents and bottoms the rest',async()=>{const f=setup(role),c=await walker(f,'Ajani Unyielding'),land=card(f,'Island','library'),spell=card(f,'Brainstorm','library'),artifact=card(f,'Sol Ring','library');await activate(f,c,0);assert.equal(artifact.zone,'hand');assert.ok(f.a.library.indexOf(land)<2&&f.a.library.indexOf(spell)<2);assert.equal(c.counters.loyalty,22);});
 test(role+': Ajani -2 captures the exiled creature power and original controller',async()=>{const f=setup(role),c=await walker(f,'Ajani Unyielding'),a=card(f,'Colossal Dreadmaw','battlefield',f.b),before=f.b.life;target(f,a);await activate(f,c,1);assert.equal(a.zone,'exile');assert.equal(f.b.life,before+6);});
 test(role+': Ajani ultimate adds creature and other-walker counters',async()=>{const f=setup(role),c=await walker(f,'Ajani Unyielding'),a=body(f),b=card(f,'Nahiri, the Harbinger');b.counters.loyalty=2;await activate(f,c,2);assert.equal(a.counters['+1/+1'],5);assert.equal(b.counters.loyalty,7);assert.equal(c.counters.loyalty,11);});
 test(role+': Chandra +1 creates two hasty 3/1 tokens with a next-end-step exile',async()=>{const f=setup(role),c=await walker(f,'Chandra, Flamecaller');await activate(f,c,0);const made=tokens(f);assert.equal(made.length,2);assert.ok(made.every(c=>c.power===3&&c.toughness===1&&c.kw('haste')));await event(f,'endStep',{player:f.b});assert.ok(made.every(c=>c.zone!=='battlefield'));});
 test(role+': Chandra 0 discards the hand before drawing its size plus one',async()=>{const f=setup(role),c=await walker(f,'Chandra, Flamecaller'),a=card(f,'Island','hand'),b=card(f,'Forest','hand');await activate(f,c,1);assert.equal(a.zone,'graveyard');assert.equal(b.zone,'graveyard');assert.equal(f.a.hand.length,3);assert.equal(c.counters.loyalty,20);});
 test(role+': Chandra -X pays chosen loyalty before damage and can be used only once this turn',async()=>{const f=setup(role),c=await walker(f,'Chandra, Flamecaller'),a=body(f),b=card(f,'Colossal Dreadmaw','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseX'&&q.prompt?.startsWith('Loyalty X')?3:undefined;await activate(f,c,2);assert.equal(c.counters.loyalty,17);assert.equal(a.zone,'graveyard');assert.equal(b.damage,3);assert.equal(f.game.activatableList(f.a).some(e=>e.card===c),false);});
 test(role+': Jace +1 still weakens enemy attackers after Jace leaves',async()=>{const f=setup(role),c=await walker(f,'Jace, Architect of Thought');await activate(f,c,0);await f.game.move(c,'graveyard');const a=body(f,f.b);await event(f,'attacks',{card:a,player:f.b,defender:f.a});assert.equal(a.power,1);f.game.untilEffects=f.game.untilEffects.filter(e=>e.kind!=='c1920TriggerDuration');const b=body(f,f.b);await event(f,'attacks',{card:b,player:f.b,defender:f.a});assert.equal(b.power,2);});
 test(role+': Jace -2 lets an opponent split and the controller choose the hand pile',async()=>{const f=setup(role),c=await walker(f,'Jace, Architect of Thought'),a=card(f,'Island','library'),b=card(f,'Forest','library'),d=card(f,'Sol Ring','library');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.startsWith('Jace: choose the first pile')?[d]:q.type==='chooseOption'&&q.options.some(o=>o.key==='one')?'one':undefined;await activate(f,c,1);assert.equal(d.zone,'hand');assert.ok(f.a.library.indexOf(a)<2&&f.a.library.indexOf(b)<2);});
 test(role+': Jace ultimate searches each library and casts the exiled nonland cards free',async()=>{const f=setup(role),c=await walker(f,'Jace, Architect of Thought'),a=card(f,'Urban Evolution','library'),b=card(f,'Sol Ring','library',f.b);await activate(f,c,2);assert.equal(a.zone,'graveyard');assert.equal(b.zone,'battlefield');assert.equal(b.ctrl,f.a);assert.equal(b.owner,f.b);});
 test(role+': Nahiri +2 optionally trades a card and adds two loyalty',async()=>{const f=setup(role),c=await walker(f,'Nahiri, the Harbinger'),a=card(f,'Island','hand');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.startsWith('Nahiri: discard')?[a]:undefined;await activate(f,c,0);assert.equal(a.zone,'graveyard');assert.equal(f.a.hand.length,1);assert.equal(c.counters.loyalty,22);});
 test(role+': Nahiri -2 offers enchantments freely but only tapped creatures and artifacts',async()=>{const f=setup(role),c=await walker(f,'Nahiri, the Harbinger'),a=body(f,f.b),b=body(f,f.b);b.tapped=true;const pool=f.game.legalTargets(c.def.abilities[1].targets[0],c,f.a);assert.equal(pool.includes(a),false);assert.equal(pool.includes(b),true);target(f,b);await activate(f,c,1);assert.equal(b.zone,'exile');});
 test(role+': Nahiri ultimate returns only the original searched incarnation at the next end step',async()=>{const f=setup(role),c=await walker(f,'Nahiri, the Harbinger'),a=card(f,'Colossal Dreadmaw','library');await activate(f,c,2);assert.equal(a.zone,'battlefield');assert.ok(a.kw('haste'));await f.game.move(a,'exile');await f.game.putPermanentOntoBattlefield(a,f.a);await event(f,'endStep',{player:f.b});assert.equal(a.zone,'battlefield');assert.equal(a.kw('haste'),false);});
 test(role+': Nissa enters with chosen X loyalty and scries with +2',async()=>{const f=setup(role),c=await play(f,'Nissa, Steward of Elements',{xVal:4});assert.equal(c.counters.loyalty,4);let scries=0;const base=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=async(g,q)=>{if(q.type==='scry')scries++;return base(g,q);};await activate(f,c,0);assert.equal(c.counters.loyalty,6);assert.equal(scries,1);});
 test(role+': Nissa 0 can put an eligible creature onto the battlefield',async()=>{const f=setup(role),c=await walker(f,'Nissa, Steward of Elements'),a=card(f,'Grizzly Bears','library');c.counters.loyalty=3;f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt?.includes('put the top card')?'yes':undefined;await activate(f,c,1);assert.equal(a.zone,'battlefield');});
 test(role+': Nissa ultimate untaps lands and preserves their land characteristics',async()=>{const f=setup(role),c=await walker(f,'Nissa, Steward of Elements'),a=card(f,'Forest'),b=card(f,'Island');a.tapped=b.tapped=true;target(f,a,b);await activate(f,c,2);for(const land of [a,b]){assert.equal(land.tapped,false);assert.ok(land.is('Land')&&land.is('Creature')&&land.hasSub('Elemental'));assert.equal(land.power,5);assert.ok(land.kw('flying')&&land.kw('haste'));}assert.ok(a.hasSub('Forest'));});
 test(role+': Ral +1 requires distinct tap and untap targets',async()=>{const f=setup(role),c=await walker(f,'Ral Zarek'),a=card(f,'Forest'),b=card(f,'Island');b.tapped=true;target(f,a,b);await activate(f,c,0);assert.equal(a.tapped,true);assert.equal(b.tapped,false);});
 test(role+': Ral -2 deals exactly three damage',async()=>{const f=setup(role),c=await walker(f,'Ral Zarek'),before=f.b.life;target(f,f.b);await activate(f,c,1);assert.equal(f.b.life,before-3);});
 test(role+': Ral ultimate flips five heads-only coins and queues every earned turn',async()=>{const f=setup(role),c=await walker(f,'Ral Zarek'),values=[0.1,0.9,0.2,0.8,0.3];let flips=0;f.game.rnd=()=>{flips++;return values.shift()??0.9;};await activate(f,c,2);assert.equal(flips,5);assert.equal(f.game.extraTurns.length,3);assert.ok(f.game.extraTurns.every(p=>p===f.a));});
 test(role+': Vraska +1 destroys a combat damager even when Vraska dies from the hit',async()=>{const f=setup(role),c=await walker(f,'Vraska the Unseen'),a=body(f,f.b);await activate(f,c,0);c.counters.loyalty=1;await f.game.damageAny(a,c,2,{combat:true});await settle(f.game);assert.equal(c.zone,'graveyard');assert.equal(a.zone,'graveyard');});
 test(role+': Vraska -3 destroys the selected nonland permanent',async()=>{const f=setup(role),c=await walker(f,'Vraska the Unseen'),a=card(f,'Sol Ring','battlefield',f.b);target(f,a);await activate(f,c,1);assert.equal(a.zone,'graveyard');});
 test(role+': Vraska Assassins make a player lose only after combat damage',async()=>{const f=setup(role),c=await walker(f,'Vraska the Unseen');await activate(f,c,2);const made=tokens(f);assert.equal(made.length,3);await f.game.damagePlayer(made[0],f.b,1);await settle(f.game);assert.equal(f.b.lost,false);await f.game.damagePlayer(made[0],f.b,1,{combat:true});await settle(f.game);assert.equal(f.b.lost,true);});
}
