import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,settle,fuel,event,mana} from './helpers/c19-c20-fixtures.mjs';
const cast=async(f,c,match=()=>true)=>{fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===c&&match(e));assert.ok(e,c.name+' cast offered');assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),true);return f.game.stack.find(s=>s.card===c&&!s.isCopy);};
for(const role of ['human','ai']){
 test(role+': Kadena discounts only the first face-down cast and draws for each face-down entry',async()=>{const f=setup(role);card(f,'Kadena, Slinking Sorcerer');const a=card(f,'Hooded Hydra','hand'),b=card(f,'Chromeshell Crab','hand');const e=f.game.castableList(f.a).find(e=>e.card===a&&e.alt?.faceDownCast);assert.ok(e);const before=mana(f.a);assert.equal(await f.game.castSpell(f.a,a,{alt:e.alt}),true);assert.equal(mana(f.a),before);await settle(f.game);assert.equal(a.faceDown,true);assert.equal(f.a.hand.length,2);assert.equal(f.game.castableList(f.a).some(e=>e.card===b&&e.alt?.faceDownCast),false);fuel(f.a);await cast(f,b,e=>e.alt?.faceDownCast);await settle(f.game);assert.equal(f.a.hand.length,2);});
 test(role+': Kadena counts earlier face-down casts and does not discount face-up spells',async()=>{const f=setup(role);const a=card(f,'Hooded Hydra','hand');await cast(f,a,e=>e.alt?.faceDownCast);await settle(f.game);card(f,'Kadena, Slinking Sorcerer');const b=card(f,'Chromeshell Crab','hand');assert.equal(f.game.spellCost(f.a,b,{faceDownCast:'morph',altCostStr:'{3}'}).generic,3);assert.equal(f.game.spellCost(f.a,b).generic,4);});
 test(role+': Kalamax copies its first instant and grows for the copy',async()=>{const f=setup(role),k=card(f,'Kalamax, the Stormsire');k.tapped=true;target(f,f.b);const c=card(f,'Lightning Bolt','hand'),before=f.b.life;await cast(f,c);await settle(f.game);assert.equal(f.b.life,before-6);assert.equal(k.counters['+1/+1'],1);const d=card(f,'Lightning Bolt','hand');await cast(f,d);await settle(f.game);assert.equal(f.b.life,before-9);assert.equal(k.counters['+1/+1'],1);});
 test(role+': Kalamax does not copy a second instant after entering and untapping stops its intervening-if trigger',async()=>{const f=setup(role);target(f,f.b);await play(f,'Lightning Bolt');const k=card(f,'Kalamax, the Stormsire');k.tapped=true;const before=f.b.life;await play(f,'Lightning Bolt');assert.equal(f.b.life,before-3);f.a.turnState=f.a.freshTurnState();const c=card(f,'Lightning Bolt','hand');await cast(f,c);k.tapped=false;await settle(f.game);assert.equal(k.counters['+1/+1']||0,0);});
 test(role+': Kalamax copies a countered instant using its announced spell choices',async()=>{const f=setup(role),k=card(f,'Kalamax, the Stormsire');k.tapped=true;target(f,f.b);const c=card(f,'Lightning Bolt','hand'),before=f.b.life,so=await cast(f,c);await f.game.counterStackObject(so);await settle(f.game);assert.equal(f.b.life,before-3);assert.equal(k.counters['+1/+1'],1);});
 test(role+': Sevinne prevents damage and copies only the first graveyard spell',async()=>{const f=setup(role),s=card(f,'Sevinne, the Chronoclasm'),src=body(f,f.b);await f.game.damageAny(src,s,20);assert.equal(s.damage,0);const c=card(f,'Ignite the Future','graveyard');await cast(f,c,e=>e.alt?.flashback);await settle(f.game);assert.equal(f.a.exile.length,7,'two batches of three plus flashback source');await f.game.damageAny(src,s,1,{cantBePrevented:true});assert.equal(s.damage,1);});
 test(role+': Rashmi casts a lesser top spell, or puts a noncastable card into hand',async()=>{const f=setup(role);card(f,'Rashmi, Eternities Crafter');const a=card(f,'Sol Ring','library');await play(f,'Urban Evolution');assert.equal(a.zone,'battlefield');f.a.turnState=f.a.freshTurnState();const b=card(f,'Island','library');await play(f,'Sol Ring');assert.equal(b.zone,'hand');});
 test(role+': Tidal Barracuda gives everyone flash but forbids opponents casting during its controller’s turn',async()=>{const f=setup(role),b=card(f,'Tidal Barracuda'),c=card(f,'Urban Evolution','hand');f.game.turnPlayer=f.b;f.game.phase='combat';fuel(f.a);assert.ok(f.game.castableList(f.a).some(e=>e.card===c));f.game.turnPlayer=f.a;const hostile=card(f,'Lightning Bolt','hand',f.b);assert.equal(f.game.canCastTiming(f.b,hostile),false);assert.equal(await f.game.castSpell(f.b,hostile,{free:true}),false);await f.game.move(b,'graveyard');f.game.turnPlayer=f.b;assert.equal(f.game.castableList(f.a).some(e=>e.card===c),false);});
 test(role+': Archon chooses a card type before entry and blocks that type for all players',async()=>{const f=setup(role);f.decide=(p,q)=>q.type==='chooseOption'&&q.options?.some(o=>o.key==='Instant')?'Instant':undefined;const a=await play(f,"Archon of Valor's Reach"),c=card(f,'Lightning Bolt','hand');fuel(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===c),false);assert.equal(await f.game.castSpell(f.a,c,{free:true}),false);await f.game.move(a,'graveyard');assert.ok(f.game.castableList(f.a).some(e=>e.card===c));});
 test(role+': Elsha casts only noncreature faces from the top, at instant timing',async()=>{const f=setup(role);card(f,'Elsha of the Infinite');const c=card(f,'Beanstalk Giant // Fertile Footsteps','library');f.game.turnPlayer=f.b;f.game.phase='combat';const land=card(f,'Forest','library');f.a.library.splice(f.a.library.indexOf(land),1);f.a.library.unshift(land);const s=await cast(f,c,e=>e.alt?.adventure);assert.equal(s.castOpts.adventure,true);await settle(f.game);assert.equal(c.zone,'exile');assert.equal(f.game.lands(f.a).length,1);assert.equal(f.game.castableList(f.a).some(e=>e.card===c),false);});
 test(role+': Elsha permissions are revoked when the top card changes or Elsha leaves',async()=>{const f=setup(role),e=card(f,'Elsha of the Infinite'),c=card(f,'Urban Evolution','library');fuel(f.a);const offer=f.game.castableList(f.a).find(x=>x.card===c);card(f,'Island','library');assert.equal(await f.game.castSpell(f.a,c,{from:'library',alt:offer.alt}),false);await f.game.move(f.a.library.at(-1),'hand');await f.game.move(e,'graveyard');assert.equal(await f.game.castSpell(f.a,c,{from:'library',alt:offer.alt}),false);});
 test(role+': Verge Rangers reveals the top and only plays top lands while behind an opponent',async()=>{const f=setup(role);card(f,'Verge Rangers');const land=card(f,'Forest','library');assert.equal(f.game.playableLands(f.a).includes(land),false);card(f,'Island','battlefield',f.b);assert.ok(f.game.playableLands(f.a).includes(land));assert.equal(await f.game.playLand(f.a,land),true);assert.equal(land.zone,'battlefield');});
 test(role+': Marang can be cast from the graveyard with a black or green permanent and loses the permission with that permanent',async()=>{const f=setup(role),s=card(f,'Abandoned Sarcophagus'),c=card(f,'Marang River Prowler','graveyard');fuel(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===c),false);const green=body(f);const e=f.game.castableList(f.a).find(e=>e.card===c);assert.ok(e);await f.game.move(green,'graveyard');assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),false);await f.game.putPermanentOntoBattlefield(green,f.a);await cast(f,c);await settle(f.game);assert.equal(c.cur.cantBlock,true);assert.equal(c.cur.unblockable,true);});
 test(role+': Backdraft grants flashback only to the current graveyard objects',async()=>{const f=setup(role),s=card(f,'Backdraft Hellkite'),a=card(f,'Lightning Bolt','graveyard');await event(f,'attacks',{card:s});const b=card(f,'Urban Evolution','graveyard');fuel(f.a);assert.ok(f.game.castableList(f.a).some(e=>e.card===a&&e.alt?.flashback));assert.equal(f.game.castableList(f.a).some(e=>e.card===b),false);await f.game.move(a,'hand');await f.game.move(a,'graveyard');assert.equal(f.game.castableList(f.a).some(e=>e.card===a),false);});
 test(role+': Gonti permission survives its source and casts the exact face-down card with any mana type',async()=>{const f=setup(role),c=card(f,'Sol Ring','library',f.b);target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.includes('Gonti')?[c]:prior(p,q);const s=await play(f,'Gonti, Lord of Luxury');assert.equal(c.zone,'exile');assert.equal(c.faceDown,true);await f.game.move(s,'graveyard');await cast(f,c,e=>e.alt?.asThoughAnyType);await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);});
 test(role+': Pako records who exiled fetched cards; Haldan plays their noncreature faces and lands',async()=>{const f=setup(role),p=card(f,'Pako, Arcane Retriever'),land=card(f,'Forest','library'),spell=card(f,'Urban Evolution','library',f.b);await event(f,'attacks',{card:p});assert.equal(p.counters['+1/+1'],f.game.players.length);assert.equal(land.counters.fetch,1);assert.equal(f.game.playableLands(f.a).includes(land),false);const h=card(f,'Haldan, Avid Arcanist');assert.ok(f.game.playableLands(f.a).includes(land));await cast(f,spell);await settle(f.game);assert.equal(spell.zone,'graveyard');await f.game.move(h,'graveyard');assert.equal(f.game.playableLands(f.a).includes(land),false);});
 test(role+': Whispersteel Dagger grants one creature cast from the damaged graveyard',async()=>{const f=setup(role),s=card(f,'Whispersteel Dagger'),h=body(f),a=card(f,'Grizzly Bears','graveyard',f.b),b=card(f,'Colossal Dreadmaw','graveyard',f.b);await f.game.attach(s,h);await f.game.damagePlayer(h,f.b,4,{combat:true});await settle(f.game);await f.game.move(s,'graveyard');await cast(f,a);await settle(f.game);assert.equal(a.ctrl,f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===b),false);});
}
