import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,fuel,settle,event} from './helpers/c19-c20-fixtures.mjs';
async function mutate(f,name,host,{order='over',decide,resolve=true,player=f.a}={}){
 const s=card(f,name,'hand',player);let first=true;f.decide=(p,q)=>{
  if(q.type==='chooseTargets'&&first){first=false;return [host];}
  if(q.type==='chooseOption'&&q.aiHint?.kind==='mutateOrder')return order;
  return decide?.(p,q);
 };fuel(player);const a=s.def.altCosts.find(a=>a.mutate);assert.equal(await f.game.castSpell(player,s,{alt:a}),true);assert.ok(f.game.stack.some(so=>so.card===s));if(resolve)await settle(f.game);return s;
}
for(const role of ['human','ai']){
 test(role+': departure of a default controller exiles every physical component with one leave event',async()=>{const f=setup(role),h=body(f),s=await mutate(f,'Dreamtail Heron',h);h.ctrl=f.b;f.game.recalc();let leaves=0;const emit=f.game.emit;f.game.emit=function(n,d){if(n==='lto'&&d.card===h)leaves++;return emit.call(this,n,d);};f.game.exileForDepartedControl([h]);for(const c of [h,s]){assert.equal(c.zone,'exile');assert.ok(f.a.exile.includes(c));}assert.equal(leaves,1);assert.equal(h.name,'Grizzly Bears');assert.equal(h.mutateState,undefined);});

 test(role+': undying returns each physical merged card with its own counter and one death event',async()=>{const f=setup(role),h=card(f,'Vorapede'),s=await mutate(f,'Dreamtail Heron',h);await f.game.destroy(h);assert.equal(h.zone,'graveyard');assert.equal(s.zone,'graveyard');assert.equal(f.game.pendingTriggers.filter(t=>t.name==='Undying').length,1);await settle(f.game);for(const c of [h,s]){assert.equal(c.zone,'battlefield');assert.equal(c.counters['+1/+1'],1);}assert.equal(h.name,'Vorapede');assert.equal(s.name,'Dreamtail Heron');});
 test(role+': undying follows only exact graveyard components after one has moved again',async()=>{const f=setup(role),h=card(f,'Vorapede'),s=await mutate(f,'Dreamtail Heron',h);await f.game.destroy(h);await f.game.move(s,'hand');await f.game.move(s,'graveyard');await settle(f.game);assert.equal(h.zone,'battlefield');assert.equal(s.zone,'graveyard');});
 test(role+': a physical token root still returns its nontoken undying component',async()=>{const f=setup(role),model=body(f),[h]=await f.game.makeTokens(M.C1920.beast({g:f.game,src:model,you:f.a}),f.a);M.OracleV8Copies.applyCopy(f.game,h,M.DEFS.Vorapede);f.game.recalc();const s=await mutate(f,'Dreamtail Heron',h);await f.game.destroy(h);await settle(f.game);assert.equal(h.zone,'ceased');assert.equal(s.zone,'battlefield');assert.equal(s.counters['+1/+1'],1);});
 test(role+': all merged cards retain their battlefield graveyard origin for Gerrard',async()=>{const f=setup(role),h=body(f),s=await mutate(f,'Dreamtail Heron',h);await f.game.destroy(h);for(const c of [h,s])assert.equal(M.C1920.graveThisTurn(f.game,c,'battlefield'),true);});

 test(role+': mutate under a manifested creature stays face down and turns the entire object face up',async()=>{const f=setup(role),h=card(f,'Grizzly Bears','hand');await f.game.putFaceDown(f.a,h);const before=f.a.hand.length;await mutate(f,'Dreamtail Heron',h,{order:'under'});assert.equal(h.faceDown,true);assert.equal(h.kw('flying'),false);assert.equal(f.a.hand.length,before);fuel(f.a);const cost=f.game.faceUpCosts(h).find(e=>e.kind==='mana cost');assert.ok(cost);assert.equal(await f.game.turnFaceUp(f.a,h,cost.cost,cost.kind),true);assert.equal(h.name,'Grizzly Bears');assert.equal(h.kw('flying'),true);assert.equal(h.mutateState.components.every(r=>!r.faceDown),true);});
 test(role+': mutate over a face-down creature reveals only the new top and does not count as turning face up',async()=>{const f=setup(role),h=card(f,'Kadena’s Silencer'.replace('’',"'"),'hand');await f.game.putFaceDown(f.a,h);let turned=0;const emit=f.game.emit;f.game.emit=function(n,d){if(n==='turnedFaceUp')turned++;return emit.call(this,n,d);};await mutate(f,'Dreamtail Heron',h);assert.equal(h.faceDown,false);assert.equal(turned,0);assert.equal(M.Mutate.present(h,f.b).find(r=>r.iid===h.iid).hidden,true);assert.equal(M.Mutate.present(h,f.a).find(r=>r.iid===h.iid).name,"Kadena's Silencer");});
 test(role+': a face-down merge containing an instant cannot be turned face up',async()=>{const f=setup(role),h=card(f,'Lightning Bolt','hand');await f.game.putFaceDown(f.a,h);await mutate(f,'Dreamtail Heron',h,{order:'under'});assert.equal(f.game.faceUpCosts(h).length,0);fuel(f.a);assert.equal(await f.game.turnFaceUp(f.a,h),false);});
 test(role+': a mutate spell copy becomes a token component, without entering or creating a token',async()=>{const f=setup(role),h=body(f),s=await mutate(f,'Dreamtail Heron',h,{resolve:false});let entered=0,created=0;const emit=f.game.emit;f.game.emit=function(n,d){if(n==='etb')entered++;if(n==='tokenCreated')created++;return emit.call(this,n,d);};await f.game.copySpell(f.game.stack.at(-1),f.a);await settle(f.game);assert.equal(h.mutateState.components.length,3);assert.equal(h.mutateState.components.filter(r=>r.isToken).length,1);assert.equal(entered,0);assert.equal(created,0);assert.equal(h.meta.c1920Mutations,2);assert.equal(s.zone,'merged');});
 test(role+': copied mutate spells use their new owner for target legality',async()=>{const f=setup(role),h=body(f),enemy=body(f,f.b);await mutate(f,'Dreamtail Heron',h,{resolve:false});f.decide=(p,q)=>q.type==='chooseTargets'?[enemy]:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':q.type==='chooseOption'&&q.aiHint?.kind==='mutateOrder'?'over':undefined;await f.game.copySpell(f.game.stack.at(-1),f.b,{mayNewTargets:true});await settle(f.game);assert.equal(enemy.name,'Dreamtail Heron');assert.equal(enemy.isToken,true);assert.equal(enemy.ctrl,f.b);});
 test(role+': AI simulation clones preserve merged component identity without altering the live game',async()=>{const f=setup(role),h=body(f),s=await mutate(f,'Dreamtail Heron',h);const clone=M.cloneGameForAISimulation(f.game,712),copied=clone.byIid(h.iid);assert.notEqual(copied,h);assert.equal(copied.mutateState.components.find(r=>r.card.iid===h.iid).card,copied);assert.notEqual(clone.byIid(s.iid),s);await clone.move(copied,'graveyard');assert.equal(h.zone,'battlefield');assert.equal(s.zone,'merged');});
 test(role+': characteristic-defining abilities underneath a mutation still set its power',async()=>{const f=setup(role),g1=card(f,'Grizzly Bears','graveyard'),g2=card(f,'Dreamtail Heron','graveyard'),h=card(f,'Boneyard Mycodrax');f.game.recalc();assert.equal(h.power,2);await mutate(f,'Glowstone Recluse',h);assert.equal(h.power,4);assert.equal(h.counters['+1/+1'],2);});
 test(role+': a merged double-faced component can transform and prevents turning the merge face down',async()=>{const f=setup(role),h=card(f,'Bloodline Keeper // Lord of Lineage');assert.ok(h.oracleFaces);await mutate(f,'Dreamtail Heron',h,{order:'under'});assert.equal(h.oracleFaces,null);M.C1920.faceDown(f.game,h);assert.equal(h.faceDown,false);await M.Mutate.transform(f.game,h);assert.equal(h.name,'Lord of Lineage');assert.equal(h.power,5);assert.equal(h.kw('flying'),true);await f.game.move(h,'hand');assert.equal(h.name,'Bloodline Keeper');});
 test(role+': saving a merged position is explicitly blocked instead of dropping physical cards',async()=>{const f=setup(role),h=body(f);await mutate(f,'Dreamtail Heron',h);assert.ok(M.gameStateSnapshotBlockers(f.game).includes('Merged permanent components'));assert.equal(M.canSnapshotGameState(f.game),false);});
 test(role+': mutate over and under preserve the existing permanent and all abilities, without ETB',async()=>{const f=setup(role),host=body(f);host.counters['+1/+1']=1;host.tapped=true;const version=host.zoneVersion,entries=f.a.turnState.permanentEntries.length,hand=f.a.hand.length;const first=await mutate(f,'Dreamtail Heron',host);assert.equal(first.zone,'merged');assert.equal(host.zoneVersion,version);assert.equal(host.name,'Dreamtail Heron');assert.equal(host.power,4);assert.equal(host.tapped,true);assert.equal(host.sick,false);assert.equal(host.kw('flying'),true);assert.equal(f.a.turnState.permanentEntries.length,entries);assert.equal(f.a.hand.length,hand+1);const second=await mutate(f,'Glowstone Recluse',host,{order:'under'});assert.equal(host.name,'Dreamtail Heron');assert.equal(host.kw('reach'),true);assert.equal(host.counters['+1/+1'],3);assert.equal(host.meta.c1920Mutations,2);assert.equal(host.mutateState.components.length,3);assert.equal(f.a.hand.length,hand+2);assert.equal(second.zone,'merged');});
 test(role+': mutate targets ownership rather than control and rejects Humans and forged costs',async()=>{const f=setup(role),owned=body(f);M.C1920.control(f.game,owned,f.b,false);const s=card(f,'Dreamtail Heron','hand');fuel(f.a);const a=s.def.altCosts[0],spec=f.game.spellTargetSpecs(s,a,f.a)[0],human=card(f,'Valiant Rescuer'),enemy=body(f,f.b);assert.ok(f.game.legalTargets(spec,s,f.a).includes(owned));assert.ok(!f.game.legalTargets(spec,s,f.a).includes(human));assert.ok(!f.game.legalTargets(spec,s,f.a).includes(enemy));assert.equal(await f.game.castSpell(f.a,s,{alt:{...a,altCostStr:'{0}'}}),false);const before=f.b.hand.length;await mutate(f,'Dreamtail Heron',owned);assert.equal(owned.ctrl,f.b);assert.equal(f.b.hand.length,before+1);});
 test(role+': an invalid mutate target resolves as an ordinary creature with no mutation trigger',async()=>{const f=setup(role),host=body(f),before=f.a.hand.length;const s=await mutate(f,'Dreamtail Heron',host,{resolve:false});await f.game.move(host,'hand');await settle(f.game);assert.equal(s.zone,'battlefield');assert.equal(s.mutateState,undefined);assert.equal(f.a.hand.length,before+1);});
 test(role+': every physical card leaves the merged permanent, while dies observers see one creature',async()=>{const f=setup(role),host=body(f),s=await mutate(f,'Dreamtail Heron',host),t=await mutate(f,'Glowstone Recluse',host,{order:'under'});let deaths=0;const emit=f.game.emit;f.game.emit=function(n,d){if(n==='dies'&&d.card===host)deaths++;return emit.call(this,n,d);};await f.game.destroy(host);assert.equal(deaths,1);for(const c of [host,s,t])assert.equal(c.zone,'graveyard');assert.equal(host.name,'Grizzly Bears');assert.equal(host.counters['+1/+1'],undefined);assert.equal(host.mutateState,undefined);assert.equal(f.a.graveyard.length,3);});
 test(role+': copied merged characteristics include all abilities without copying components or mutation history',async()=>{const f=setup(role),h=body(f);await mutate(f,'Dreamtail Heron',h);await mutate(f,'Glowstone Recluse',h,{order:'under'});const [copy]=await f.game.copyPermanentToken(h,f.a);assert.equal(copy.name,'Dreamtail Heron');assert.equal(copy.kw('reach'),true);assert.equal(copy.mutateState,undefined);assert.equal(copy.meta.c1920Mutations,undefined);const before=f.a.hand.length;await mutate(f,'Trumpeting Gnarr',copy,{order:'under'});assert.equal(f.a.hand.length,before+1);assert.equal(copy.meta.c1920Mutations,1);assert.equal(copy.counters['+1/+1'],2);assert.equal(copy.isToken,true);});
 test(role+': Rayami applies one death replacement to every nontoken merged component',async()=>{const f=setup(role),r=card(f,'Rayami, First of the Fallen'),h=body(f),s=await mutate(f,'Dreamtail Heron',h);await f.game.destroy(h);assert.equal(h.zone,'exile');assert.equal(s.zone,'exile');assert.equal(h.counters.blood,1);assert.equal(s.counters.blood,1);assert.equal(r.kw('flying'),true);});
 test(role+': a token top controls token status but its nontoken components survive leaving play',async()=>{const f=setup(role),[h]=await f.game.makeTokens(M.C1920.beast({g:f.game,src:body(f),you:f.a}),f.a);const s=await mutate(f,'Dreamtail Heron',h,{order:'under'});assert.equal(h.isToken,true);await f.game.destroy(h);assert.equal(h.zone,'ceased');assert.equal(s.zone,'graveyard');});
 test(role+': a commander underneath deals commander damage for its physical card and returns independently',async()=>{const f=setup(role),h=body(f),s=card(f,'Otrimi, the Ever-Playful','command');s.commander=true;f.a.commanders=[s];fuel(f.a);let first=true;f.decide=(p,q)=>q.type==='chooseTargets'&&first?(first=false,[h]):q.type==='chooseOption'&&q.aiHint?.kind==='mutateOrder'?'under':q.type==='chooseOption'&&q.options.some(o=>o.key==='cz')?'cz':undefined;assert.equal(await f.game.castSpell(f.a,s,{from:'command',alt:s.def.altCosts[0]}),true);await settle(f.game);assert.equal(h.commander,true);assert.equal(s.cmdCasts,1);await f.game.damagePlayer(h,f.b,3,{combat:true});assert.equal(f.b.commanderDamage[s.iid],3);assert.equal(f.b.commanderDamage[h.iid],undefined);await f.game.move(h,'hand');assert.equal(s.zone,'command');assert.equal(h.zone,'hand');assert.equal(h.commander,false);});
 test(role+': Archipelagore, Greathorn, Hemophage and Gnarr resolve their mutation effects',async()=>{const f=setup(role),h=body(f),enemy=body(f,f.b);await mutate(f,'Archipelagore',h,{decide:(p,q)=>q.type==='chooseTargets'?[enemy]:undefined});assert.equal(enemy.tapped,true);assert.equal(enemy.meta.noUntapOnce,true);await mutate(f,'Migratory Greathorn',h,{order:'under',decide:(p,q)=>q.type==='chooseTargets'?[enemy]:undefined});assert.equal(f.game.lands(f.a).length,1);assert.equal(f.game.lands(f.a)[0].tapped,true);const a=f.a.life,b=f.b.life;await mutate(f,'Insatiable Hemophage',h,{order:'under',decide:(p,q)=>q.type==='chooseTargets'?[enemy]:undefined});assert.equal(f.a.life,a+3);assert.equal(f.b.life,b-3);await mutate(f,'Trumpeting Gnarr',h,{order:'under',decide:(p,q)=>q.type==='chooseTargets'?[enemy]:undefined});assert.ok(f.game.creatures(f.a).some(c=>c.hasSub('Beast')&&c.isToken));});
 test(role+': Boneyard Lurker returns a permanent while Cavern Whisperer and Harvester make opposing choices',async()=>{const f=setup(role),h=body(f),grave=card(f,'Sol Ring','graveyard');await mutate(f,'Boneyard Lurker',h,{decide:(p,q)=>q.type==='chooseTargets'?[grave]:undefined});assert.equal(grave.zone,'hand');const discard=card(f,'Forest','hand',f.b),victim=body(f,f.b);await mutate(f,'Cavern Whisperer',h,{order:'under'});assert.equal(discard.zone,'graveyard');await mutate(f,'Chittering Harvester',h,{order:'under'});assert.equal(victim.zone,'graveyard');});
 test(role+': Shoreshark bounces an enemy; Demolisher makes a Beast; Snatcher takes a noncreature artifact',async()=>{for(const name of ['Pouncing Shoreshark','Sawtusk Demolisher','Souvenir Snatcher']){const f=setup(role),h=body(f),enemy=name==='Pouncing Shoreshark'?body(f,f.b):card(f,'Sol Ring','battlefield',f.b);await mutate(f,name,h,{decide:(p,q)=>q.type==='chooseTargets'?[enemy]:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined});if(name==='Pouncing Shoreshark')assert.equal(enemy.zone,'hand');if(name==='Sawtusk Demolisher'){assert.equal(enemy.zone,'graveyard');assert.ok(f.game.creatures(f.b).some(c=>c.hasSub('Beast')));}if(name==='Souvenir Snatcher')assert.equal(enemy.ctrl,f.a);}});
 test(role+': Starrix enters the counted permanents without casting them; Mindleecher grants lasting private play',async()=>{const f=setup(role),h=body(f),sol=card(f,'Sol Ring','library'),instant=card(f,'Lightning Bolt','library');await mutate(f,'Auspicious Starrix',h);assert.equal(sol.zone,'battlefield');assert.equal(instant.zone,'exile');const enemy=card(f,'Sol Ring','library',f.b);await mutate(f,'Mindleecher',h,{order:'under'});assert.equal(enemy.zone,'exile');assert.equal(enemy.faceDown,true);assert.ok(enemy.meta.revealedTo.includes(f.a.idx));await f.game.move(h,'hand');fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===enemy);assert.ok(e);assert.equal(await f.game.castSpell(f.a,enemy,{from:e.from,alt:e.alt}),true);await settle(f.game);assert.equal(enemy.ctrl,f.a);});
 test(role+': a temporary later copy effect expires back to the merged characteristics',async()=>{const f=setup(role),h=body(f);await mutate(f,'Dreamtail Heron',h);await mutate(f,'Glowstone Recluse',h,{order:'under'});M.OracleV8Copies.applyCopy(f.game,h,M.DEFS['Grizzly Bears'],{duration:'eot'});f.game.recalc();assert.equal(h.name,'Grizzly Bears');f.game.untilEffects=f.game.untilEffects.filter(e=>e.expires!=='eot');f.game.recalc();assert.equal(h.name,'Dreamtail Heron');assert.equal(h.kw('reach'),true);});
 test(role+': linked exile returns every physical component as separate permanents',async()=>{const f=setup(role),h=body(f),s=await mutate(f,'Dreamtail Heron',h),link=body(f);const ctx={g:f.game,src:link,you:f.a,sourceZoneVersion:link.zoneVersion};await M.OracleV8Linked.run(ctx,{action:'linked-exile-until'},{sameSource:M.C1920.same,subjects:()=>[h]});assert.equal(h.zone,'exile');assert.equal(s.zone,'exile');await f.game.move(link,'hand');assert.equal(h.zone,'battlefield');assert.equal(s.zone,'battlefield');assert.equal(h.name,'Grizzly Bears');assert.equal(s.name,'Dreamtail Heron');assert.equal(h.mutateState,undefined);});
}

test('real local AI keeps the stronger existing creature on top of a mutation',async()=>{const f=setup('ai'),h=card(f,'Otrimi, the Ever-Playful'),s=card(f,'Dreamtail Heron','hand');f.decide=(p,q)=>q.type==='chooseTargets'?[h]:undefined;fuel(f.a);assert.equal(await f.game.castSpell(f.a,s,{alt:s.def.altCosts[0]}),true);await settle(f.game);assert.equal(h.name,'Otrimi, the Ever-Playful');assert.equal(h.kw('flying'),true);assert.equal(f.game.aiDecisionLog.some(r=>r.fallback),false);});
