import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,tokens,settle,fuel,event} from './helpers/c19-c20-fixtures.mjs';
const stack=async(f,name,p=f.a)=>{const c=card(f,name,'hand',p);fuel(p);const prior=f.game.turnPlayer;f.game.turnPlayer=p;try{assert.equal(await f.game.castSpell(p,c),true);}finally{f.game.turnPlayer=prior;}return f.game.stack.find(s=>s.card===c);};
for(const role of ['human','ai']){
 test(role+': Djinn Illuminatus pays replicate before casting and creates a single multi-copy trigger',async()=>{const f=setup(role);card(f,'Djinn Illuminatus');target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseX'&&q.prompt?.startsWith('Replicate')?3:prior(p,q);const before=f.b.life;await play(f,'Lightning Bolt');assert.equal(f.b.life,before-12);});
 test(role+': Djinn replicate and Twinning Staff produce N plus one copies',async()=>{const f=setup(role);card(f,'Djinn Illuminatus');card(f,'Twinning Staff');target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseX'&&q.prompt?.startsWith('Replicate')?2:prior(p,q);const before=f.b.life;await play(f,'Lightning Bolt');assert.equal(f.b.life,before-12);});
 test(role+': Wort creates two Goblin Warriors and pays conspire with two sharing a spell color',async()=>{const f=setup(role),w=await play(f,'Wort, the Raidmother');assert.equal(tokens(f).length,2);target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt?.startsWith('Conspire')?'yes':q.type==='chooseCards'&&q.prompt?.startsWith('Conspire')?tokens(f).slice(0,2):prior(p,q);const before=f.b.life;await play(f,'Lightning Bolt');assert.equal(f.b.life,before-6);assert.equal(tokens(f).filter(c=>c.tapped).length,2);assert.equal(w.tapped,false);});
 test(role+': Wort conspire can tap Kalamax and its copy combines with the first-instant trigger',async()=>{const f=setup(role),w=await play(f,'Wort, the Raidmother'),k=card(f,'Kalamax, the Stormsire');target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt?.startsWith('Conspire')?'yes':q.type==='chooseCards'&&q.prompt?.startsWith('Conspire')?[w,k]:prior(p,q);const before=f.b.life;await play(f,'Lightning Bolt');assert.equal(f.b.life,before-9);assert.equal(k.tapped,true);assert.equal(k.counters['+1/+1'],2);});
 test(role+': Twinning Staff adds one copy to a single multi-copy instruction',async()=>{const f=setup(role);card(f,'Twinning Staff');const so=await stack(f,'Urban Evolution');const copies=await f.game.copySpells(so,f.a,2,{mayNewTargets:true});assert.equal(copies.length,3);await settle(f.game);assert.equal(f.a.hand.length,12);});
 test(role+': Two Staffs add two copies and a zero-copy instruction stays zero',async()=>{const f=setup(role);card(f,'Twinning Staff');card(f,'Twinning Staff');const so=await stack(f,'Urban Evolution');assert.equal((await f.game.copySpells(so,f.a,0)).length,0);assert.equal((await f.game.copySpells(so,f.a,2)).length,4);await settle(f.game);assert.equal(f.a.hand.length,15);});
 test(role+': Increasing Vengeance plus Twinning Staff makes three copies when cast from graveyard',async()=>{const f=setup(role);card(f,'Twinning Staff');const so=await stack(f,'Urban Evolution');target(f,so);await play(f,'Increasing Vengeance',{from:'graveyard',alt:{flashback:true,altCostStr:'{3}{R}{R}'}});assert.equal(f.a.hand.length,12);});
 test(role+': Twinning Staff activation pays seven and taps, then its replacement adds a second copy',async()=>{const f=setup(role),c=card(f,'Twinning Staff'),so=await stack(f,'Urban Evolution');target(f,so);fuel(f.a);const e=f.game.activatableList(f.a).find(e=>e.card===c);assert.ok(e);assert.equal(await f.game.activateAbility(f.a,e),true);assert.equal(c.tapped,true);await settle(f.game);assert.equal(f.a.hand.length,9);});
 test(role+': Channeled Force discards X before opponents can respond and keeps X in a copy',async()=>{const f=setup(role),a=card(f,'Island','hand'),b=card(f,'Forest','hand'),victim=card(f,'Colossal Dreadmaw','battlefield',f.b),s=card(f,'Channeled Force','hand');target(f,f.a,victim);fuel(f.a);const before=f.a.hand.length;assert.equal(await f.game.castSpell(f.a,s,{xVal:2}),true);assert.equal(a.zone,'graveyard');assert.equal(b.zone,'graveyard');assert.equal(f.a.hand.length,before-3);const so=f.game.stack.find(so=>so.card===s);assert.equal(so.x,2);await f.game.copySpell(so,f.a,{mayNewTargets:false});await settle(f.game);assert.equal(f.a.hand.length,before+1);assert.equal(victim.damage,4);});
 test(role+': Channeled Force permits zero and its non-mana X can exceed life total',async()=>{const f=setup(role);f.a.life=1;for(let n=0;n<3;n++)card(f,'Island','hand');target(f,f.a);const s=card(f,'Channeled Force','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,s,{xVal:3}),true);assert.equal(f.game.stack.find(so=>so.card===s).x,3);await settle(f.game);assert.equal(f.a.life,1);});
 test(role+': Ignite grants play through the next own turn, including lands, and then expires',async()=>{const f=setup(role,4);f.a.turnsStarted=1;const land=card(f,'Forest','library'),spell=card(f,'Urban Evolution','library');await play(f,'Ignite the Future');assert.equal(land.zone,'exile');assert.equal(spell.zone,'exile');fuel(f.a);assert.ok(f.game.playableLands(f.a).includes(land));assert.ok(f.game.castableList(f.a).some(e=>e.card===spell));for(const p of f.game.players.slice(1)){p.turnsStarted++;f.game.expireOwnTurnExilePermissions(p);}assert.ok(f.game.castableList(f.a).some(e=>e.card===spell));f.a.turnsStarted++;assert.ok(f.game.castableList(f.a).some(e=>e.card===spell));f.game.expireOwnTurnExilePermissions(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===spell),false);});
 test(role+': Ignite cast from the graveyard grants free casting and binds the exact exiled object',async()=>{const f=setup(role),s=card(f,'Urban Evolution','library');await play(f,'Ignite the Future',{from:'graveyard',alt:{flashback:true,altCostStr:'{7}{R}'}});const e=f.game.castableList(f.a).find(e=>e.card===s);assert.ok(e?.alt.free);await f.game.move(s,'hand');await f.game.move(s,'exile');assert.equal(f.game.castableList(f.a).some(e=>e.card===s),false);});
 test(role+': Refuse deals the targeted spell mana value without countering it',async()=>{const f=setup(role),so=await stack(f,'Urban Evolution',f.b),before=f.b.life;target(f,so);await play(f,'Refuse // Cooperate',{alt:{splitHalf:'refuse',altCostStr:'{3}{R}',name:'Refuse'}});assert.equal(f.b.life,before-5);assert.equal(so.card.zone,'graveyard');assert.ok(f.b.hand.length>=3);});
 test(role+': Cooperate is offered only from the graveyard and is exiled after copying',async()=>{const f=setup(role),so=await stack(f,'Urban Evolution'),c=card(f,'Refuse // Cooperate','graveyard');target(f,so);fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.splitHalf==='cooperate');assert.ok(e);assert.equal(await f.game.castSpell(f.a,c,{from:e.from,alt:e.alt}),true);await settle(f.game);assert.equal(c.zone,'exile');assert.ok(f.a.hand.length>=6);});
 test(role+': Sudden Substitution exchanges control of the spell and creature',async()=>{const f=setup(role),so=await stack(f,'Urban Evolution'),victim=body(f,f.b);target(f,so,victim);const before=f.b.hand.length;await play(f,'Sudden Substitution');assert.equal(victim.ctrl,f.a);assert.equal(so.ctrl,f.b);assert.equal(f.b.hand.length,before+3);});
 test(role+': Increasing Vengeance cast from the graveyard copies twice',async()=>{const f=setup(role),so=await stack(f,'Urban Evolution'),before=f.a.hand.length;target(f,so);await play(f,'Increasing Vengeance',{from:'graveyard',alt:{flashback:true,altCostStr:'{3}{R}{R}'}});assert.equal(f.a.hand.length,before+9);});
 test(role+': Stolen Identity copies a creature and its encoded card follows the carrier’s controller',async()=>{const f=setup(role),c=body(f);target(f,c);const choose=f.decide;f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.includes('encode on')?[c]:q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':choose(p,q);const s=await play(f,'Stolen Identity');assert.equal(tokens(f).length,1);assert.equal(s.zone,'exile');const before=tokens(f).length;await f.game.damagePlayer(c,f.b,2,{combat:true});await settle(f.game);assert.ok(tokens(f).length>before);M.C1920.control(f.game,c,f.b,false);await f.game.damagePlayer(c,f.a,2,{combat:true});await settle(f.game);assert.ok(tokens(f,f.b).length>0);await f.game.move(c,'hand');const count=tokens(f).length;await f.game.putPermanentOntoBattlefield(c,f.a);await f.game.damagePlayer(c,f.b,2,{combat:true});await settle(f.game);assert.equal(tokens(f).length,count);});
}
test('Runic Repetition cannot target a face-down card or an exiled replacement incarnation',async()=>{const f=setup(),c=card(f,'Mass Diminish','exile'),s=card(f,'Runic Repetition','hand');c.faceDown=true;assert.equal(f.game.legalTargets(s.def.targets[0],s,f.a).includes(c),false);c.faceDown=false;target(f,c);fuel(f.a);assert.equal(await f.game.castSpell(f.a,s),true);await f.game.move(c,'hand');await f.game.move(c,'exile');await settle(f.game);assert.equal(c.zone,'exile');assert.equal(s.zone,'graveyard');});
