import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,target,settle,fuel,event} from './helpers/c19-c20-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Vastwood Hydra distributes its death snapshot counters without targeting',async()=>{const f=setup(role),h=await play(f,'Vastwood Hydra',{xVal:3}),a=body(f),b=body(f);assert.equal(h.counters['+1/+1'],3);f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Vastwood')?[a]:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await f.game.destroy(h);await settle(f.game);assert.equal(a.counters['+1/+1'],3);assert.equal(h.zone,'graveyard');});
 test(role+': Bogbonder can move chosen counter kinds onto an opposing creature',async()=>{const f=setup(role),a=body(f),b=body(f,f.b);a.counters['+1/+1']=3;a.counters.vigilance=1;f.decide=(p,q)=>q.type==='chooseTargets'?[b]:q.type==='chooseX'?q.max:undefined;await play(f,'Slippery Bogbonder');assert.equal(b.counters.hexproof,1);assert.equal(b.counters['+1/+1'],3);assert.equal(b.counters.vigilance,1);assert.equal(a.counters['+1/+1'],0);});
 test(role+': Tayam adds vigilance at entry and pays three counters before its ability can be countered',async()=>{const f=setup(role),t=card(f,'Tayam, Luminous Enigma'),a=await play(f,'Grizzly Bears'),b=await play(f,'Grizzly Bears');t.counters['+1/+1']=1;assert.equal(a.counters.vigilance,1);assert.equal(t.counters.vigilance,undefined);fuel(f.a);const entry=f.game.activatableList(f.a).find(e=>e.card===t);assert.equal(await f.game.activateAbility(f.a,entry),true);assert.equal([t,a,b].reduce((n,c)=>n+Object.values(c.counters).reduce((x,n)=>x+n,0),0),0);await f.game.counterStackObject(f.game.stack.at(-1));assert.equal(f.a.graveyard.length,0);});
 test(role+': Tayam can return a land milled by the same resolution',async()=>{const f=setup(role),t=card(f,'Tayam, Luminous Enigma'),land=card(f,'Forest','library');t.counters.vigilance=3;f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Tayam: return')?[land]:undefined;await activate(f,t);assert.equal(land.zone,'battlefield');assert.equal(t.counters.vigilance,0);});
 test(role+': Vitality Hunter becomes monstrous once and puts X lifelink counters on distinct targets',async()=>{const f=setup(role),s=card(f,'Vitality Hunter'),a=body(f),b=body(f);f.decide=(p,q)=>q.type==='chooseX'?2:q.type==='chooseTargets'?[a,b]:undefined;await activate(f,s);assert.equal(s.counters['+1/+1'],2);assert.equal(a.counters.lifelink,1);assert.equal(b.counters.lifelink,1);await activate(f,s);assert.equal(s.counters['+1/+1'],2);assert.equal(a.counters.lifelink,1);});
 test(role+': Ravenous Gigantotherium devours before entry and receives damage back from creatures it kills',async()=>{const f=setup(role),food=body(f),enemy=card(f,'Grizzly Bears','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Devour')?[food]:q.type==='chooseTargets'?[enemy]:undefined;const r=await play(f,'Ravenous Gigantotherium');assert.equal(food.zone,'graveyard');assert.equal(r.counters['+1/+1'],3);assert.equal(r.damage,2);assert.equal(enemy.zone,'graveyard');});
 test(role+': Yannik exiles without targeting and returns its exact linked creature when it leaves',async()=>{const f=setup(role),a=body(f),b=body(f);f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Yannik: exile')?[a]:q.type==='chooseTargets'?q.candidates.includes(b)?[b]:q.candidates.slice(0,1):undefined;const y=await play(f,'Yannik, Scavenging Sentinel');assert.equal(a.zone,'exile');assert.equal(b.counters['+1/+1'],2);await f.game.move(y,'hand');assert.equal(a.zone,'battlefield');assert.equal(a.counters['+1/+1'],undefined);});
 test(role+': Nascent Metamorph copies from an opponent’s library on both attack and block',async()=>{for(const on of ['attacks','blocks']){const f=setup(role),s=card(f,'Nascent Metamorph'),a=card(f,'Grizzly Bears','library',f.b),land=card(f,'Forest','library',f.b);const count=f.b.library.length;target(f,f.b);await event(f,on,on==='attacks'?{card:s}:{blocker:s,attacker:body(f,f.b)});assert.equal(s.name,'Grizzly Bears');assert.equal(s.power,2);assert.equal(a.zone,'library');assert.equal(land.zone,'library');assert.equal(f.b.library.length,count);}});
 test(role+': Cairn Wanderer inherits printed keywords and protection from either graveyard, then loses them',async()=>{const f=setup(role),s=card(f,'Cairn Wanderer'),a=card(f,'Sphinx of the Steel Wind','graveyard',f.b),red=card(f,'Lightning Bolt','hand',f.b);assert.equal(s.kw('flying'),true);assert.equal(f.game.isProtectedFrom(s,red),true);await f.game.move(a,'exile');f.game.recalc();assert.equal(s.kw('flying'),false);assert.equal(f.game.isProtectedFrom(s,red),false);});
 test(role+': Rayami exiles a dying nontoken with a blood counter and reads every such exiled card',async()=>{const f=setup(role),r=card(f,'Rayami, First of the Fallen'),s=card(f,'Sphinx of the Steel Wind','battlefield',f.b);await f.game.destroy(s);assert.equal(s.zone,'exile');assert.equal(s.counters.blood,1);f.game.recalc();assert.equal(r.kw('flying'),true);assert.equal(f.game.isProtectedFrom(r,card(f,'Lightning Bolt','hand',f.b)),true);await f.game.move(s,'hand');assert.equal(r.kw('flying'),false);});
 test(role+': Rayami applies to itself in a simultaneous wipe but does not exile tokens',async()=>{const f=setup(role),r=card(f,'Rayami, First of the Fallen'),b=body(f);const[t]=await f.game.makeTokens(M.C1920.token('Beast',['Beast'],3,3,['G']),f.a);await f.game.destroyMany([r,b,t]);assert.equal(r.zone,'exile');assert.equal(b.zone,'exile');assert.equal(b.counters.blood,1);assert.notEqual(t.zone,'exile');});
 test(role+': Manascape gains opposing basic mana and activated abilities, with flexible colored activation costs',async()=>{const f=setup(role),forest=card(f,'Forest','battlefield',f.b),land=card(f,'Gavony Township','battlefield',f.b),r=await play(f,'Manascape Refractor');assert.equal(r.tapped,true);r.tapped=false;const mana=f.game.manaSources(f.a).find(e=>e.card===r&&e.produce.some(o=>o.G===1));assert.ok(mana);assert.ok(r.cur.extraAbilities.length);const a=body(f);for(const k of Object.keys(f.a.pool))f.a.pool[k]=0;f.a.pool.C=4;const entry=f.game.activatableList(f.a).find(e=>e.card===r&&!e.manaAbility);assert.ok(entry);assert.equal(await f.game.activateAbility(f.a,entry),true);await settle(f.game);assert.equal(a.counters['+1/+1'],1);assert.equal(f.a.pool.C,0);await f.game.move(land,'hand');assert.equal(r.cur.extraAbilities.length,0);assert.ok(forest.zone==='battlefield');});
}
