import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,tokens,settle,fuel,event,activate} from './helpers/c19-c20-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Soulflayer retains keywords from its actual delve payment, but a blink clears them',async()=>{const f=setup(role),a=card(f,'Zetalpa, Primal Dawn','graveyard');f.decide=(p,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='delve'?[a]:undefined;const s=await play(f,'Soulflayer');assert.equal(a.zone,'exile');assert.equal(s.kw('flying'),true);assert.equal(s.kw('indestructible'),true);await f.game.move(a,'hand');assert.equal(s.kw('flying'),true);await f.game.move(s,'exile');await f.game.putPermanentOntoBattlefield(s,f.a);assert.equal(s.kw('flying'),false);});
 test(role+': Ethereal Forager returns only an instant or sorcery actually exiled with its delve ability',async()=>{const f=setup(role),a=card(f,'Urban Evolution','graveyard'),b=card(f,'Lightning Bolt','exile');f.decide=(p,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='delve'?[a]:q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':undefined;const s=await play(f,'Ethereal Forager');assert.equal(a.zone,'exile');await event(f,'attacks',{card:s});assert.equal(a.zone,'hand');assert.equal(b.zone,'exile');});
 test(role+': Kathril places one counter per available keyword and grows by their actual count',async()=>{const f=setup(role);card(f,'Zetalpa, Primal Dawn','graveyard');card(f,'Zetalpa, Primal Dawn','graveyard');const b=body(f);f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.includes('Kathril')?[b]:undefined;const s=await play(f,'Kathril, Aspect Warper');for(const k of ['flying','double strike','vigilance','trample','indestructible'])assert.equal(b.counters[k],1);assert.equal(s.counters['+1/+1'],5);assert.equal(s.power,8);});
 test(role+': Frontline Medic grants indestructible to the current team with three attackers and sacrifices to counter X',async()=>{const f=setup(role),s=card(f,'Frontline Medic'),a=body(f),b=body(f),reserve=body(f);await event(f,'attackersDeclared',{player:f.a,attackers:[s,a,b]});assert.equal(reserve.kw('indestructible'),true);const spell=card(f,'Hooded Hydra','hand',f.b);fuel(f.b);const turn=f.game.turnPlayer;f.game.turnPlayer=f.b;assert.equal(await f.game.castSpell(f.b,spell,{xVal:2}),true);f.game.turnPlayer=turn;for(const k of Object.keys(f.b.pool))f.b.pool[k]=0;target(f,f.game.stack.find(x=>x.card===spell));await activate(f,s);assert.equal(s.zone,'graveyard');assert.equal(spell.zone,'graveyard');});
 test(role+': Fireflux exiles another attacker and puts the revealed creature into combat',async()=>{const f=setup(role),s=card(f,'Fireflux Squad'),a=body(f),replacement=card(f,'Colossal Dreadmaw','library');s.attacking=f.b;a.attacking=f.b;f.game.combat={attackers:[s,a],hadAttackers:true};f.game.phase='combat';f.game.step='attackers';target(f,a);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':prior(p,q);await event(f,'attacks',{card:s});assert.equal(a.zone,'exile');assert.equal(replacement.zone,'battlefield');assert.equal(replacement.tapped,true);assert.ok(replacement.attacking);assert.ok(f.game.combat.attackers.includes(replacement));});
 test(role+': Floodgates lets the active player choose, then sacrifices at three and deals six through a reflexive trigger',async()=>{const f=setup(role),s=card(f,'Lavabrink Floodgates'),b=body(f,f.b);s.counters.doom=2;let chooser;f.decide=(p,q)=>{if(q.type==='chooseOption'&&q.prompt?.includes('doom')){chooser=p;return 'add';}};await event(f,'upkeep',{player:f.b});assert.equal(chooser,f.b);assert.equal(s.zone,'graveyard');assert.equal(b.zone,'graveyard');});
 test(role+': Oona pays a hybrid X activation and makes tokens only for the chosen color',async()=>{const f=setup(role),s=card(f,'Oona, Queen of the Fae');card(f,'Island','library',f.b);card(f,'Urban Evolution','library',f.b);card(f,'Grizzly Bears','library',f.b);target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseX'?3:q.type==='chooseOption'&&q.options?.some(o=>o.key==='G')?'G':prior(p,q);await activate(f,s);assert.equal(f.b.exile.length,3);assert.equal(tokens(f).length,2);assert.equal(tokens(f)[0].hasSub('Rogue'),true);});
 test(role+': Sygg checks total life lost even after life is regained',async()=>{const f=setup(role);card(f,'Sygg, River Cutthroat');f.decide=(p,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':undefined;await f.game.loseLife(f.b,3);await f.game.gainLife(f.b,3);await event(f,'endStep',{player:f.b});assert.equal(f.a.hand.length,1);});
 test(role+': Xyris ignores only the first draw of the opponent’s own draw step',async()=>{const f=setup(role);card(f,'Xyris, the Writhing Storm');await f.game.draw(f.b,1);await settle(f.game);assert.equal(tokens(f).length,1);f.game.turnPlayer=f.b;f.game.phase='draw';await f.game.draw(f.b,2);await settle(f.game);assert.equal(tokens(f).length,2);f.b.turnState.c1920DrawStepN=0;await f.game.draw(f.b,1);await settle(f.game);assert.equal(tokens(f).length,2);});
 test(role+': Xyris combat damage draws for both players and creates Snakes for the opposing draws',async()=>{const f=setup(role),s=card(f,'Xyris, the Writhing Storm');await f.game.damagePlayer(s,f.b,3,{combat:true});await settle(f.game);assert.equal(f.a.hand.length,3);assert.equal(f.b.hand.length,3);assert.equal(tokens(f).length,3);});
 test(role+': Wall of Stolen Identity copies with Wall and defender, taps its model and locks it only while control persists',async()=>{const f=setup(role),model=body(f,f.b);f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt?.includes('Wall of Stolen Identity')?[model]:undefined;const c=await play(f,'Wall of Stolen Identity');assert.equal(c.hasSub('Wall'),true);assert.equal(c.kw('defender'),true);assert.equal(c.power,2);assert.equal(model.tapped,true);assert.equal(model.cur.cantUntap,true);M.C1920.control(f.game,c,f.b,false);assert.equal(model.cur.cantUntap,false);});
 test(role+': Yavimaya Dryad searches its controller’s Forest into play tapped for the chosen player',async()=>{const f=setup(role),land=card(f,'Forest','library');target(f,f.b);const prior=f.decide;f.decide=(p,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='optTrigger'?'yes':q.type==='chooseCards'&&q.search?[land]:prior(p,q);await play(f,'Yavimaya Dryad');assert.equal(land.ctrl,f.b);assert.equal(land.tapped,true);assert.equal(land.zone,'battlefield');});
}
