import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,target,tokens,settle,fuel,event} from './helpers/c19-c20-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Anowon combines simultaneous Rogue damage to one player into one mill and one draw',async()=>{const f=setup(role),s=card(f,'Anowon, the Ruin Thief'),a=card(f,'Marang River Prowler');card(f,'Grizzly Bears','library',f.b);card(f,'Grizzly Bears','library',f.b);assert.equal(a.power,3);const library=f.b.library.length;await f.game.damageBatch([{src:s,target:f.b,n:2},{src:a,target:f.b,n:3}],{combat:true});await settle(f.game);assert.equal(f.b.library.length,library-5);assert.equal(f.a.hand.length,1);});
 test(role+': Anowon ignores non-Rogue and noncombat damage and triggers once per damaged player',async()=>{const f=setup(role),s=card(f,'Anowon, the Ruin Thief'),a=body(f),other=f.game.players[2];card(f,'Grizzly Bears','library',f.b);card(f,'Grizzly Bears','library',other);await f.game.damageBatch([{src:s,target:f.b,n:2},{src:s,target:other,n:2},{src:a,target:f.b,n:2}],{combat:true});await settle(f.game);assert.equal(f.a.hand.length,2);const before=f.b.library.length;await f.game.damagePlayer(s,f.b,2);await settle(f.game);assert.equal(f.b.library.length,before);});
 test(role+': Prowl depends on the damaging creature’s type at the time of combat damage',async()=>{const f=setup(role),s=card(f,'Marang River Prowler'),c=card(f,'Latchkey Faerie','hand');fuel(f.a);assert.equal(f.game.castableList(f.a).some(e=>e.card===c&&e.alt?.c1920Prowl),false);await f.game.damagePlayer(s,f.b,1,{combat:true});await f.game.move(s,'graveyard');const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.c1920Prowl);assert.ok(e);const before=f.a.hand.length;assert.equal(await f.game.castSpell(f.a,c,{alt:e.alt}),true);await settle(f.game);assert.equal(f.a.hand.length,before);f.a.turnState=f.a.freshTurnState();const d=card(f,'Stinkdrinker Bandit','hand');assert.equal(f.game.castableList(f.a).some(e=>e.card===d&&e.alt?.c1920Prowl),false);});
 test(role+': Prowl accepts a shared Sphinx type for Enigma, whose entry returns one permanent per opponent',async()=>{const f=setup(role),s=card(f,'Curator of Mysteries'),a=body(f,f.b),b=body(f,f.game.players[2]);await f.game.damagePlayer(s,f.b,1,{combat:true});target(f,a,b);const c=card(f,'Enigma Thief','hand');fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.c1920Prowl);assert.ok(e);assert.equal(await f.game.castSpell(f.a,c,{alt:e.alt}),true);await settle(f.game);assert.equal(a.zone,'hand');assert.equal(b.zone,'hand');});
 test(role+': Notorious Throng counts all damage to opponents and its paid prowl grants an extra turn',async()=>{const f=setup(role),s=card(f,'Marang River Prowler');await f.game.damagePlayer(s,f.b,2,{combat:true});await f.game.damagePlayer(s,f.game.players[2],3);const c=card(f,'Notorious Throng','hand');fuel(f.a);const e=f.game.castableList(f.a).find(e=>e.card===c&&e.alt?.c1920Prowl);assert.ok(e);let turns=0;f.game.scheduleExtraTurn=p=>{assert.equal(p,f.a);turns++;};assert.equal(await f.game.castSpell(f.a,c,{alt:e.alt}),true);await settle(f.game);assert.equal(tokens(f).length,5);assert.equal(turns,1);});
 test(role+': Stinkdrinker creates a separate trigger for each unblocked Rogue',async()=>{const f=setup(role),s=card(f,'Stinkdrinker Bandit'),a=card(f,'Marang River Prowler'),b=card(f,'Latchkey Faerie');for(const c of [s,a,b])c.attacking=f.b;b.wasBlocked=true;await f.game.emit('blockersDeclared',{player:f.a,attackers:[s,a,b]});await f.game.flushTriggers();const tr=f.game.stack.filter(s=>s.kind==='trigger');assert.equal(tr.length,2);await f.game.counterStackObject(tr[0]);await settle(f.game);assert.equal([s,a].filter(c=>c.power===4).length,1);assert.equal(b.power,3);});
 test(role+': Silent Arbiter limits attack and block declarations to one distinct creature',async()=>{const f=setup(role);const s=card(f,'Silent Arbiter'),a=body(f),b=body(f),x=body(f,f.b),y=body(f,f.b);for(const c of [a,b,x,y])c.sick=false;a.attacking=f.b;b.attacking=f.b;assert.equal(f.game.attackGroupLegal([a,b]),false);assert.equal(f.game.attackGroupLegal([a]),true);assert.equal(f.game.blockDeclarationLegal([a,b],[{blocker:x,attacker:a},{blocker:y,attacker:b}]),false);await f.game.move(s,'graveyard');assert.equal(f.game.attackGroupLegal([a,b]),true);});
 test(role+': Pramikon restricts the nearest opponent in its chosen direction',async()=>{const f=setup(role),c=body(f);c.sick=false;f.decide=(p,q)=>q.type==='chooseOption'&&q.options?.some(o=>o.key==='left')?'left':undefined;const s=await play(f,'Pramikon, Sky Rampart');assert.ok(f.game.legalDeclarationAttackTargets(c).includes(f.b));assert.equal(f.game.legalDeclarationAttackTargets(c).includes(f.game.players[2]),false);await f.game.move(s,'graveyard');assert.ok(f.game.legalDeclarationAttackTargets(c).includes(f.game.players[2]));});
 test(role+': Capricopian activation belongs only to the attacked player during declare attackers',async()=>{const f=setup(role),s=await play(f,'Capricopian',{xVal:3});s.attacking=f.b;f.game.phase='combat';f.game.step='attackers';fuel(f.b);const third=f.game.players[2];f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt?.includes('reselect')?String(third.idx):undefined;assert.equal(f.game.activatableList(f.a).some(e=>e.card===s),false);const e=f.game.activatableList(f.b).find(e=>e.card===s);assert.ok(e);assert.equal(await f.game.activateAbility(f.b,e),true);await settle(f.game);assert.equal(s.counters['+1/+1'],4);assert.equal(s.attacking,third);assert.equal(f.game.activatableList(f.b).some(e=>e.card===s),false);});
}
