import test from'node:test';import assert from'node:assert/strict';import{loadEngine}from'./helpers/load-engine.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
const M=loadEngine(),fund=p=>{for(const k of['W','U','B','R','G','C'])p.pool[k]=30;};
function game(role){const f=context(M,role);for(const p of f.game.players)if(!p.isAI){const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:prior(g,q);}return f;}
async function cast(f,p,name,targets=[]){const c=put(M,f.game,p,name,'hand');fund(p);const before=Object.values(p.pool).reduce((s,n)=>s+n,0);assert.equal(await f.game.castSpell(p,c,{from:'hand',quickTargets:targets}),true);assert.ok(Object.values(p.pool).reduce((s,n)=>s+n,0)<before);return c;}
for(const role of['human','ai'])for(const name of['Darksteel Reactor',"Ajani's Mantra"]){
 test(`${role}: paid ${name} queues its optional upkeep without asking before responses`,async()=>{const f=game(role),source=await cast(f,f.a,name);await settle(f.game);await f.game.emit('upkeep',{player:f.a});await f.game.flushTriggers();assert.equal(f.game.stack.length,1);assert.equal(f.trace.filter(x=>x.q.aiHint?.kind==='optTrigger').length,0);assert.equal(f.game.stack[0].srcCard,source);await f.game.resolveTop();assert.equal(f.trace.filter(x=>x.q.aiHint?.kind==='optTrigger').length,1);});
 test(`${role}: Stifle counters ${name}'s optional upkeep before its effect is offered`,async()=>{const f=game(role),source=await cast(f,f.a,name);await settle(f.game);await f.game.emit('upkeep',{player:f.a});await f.game.flushTriggers();const pending=f.game.stack[0];assert.ok(pending);await cast(f,f.b,'Stifle',[pending]);await settle(f.game);assert.equal(f.trace.filter(x=>x.q.aiHint?.kind==='optTrigger').length,0);assert.equal(source.counters.charge||0,0);assert.equal(f.a.life,40);});
}
test('a human declining an optional upkeep still receives an independent Stack object first',async()=>{const f=game('human'),source=await cast(f,f.a,'Darksteel Reactor');await settle(f.game);const prior=f.a.controller.decide.bind(f.a.controller);let offered=0;f.a.controller.decide=(g,q)=>{if(q.aiHint?.kind==='optTrigger'){offered++;return'no';}return prior(g,q);};await f.game.emit('upkeep',{player:f.a});await f.game.flushTriggers();assert.equal(offered,0);assert.equal(f.game.stack.length,1);await settle(f.game);assert.equal(offered,1);assert.equal(source.counters.charge||0,0);});
for(const role of['human','ai'])test(`${role}: a copied optional trigger retains its own resolution choice`,async()=>{const f=game(role),source=await cast(f,f.a,"Ajani's Mantra");await settle(f.game);await f.game.emit('upkeep',{player:f.a});await f.game.flushTriggers();await f.game.copyStackAbility(f.game.stack[0],f.a);assert.equal(f.trace.filter(x=>x.q.aiHint?.kind==='optTrigger').length,0);await settle(f.game);assert.equal(f.trace.filter(x=>x.q.aiHint?.kind==='optTrigger').length,2);assert.equal(f.a.life,42);});
for(const role of['human','ai'])test(`${role}: Ghostly Flicker cannot let an old Reactor upkeep charge its new incarnation`,async()=>{const f=game(role),island=put(M,f.game,f.a,'Island'),source=await cast(f,f.a,'Darksteel Reactor');await settle(f.game);await f.game.emit('upkeep',{player:f.a});await f.game.flushTriggers();const old=source.zoneVersion,prior=f.a.controller.decide.bind(f.a.controller);if(role==='human')f.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.max===2?[source,island]:prior(g,q);await cast(f,f.a,'Ghostly Flicker');await f.game.resolveTop();assert.ok(source.zoneVersion>old);await settle(f.game);assert.equal(source.counters.charge||0,0);});
for(const role of['human','ai'])for(const name of['Foundation Breaker','Reclamation Sage','Restoration Angel','Greenwarden of Murasa','Impulsivity','Noxious Gearhulk'])test(`${role}: ${name} announces its required target before an optional effect can be countered`,async()=>{
 const f=game(role),witness=put(M,f.game,['Restoration Angel','Greenwarden of Murasa','Impulsivity'].includes(name)?f.a:f.b,
   ['Foundation Breaker','Reclamation Sage'].includes(name)?'Sol Ring':['Greenwarden of Murasa','Impulsivity'].includes(name)?'Shock':'Grizzly Bears',
   ['Greenwarden of Murasa','Impulsivity'].includes(name)?'graveyard':'battlefield');
 const source=await cast(f,f.a,name);await f.game.resolveTop();assert.equal(f.game.stack.length,1);const tr=f.game.stack[0];assert.equal(tr.srcCard,source);assert.equal(tr.targets.flat()[0],witness);assert.equal(tr.targetSpecs[0].upTo||false,false);assert.ok(f.trace.some(row=>row.q.type==='chooseTargets'&&row.q.min===1));assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);
 await cast(f,f.b,'Stifle',[tr]);await settle(f.game);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);assert.equal(witness.zone,['Greenwarden of Murasa','Impulsivity'].includes(name)?'graveyard':'battlefield');
});
test('declining Reclamation Sage after target announcement preserves its target',async()=>{const f=game('human'),witness=put(M,f.game,f.a,'Sol Ring'),source=await cast(f,f.a,'Reclamation Sage');await f.game.resolveTop();const tr=f.game.stack[0];assert.equal(tr.targets[0],witness);const prior=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=(g,q)=>q.aiHint?.kind==='optTrigger'?'no':prior(g,q);await settle(f.game);assert.equal(witness.zone,'battlefield');assert.equal(source.zone,'battlefield');});
for(const role of['human','ai'])test(`${role}: an optional effect with an illegal target fizzles before asking whether to perform it`,async()=>{const f=game(role),witness=put(M,f.game,f.b,'Sol Ring');await cast(f,f.a,'Reclamation Sage');await f.game.resolveTop();await cast(f,f.b,'Wipe Away',[witness]);await settle(f.game);assert.equal(witness.zone,'hand');assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);});
for(const role of['human','ai'])test(`${role}: no legal required target removes Reclamation Sage's trigger without an optional-effect prompt`,async()=>{const f=game(role);await cast(f,f.a,'Reclamation Sage');await settle(f.game);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);});
for(const role of['human','ai'])test(`${role}: choosing Amphin Mutineer's up-to target is the only optional announcement`,async()=>{const f=game(role),witness=put(M,f.game,f.b,'Grizzly Bears');if(role==='human'){const prior=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=(g,q)=>q.type==='chooseTargets'?[witness]:prior(g,q);}await cast(f,f.a,'Amphin Mutineer');await f.game.resolveTop();assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].targets[0],witness);assert.equal(f.game.stack[0].targetSpecs[0].upTo,true);await settle(f.game);assert.equal(witness.zone,'exile');assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);assert.equal(f.game.creatures(f.b).filter(c=>c.isToken&&c.hasSub('Salamander')).length,1);});
test('Amphin Mutineer with zero chosen targets still puts its trigger on the Stack',async()=>{const f=game('human');put(M,f.game,f.b,'Grizzly Bears');await cast(f,f.a,'Amphin Mutineer');await f.game.resolveTop();assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].targets.filter(Boolean).length,0);await settle(f.game);assert.equal(f.game.bf().some(c=>c.isToken),false);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);});
async function reachMain(f){const emit=f.game.emit,stop=new Error('upkeep reached');f.game.emit=async function(name,data){if(name==='upkeep')throw stop;return emit.call(this,name,data);};try{await assert.rejects(f.game.runTurn(),e=>e===stop);}finally{f.game.emit=emit;}f.game.phase='main1';f.game.step='main';}
for(const role of['human','ai'])test(`${role}: Pyreswipe Hawk's spend-six target choice is the only optional choice`,async()=>{const f=game(role),witness=put(M,f.game,f.b,'Sol Ring'),source=await cast(f,f.a,'Pyreswipe Hawk');await settle(f.game);await reachMain(f);if(role==='human'){const prior=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(witness)?[witness]:prior(g,q);}await cast(f,f.a,'Colossal Dreadmaw');const trigger=f.game.stack.find(so=>so.kind==='trigger'&&so.srcCard===source);assert.ok(trigger);const selected=trigger.targets[0];if(role==='human')assert.equal(selected?.iid,witness.iid);else assert.ok(!selected||selected===witness);await settle(f.game);assert.equal(witness.ctrl.idx,selected?f.a.idx:f.b.idx);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);});
for(const role of['human','ai'])test(`${role}: Renegade Bull announces the graveyard target before offering its copied spell on resolution`,async()=>{const f=game(role),witness=put(M,f.game,f.a,'Shock','graveyard'),source=await cast(f,f.a,'Renegade Bull');await settle(f.game);await reachMain(f);await cast(f,f.a,'Rancor',[source]);await settle(f.game);f.b.life=2;if(role==='human'){const prior=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=(g,q)=>q.type==='attackers'?[{card:source,target:f.b}]:q.type==='chooseTargets'&&q.candidates.includes(witness)?[witness]:prior(g,q);}let observed=false,selected=false;f.game.priorityRound=async()=>{assert.equal(f.game._stackResolutionDepth||0,0,'free casting cannot request priority during the parent resolution');const tr=f.game.stack.find(so=>so.kind==='trigger'&&so.srcCard===source&&so.targetSpecs?.some(spec=>spec.zone==='graveyard'));if(tr){observed=true;selected=tr.targets.includes(witness);assert.ok(selected||!tr.targets.filter(Boolean).length);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='freeCast').length,0);}await settle(f.game);};await f.game.combatPhase(f.a);assert.equal(observed,true);if(role==='human')assert.equal(selected,true);assert.equal(witness.zone,selected?'exile':'graveyard');assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,0);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='freeCast').length,selected?1:0);});
for(const role of['human','ai'])for(const name of['Cavalier of Thorns','Greenwarden of Murasa'])test(`${role}: ${name}'s death ability chooses its required graveyard target before Stifle can prevent the exile choice`,async()=>{const f=game(role);put(M,f.game,f.a,'Shock','graveyard');const source=await cast(f,f.a,name);await settle(f.game);put(M,f.game,f.a,'Forest','graveyard');const before=f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length;await cast(f,f.b,'Murder',[source]);await f.game.resolveTop();const tr=f.game.stack[0];assert.ok(tr);assert.equal(tr.srcCard,source);assert.ok(tr.targets[0]);assert.equal(tr.targetSpecs[0].upTo,false);assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,before);await cast(f,f.b,'Stifle',[tr]);await settle(f.game);assert.equal(source.zone,'graveyard');assert.equal(f.trace.filter(row=>row.q.aiHint?.kind==='optTrigger').length,before);});
for(const role of['human','ai'])test(`${role}: Restoration Angel may exile a token, which cannot return to the battlefield`,async()=>{const f=game(role);await cast(f,f.a,'Raise the Alarm');await settle(f.game);const source=await cast(f,f.a,'Restoration Angel');await f.game.resolveTop();const tr=f.game.stack[0],target=tr.targets[0];assert.ok(target.isToken);assert.equal(tr.srcCard.iid,source.iid);await settle(f.game);assert.equal(f.game.bf().includes(target),false);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken).length,1);});
for(const role of['human','ai'])test(`${role}: Cavalier of Thorns cannot return its target after Cremate prevents its own exile payment`,async()=>{const f=game(role),source=await cast(f,f.a,'Cavalier of Thorns');await settle(f.game);put(M,f.game,f.a,'Shock','graveyard');await cast(f,f.b,'Murder',[source]);await f.game.resolveTop();const tr=f.game.stack[0],target=tr.targets[0];assert.ok(target);await cast(f,f.b,'Cremate',[source]);await f.game.resolveTop();assert.equal(source.zone,'exile');assert.equal(target.zone,'graveyard');await settle(f.game);assert.equal(target.zone,'graveyard');});
test('Greenwarden of Murasa may target itself for its death ability, but exiling it cannot return the new exile object',async()=>{const f=game('human'),source=await cast(f,f.a,'Greenwarden of Murasa');await settle(f.game);await cast(f,f.b,'Murder',[source]);await f.game.resolveTop();assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].targets[0]?.iid,source.iid);await settle(f.game);assert.equal(source.zone,'exile');});
for(const role of['human','ai'])test(`${role}: Cavalier of Thorns pays its own exile before returning the announced card to the library`,async()=>{const f=game(role),source=await cast(f,f.a,'Cavalier of Thorns');await settle(f.game);put(M,f.game,f.a,'Shock','graveyard');await cast(f,f.b,'Murder',[source]);await f.game.resolveTop();const tr=f.game.stack[0],target=tr.targets[0];assert.ok(target);assert.equal(source.zoneVersion,tr.ctx.sourceZoneVersion+1);await settle(f.game);assert.equal(source.zone,'exile');assert.equal(target.zone,'library');assert.equal(f.a.library.at(-1)?.iid,target.iid);});
