import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {loadEngine} from './helpers/load-engine.mjs';import {context,settle} from './helpers/oracle-v8-fixtures.mjs';import {semanticClass,createImportPlan} from '../scripts/import-oracle-batch.mjs';import {operationProofV24} from './helpers/oracle-v24-permanents-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v24-permanents.json',import.meta.url),'utf8'));
const M=loadEngine();
const plan=createImportPlan({cards:rows,bulk:{type:'oracle_cards'},sequence:9940,limit:rows.length,compilerVersion:24});assert.equal(plan.report.cards.length,rows.length);const absent=plan.report.cards.filter(entry=>!M.DEFS[entry.raw.name]);if(absent.length){M.registerOracleBatch({...plan.report,cards:absent});M.initData(M.RAW_DATA);}
const fund=player=>{for(const color of ['W','U','B','R','G','C'])player.pool[color]=100;};
const fixtureDefinition=(name,types,extra={})=>({name,types,subtypes:[],super:[],cost:'{2}',oracle:'',...extra});
const zoneCard=(M,p,definition,zone)=>{const card=new M.CardInst(typeof definition==='string'?M.DEFS[definition]:definition,p);card.zone=zone;p[zone].push(card);return card;};
const permanent=(M,g,p,definition)=>{const card=zoneCard(M,p,definition,'hand');p.hand.splice(p.hand.indexOf(card),1);card.zone='battlefield';card.ctrl=p;card.sick=false;g.battlefield.push(card);g.recalc();return card;};
const h={gameFor:(M,_controllers,{ai})=>({...context(M,ai?'ai':'human'),role:ai?'ai':'human'}),fund,fixtureDefinition,zoneCard,permanent,resolveAll:settle,assertControllerRole:(M,ctx)=>assert.equal(ctx.a.controller instanceof M.AIController,ctx.role==='ai')};
test('whole linked cards retain every rule and reject unknown riders',()=>{for(const card of rows){assert.ok(semanticClass(card,{compilerVersion:24}).semanticClass,card.name);assert.equal(semanticClass({...card,oracle_text:card.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:24}).semanticClass,undefined);}});
for(const role of ['human','ai'])for(const entry of plan.report.cards)test(role+': '+entry.raw.name,async()=>{const op=entry.implementation.find(op=>JSON.stringify(op).includes('permanent-linked-acquire-v24')||entry.raw.name==='Thief of Existence'&&op.kind==='generic-trigger');assert.ok(op);assert.ok(await operationProofV24(M,entry,op,role,h));});
for(const role of ['human','ai'])test(role+': copied Hideaway acquisitions authorize every linked card under CR607.3',async()=>{
 const {game:g,a}=context(M,role);fund(a);const cards=[];for(let group=0;group<2;group++){cards.push(zoneCard(M,a,fixtureDefinition('V24 copied hidden '+group,['Creature'],{cost:'{10}',power:'7',toughness:'9'}),'library'));for(let i=0;i<3;i++)zoneCard(M,a,fixtureDefinition('V24 copied bottom '+group+'-'+i,['Creature'],{power:'1',toughness:'2'}),'library');}
 const prior=a.controller.decide.bind(a.controller);a.controller.decide=(game,q)=>prior(game,q.type==='chooseCards'&&cards.some(card=>q.from.includes(card))?{...q,from:q.from.filter(card=>cards.includes(card)),min:1,max:1}:q);
 const source=zoneCard(M,a,"Clive's Hideaway",'hand');assert.equal(await g.playLand(a,source),true);await g.flushTriggers();const trigger=g.stack.find(row=>row.srcCard===source);assert.ok(trigger);assert.ok(await g.copyStackAbility(trigger,a,{mayNewTargets:false}));await settle(g);assert.equal(M.OracleV24Permanents.linked(g,source,'permanent-linked-v24').length,2);
 for(let i=0;i<4;i++)permanent(M,g,a,fixtureDefinition('V24 copied legendary '+i,['Creature'],{super:['Legendary'],power:'1',toughness:'3'}));const activation=g.activatableList(a).find(row=>row.card===source);assert.ok(activation);const before=Object.values(a.pool).reduce((sum,n)=>sum+n,0);assert.equal(await g.activateAbility(a,activation),true);await settle(g);assert.equal(Object.values(a.pool).reduce((sum,n)=>sum+n,0),before-2);assert.ok(cards.every(card=>card.zone==='battlefield'),'one resolution offers both cards exiled by copied Hideaway triggers');
});
