import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createFixturePlan,registerCanonicalFixturePlan} from './helpers/oracle-fixture-plan.mjs';import {loadEngine} from './helpers/load-engine.mjs';import {names,proveMoreV70} from './helpers/oracle-v70-more-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v70-more.json',import.meta.url))),plan=createFixturePlan(rows,70,9972),M=loadEngine();registerCanonicalFixturePlan(M,plan);
test('v70 ten complete sources reject unknown appended clauses',()=>{assert.equal(rows.length,10);for(const row of rows)assert.equal(plan.classify({...row,oracle_text:row.oracle_text+'\nPerform an unsupported action.'}).semanticClass,undefined,row.name);});
for(const role of ['human','ai'])for(const name of names)for(const positive of [true,false])test(`${role}: ${name} complete paid rules ${positive}`,()=>proveMoreV70(M,name,role,positive));

import {context,settle} from './helpers/oracle-v8-fixtures.mjs';
import {fund,total,def,put,permanent,choose} from './helpers/oracle-v30-permanents-proof.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
for(const role of ['human','ai']){
 const setup=()=>{const f=context(M,role);fund(f.a);fund(f.b);return f;};
 const paid=async(g,p,c,resolve=true,alt)=>{const before=total(p);assert.equal(await g.castSpell(p,c,{from:c.zone,...(alt?{alt}:{})}),true);assert.ok(total(p)<before);if(resolve)await settle(g);return g.stack.find(so=>so.card===c);};
 test(`${role}: boundary Reverent Silence cannot pay life gain through a prohibition`,async()=>{const {game:g,a,b}=setup();permanent(M,g,a,M.DEFS.Forest);const card=put(M,a,'Reverent Silence','hand'),option=g.castableList(a).find(r=>r.card===card&&r.alt?.oracleAlternativeId==='silence-v70');assert.ok(option);g.untilEffects.push({kind:'lifeGainProhibitionV9',players:[b],expires:'eot'});assert.equal(g.castableList(a).some(r=>r.card===card&&r.alt?.oracleAlternativeId==='silence-v70'),false);const mana=total(a),life=b.life;assert.equal(await g.castSpell(a,card,{from:'hand',alt:option.alt}),false);assert.equal(total(a),mana);assert.equal(b.life,life);assert.equal(card.zone,'hand');await paid(g,a,card);assert.equal(card.zone,'graveyard');assertGameStateInvariants(g);});
 test(`${role}: boundary Eelectrocute counter exile and expired roll permission`,async()=>{const {game:g,a,b}=setup();choose(a,q=>q.type==='chooseTargets'?{...q,candidates:[b],min:1,max:1}:null);const card=put(M,a,'Eelectrocute','hand');await paid(g,a,card);g.rnd=()=>0.99;await g.rollDice(a,6,1,{source:card});const option=g.castableList(a).find(r=>r.card===card);assert.ok(option);const so=await paid(g,a,card,false,option.alt);await g.counterStackObject(so);assert.equal(card.zone,'exile');const next=put(M,a,'Eelectrocute','graveyard'),stale=g.castableList(a).find(r=>r.card===next);assert.ok(stale);g.turnNo++;assert.equal(g.castableList(a).some(r=>r.card===next),false);const mana=total(a);assert.equal(await g.castSpell(a,next,{from:'graveyard',alt:stale.alt}),false);assert.equal(total(a),mana);assert.equal(next.zone,'graveyard');assertGameStateInvariants(g);});
 test(`${role}: boundary Command the Stage ignores combat damage and Ugin ignores wrong spells`,async()=>{const {game:g,a,b}=setup(),stage=put(M,a,'Command the Stage','hand');await paid(g,a,stage);const attacker=permanent(M,g,a,def('Boundary attacker',['Creature'],{power:'1',toughness:'2'}));await g.damageAny(attacker,b,1,{combat:true});g.turnNo++;await g.emit('upkeep',{player:a});await settle(g);assert.equal(stage.zone,'graveyard');const binding=put(M,a,"Ugin's Binding",'hand'),target=permanent(M,g,b,def('Boundary binding target',['Artifact']));choose(a,q=>q.type==='chooseTargets'?{...q,candidates:[target],min:1,max:1}:null);await paid(g,a,binding);const other=permanent(M,g,b,def('Boundary untouched',['Artifact']));for(const [name,cost]of [['Boundary six','{6}'],['Boundary colored seven','{6}{R}']]){await paid(g,a,put(M,a,def(name,['Artifact'],{cost}),'hand'));assert.equal(binding.zone,'graveyard');assert.equal(other.zone,'battlefield');}assertGameStateInvariants(g);});
 test(`${role}: boundary Radiate rejects multiple distinct targets`,async()=>{const {game:g,a,b}=setup(),first=permanent(M,g,a,def('Boundary Radiate first',['Creature'],{power:'1',toughness:'5'})),second=permanent(M,g,b,def('Boundary Radiate second',['Creature'],{power:'1',toughness:'5'}));let choices=[first,second];choose(a,q=>q.type==='chooseTargets'?{...q,candidates:[choices.shift()],min:1,max:1}:null);const spell=put(M,a,def('Boundary double target',['Instant'],{cost:'{R}',targets:[M.T.creature(),M.T.creature()],resolve:async()=>{}}),'hand'),so=await paid(g,a,spell,false),radiate=put(M,a,'Radiate','hand'),spec=g.spellTargetSpecs(radiate,{},a)[0];assert.equal(g.legalTargets(spec,radiate,a).includes(so),false);await settle(g);assertGameStateInvariants(g);});
 test(`${role}: boundary Choreographed Sparks resolves both chosen modes`,async()=>{const {game:g,a,b}=setup(),instant=put(M,a,def('Boundary copied instant',['Instant'],{cost:'{U}',resolve:ctx=>ctx.g.gainLife(ctx.you,2,ctx.src)}),'hand'),creature=put(M,a,def('Boundary copied creature',['Creature'],{cost:'{2}',power:'3',toughness:'4'}),'hand');const second=await paid(g,a,creature,false),first=await paid(g,a,instant,false);let aims=[first,second];choose(a,q=>q.type==='chooseTargets'?{...q,candidates:[aims.shift()],min:1,max:1}:null);const decide=a.controller.decide.bind(a.controller);a.controller.decide=async(game,q)=>q.type==='chooseMulti'?Promise.all(q.options.map(option=>decide(game,{...q,type:'chooseOption',options:[option]}))):decide(game,q);const life=a.life;await paid(g,a,put(M,a,'Choreographed Sparks','hand'));assert.equal(a.life,life+4);const token=g.creatures(a).find(c=>c.isToken);assert.ok(token);assert.equal(token.kw('haste'),true);assert.equal(creature.kw('haste'),false);await g.emit('endStep',{player:b});await settle(g);assert.equal(token.zone,'ceased');assert.equal(creature.zone,'battlefield');assertGameStateInvariants(g);});
}
