import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{loadEngine}from'./helpers/load-engine.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
const M=loadEngine(),sources=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-source-duration-source.json',import.meta.url)));for(const c of sources)assert.ok(semanticClass(c).semanticClass,c.name);const missing=sources.filter(c=>!M.DEFS[c.name]);if(missing.length){const {report}=createImportPlan({cards:missing,baseNames:new Set(),bulk:{type:'oracle_cards',updated_at:'2026-08-30T09:01:56.964+00:00'},limit:missing.length,sequence:9996,compilerVersion:8});M.registerOracleBatch(report);M.initData(M.RAW_DATA);}

const fund=p=>{for(const color of'WUBRGC')p.pool[color]=30;};
function make(role){const c=context(M,role);for(const p of c.game.players)if(!p.isAI){const decide=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='tapUntap'?'untap':q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:q.type==='chooseTargets'&&q.aiHint?.goal==='damage'&&q.candidates.some(c=>c instanceof M.Player&&c!==p)?[q.candidates.find(c=>c instanceof M.Player&&c!==p)]:decide(g,q);}return c;}
async function cast(c,p,name,targets=[],resolve=true){const card=put(M,c.game,p,name,'hand');if(!c.game.stack.length&&!card.is('Instant'))c.game.turnPlayer=p;fund(p);const before=Object.values(p.pool).reduce((a,b)=>a+b,0);assert.equal(await c.game.castSpell(p,card,{from:'hand',quickTargets:targets}),true);assert.ok(Object.values(p.pool).reduce((a,b)=>a+b,0)<before);if(resolve)await settle(c.game);return card;}
async function steal(c,name='Mind Flayer'){const target=put(M,c.game,c.b,name==='Master Thief'?'Sol Ring':'Colossal Dreadmaw');const source=await cast(c,c.a,name);assert.equal(target.ctrl.idx,c.a.idx);return{source,target};}
async function disrupt(c,source,kind){if(kind==='destroy')await cast(c,c.b,'Murder',[source]);else if(kind==='blink')await cast(c,c.a,'Cloudshift',[source]);else if(kind==='control'){await cast(c,c.b,'Control Magic',[source]);}else if(kind==='phase'){await cast(c,c.b,'Slip Out the Back',[source]);}else throw Error(kind);}
for(const role of['human','ai']){
 for(const name of['Mind Flayer','Master Thief','Dragonlord Silumgar'])test(role+': '+name+' pays and transfers control until a real source removal',async()=>{const c=make(role),{source,target}=await steal(c,name);await cast(c,c.b,'Murder',[source]);assert.equal(target.ctrl.idx,c.b.idx);assert.equal(source.zone,'graveyard');});
 for(const kind of['destroy','blink','control','phase'])test(role+': '+kind+' before Mind Flayer resolution cannot begin the old source duration',async()=>{const c=make(role),target=put(M,c.game,c.b,'Colossal Dreadmaw'),source=await(async()=>{if(kind==='control')await cast(c,c.b,'Vedalken Orrery');return cast(c,c.a,'Mind Flayer',[],false);})();await c.game.resolveTop();assert.ok(c.game.stack.some(s=>s.srcCard===source));await disrupt(c,source,kind);if(kind==='blink'){assert.equal(target.ctrl.idx,c.a.idx,'new source trigger may gain a fresh duration');await cast(c,c.b,'Murder',[source]);}assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': source phasing ends an established control duration permanently',async()=>{const c=make(role),{source,target}=await steal(c);await disrupt(c,source,'phase');assert.equal(target.ctrl.idx,c.b.idx);c.game.phaseInFor(c.a);c.game.recalc();assert.equal(source.phasedOut,false);assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': target phasing alone retains the duration while its source is visible',async()=>{const c=make(role),{source,target}=await steal(c);await cast(c,c.a,'Slip Out the Back',[target]);assert.equal(target.phasedOut,true);c.game.phaseInFor(c.a);c.game.recalc();assert.equal(target.ctrl.idx,c.a.idx);await cast(c,c.b,'Murder',[source]);assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': another control layer on the stolen object survives source loss',async()=>{const c=make(role),{source,target}=await steal(c);await cast(c,c.b,'Control Magic',[target]);assert.equal(target.ctrl.idx,c.b.idx);await cast(c,c.b,'Murder',[source]);assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': an actual Control Magic on the source expires its linked control immediately',async()=>{const c=make(role),{source,target}=await steal(c);const aura=await cast(c,c.b,'Control Magic',[source]);assert.equal(source.ctrl.idx,c.b.idx);assert.equal(target.ctrl.idx,c.b.idx);await cast(c,c.a,'Disenchant',[aura]);assert.equal(source.ctrl.idx,c.a.idx);assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': indestructible grant follows its source duration and timestamp',async()=>{const c=make(role),target=put(M,c.game,c.a,'Grizzly Bears'),source=await cast(c,c.a,'Aegis Angel');assert.equal(target.kw('indestructible'),true);await cast(c,c.b,'Murder',[target]);assert.equal(target.zone,'battlefield');await cast(c,c.b,'Murder',[source]);assert.equal(target.kw('indestructible'),false);await cast(c,c.b,'Murder',[target]);assert.equal(target.zone,'graveyard');});
 test(role+': Extraction Specialist restricts the returned creature only',async()=>{const c=make(role),target=put(M,c.game,c.a,'Grizzly Bears','graveyard'),source=await cast(c,c.a,'Extraction Specialist');assert.equal(target.zone,'battlefield');assert.equal(target.cur.cantAttack,true);assert.equal(target.cur.cantBlock,true);assert.equal(source.cur.cantAttack,false);await cast(c,c.b,'Murder',[source]);assert.equal(target.cur.cantAttack,false);assert.equal(target.cur.cantBlock,false);});
 test(role+': Possession Engine restricts its captured target until source loss',async()=>{const c=make(role),{source,target}=await steal(c,'Possession Engine');assert.equal(target.cur.cantAttack,true);assert.equal(target.cur.cantBlock,true);await cast(c,c.b,'Disenchant',[source]);assert.equal(target.ctrl.idx,c.b.idx);assert.equal(target.cur.cantAttack,false);});
 test(role+': clone independently ends source-linked control after a real removal',async()=>{const c=make(role),{source,target}=await steal(c),game=M.cloneGameForAISimulation(c.game,73),other={...c,game,a:game.players[c.a.idx],b:game.players[c.b.idx]};game.priorityRound=async()=>{};game.reviewGlobalEffectWithHuman=async()=>{};await cast(other,other.b,'Murder',[game.byIid(source.iid)]);assert.equal(game.byIid(target.iid).ctrl.idx,other.b.idx);assert.equal(target.ctrl.idx,c.a.idx);});
 for(const name of['Quicksmith Spy','Quicksmith Rebel'])test(role+': '+name+' grants a real paid tap ability then loses it when phased',async()=>{const c=make(role),target=put(M,c.game,c.a,'Sol Ring'),source=await cast(c,c.a,name);const action=c.game.activatableList(c.a).find(e=>e.card===target&&e.ability);assert.ok(action);const before=name==='Quicksmith Spy'?c.a.hand.length:c.b.life;assert.equal(await c.game.activateAbility(c.a,action),true);await settle(c.game);assert.equal(name==='Quicksmith Spy'?c.a.hand.length:c.b.life,before+(name==='Quicksmith Spy'?1:-2));await cast(c,c.b,'Slip Out the Back',[source]);assert.equal(c.game.activatableList(c.a).some(e=>e.card===target&&e.ability),false);});
 for(const name of['Rubinia Soulsinger','Hivis of the Scale','Helm of Possession'])test(role+': '+name+' keeps its real tap duration and releases on untapping',async()=>{const c=make(role),target=put(M,c.game,c.b,'Shivan Dragon'),fodder=put(M,c.game,c.a,'Grizzly Bears'),source=await cast(c,c.a,name);source.sick=false;fund(c.a);const action=c.game.activatableList(c.a).find(e=>e.card===source&&e.ability);assert.ok(action);assert.equal(await c.game.activateAbility(c.a,action),true);await settle(c.game);assert.equal(source.tapped,true);assert.equal(target.ctrl.idx,c.a.idx);if(name==='Helm of Possession')assert.equal(fodder.zone,'graveyard');await cast(c,c.b,'Twiddle',[source]);assert.equal(source.tapped,false);assert.equal(target.ctrl.idx,c.b.idx);});
}
async function hawk(c,pending=false){const target=put(M,c.game,c.b,'Sol Ring'),source=await cast(c,c.a,'Pyreswipe Hawk');if(!c.a.isAI){const before=c.a.controller.decide.bind(c.a.controller);c.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.aiHint?.goal==='steal'&&q.candidates.includes(target)?[target]:before(g,q);}await cast(c,c.a,'Colossal Dreadmaw',[],false);const trigger=c.game.stack.find(s=>s.srcCard===source);assert.ok(trigger);assert.ok(trigger.targets[0]);if(!c.a.isAI)assert.equal(trigger.targets[0].iid,target.iid);const selected=trigger.targets[0];if(!pending)await settle(c.game);return{source,target:selected,trigger};}
for(const role of['human','ai']){
 test(role+': paid native Hawk immediately returns its artifact when control of Hawk changes',async()=>{const c=make(role),{source,target}=await hawk(c);assert.equal(target.ctrl.idx,c.a.idx);const aura=await cast(c,c.b,'Control Magic',[source]);assert.equal(target.ctrl.idx,c.b.idx);await cast(c,c.a,'Disenchant',[aura]);assert.equal(source.ctrl.idx,c.a.idx);assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': paid Murder before native Hawk trigger cannot start its already-ended duration',async()=>{const c=make(role),{source,target}=await hawk(c,true);await cast(c,c.b,'Murder',[source]);assert.equal(source.zone,'graveyard');assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': Hawk control return is automatic and does not create a counterable leave trigger',async()=>{const c=make(role),{source,target}=await hawk(c);await cast(c,c.b,'Murder',[source],false);await c.game.resolveTop();assert.equal(target.ctrl.idx,c.b.idx);assert.equal(c.game.stack.some(s=>s.srcCard===source),false);});
 test(role+': losing and regaining Hawk before its trigger resolves never restarts the old duration',async()=>{const c=make(role);await cast(c,c.b,'Vedalken Orrery');const {source,target}=await hawk(c,true),aura=await cast(c,c.b,'Control Magic',[source],false);await c.game.resolveTop();assert.equal(source.ctrl.idx,c.b.idx);await cast(c,c.b,'Disenchant',[aura]);assert.equal(source.ctrl.idx,c.a.idx);assert.equal(target.ctrl.idx,c.b.idx);});
 for(const name of['Amber Prison','Dungeon Geists'])test(role+': '+name+' loses its existing untap lock permanently on source phasing',async()=>{const c=make(role),target=put(M,c.game,c.b,'Colossal Dreadmaw'),source=await cast(c,c.a,name);if(name==='Amber Prison'){source.sick=false;fund(c.a);const action=c.game.activatableList(c.a).find(e=>e.card===source&&e.ability);assert.equal(await c.game.activateAbility(c.a,action),true);await settle(c.game);}assert.equal(target.cur.cantUntap,true);c.game.phaseOut(source);assert.equal(target.cur.cantUntap,false);c.game.phaseInFor(c.a);c.game.recalc();assert.equal(target.cur.cantUntap,false);});
}
test('human: native Hawk may legally select an artifact you already control',async()=>{const c=make('human'),target=put(M,c.game,c.a,'Sol Ring'),source=await cast(c,c.a,'Pyreswipe Hawk'),before=c.a.controller.decide.bind(c.a.controller);c.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.aiHint?.goal==='steal'&&q.candidates.includes(target)?[target]:before(g,q);await cast(c,c.a,'Colossal Dreadmaw',[],false);assert.equal(c.game.stack.find(s=>s.srcCard===source).targets[0]?.iid,target.iid);await settle(c.game);assert.equal(target.ctrl.idx,c.a.idx);});
for(const role of['human','ai']){
 test(role+': simultaneous source and target phasing ends the duration before either phases in',async()=>{const c=make(role),{source,target}=await steal(c);c.game.phaseOutMany([source,target]);assert.equal(c.game.untilEffects.some(e=>e.sourceDuration?.sourceIid===source.iid),false);c.game.phaseInFor(c.a);c.game.recalc();assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': a source phased out and back before its trigger resolves cannot renew the captured duration',async()=>{const c=make(role),target=put(M,c.game,c.b,'Colossal Dreadmaw'),source=await cast(c,c.a,'Mind Flayer',[],false);await c.game.resolveTop();await cast(c,c.b,'Slip Out the Back',[source],false);await c.game.resolveTop();assert.equal(source.phasedOut,true);c.game.phaseInFor(c.a);c.game.recalc();await settle(c.game);assert.equal(target.ctrl.idx,c.b.idx);});
 test(role+': taking a Mind Flayer immediately ends its own older control layer',async()=>{const c=make(role),third=c.game.addPlayer('C',{name:'C'},c.b.controller,false),target=put(M,c.game,third,'Grizzly Bears'),older=await cast(c,c.b,'Mind Flayer');assert.equal(target.ctrl.idx,c.b.idx);if(!c.a.isAI){const previous=c.a.controller.decide.bind(c.a.controller);c.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(older)?[older]:previous(g,q);}const newer=await cast(c,c.a,'Mind Flayer');assert.equal(older.ctrl.idx,c.a.idx);assert.equal(target.ctrl.idx,third.idx);await cast(c,c.b,'Murder',[newer]);assert.equal(older.ctrl.idx,c.b.idx);assert.equal(target.ctrl.idx,third.idx);});
}
for(const oracle_text of[
 'When this creature enters, gain control of target creature for as long as you control an unrelated creature.',
 'When this creature enters, gain control of target creature for as long as this creature is happy.',
 'When this creature enters, target creature gains indestructible for as long as you control Someone Else.',
 'When this creature enters, target creature gets +1/+1 for as long as you control this creature and win the game.',
 'When this creature enters, draw a card for as long as you control this creature.',
])test('duration compiler rejects incomplete or unrelated lifetime: '+oracle_text,()=>{assert.equal(semanticClass({name:'Closed Source',layout:'normal',type_line:'Creature — Wizard',mana_cost:'{U}',oracle_text}).semanticClass,undefined);});
