import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{loadEngine}from'./helpers/load-engine.mjs';import{context,settle}from'./helpers/oracle-v8-fixtures.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';import{proveWholeV30,fund,total,def,put,permanent,choose,cards,targets,source,activate}from'./helpers/oracle-v30-permanents-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v30-permanents.json',import.meta.url),'utf8')),M=loadEngine(),plan=createImportPlan({cards:rows,bulk:{type:'oracle_cards'},sequence:9983,limit:rows.length,compilerVersion:30});assert.equal(plan.report.cards.length,rows.length);const absent=plan.report.cards.filter(e=>!M.DEFS[e.raw.name]);if(absent.length)M.registerOracleBatch({...plan.report,cards:absent});M.initData(M.RAW_DATA);
test('30 complete source closure',()=>{for(const c of rows){assert.ok(semanticClass(c,{compilerVersion:30}).semanticClass,c.name);assert.equal(semanticClass({...c,oracle_text:c.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:30}).semanticClass,undefined,c.name);}});
for(const role of['human','ai'])for(const c of rows)test(role+': '+c.name+' actual paid whole source',async()=>{const f=context(M,role);f.role=role;await proveWholeV30(M,f,c.name,settle);});

const setup=async(role,name)=>{const f=context(M,role);f.role=role;fund(f.a);fund(f.b);const c=await source(M,f,name,settle);c.sick=false;return {...f,c};};
const edge=(name,run)=>{for(const role of['human','ai'])test(role+': '+name,async()=>{await run(role);});};
edge('Kalitas does not create a Vampire when destruction is prevented',async role=>{const f=await setup(role,'Kalitas, Bloodchief of Ghet'),{game:g,a,b,c}=f,q=permanent(M,g,b,def('Indestructible donor',['Creature'],{kws:['indestructible']}));targets(a,[q]);await activate(f,c,settle);assert.equal(q.zone,'battlefield');assert.equal(g.bf().filter(x=>x.isToken&&x.hasSub('Vampire')).length,0);assert.equal(c.tapped,true);});
edge('sequential Yeti damage uses reduced power after wither',async role=>{const f=await setup(role,'Karplusan Yeti'),{game:g,a,b,c}=f;await M.OracleV20.helpers.runGenericEffect({g,you:a,src:c,targets:[],sourceZoneVersion:c.zoneVersion},{action:'pump',target:'self',power:0,toughness:0,keywords:['wither']});const q=permanent(M,g,b,def('Wither target',['Creature'],{power:'5',toughness:'10'}));targets(a,[q]);await activate(f,c,settle);assert.equal(q.counters['-1/-1'],3);assert.equal(q.power,2);assert.equal(c.damage,2);});
edge('Durkwood source leaving stops its conditional damage',async role=>{const f=await setup(role,'Durkwood Tracker'),{game:g,a,b,c}=f,q=permanent(M,g,b,def('Attacking conditional target'));q.attacking=a;targets(a,[q]);const option=g.activatableList(a).find(x=>x.card===c&&!x.manaAbility);assert.equal(await g.activateAbility(a,option),true);await g.sacrifice(a,c);await settle(g);assert.equal(q.damage,0);assert.equal(c.zone,'graveyard');});
edge('Palazzo retains source power after leaving and protects planeswalkers',async role=>{const f=await setup(role,'Palazzo Archers'),{game:g,a,b,c}=f,pw=permanent(M,g,a,def('Protected walker',['Planeswalker'],{loyalty:4})),q=permanent(M,g,b,def('Flying walker attacker',['Creature'],{kws:['flying'],toughness:'12'}));await M.OracleV20.helpers.runGenericEffect({g,you:a,src:c,targets:[],sourceZoneVersion:c.zoneVersion},{action:'pump',target:'self',power:2,toughness:2,keywords:[]});const n=c.power;q.attacking=pw;await g.emit('attacks',{card:q,player:b,defender:pw});await g.sacrifice(a,c);await settle(g);assert.equal(q.damage,n);});
edge('Cube excludes Ooze and changeling and returns an undissolved exile',async role=>{const f=context(M,role);fund(f.a);const{game:g,a,b}=f,q=permanent(M,g,b,def('Legal non-Ooze')),ooze=permanent(M,g,b,def('Ooze donor',['Creature'],{subtypes:['Ooze']})),change=permanent(M,g,b,def('Changeling donor',['Creature'],{changeling:true}));targets(a,[q]);const c=await source(M,f,'Gelatinous Cube',settle),spec=c.def.triggers.find(x=>x.targets?.length).targets[0];assert.equal(g.legalTargets(spec,c,a).includes(ooze),false);assert.equal(g.legalTargets(spec,c,a).includes(change),false);assert.equal(q.zone,'exile');await g.sacrifice(a,c);await settle(g);assert.equal(q.zone,'battlefield');assert.equal(q.ctrl,b);});
edge('Nexus return ignores a changed exile incarnation',async role=>{const f=await setup(role,'Parallax Nexus'),{game:g,a,b,c}=f,q=put(M,b,def('Nexus changed incarnation'),'hand');targets(a,[b]);cards(b,[q]);await activate(f,c,settle);assert.equal(q.zone,'exile');await g.move(q,'hand');await g.move(q,'exile');await g.sacrifice(a,c);await settle(g);assert.equal(q.zone,'exile');});
edge('Priest leave ignores an exiled card that changed incarnation',async role=>{const f=context(M,role);fund(f.a);const{game:g,a,b}=f,q=put(M,b,def('Priest changed exile',['Instant'],{cost:'{4}'}),'hand');cards(a,[q]);targets(a,[b]);const c=await source(M,f,'Severance Priest',settle);assert.equal(q.zone,'exile');await g.move(q,'hand');await g.move(q,'exile');await g.sacrifice(a,c);await settle(g);assert.equal(g.bf().filter(x=>x.isToken&&x.hasSub('Spirit')).length,0);});
edge('Jester mismatched payment does not counter and copied ability does not pay again',async role=>{const f=context(M,role);fund(f.a);fund(f.b);const{game:g,a,b}=f,q=put(M,b,def('Paid mismatched name',['Instant']));for(let i=0;i<4;i++)put(M,b,'Forest');targets(a,[b]);const c=await source(M,f,"Jester's Scepter",settle);c.sick=false;const spell=put(M,b,def('Different spell name',['Instant'],{resolve:async()=>{b.mismatchResolved=true;}}),'hand');g.turnPlayer=b;assert.equal(await g.castSpell(b,spell,{from:'hand'}),true);targets(a,[g.stack.find(x=>x.card===spell)]);cards(a,[q]);const before=total(a),option=g.activatableList(a).find(x=>x.card===c&&!x.manaAbility);assert.equal(await g.activateAbility(a,option),true);const so=g.stack.at(-1);assert.ok(await g.copyStackAbility(so,a));assert.equal(total(a),before-2);assert.equal(q.zone,'graveyard');assert.equal(M.OracleV25Permanents.linked(g,c,'permanent-linked-v25').length,4);await settle(g);assert.equal(b.mismatchResolved,true);});
edge('colored combat ignores red and fires for a black attacker while blocking',async role=>{const f=await setup(role,'Serra Inquisitors'),{game:g,a,b,c}=f,red=permanent(M,g,b,def('Red attacker',['Creature'],{colorsOverride:['R']})),black=permanent(M,g,b,def('Black attacker',['Creature'],{colorsOverride:['B']})),n=c.power;await g.emit('blocks',{blocker:c,attacker:red});await settle(g);assert.equal(c.power,n);await g.emit('blocks',{blocker:c,attacker:black});await settle(g);assert.equal(c.power,n+2);});
edge('Recruiter leaves a large target uncontrolled without another Lizard',async role=>{const f=context(M,role);fund(f.a);const{game:g,a,b}=f,q=permanent(M,g,b,def('Large recruit target',['Creature'],{power:'5',toughness:'8'}));targets(a,[q]);await source(M,f,'Reptilian Recruiter',settle);assert.equal(q.ctrl,b);assert.equal(q.kw('haste'),false);});
edge('Recruiter can take a large target with another Lizard',async role=>{const f=context(M,role);fund(f.a);const{game:g,a,b}=f;permanent(M,g,a,def('Other Lizard',['Creature'],{subtypes:['Lizard']}));const q=permanent(M,g,b,def('Large recruit target',['Creature'],{power:'5',toughness:'8'}));g.tap(q);targets(a,[q]);await source(M,f,'Reptilian Recruiter',settle);assert.equal(q.ctrl,a);assert.equal(q.tapped,false);assert.equal(q.kw('haste'),true);});
edge('Cloudspire counts a dual Mount Vehicle once and retains departed entry history',async role=>{const f=await setup(role,'Cloudspire Coordinator'),{game:g,a,c}=f,q=put(M,a,def('Dual Mount Vehicle',['Artifact','Creature'],{subtypes:['Mount','Vehicle']}),'hand');await g.putPermanentOntoBattlefield(q,a);await g.sacrifice(a,q);await activate(f,c,settle);assert.equal(g.bf().filter(x=>x.isToken&&x.hasSub('Pilot')).length,1);});
edge('Tunnel intervening condition resets and retains a departed face-down entrant',async role=>{const f=await setup(role,'Tunnel Tipster'),{game:g,a,c}=f;for(const p of g.players)p.turnState=p.freshTurnState();await g.emit('endStep',{player:a});await settle(g);assert.equal(c.counters['+1/+1']||0,0);await M.OracleV20.helpers.runGenericEffect({g,you:a,src:c,targets:[],sourceZoneVersion:c.zoneVersion},{action:'face-down',kind:'manifest',who:'you',n:1});const entrant=g.bf().find(x=>x.ctrl===a&&x.faceDown);assert.ok(entrant);await g.sacrifice(a,entrant);await g.emit('endStep',{player:a});await settle(g);assert.equal(c.counters['+1/+1'],1);for(const p of g.players)p.turnState=p.freshTurnState();await g.emit('endStep',{player:a});await settle(g);assert.equal(c.counters['+1/+1'],1);});
edge('Fugitive own entry history resets and targeted spell filter excludes foreign targets',async role=>{const f=await setup(role,'Fugitive Droid'),{game:g,a,b,c}=f;assert.equal(c.cur.unblockable,true);for(const p of g.players)p.turnState=p.freshTurnState();g.recalc();assert.equal(c.cur.unblockable,false);const q=permanent(M,g,b,def('Foreign protected creature')),spell=put(M,b,def('Foreign-target spell',['Instant'],{targets:[M.T.creature()],resolve:async()=>{}}),'hand');g.turnPlayer=b;targets(b,[q]);assert.equal(await g.castSpell(b,spell,{from:'hand'}),true);const so=g.stack.find(x=>x.card===spell);assert.equal(g.legalTargets(c.def.abilities[0].targets[0],c,a).includes(so),false);await settle(g);});

test('30 linked consumers reject source text with acquisition removed',()=>{for(const name of["Jester's Scepter",'Severance Priest']){const c=rows.find(c=>c.name===name),changed={...c,oracle_text:c.oracle_text.split('\n').filter(line=>!line.startsWith('When ')||line.includes('leaves')).join('\n')};assert.equal(semanticClass(changed,{compilerVersion:30}).semanticClass,undefined,name);}});
