import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createOracleCompilerCache} from '../scripts/oracle-compiler-cache.mjs';

test('classification cache resumes exact rows and preserves descriptor values', t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'oracle-classification-'));
  t.after(() => fs.rmSync(directory, {recursive: true, force: true}));
  const compilerDirectory = path.join(directory, 'compiler');
  fs.mkdirSync(compilerDirectory);
  const grammar = path.join(compilerDirectory, 'oracle-example.mjs');
  fs.writeFileSync(grammar, 'version-one');
  const options = {directory: path.join(directory, 'cache'), compilerVersion: 31, compilerDirectory};
  const card = {name: 'Source', oracle_text: 'Draw a card.'};
  const result = {semanticClass: 'spell-template', implementation: [{max: Infinity, optional: undefined}]};
  const cache = createOracleCompilerCache(options);
  cache.set(card, result);
  const future = path.join(compilerDirectory, 'oracle-extensions-v32.mjs');
  fs.writeFileSync(future, 'a later additive grammar');
  assert.deepEqual(createOracleCompilerCache(options).get(card), result, 'later grammar does not change earlier compiler semantics');
  fs.writeFileSync(path.join(compilerDirectory, 'oracle-v31-common.mjs'), 'changed current grammar');
  assert.equal(createOracleCompilerCache(options).get(card), undefined, 'current-version grammar changes invalidate the cache');
  fs.rmSync(path.join(compilerDirectory, 'oracle-v31-common.mjs'));
  assert.deepEqual(createOracleCompilerCache(options).get(card), result);
  const clone = cache.get(card); clone.implementation.length = 0;
  assert.deepEqual(cache.get(card), result);
  assert.equal(cache.get({...card, oracle_text: 'Draw two cards.'}), undefined);
  assert.equal(createOracleCompilerCache({...options, compilerVersion: 30}).get(card), undefined);
  fs.writeFileSync(grammar, 'version-two');
  assert.equal(createOracleCompilerCache(options).get(card), undefined);
  fs.writeFileSync(grammar, 'version-one');
  const files = fs.readdirSync(options.directory, {recursive: true}).filter(name => name.endsWith('.bin'));
  fs.writeFileSync(path.join(options.directory, files[0]), 'interrupted bytes');
  assert.equal(createOracleCompilerCache(options).get(card), undefined);
  cache.set(card, {reason: 'unsupported-clause'});
  assert.deepEqual(cache.get(card), {reason: 'unsupported-clause'});
});
