import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {semanticClass} from '../scripts/import-oracle-batch.mjs';import {loadEngine} from './helpers/load-engine.mjs';import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
const M=loadEngine(),raw=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-creature-upgrade-source.json',import.meta.url))),entries=raw.map((card,i)=>{const parsed=semanticClass(card),types=card.type_line.split(' — ')[0].split(' ');assert.ok(parsed.semanticClass,card.name);return {position:i+1,oracleId:card.oracle_id,scryfallId:card.id,...parsed,raw:{name:card.name,oracle:card.oracle_text,cost:card.mana_cost,types:types.filter(t=>!['Legendary','Snow','Basic'].includes(t)),super:types.filter(t=>['Legendary','Snow','Basic'].includes(t)),subtypes:card.type_line.split(' — ')[1]?.split(' ')||[],power:card.power,toughness:card.toughness,_ci:card.color_identity},catalog:{typeLine:card.type_line,commanderLegality:'legal'}};});
M.registerOracleBatch({id:'creature-upgrade-source-draft',sequence:9992,cards:entries.filter(e=>!M.DEFS[e.raw.name])});M.initData(M.RAW_DATA);
const fund=p=>{for(const c of ['W','U','B','R','G','C'])p.pool[c]=100;},total=p=>Object.values(p.pool).reduce((n,v)=>n+v,0);
function setup(role,opponents=1){const ctx=context(M,role,opponents);ctx.choice={tribute:'yes'};for(const p of ctx.game.players){const decide=p.controller.decide.bind(p.controller);p.controller.decide=async(g,q)=>{if(p!==ctx.a&&q.aiHint?.kind==='tribute'){ctx.trace.push({q,result:ctx.choice.tribute,by:p});return ctx.choice.tribute;}if(role==='human'&&p===ctx.a&&q.type==='chooseX')return 3;if(role==='human'&&p===ctx.a&&q.type==='chooseTargets')return q.candidates.filter(c=>c!==ctx.a&&c.ctrl!==ctx.a).slice(0,q.max||q.min||1);return decide(g,q);};}return ctx;}
async function cast(ctx,name){fund(ctx.a);const card=put(M,ctx.game,ctx.a,name,'hand'),before=total(ctx.a);assert.equal(await ctx.game.castSpell(ctx.a,card,{from:'hand'}),true);await settle(ctx.game);assert.ok(total(ctx.a)<before);return card;}
async function activate(ctx,card,{settled=true}={}){fund(ctx.a);const ability=ctx.game.activatableList(ctx.a).find(row=>row.card===card&&row.ability.oracleCompiled),before=total(ctx.a);assert.ok(ability,card.name);assert.equal(await ctx.game.activateAbility(ctx.a,ability),true);assert.ok(total(ctx.a)<before);if(settled)await settle(ctx.game);return ability;}
for(const role of ['human','ai']){
 for(const entry of entries)test(`${role}: ${entry.raw.name} uses its paid source and real upgrade process`,async()=>{const ctx=setup(role),{game,a,b}=ctx;for(const p of [a,b])for(let i=0;i<3;i++)put(M,game,p,'Forest');put(M,game,b,'Serra Angel');put(M,game,b,'Sol Ring');const source=await cast(ctx,entry.raw.name),tribute=entry.implementation.find(o=>o.kind==='creature-upgrade-entry-v8');if(tribute){assert.equal(source.meta.oracleTributePaid,true);assert.equal(source.counters['+1/+1'],tribute.n);assert.ok(ctx.trace.some(row=>row.q.aiHint?.kind==='tributeOpponent'));assert.ok(ctx.trace.some(row=>row.q.aiHint?.kind==='tribute'&&row.by===b));}else{const upgrade=entry.implementation.find(o=>o.kind==='generic-ability'&&o.effects.some(e=>e.action==='monstrosity-v8'));assert.ok(upgrade);const seen=[],emit=game.emit.bind(game);game.emit=async(event,data)=>{if(event==='monstrous')seen.push(data);return emit(event,data);};await activate(ctx,source);assert.equal(source.meta.oracleMonstrous,true);const n=upgrade.effects[0].n==='X'?source.meta.oracleMonstrosityX:upgrade.effects[0].n;assert.equal(source.counters['+1/+1'],n);assert.equal(seen.length,1);assert.equal(seen[0].card,source);assert.equal(seen[0].x,n);if(source.zone==='battlefield'){const counters=source.counters['+1/+1'];await activate(ctx,source);assert.equal(source.counters['+1/+1'],counters);assert.equal(seen.length,1);}}assert.equal((game.aiDecisionLog||[]).some(row=>row.fallback),false);});
 test(`${role}: paid Monstrosity survives loss of counters, phasing and abilities, then blink resets its designation`,async()=>{const ctx=setup(role),{game,a,b}=ctx,source=await cast(ctx,'Fleecemane Lion');await activate(ctx,source);assert.equal(source.kw('hexproof'),true);assert.equal(source.kw('indestructible'),true);game.removeCounters(source,'+1/+1',1);assert.equal(source.meta.oracleMonstrous,true);await activate(ctx,source);assert.equal(source.counters['+1/+1']||0,0);game.phaseOut(source);game.phaseInFor(a);assert.equal(source.meta.oracleMonstrous,true);const aura=put(M,game,a,'Lignify','hand');await game.move(aura,'battlefield',{attachTo:source});assert.equal(source.cur.abilitiesDisabled,true);assert.equal(source.meta.oracleMonstrous,true);await game.move(aura,'graveyard');assert.equal(source.kw('hexproof'),true);const version=source.zoneVersion;await game.move(source,'exile');await game.putPermanentOntoBattlefield(source,a);assert.ok(source.zoneVersion>version);assert.equal(!!source.meta.oracleMonstrous,false);assert.equal(source.kw('hexproof'),false);await activate(ctx,source);assert.equal(source.counters['+1/+1'],1);});
 test(`${role}: a paid pending Monstrosity cannot modify a phased or blinked source`,async()=>{for(const mode of ['phase','blink']){const ctx=setup(role),{game,a}=ctx,source=await cast(ctx,'Ill-Tempered Cyclops');await activate(ctx,source,{settled:false});if(mode==='phase')game.phaseOut(source);else{await game.move(source,'exile');await game.putPermanentOntoBattlefield(source,a);}await settle(game);assert.equal(!!source.meta.oracleMonstrous,false);assert.equal(source.counters['+1/+1']||0,0);}});
 test(`${role}: competing paid Monstrosity abilities resolve once in Stack order`,async()=>{const ctx=setup(role),source=await cast(ctx,'Ill-Tempered Cyclops');await activate(ctx,source,{settled:false});await activate(ctx,source,{settled:false});assert.equal(ctx.game.stack.length,2);await settle(ctx.game);assert.equal(source.counters['+1/+1'],3);});
 test(`${role}: zero X still becomes monstrous and Hardened Scales does not change the remembered X`,async()=>{for(const x of [0,2]){const ctx=setup(role),{game,a}=ctx;await cast(ctx,'Hardened Scales');const source=await cast(ctx,'Hydra Broodmaster'),decide=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>q.type==='chooseX'?x:decide(g,q);await activate(ctx,source);assert.equal(source.meta.oracleMonstrous,true);assert.equal(source.meta.oracleMonstrosityX,x);assert.equal(source.counters['+1/+1']||0,x?x+1:0);const hydras=game.bf().filter(c=>c.isToken&&c.hasSub('Hydra'));assert.equal(hydras.length,x);for(const token of hydras){assert.equal(token.power,x);assert.equal(token.toughness,x);}}});
 test(`${role}: copied Slime tokens have neither the designation nor the counters, while saves and local AI clones retain the original`,async()=>{const ctx=setup(role),{game,a}=ctx,source=await cast(ctx,'Splitting Slime');await activate(ctx,source);const token=game.bf().find(card=>card!==source&&card.name===source.name);assert.ok(token?.isToken);assert.equal(!!token.meta.oracleMonstrous,false);assert.equal(token.counters['+1/+1']||0,0);const clone=M.cloneGameForAISimulation(game,72);assert.equal(clone.byIid(source.iid).meta.oracleMonstrous,true);assert.equal(clone.byIid(token.iid).meta.oracleMonstrous,undefined);const saved=M.captureGameState(game);assert.ok(saved,JSON.stringify(M.gameStateSnapshotBlockers(game)));const restored=setup(role).game;M.restoreGameState(restored,JSON.parse(JSON.stringify(saved)));assert.equal(restored.byIid(source.iid).meta.oracleMonstrous,true);assert.equal(restored.byIid(token.iid).meta.oracleMonstrous,undefined);await activate(ctx,token);assert.equal(token.counters['+1/+1'],3);});
 test(`${role}: unpaid Tribute triggers belong to the entering incarnation even if it blinks before resolution`,async()=>{const ctx=setup(role),{game,a}=ctx;ctx.choice.tribute='no';fund(a);const source=put(M,game,a,'Snake of the Golden Grove','hand'),life=a.life;assert.equal(await game.castSpell(a,source,{from:'hand'}),true);await game.resolveTop();assert.equal(source.meta.oracleTributePaid,false);await game.flushTriggers();assert.equal(game.stack.length,1);ctx.choice.tribute='yes';await game.move(source,'exile');await game.putPermanentOntoBattlefield(source,a);assert.equal(source.meta.oracleTributePaid,true);await settle(game);assert.equal(a.life,life+4);assert.equal(source.counters['+1/+1'],3);});
 test(`${role}: Tribute opponent is selected from the actual living opponents and the entrant is absent during its choice`,async()=>{const ctx=setup(role,2),{game,a,others}=ctx,decide=a.controller.decide.bind(a.controller);if(role==='human')a.controller.decide=async(g,q)=>q.aiHint?.kind==='tributeOpponent'?String(others[1].idx):decide(g,q);for(const opponent of others){const decide=opponent.controller.decide.bind(opponent.controller);opponent.controller.decide=async(g,q)=>{if(q.aiHint?.kind==='tribute'){assert.equal(game.bf().includes(q.aiHint.source),false);assert.equal(q.aiHint.source.counters['+1/+1']||0,0);}return decide(g,q);};}const card=await cast(ctx,'Ornitharch'),selected=ctx.trace.find(r=>r.q.aiHint?.kind==='tribute');assert.ok(others.includes(selected.by));if(role==='human')assert.equal(selected.by,others[1]);assert.equal(card.counters['+1/+1'],2);});
 test(`${role}: Tribute and other entry counters merge before Hardened Scales applies once`,async()=>{const ctx=setup(role),{game,a}=ctx;await cast(ctx,'Hardened Scales');await cast(ctx,'Thunderous Velocipede');const card=await cast(ctx,'Ornitharch');assert.equal(card.counters['+1/+1'],6);assert.equal(card.meta.oracleTributePaid,true);});
 test(`${role}: a real local AI chooses whether to pay an opponent's Tribute`,async()=>{const ctx=setup(role),{game,b}=ctx;b.controller=new M.AIController(b,{difficulty:'hard',style:'balanced'});const card=await cast(ctx,'Pharagax Giant');assert.equal(typeof card.meta.oracleTributePaid,'boolean');assert.equal(card.counters['+1/+1']||0,card.meta.oracleTributePaid?2:0);assert.equal(b.life,card.meta.oracleTributePaid?40:35);assert.equal((game.aiDecisionLog||[]).some(row=>row.fallback),false);});
}
test('creature upgrade descriptors fail closed for unsupported state and entry operations',()=>{for(const operation of [{kind:'creature-upgrade-entry-v8',mode:'tribute',n:0,contract:'creature-upgrade-status'},{kind:'creature-upgrade-entry-v8',mode:'tribute',n:2,contract:'creature-upgrade-status',freeDraw:true}])assert.throws(()=>M.OracleV8CreatureUpgrades.compile(operation));});
