import fs from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createFixturePlan,registerCanonicalFixturePlan} from './helpers/oracle-fixture-plan.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {names,proveCommonV74} from './helpers/oracle-v74-common-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v74-common.json',import.meta.url)));
const plan=createFixturePlan(rows,74,9974),M=loadEngine();registerCanonicalFixturePlan(M,plan);
test('v74 exact complete source rows reject appended unsupported instructions',()=>{for(const row of rows)assert.equal(plan.classify({...row,oracle_text:row.oracle_text+'\nPerform an unsupported action.'}).semanticClass,undefined,row.name);});
for(const role of ['human','ai'])for(const name of names)for(const positive of [true,false])test(`${role}: ${name} ${positive}`,()=>proveCommonV74(M,name,role,positive));
