import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import{loadEngine}from'./helpers/load-engine.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';
const M=loadEngine(),sources=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-name-groups-source.json',import.meta.url)));
for(const card of sources)assert.ok(semanticClass(card).semanticClass,card.name+': whole source compiles');
const missing=sources.filter(c=>!M.DEFS[c.name]);if(missing.length){const {report}=createImportPlan({cards:missing,baseNames:new Set(),bulk:{type:'oracle_cards',updated_at:'2026-08-30T09:01:56.964+00:00'},limit:missing.length,sequence:9995,compilerVersion:8});M.registerOracleBatch(report);M.initData(M.RAW_DATA);}
async function cast(c,name,{resolve=true}={}){const card=put(M,c.game,c.a,name,'hand');for(const color of'WUBRGC')c.a.pool[color]=20;assert.equal(await c.game.castSpell(c.a,card,{from:'hand'}),true);assert.ok(c.game.stack.some(s=>s.card===card));if(resolve)await settle(c.game);return card;}
for(const role of['human','ai']){
 for(const response of ['Cloudshift','Heroic Intervention'])test(role+': '+response+' invalidates the sole named-group target before resolution',async()=>{
  const c=context(M,role),first=put(M,c.game,c.b,'Grizzly Bears'),second=put(M,c.game,c.b,'Grizzly Bears'),spell=await cast(c,'Sever the Bloodline',{resolve:false}),target=c.game.stack.find(s=>s.card===spell).targets.flat()[0],version=target.zoneVersion;
  const original=c.b.controller.decide.bind(c.b.controller);c.b.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(target)?[target]:original(g,q);await cast({...c,a:c.b},response);assert.equal(first.zone,'battlefield');assert.equal(second.zone,'battlefield');assert.equal(spell.zone,'graveyard');if(response==='Cloudshift')assert.ok(target.zoneVersion>version);
 });
 test(role+': an untargeted same-name copy is exiled even with real equipped hexproof',async()=>{
  const c=context(M,role),first=put(M,c.game,c.b,'Grizzly Bears'),[copy]=await c.game.copyPermanentToken(first,c.b);c.game.turnPlayer=c.b;const boots=await cast({...c,a:c.b},'Swiftfoot Boots');
  const original=c.b.controller.decide.bind(c.b.controller);c.b.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(copy)?[copy]:original(g,q);const equip=c.game.activatableList(c.b).find(e=>e.card===boots&&e.equip);assert.ok(equip);assert.equal(await c.game.activateAbility(c.b,equip),true);await settle(c.game);assert.ok(copy.kw('hexproof'));c.game.turnPlayer=c.a;await cast(c,'Sever the Bloodline');assert.equal(first.zone,'exile');assert.equal(copy.zone,'ceased');
 });
 test(role+': the group uses the target name at resolution after a paid Mirrorweave response',async()=>{
  const c=context(M,role),first=put(M,c.game,c.b,'Grizzly Bears'),second=put(M,c.game,c.b,'Grizzly Bears'),model=put(M,c.game,c.a,'Colossal Dreadmaw');await cast(c,'Sever the Bloodline',{resolve:false});
  const original=c.b.controller.decide.bind(c.b.controller);c.b.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(model)?[model]:original(g,q);await cast({...c,a:c.b},'Mirrorweave');for(const card of [first,second,model])assert.equal(card.zone,'exile');
 });
 test(role+': a removed Sunsinger still uses its last battlefield name for its resolving paid group ability',async()=>{
  const c=context(M,role),source=await cast(c,'Cylian Sunsinger'),[copy]=await c.game.copyPermanentToken(source,c.b);for(const color of'WUBRGC')c.a.pool[color]=20;const entry=c.game.activatableList(c.a).find(e=>e.card===source);assert.equal(await c.game.activateAbility(c.a,entry),true);
  const original=c.b.controller.decide.bind(c.b.controller);c.b.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(source)?[source]:original(g,q);await cast({...c,a:c.b},'Murder');assert.equal(source.zone,'graveyard');assert.equal(copy.power,5);assert.equal(copy.toughness,5);
 });
 for(const name of ['Bile Blight','Echoing Decay','Homing Lightning','Sever the Bloodline'])test(role+': '+name+' affects every same-name creature through its paid spell',async()=>{
  const c=context(M,role),[first,second]=await c.game.makeTokens('soldierW',c.b,{n:2}),[different]=await c.game.makeTokens('goblin',c.b);await cast(c,name);assert.equal(first.zone,'ceased');assert.equal(second.zone,'ceased');assert.equal(different.zone,'battlefield');
 });
 test(role+': Echoing Courage applies its boost to matching creatures controlled by either player',async()=>{const c=context(M,role),[first]=await c.game.makeTokens('soldierW',c.a),[second]=await c.game.makeTokens('soldierW',c.b),different=put(M,c.game,c.a,'Sol Ring');await cast(c,'Echoing Courage');assert.equal(first.power,3);assert.equal(second.power,3);assert.equal(different.zone,'battlefield');});
 for(const [name,key,permanent]of [['Echoing Ruin','treasure','Sol Ring'],['Echoing Calm',null,'Ghostly Prison'],['Wake of Destruction',null,'Forest']])test(role+': '+name+' uses a single fixed group across both controllers',async()=>{
  const c=context(M,role),model=put(M,c.game,c.b,permanent),[copy]=await c.game.copyPermanentToken(model,c.b),[own]=await c.game.copyPermanentToken(model,c.a),other=put(M,c.game,c.b,'Island');await cast(c,name);assert.equal(model.zone,'graveyard');assert.equal(copy.zone,'ceased');assert.equal(own.zone,'ceased');assert.equal(other.zone,'battlefield');
 });
 test(role+': Legions to Ashes exiles target plus matching tokens only for that target controller',async()=>{const c=context(M,role),model=put(M,c.game,c.b,'Sol Ring'),[copy]=await c.game.copyPermanentToken(model,c.b),[own]=await c.game.copyPermanentToken(model,c.a);await cast(c,'Legions to Ashes');assert.equal(model.zone,'exile');assert.equal(copy.zone,'ceased');assert.equal(own.zone,'battlefield');});
 test(role+': Echoing Return uses only your graveyard and returns every card sharing the target name',async()=>{const c=context(M,role),first=put(M,c.game,c.a,'Grizzly Bears','graveyard'),second=put(M,c.game,c.a,'Grizzly Bears','graveyard'),enemy=put(M,c.game,c.b,'Grizzly Bears','graveyard'),different=put(M,c.game,c.a,'Forest','graveyard');await cast(c,'Echoing Return');assert.equal(first.zone,'hand');assert.equal(second.zone,'hand');assert.equal(enemy.zone,'graveyard');assert.equal(different.zone,'graveyard');});
 test(role+': paid Izzet Staticaster tap activation deals one simultaneous damage to every matching creature',async()=>{const c=context(M,role),source=await cast(c,'Izzet Staticaster'),victims=await c.game.makeTokens('soldierW',c.b,{n:2}),[different]=await c.game.makeTokens('goblin',c.b);source.sick=false;if(role==='human'){const decide=c.a.controller.decide.bind(c.a.controller);c.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(victims[0])?[victims[0]]:decide(g,q);}const entry=c.game.activatableList(c.a).find(e=>e.card===source);assert.ok(entry);assert.equal(await c.game.activateAbility(c.a,entry),true);assert.equal(source.tapped,true);await settle(c.game);assert.ok(victims.every(c=>c.zone==='ceased'));assert.equal(different.zone,'battlefield');});
 test(role+': paid Cylian Sunsinger activation boosts same-name creatures across controllers',async()=>{const c=context(M,role),source=await cast(c,'Cylian Sunsinger'),[copy]=await c.game.copyPermanentToken(source,c.b),different=put(M,c.game,c.a,'Grizzly Bears');for(const color of'WUBRGC')c.a.pool[color]=20;const entry=c.game.activatableList(c.a).find(e=>e.card===source);assert.ok(entry);assert.equal(await c.game.activateAbility(c.a,entry),true);await settle(c.game);assert.equal(source.power,5);assert.equal(copy.power,5);assert.equal(different.power,2);});
 test(role+': Rat King pays three real Rat sacrifices and returns matching cards tapped together',async()=>{const c=context(M,role),source=await cast(c,'Rat King, Verminister'),rats=await c.game.makeTokens('rat',c.a,{n:3}),first=put(M,c.game,c.a,'Grizzly Bears','graveyard'),second=put(M,c.game,c.a,'Grizzly Bears','graveyard');source.sick=false;if(role==='human'){const decide=c.a.controller.decide.bind(c.a.controller);c.a.controller.decide=(g,q)=>q.type==='chooseCards'&&rats.every(card=>q.from.includes(card))?rats:decide(g,q);}const entry=c.game.activatableList(c.a).find(e=>e.card===source);assert.ok(entry);assert.equal(await c.game.activateAbility(c.a,entry),true);assert.ok(rats.every(c=>c.zone==='ceased'));await settle(c.game);assert.equal(first.zone,'battlefield');assert.equal(second.zone,'battlefield');assert.equal(first.tapped,true);assert.equal(second.tapped,true);});
 test(role+': paid Raise the Alarm gives unnamed tokens the printed-subtypes-plus-Token name',async()=>{const c=context(M,role);await cast(c,'Raise the Alarm');const made=c.game.bf().filter(c=>c.isToken);assert.equal(made.length,2);for(const token of made){assert.equal(token.name,'Soldier Token');assert.ok(token.hasSub('Soldier'));assert.equal(token.hasSub('Token'),false);}});
 test(role+': keyed named tokens and copies preserve their exact names',async()=>{const c=context(M,role);for(const [key,name]of[['treasure','Treasure Token'],['germ','Phyrexian Germ Token'],['kobold','Kobolds of Kher Keep'],['lightningRager','Lightning Rager'],['serpentKoma',"Koma's Coil"],['stormCrow','Storm Crow']]){const [card]=await c.game.makeTokens(key,c.a);assert.equal(card.name,name);}const bear=put(M,c.game,c.a,'Grizzly Bears'),[copy]=await c.game.copyPermanentToken(bear,c.a);assert.equal(copy.name,'Grizzly Bears');const [explicit]=await c.game.makeTokens({name:'Soldier',explicitTokenName:true,cost:null,super:[],types:['Creature'],subtypes:['Soldier'],power:'1',toughness:'1',kws:[]},c.a);assert.equal(explicit.name,'Soldier');});
 test(role+': save and AI clone retain the canonical keyed name and executable Treasure mana ability',async()=>{const c=context(M,role),[token]=await c.game.makeTokens('treasure',c.a);const clone=M.cloneGameForAISimulation(c.game,53);assert.equal(clone.byIid(token.iid).name,'Treasure Token');assert.ok(clone.byIid(token.iid).def.mana);const data=M.captureGameState(c.game);assert.ok(data);const fresh=context(M,role);M.restoreGameState(fresh.game,JSON.parse(JSON.stringify(data)));const restored=fresh.game.byIid(token.iid);assert.equal(restored.name,'Treasure Token');assert.ok(restored.def.mana);for(const color of'WUBRGC')restored.ctrl.pool[color]=0;assert.equal(await fresh.game.payMana(restored.ctrl,M.parseCost('{U}')),true);assert.equal(restored.zone,'ceased');assert.equal(token.zone,'battlefield');});
 test(role+': actual Echoing Truth matches a default named token and leaves the explicitly named same-subtype token',async()=>{const c=context(M,role);await cast(c,'Raise the Alarm');const ordinary=c.game.bf().filter(c=>c.isToken),[explicit]=await c.game.makeTokens({name:'Soldier',explicitTokenName:true,cost:null,super:[],types:['Creature'],subtypes:['Soldier'],power:'1',toughness:'1',kws:[]},c.b);for(const token of ordinary){token.ctrl=c.b;}c.game.recalc();if(role==='human'){const decide=c.a.controller.decide.bind(c.a.controller);c.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(ordinary[0])?[ordinary[0]]:decide(g,q);}await cast(c,'Echoing Truth');assert.ok(ordinary.every(c=>c.zone==='ceased'));assert.equal(explicit.zone,'battlefield');});
}
