import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v20-costs.json',import.meta.url),'utf8'));
// A focused runtime regression may load an explicit fixture subset; the default
// suite still compiles and checks every pinned card below.
const requested=process.env.ORACLE_V20_COSTS_FIXTURES?new Set(JSON.parse(process.env.ORACLE_V20_COSTS_FIXTURES)):null;
if(requested)for(const name of requested)assert.ok(rows.some(card=>card.name===name),'Unknown requested v20 fixture: '+name);
const M=loadEngine(),absent=rows.filter(c=>(!requested||requested.has(c.name))&&!M.DEFS[c.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9940,limit:absent.length,compilerVersion:20});assert.equal(plan.report.cards.length,absent.length);M.registerOracleBatch(plan.report);M.initData(M.RAW_DATA);}
function choice(p,fn){const previous=p.controller.decide.bind(p.controller);p.controller.decide=async(g,q)=>(await fn(g,q))??previous(g,q);}
function fund(p){for(const c of ['W','U','B','R','G','C'])p.pool[c]=40;}
test('v20 cost cards consume every rule, reject an unknown suffix, and retain v19 descriptors',()=>{
 for(const c of rows){assert.ok(semanticClass(c,{compilerVersion:20}).semanticClass,c.name);const bad=c.card_faces?{...c,card_faces:c.card_faces.map((f,i)=>i?f:{...f,oracle_text:f.oracle_text+'\nDo an unsupported thing.'})}:{...c,oracle_text:c.oracle_text+'\nDo an unsupported thing.'};assert.equal(semanticClass(bad,{compilerVersion:20}).semanticClass,undefined,c.name);const frozen=semanticClass(c,{compilerVersion:19});if(frozen.semanticClass)assert.deepEqual(semanticClass(c,{compilerVersion:20}),frozen,c.name);}
});
for(const role of ['human','ai']){
 test(role+': Bargaining Table fixes X to the chosen opponent hand and supports zero',async()=>{
  const {game,a,b,others}=context(M,role,2),source=put(M,game,a,'Bargaining Table'),other=others[1];put(M,game,b,'Forest','hand');put(M,game,b,'Forest','hand');put(M,game,b,'Forest','hand');let opponent=other;choice(a,(g,q)=>q.aiHint?.kind==='oracleOpponentCostXV20'?String(opponent.idx):undefined);const action=()=>game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleOperation?.fixedXCostV20);const hand=a.hand.length;assert.ok(action());assert.equal(await game.activateAbility(a,action()),true);assert.equal(game.stack.find(row=>row.srcCard===source).ctx.x,0);await settle(game);assert.equal(a.hand.length,hand+1);game.untap(source);opponent=b;a.pool.C=2;assert.equal(await game.activateAbility(a,action()),false);assert.equal(source.tapped,false);assert.equal(a.pool.C,2);a.pool.C=3;assert.equal(await game.activateAbility(a,action()),true);assert.equal(a.pool.C,0);assert.equal(game.stack.find(row=>row.srcCard===source).ctx.x,3);await settle(game);assert.equal(a.hand.length,hand+2);assertGameStateInvariants(game);
 });
 test(role+': Bargaining Table applies ordinary activation reductions after fixing X',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Bargaining Table'),reducer=put(M,game,a,'Grizzly Bears');reducer.def={...reducer.def,abilityCostReduction:()=>2};game.recalc();for(let i=0;i<3;i++)put(M,game,b,'Forest','hand');a.pool.C=1;choice(a,(g,q)=>q.aiHint?.kind==='oracleOpponentCostXV20'?String(b.idx):undefined);const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleOperation?.fixedXCostV20);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.C,0);assert.equal(game.stack.find(row=>row.srcCard===source).ctx.x,3);await settle(game);assert.equal(a.hand.length,1);assertGameStateInvariants(game);
 });
 test(role+': Torrent Elemental has no activation while exiled face down',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Torrent Elemental','hand');fund(a);await game.move(source,'exile',{exileFaceDown:true});assert.equal(source.faceDown,true);assert.equal(game.activatableList(a).some(row=>row.card===source&&row.gyAbility),false);assert.equal(await game.activateAbility(a,{card:source,gyAbility:true,gyAbilityOverride:source.def.oracleExileAbilityV20}),false);assert.equal(game.stack.length,0);assertGameStateInvariants(game);
 });
 test(role+': Torrent Elemental activates only from exile at sorcery timing',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Torrent Elemental','graveyard');fund(a);const action=()=>game.activatableList(a).find(row=>row.card===source&&row.gyAbilityOverride?.oracleFromZoneV20==='exile');assert.equal(!!action(),false);await game.move(source,'exile');game.phase='combat';assert.equal(!!action(),false);game.phase='main1';assert.ok(action());game.turnPlayer=b;assert.equal(!!action(),false);game.turnPlayer=a;const before=Object.values(a.pool).reduce((n,x)=>n+x,0);assert.equal(await game.activateAbility(a,action()),true);assert.equal(before-Object.values(a.pool).reduce((n,x)=>n+x,0),5);assert.equal(source.zone,'exile');await settle(game);assert.equal(source.zone,'battlefield');assert.equal(source.tapped,true);assertGameStateInvariants(game);
 });
 test(role+': countered Torrent Elemental stays exiled and a new incarnation cannot return',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Torrent Elemental','exile');fund(a);const action=()=>game.activatableList(a).find(row=>row.card===source&&row.gyAbilityOverride?.oracleFromZoneV20==='exile');assert.equal(await game.activateAbility(a,action()),true);assert.equal(await game.counterStackObject(game.stack.find(row=>row.srcCard===source)),true);await settle(game);assert.equal(source.zone,'exile');assert.equal(await game.activateAbility(a,action()),true);await game.move(source,'graveyard');await game.move(source,'exile');await settle(game);assert.equal(source.zone,'exile');assertGameStateInvariants(game);
 });
 test(role+': Crypt Rats generic X cannot consume Jegantha colored-only black mana',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Crypt Rats'),jegantha=put(M,game,a,'Jegantha, the Wellspring');const ability=game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.manaXColorsV20).ability,cost=game.abilityManaCost(a,source,ability.cost.mana,{ability});assert.equal(game.canPayMana(a,cost,{card:source,isAbility:true,ability},{xVal:1}),false,'automatic Jegantha mana remains generic-ineligible');assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===jegantha&&row.manaAbility)),true);assert.equal(a.pool.B,1);assert.equal(a.coloredOnlyPool.B,1);assert.equal(game.canPayMana(a,cost,{card:source,isAbility:true,ability},{xVal:1}),false,'floating Jegantha mana remains generic-ineligible');choice(a,(g,q)=>q.type==='chooseX'?1:undefined);assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.manaXColorsV20)),false);a.pool.B++;assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.manaXColorsV20)),true);assert.equal(a.pool.B,1);assert.equal(a.coloredOnlyPool.B,1);await settle(game);assertGameStateInvariants(game);
 });
 test(role+': Crypt Rats applies Training Grounds to generic X and still requires black payment',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Crypt Rats');put(M,game,a,'Training Grounds');a.pool.B=1;a.pool.C=5;choice(a,(g,q)=>q.type==='chooseX'?3:undefined);const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.manaXColorsV20),life=b.life;assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.B,0);assert.equal(a.pool.C,5);assert.equal(game.stack.find(row=>row.srcCard===source).ctx.x,3);await settle(game);assert.equal(b.life,life-3);assert.equal(source.zone,'graveyard');assertGameStateInvariants(game);
 });
 test(role+': Crypt Rats generic X is not a black mana symbol for Krrik life payment',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Crypt Rats');put(M,game,a,"K'rrik, Son of Yawgmoth");const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.manaXColorsV20),cost=game.abilityManaCost(a,source,action.ability.cost.mana,{ability:action.ability});assert.equal(game.canPayMana(a,cost,{card:source,isAbility:true,ability:action.ability},{xVal:1}),false);assert.equal(a.life,40);assertGameStateInvariants(game);
 });
 test(role+': restricted X uses real black mana even with color flexibility',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Crypt Rats'),orrery=put(M,game,a,'Chromatic Orrery');orrery.tapped=true;a.pool.C=4;const action=()=>game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.manaXColorsV20),ability=action().ability,cost=game.abilityManaCost(a,source,ability.cost.mana,{ability});assert.equal(game.canPayMana(a,cost,{card:source,isAbility:true,ability},{xVal:2}),false);choice(a,(g,q)=>q.type==='chooseX'?2:undefined);assert.equal(await game.activateAbility(a,action()),false);assert.equal(a.pool.C,4);a.pool.B=2;const life=b.life;assert.equal(await game.activateAbility(a,action()),true);assert.equal(a.pool.B,0);assert.equal(a.pool.C,4);await settle(game);assert.equal(b.life,life-2);assert.equal(source.zone,'graveyard');assertGameStateInvariants(game);
 });
 test(role+': Consume Spirit preserves its fixed cost and can cast with zero restricted X',async()=>{
  const {game,a,b}=context(M,role),spell=put(M,game,a,'Consume Spirit','hand');a.pool.C=1;a.pool.B=1;choice(a,(g,q)=>q.type==='chooseX'?0:q.type==='chooseTargets'?[b]:undefined);const life=b.life;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(a.pool.C+a.pool.B,0);assert.equal(game.stack.find(row=>row.card===spell).x,0);await settle(game);assert.equal(b.life,life);assertGameStateInvariants(game);
 });
 test(role+': Bloodthorn Flail pays either mana or a discarded card through one equip action',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Bloodthorn Flail'),first=put(M,game,a,'Grizzly Bears'),second=put(M,game,a,'Grizzly Bears');let discard=false;const card=put(M,game,a,'Forest','hand');choice(a,(g,q)=>q.type==='chooseTargets'?[discard?second:first]:q.aiHint?.kind==='oracleEquipChoiceV20'?(discard?'discard':'mana'):q.type==='chooseCards'&&q.from?.includes(card)?[card]:undefined);a.pool.C=3;const action=()=>game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleEquip);assert.equal(game.activatableList(a).filter(row=>row.card===source&&row.ability?.oracleEquip).length,1);assert.equal(await game.activateAbility(a,action()),true);assert.equal(a.pool.C,0);assert.equal(card.zone,'hand');await settle(game);assert.equal(source.attachedTo,first.iid);discard=true;assert.ok(action());assert.equal(await game.activateAbility(a,action()),true);assert.equal(card.zone,'graveyard');assert.equal(source.attachedTo,first.iid);await settle(game);assert.equal(source.attachedTo,second.iid);assert.equal(second.power,4);assertGameStateInvariants(game);
 });
 test(role+': Bloodthorn Flail rejects a cancelled or stale discard without paying or attaching',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Bloodthorn Flail'),host=put(M,game,a,'Grizzly Bears'),card=put(M,game,a,'Forest','hand');let stale=false;choice(a,async(g,q)=>{if(q.type==='chooseTargets')return [host];if(q.aiHint?.kind==='oracleEquipChoiceV20')return 'discard';if(q.type==='chooseCards'&&q.from?.includes(card)){if(!stale)return [];await game.move(card,'exile');await game.move(card,'hand');return [card];}});for(stale of [false,true]){assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleEquip)),false);assert.equal(source.attachedTo,null);assert.equal(card.zone,'hand');assert.equal(game.stack.length,0);}assertGameStateInvariants(game);
 });
 test(role+': Cavern floating mana retains its chosen type after a new entry choice',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Cavern of Souls','hand');let type='Dragon';choice(a,(g,q)=>q.aiHint?.kind==='chooseType'?type:undefined);await game.move(source,'battlefield',{ctrl:a});assert.equal(M.oracleChosenSubtypeV16(source),'Dragon');assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.manaSource?.m.spentRiderV20)),true);await game.move(source,'exile');type='Elf';await game.move(source,'battlefield',{ctrl:a});source.tapped=true;const dragon=put(M,game,a,'Grizzly Bears','hand'),elf=put(M,game,a,'Grizzly Bears','hand');dragon.def={...dragon.def,cost:'{1}',subtypes:['Dragon']};elf.def={...elf.def,cost:'{1}',subtypes:['Elf']};assert.equal(game.canPayMana(a,M.parseCost('{1}'),{card:elf,castOpts:{}}),false);assert.equal(game.canPayMana(a,M.parseCost('{1}'),{card:dragon,castOpts:{}}),true);assert.equal(await game.castSpell(a,dragon,{from:'hand'}),true);assert.equal(await game.counterStackObject(game.stack.find(row=>row.card===dragon)),false);await settle(game);assertGameStateInvariants(game);
 });
 test(role+': mana haste keeps its printed duration and disappears on a new creature incarnation',async()=>{
  const {game,a}=context(M,role),hall=put(M,game,a,'Hall of the Bandit Lord'),spell=put(M,game,a,'Grizzly Bears','hand');a.pool.G=1;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);const so=game.stack.find(r=>r.card===spell);assert.equal(so.oracleManaRidersV20.length,1);await settle(game);assert.equal(spell.kw('haste'),true);game.turnNo++;game.recalc();assert.equal(spell.kw('haste'),true);await game.move(spell,'exile');await game.move(spell,'battlefield',{ctrl:a});assert.equal(spell.kw('haste'),false);const servant=put(M,game,a,'Generator Servant'),second=put(M,game,a,'Grizzly Bears','hand');a.pool.G=1;assert.equal(await game.castSpell(a,second,{from:'hand'}),true);assert.equal(servant.zone,'graveyard');await settle(game);assert.equal(second.kw('haste'),true);game.turnNo++;game.recalc();assert.equal(second.kw('haste'),false);assertGameStateInvariants(game);
 });
 test(role+': Boseiju mana prevents a counter only for the instant or sorcery that used it',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Boseiju, Who Shelters All'),spell=put(M,game,a,'Divination','hand');a.pool.C=1;a.pool.U=1;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);const so=game.stack.find(r=>r.card===spell);assert.equal(await game.counterStackObject(so),false);await settle(game);game.untap(source);a.pool.G=1;const creature=put(M,game,a,'Grizzly Bears','hand');assert.equal(await game.castSpell(a,creature,{from:'hand'}),true);const ordinary=game.stack.find(r=>r.card===creature);assert.equal(ordinary.oracleManaRidersV20.length,0);assert.equal(await game.counterStackObject(ordinary),true);await settle(game);assertGameStateInvariants(game);
 });
 test(role+': each Gilanra mana unit creates its own delayed draw even after the spell is countered',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Gilanra, Caller of Wirewood');const ability=()=>game.activatableList(a).find(r=>r.card===source&&r.manaAbility);assert.equal(await game.activateAbility(a,ability()),true);game.untap(source);assert.equal(await game.activateAbility(a,ability()),true);await game.move(source,'exile');const spell=put(M,game,a,'Grizzly Bears','hand');spell.def={...spell.def,cost:'{6}'};a.pool.C=4;const hand=a.hand.length;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);const so=game.stack.find(r=>r.card===spell);assert.equal(so.oracleCreatureManaV20,2);assert.equal(game.stack.filter(r=>r.kind==='trigger'&&r.srcCard===source).length,2);assert.equal(await game.counterStackObject(so),true);await settle(game);assert.equal(a.hand.length,hand+1);assertGameStateInvariants(game);
 });
 test(role+': countering one Jade mana trigger removes one entry counter and hexproof expires next turn',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Jade Orb of Dragonkind');const ability=()=>game.activatableList(a).find(r=>r.card===source&&r.manaAbility);assert.equal(await game.activateAbility(a,ability()),true);game.untap(source);assert.equal(await game.activateAbility(a,ability()),true);await game.move(source,'exile');const spell=put(M,game,a,'Grizzly Bears','hand');spell.def={...spell.def,cost:'{2}',subtypes:['Dragon']};assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);const triggers=game.stack.filter(r=>r.kind==='trigger'&&r.srcCard===source);assert.equal(triggers.length,2);assert.equal(await game.counterStackObject(triggers[0]),true);await settle(game);assert.equal(spell.counters['+1/+1'],1);assert.equal(spell.kw('hexproof'),true);a.turnsStarted++;game.recalc();assert.equal(spell.kw('hexproof'),false);assert.equal(spell.counters['+1/+1'],1);assertGameStateInvariants(game);
 });
 test(role+': mana spent on an activated ability creates no later spell bonus',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Scaled Nurturer');assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source&&r.manaAbility)),true);const payment={card:source,isAbility:true};assert.equal(await game.payMana(a,M.parseCost('{1}'),payment),true);assert.equal(payment.oracleManaRidersV20,undefined);assert.equal(payment.oracleCreatureManaV20,undefined);const spell=put(M,game,a,'Grizzly Bears','hand');spell.def={...spell.def,subtypes:['Dragon']};a.pool.C=1;a.pool.G=1;const life=a.life;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);await settle(game);assert.equal(a.life,life);assertGameStateInvariants(game);
 });
 test(role+': collect evidence pays its total mana value before the activated effect resolves',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Forensic Researcher'),target=put(M,game,b,'Grizzly Bears'),one=put(M,game,a,'Sol Ring','graveyard'),two=put(M,game,a,'Grizzly Bears','graveyard');choice(a,(g,q)=>q.type==='chooseTargets'?[target]:q.aiHint?.activationPaymentV20?[one,two]:undefined);const ability=()=>game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.additionalCostV20);assert.ok(ability());assert.equal(await game.activateAbility(a,ability()),true);assert.equal(source.tapped,true);assert.equal(one.zone,'exile');assert.equal(two.zone,'exile');assert.equal(target.tapped,false);await settle(game);assert.equal(target.tapped,true);game.untap(source);assert.equal(!!ability(),false);assertGameStateInvariants(game);
 });
 test(role+': collect evidence rejects insufficient, duplicate and stale graveyard choices without tapping',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Forensic Researcher'),target=put(M,game,b,'Grizzly Bears'),one=put(M,game,a,'Sol Ring','graveyard'),two=put(M,game,a,'Grizzly Bears','graveyard');let mode='short';choice(a,async(g,q)=>{if(q.type==='chooseTargets')return [target];if(!q.aiHint?.activationPaymentV20)return;if(mode==='short')return [one];if(mode==='duplicate')return [two,two];await game.move(two,'exile');await game.move(two,'graveyard');return [one,two];});for(mode of ['short','duplicate','stale']){assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.additionalCostV20)),false);assert.equal(source.tapped,false);assert.equal(one.zone,'graveyard');assert.equal(two.zone,'graveyard');assert.equal(game.stack.length,0);}assertGameStateInvariants(game);
 });
 test(role+': Blight adds the printed counters as a cost and the ability still resolves',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Sting-Slinger'),donor=put(M,game,a,'Grizzly Bears');a.pool.C=1;a.pool.R=1;choice(a,(g,q)=>q.aiHint?.activationPaymentV20?[donor]:undefined);const life=b.life;assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.ability?.cost.additionalCostV20)),true);assert.equal(donor.counters['-1/-1'],1);assert.equal(a.pool.C+a.pool.R,0);assert.equal(b.life,life);await settle(game);assert.equal(b.life,life-2);assertGameStateInvariants(game);
 });
 test(role+': Cryptex is a mana ability that exiles evidence and adds its unlock counter immediately',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Cryptex'),card=put(M,game,a,'Serra Angel','graveyard');choice(a,(g,q)=>q.aiHint?.activationPaymentV20?[card]:undefined);assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.manaAbility)),true);assert.equal(card.zone,'exile');assert.equal(source.counters.unlock,1);assert.equal(Object.values(a.pool).reduce((n,x)=>n+x,0),1);assert.equal(source.tapped,true);assert.equal(game.stack.length,0);assertGameStateInvariants(game);
 });
 test(role+': Forage supports Food sacrifice and graveyard exile as separate paid alternatives',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Thornvault Forager');await game.makeTokens('food',a,{n:1});const food=game.bf().find(c=>c.hasSub('Food')),grave=Array.from({length:3},()=>put(M,game,a,'Forest','graveyard'));let useFood=true;choice(a,(g,q)=>q.aiHint?.kind==='oracleForageV20'?(useFood?'forage-food':'forage-grave'):q.aiHint?.activationPaymentV20?(useFood?[food]:grave):undefined);const ability=()=>game.activatableList(a).find(row=>row.card===source&&row.manaSource?.m.activationPaymentV20);assert.equal(await game.activateAbility(a,ability()),true);assert.ok(['graveyard','ceased'].includes(food.zone));assert.ok(grave.every(c=>c.zone==='graveyard'));assert.equal(Object.values(a.pool).reduce((n,x)=>n+x,0),2);game.untap(source);useFood=false;assert.equal(await game.activateAbility(a,ability()),true);assert.ok(grave.every(c=>c.zone==='exile'));assert.equal(Object.values(a.pool).reduce((n,x)=>n+x,0),4);assert.equal(game.stack.length,0);assertGameStateInvariants(game);
 });
 test(role+': graveyard Blight activation pays counters and retains its sorcery timing',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,"Evershrike's Gift",'graveyard'),donor=put(M,game,a,'Serra Angel');a.pool.C=1;a.pool.W=1;choice(a,(g,q)=>q.aiHint?.activationPaymentV20?[donor]:undefined);game.phase='combat';assert.equal(game.activatableList(a).some(r=>r.card===source),false);game.phase='main1';assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source&&r.gyAbility)),true);assert.equal(donor.counters['-1/-1'],2);assert.equal(a.pool.C+a.pool.W,0);assert.equal(source.zone,'graveyard');await settle(game);assert.equal(source.zone,'hand');assertGameStateInvariants(game);
 });
 test(role+': hand-reveal mana produces only the chosen count and never uses the stack',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Metalworker'),first=put(M,game,a,'Sol Ring','hand'),second=put(M,game,a,'Sol Ring','hand'),wrong=put(M,game,a,'Forest','hand'),reveals=[];game.revealToHuman=async q=>reveals.push(q.cards.map(c=>c.iid));let answer=[first];const prior=a.controller.decide.bind(a.controller);a.controller.decide=(g,q)=>q.type==='chooseCards'&&q.aiHint?.src===source?answer:prior(g,q);const action=()=>game.activatableList(a).find(r=>r.card===source&&r.manaAbility);assert.equal(await game.activateAbility(a,action()),true);assert.equal(a.pool.C,2);assert.equal(source.tapped,true);assert.deepEqual(reveals,[[first.iid]]);assert.equal(game.stack.length,0);assert.ok([first,second,wrong].every(c=>c.zone==='hand'));game.untap(source);answer=[];assert.equal(await game.activateAbility(a,action()),true);assert.equal(a.pool.C,2);assertGameStateInvariants(game);
 });
 test(role+': an invalid or changed hand reveal cannot tap the mana source',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Metalworker'),card=put(M,game,a,'Sol Ring','hand'),wrong=put(M,game,a,'Forest','hand');let mode='invalid';const prior=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>{if(q.type!=='chooseCards'||q.aiHint?.src!==source)return prior(g,q);if(mode==='cancel')return null;if(mode==='invalid')return [wrong];if(mode==='duplicate')return [card,card];await game.move(card,'exile');await game.move(card,'hand');return [card];};for(mode of ['invalid','duplicate','cancel','stale']){assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source&&r.manaAbility)),false);assert.equal(source.tapped,false);assert.equal(a.pool.C,0);assert.equal(game.stack.length,0);}assertGameStateInvariants(game);
 });
 test(role+': Tap X selects an exact announced quantity including zero',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Secluded Starforge'),target=put(M,game,a,'Grizzly Bears'),first=put(M,game,a,'Sol Ring'),second=put(M,game,a,'Sol Ring');a.pool.C=2;let x=2;choice(a,(g,q)=>q.type==='chooseX'?x:q.type==='chooseCards'&&q.aiHint?.kind==='tapCost'?[first,second].slice(0,x):q.type==='chooseTargets'?[target]:undefined);const action=()=>game.activatableList(a).find(r=>r.card===source&&r.ability?.cdkTapX);assert.equal(await game.activateAbility(a,action()),true);assert.equal(a.pool.C,0);assert.ok([source,first,second].every(c=>c.tapped));await settle(game);assert.equal(target.power,4);for(const c of [source,first,second])game.untap(c);a.pool.C=2;x=0;assert.equal(await game.activateAbility(a,action()),true);assert.equal(first.tapped,false);assert.equal(second.tapped,false);await settle(game);assert.equal(target.power,4);assertGameStateInvariants(game);
 });
 test(role+': Tap X rejects a stale donor before spending mana or tapping anything',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Secluded Starforge'),target=put(M,game,a,'Grizzly Bears'),donor=put(M,game,a,'Sol Ring');a.pool.C=2;choice(a,async(g,q)=>{if(q.type==='chooseX')return 1;if(q.type==='chooseCards'&&q.aiHint?.kind==='tapCost'){await game.move(donor,'exile');await game.move(donor,'battlefield',{ctrl:a});return [donor];}if(q.type==='chooseTargets')return [target];});assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source&&r.ability?.cdkTapX)),false);assert.equal(source.tapped,false);assert.equal(donor.tapped,false);assert.equal(a.pool.C,2);assertGameStateInvariants(game);
 });
 test(role+': Craft pays both battlefield and graveyard materials before its return resolves',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Visage of Dread // Dread Osseosaur'),first=put(M,game,a,'Grizzly Bears'),second=put(M,game,a,'Grizzly Bears','graveyard');a.pool.C=5;a.pool.B=1;const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleCraftV20);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.C+a.pool.B,0);assert.equal(first.zone,'exile');assert.equal(second.zone,'exile');assert.equal(source.zone,'exile');assert.equal(source.oracleFace,'front');await settle(game);assert.equal(source.oracleFace,'back');assert.equal(source.name,'Dread Osseosaur');assert.equal(source.meta.oracleCraftV20.rows.length,2);assert.equal(source.meta.oracleCraftV20.version,source.zoneVersion);assertGameStateInvariants(game);
 });
 test(role+': Craft cancellation and a changed graveyard incarnation spend no mana or other costs',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Oteclan Landmark // Oteclan Levitator'),material=put(M,game,a,'Sol Ring','graveyard');a.pool.C=2;a.pool.W=1;const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleCraftV20);assert.ok(action);let stale=false;choice(a,async(g,q)=>{if(q.aiHint?.kind!=='oracleCraftV20')return undefined;if(stale){await game.move(material,'exile');await game.move(material,'graveyard');return [material];}return [];});assert.equal(await game.activateAbility(a,action),false);assert.equal(source.zone,'battlefield');assert.equal(material.zone,'graveyard');assert.equal(a.pool.C+a.pool.W,3);stale=true;assert.equal(await game.activateAbility(a,action),false);assert.equal(source.zone,'battlefield');assert.equal(material.zone,'graveyard');assert.equal(a.pool.C+a.pool.W,3);assert.equal(game.stack.length,0);assertGameStateInvariants(game);
 });
 test(role+': countering Craft retains exile and a changed exiled source cannot be returned',async()=>{
  const {game,a}=context(M,role);fund(a);const source=put(M,game,a,'Tithing Blade // Consuming Sepulcher');put(M,game,a,'Grizzly Bears','graveyard');const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleCraftV20);assert.equal(await game.activateAbility(a,action),true);const so=game.stack.find(row=>row.srcCard===source);assert.equal(await game.counterStackObject(so),true);assert.equal(source.zone,'exile');await game.move(source,'battlefield',{ctrl:a});put(M,game,a,'Grizzly Bears','graveyard');assert.equal(await game.activateAbility(a,game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleCraftV20)),true);await game.move(source,'graveyard');await game.move(source,'exile');await settle(game);assert.equal(source.zone,'exile');assert.equal(source.oracleFace,'front');assertGameStateInvariants(game);
 });
 test(role+': Craft returns under the owner and only works at sorcery timing',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Oteclan Landmark // Oteclan Levitator');source.owner=b;put(M,game,a,'Sol Ring','graveyard');fund(a);game.phase='combat';assert.equal(game.activatableList(a).some(row=>row.card===source&&row.ability?.oracleCraftV20),false);game.phase='main1';const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleCraftV20);assert.equal(await game.activateAbility(a,action),true);await settle(game);assert.equal(source.ctrl,b);assert.equal(source.oracleFace,'back');assertGameStateInvariants(game);
 });
 test(role+': the same Treasure cannot pay Craft mana and serve as its material',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Oteclan Landmark // Oteclan Levitator');await game.makeTokens('treasure',a,{n:1});a.pool.C=2;const treasure=game.bf().find(c=>c.hasSub('Treasure'));assert.ok(treasure);assert.equal(game.activatableList(a).some(row=>row.card===source&&row.ability?.oracleCraftV20),false);a.pool.W=1;const action=game.activatableList(a).find(row=>row.card===source&&row.ability?.oracleCraftV20);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.C+a.pool.W,0);await settle(game);assert.equal(source.oracleFace,'back');assertGameStateInvariants(game);
 });
 test(role+': mana flexibility spends actual colors, preserves colorless symbols, and respects the printed scope',async()=>{
  const {game,a}=context(M,role),oath=put(M,game,a,'Oath of Nissa'),creature=put(M,game,a,'Grizzly Bears','hand'),walker=put(M,game,a,'Grizzly Bears','hand');walker.def={...walker.def,types:['Planeswalker'],loyalty:2};game.recalc();a.pool.C=1;assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:creature,castOpts:{}}),false);assert.equal(await game.payMana(a,M.parseCost('{U}'),{card:walker,castOpts:{}}),true);assert.equal(a.pool.C,0);a.pool.R=1;assert.equal(game.canPayMana(a,M.parseCost('{C}'),{card:walker,castOpts:{}}),false);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:walker,isAbility:true}),false);M.OracleV8AbilityLoss.add(game,[oath],{});assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:walker,castOpts:{}}),false);assert.equal(a.pool.R,1);const orrery=put(M,game,a,'Chromatic Orrery');orrery.tapped=true;assert.equal(await game.payMana(a,M.parseCost('{U}'),{card:creature,isAbility:true}),true);assert.equal(a.pool.R,0);assertGameStateInvariants(game);
 });
 test(role+': a granted flashback cost is paid and resolution exiles the actual spell',async()=>{
  const {game,a}=context(M,role),grant=put(M,game,a,'Flashback','hand'),spell=put(M,game,a,'Divination','graveyard');fund(a);assert.equal(await game.castSpell(a,grant,{from:'hand'}),true);await settle(game);const action=game.castableList(a).find(row=>row.card===spell&&row.alt?.flashback);assert.ok(action);for(const color of Object.keys(a.pool))a.pool[color]=0;a.pool.C=1;a.pool.U=1;assert.equal(await game.castSpell(a,spell,{from:'graveyard',alt:action.alt}),false);a.pool.C=2;assert.equal(await game.castSpell(a,spell,{from:'graveyard',alt:action.alt}),true);assert.equal(a.pool.C+a.pool.U,0);await settle(game);assert.equal(spell.zone,'exile');assertGameStateInvariants(game);
 });
 test(role+': granted flashback expires and does not follow a returned graveyard object',async()=>{
  const {game,a}=context(M,role),grant=put(M,game,a,'Flashback','hand'),spell=put(M,game,a,'Divination','graveyard');fund(a);assert.equal(await game.castSpell(a,grant,{from:'hand'}),true);await settle(game);const action=game.castableList(a).find(row=>row.card===spell&&row.alt?.flashback);assert.ok(action);game.turnNo++;assert.equal(game.castableList(a).some(row=>row.card===spell),false);game.turnNo--;await game.move(spell,'exile');await game.move(spell,'graveyard');assert.equal(game.castableList(a).some(row=>row.card===spell),false);assert.equal(await game.castSpell(a,spell,{from:'graveyard',alt:action.alt}),false);assertGameStateInvariants(game);
 });
 test(role+': graveyard casting pays each other creature surcharge and a Maestro sacrifice is used only once per turn',async()=>{
  const {game,a}=context(M,role),risen=put(M,game,a,'Risen Executioner','graveyard');put(M,game,a,'Grizzly Bears','graveyard');put(M,game,a,'Grizzly Bears','graveyard');a.pool.C=3;a.pool.B=2;assert.equal(game.castableList(a).some(row=>row.card===risen),false);a.pool.C=4;const cast=game.castableList(a).find(row=>row.card===risen);assert.ok(cast);assert.equal(await game.castSpell(a,risen,{from:'graveyard',alt:cast.alt}),true);assert.equal(a.pool.C+a.pool.B,0);await settle(game);put(M,game,a,'Maestros Ascendancy');const spell=put(M,game,a,'Divination','graveyard');fund(a);const option=game.castableList(a).find(row=>row.card===spell&&row.alt?.starterPermission==='oracle-v20');assert.ok(option);assert.equal(await game.castSpell(a,spell,{from:'graveyard',alt:option.alt}),true);assert.equal(risen.zone,'graveyard');await settle(game);assert.equal(spell.zone,'exile');const next=put(M,game,a,'Divination','graveyard');put(M,game,a,'Grizzly Bears');assert.equal(game.castableList(a).some(row=>row.card===next),false);game.turnNo++;assert.equal(game.castableList(a).some(row=>row.card===next),true);assertGameStateInvariants(game);
 });
 test(role+': Prowl requires matching combat damage this turn and rejects forged alternative fields',async()=>{
  const {game,a,b}=context(M,role),spell=put(M,game,a,"Thieves' Fortune",'hand'),bear=put(M,game,a,'Grizzly Bears'),rogue=put(M,game,a,'Grizzly Bears');rogue.def={...rogue.def,subtypes:['Rogue']};game.recalc();a.pool.U=1;
  assert.equal(game.castableList(a).some(r=>r.card===spell),false);await game.damagePlayer(bear,b,1,{combat:true});assert.equal(game.castableList(a).some(r=>r.card===spell),false);await game.damagePlayer(rogue,b,1);assert.equal(game.castableList(a).some(r=>r.card===spell),false);await game.damagePlayer(rogue,b,1,{combat:true});const alt=game.castableList(a).find(r=>r.card===spell&&r.alt?.c1920Prowl).alt;assert.equal(await game.castSpell(a,spell,{from:'hand',alt:{c1920Prowl:true,altCostStr:'{0}'}}),false);assert.equal(await game.castSpell(a,spell,{from:'hand',alt:{...alt,free:true}}),false);const history=a.turnState.c1920ProwlTypes;a.turnState.c1920ProwlTypes=[];assert.equal(await game.castSpell(a,spell,{from:'hand',alt}),false);assert.equal(a.pool.U,1);a.turnState.c1920ProwlTypes=history;assert.equal(await game.castSpell(a,spell,{from:'hand',alt}),true);assert.equal(a.pool.U,0);await settle(game);assertGameStateInvariants(game);
 });
 test(role+': copies retain a paid Prowl choice and an unpaid normal cast receives no Prowl bonus',async()=>{
  const {game,a,b}=context(M,role),rogue=put(M,game,a,'Grizzly Bears');rogue.def={...rogue.def,subtypes:['Rogue']};game.recalc();await game.damagePlayer(rogue,b,1,{combat:true});fund(a);const spell=put(M,game,a,'Morsel Theft','hand'),hand=a.hand.length,alt=game.castableList(a).find(r=>r.card===spell&&r.alt?.c1920Prowl).alt;assert.equal(await game.castSpell(a,spell,{from:'hand',alt}),true);const so=game.stack.find(r=>r.card===spell);await game.copySpell(so,a,{mayNewTargets:false});await settle(game);assert.equal(a.hand.length,hand+1);const normal=put(M,game,a,'Morsel Theft','hand'),before=a.hand.length;assert.equal(await game.castSpell(a,normal,{from:'hand'}),true);await settle(game);assert.equal(a.hand.length,before-1);assertGameStateInvariants(game);
 });
 test(role+': Kicker X is a separately paid variable and its captured value survives the permanent leaving',async()=>{
  const {game,a}=context(M,role),spell=put(M,game,a,'Verdeloth the Ancient','hand');a.pool.G=2;a.pool.C=6;choice(a,(g,q)=>q.aiHint?.kind==='kicker'?'yes':q.type==='chooseX'?2:undefined);assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(a.pool.G+a.pool.C,0);const so=game.stack.find(r=>r.card===spell);assert.equal(so.x,0);assert.equal(so.castOpts._kickerX,2);await game.resolveTop();await game.move(spell,'exile');await game.move(spell,'battlefield',{ctrl:a});await settle(game);assert.equal(game.creatures(a).filter(c=>c.isToken&&c.hasSub('Saproling')).length,2);assertGameStateInvariants(game);
 });
 test(role+': Kicker X rejects an invalid choice without payment and permits a real zero choice',async()=>{
  const {game,a}=context(M,role),spell=put(M,game,a,'Kangee, Aerie Keeper','hand');fund(a);let x=-1;choice(a,(g,q)=>q.aiHint?.kind==='kicker'?'yes':q.type==='chooseX'?x:undefined);const total=()=>Object.values(a.pool).reduce((n,v)=>n+v,0),before=total();assert.equal(await game.castSpell(a,spell,{from:'hand'}),false);assert.equal(total(),before);assert.equal(spell.zone,'hand');x=0;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);await settle(game);assert.equal(spell.counters.feather||0,0);assert.equal(before-total(),6);assertGameStateInvariants(game);
 });

 test(role+': a revealed creature remains public while its spell is on the stack and determines the resolving amount',async()=>{
  const {game,a}=context(M,role),spell=put(M,game,a,'Living Destiny','hand');fund(a);const before=a.life;assert.equal(await game.castSpell(a,spell,{from:'hand'}),false);const revealed=put(M,game,a,'Serra Angel','hand');assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(game.revealedHandCardsV17().includes(revealed),true);await settle(game);assert.equal(a.life,before+5);assert.equal(revealed.zone,'hand');assert.equal(game.revealedHandCardsV17().includes(revealed),false);assertGameStateInvariants(game);
 });
 test(role+': revealed creature power is live in hand and copies retain the original hand-object last known power',async()=>{
  const {game,a,b}=context(M,role),spell=put(M,game,a,'Charge of the Forever-Beast','hand'),revealed=put(M,game,a,'Grizzly Bears','hand'),target=put(M,game,b,'Grizzly Bears');target.def={...target.def,toughness:'40'};revealed.def={...revealed.def,oracleCharacteristicPT:true,cdaPower:(g,c)=>c.owner.hand.length,cdaToughness:()=>4};game.recalc();fund(a);assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);put(M,game,a,'Forest','hand');put(M,game,a,'Forest','hand');assert.equal(revealed.power,3);await settle(game);assert.equal(target.damage,3);const second=put(M,game,a,'Charge of the Forever-Beast','hand');assert.equal(await game.castSpell(a,second,{from:'hand'}),true);const so=game.stack.find(row=>row.card===second);await game.copySpell(so,a,{mayNewTargets:false});put(M,game,a,'Forest','hand');assert.equal(revealed.power,4);await game.move(revealed,'graveyard');await game.move(revealed,'hand');for(let i=0;i<4;i++)put(M,game,a,'Forest','hand');assert.equal(game.revealedHandCardsV17().includes(revealed),false);await settle(game);assert.equal(target.damage,11);assertGameStateInvariants(game);
 });
 test(role+': a mana ability cannot discard the only creature committed to the reveal cost',async()=>{
  const {game,a}=context(M,role),spell=put(M,game,a,'Living Destiny','hand'),revealed=put(M,game,a,'Serra Angel','hand'),witch=put(M,game,a,'Bog Witch');a.pool.B=1;a.pool.G=1;assert.equal(await game.castSpell(a,spell,{from:'hand'}),false);assert.equal(revealed.zone,'hand');assert.equal(witch.tapped,false);assert.equal(a.pool.B,1);assert.equal(a.pool.G,1);const donor=put(M,game,a,'Forest','hand');assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(donor.zone,'graveyard');assert.equal(revealed.zone,'hand');assert.equal(witch.tapped,true);await settle(game);assertGameStateInvariants(game);
 });

 test(role+': the Plains tap alternative preserves the normal mana route and rejects a vanished condition',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Ramosian Rally','hand'),donor=put(M,game,a,'Grizzly Bears');assert.equal(game.castableList(a).some(row=>row.card===card),false);const plains=put(M,game,a,'Plains');const action=game.castableList(a).find(row=>row.card===card&&row.alt?.oracleTapAlternativeV20);assert.ok(action);assert.equal(await game.castSpell(a,card,{from:'hand',alt:{...action.alt,free:true}}),false);await game.move(plains,'exile');assert.equal(await game.castSpell(a,card,{from:'hand',alt:action.alt}),false);assert.equal(donor.tapped,false);await game.move(plains,'battlefield',{ctrl:a});assert.equal(await game.castSpell(a,card,{from:'hand',alt:game.castableList(a).find(row=>row.card===card&&row.alt?.oracleTapAlternativeV20).alt}),true);assert.equal(donor.tapped,true);assert.equal(plains.tapped,false);await settle(game);const normal=put(M,game,a,'Ramosian Rally','hand');a.pool.C=3;a.pool.W=1;assert.equal(await game.castSpell(a,normal,{from:'hand'}),true);await settle(game);assert.equal(a.pool.C+a.pool.W,0);assertGameStateInvariants(game);
 });

 test(role+': hybrid Power-up subtracts the current printed mana cost, uses its own once limit and resets after blinking',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Brawn, Amadeus Cho','hand');await game.move(card,'battlefield',{ctrl:a});await settle(game);a.pool.C=3;const action=game.activatableList(a).find(row=>row.card===card&&row.ability?.powerUp);assert.ok(action);const hand=a.hand.length;assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.C,0);await settle(game);assert.equal(card.counters['+1/+1'],hand);a.pool.C=3;assert.equal(await game.activateAbility(a,action),false);assert.equal(a.pool.C,3);await game.move(card,'exile');await game.move(card,'battlefield',{ctrl:a});await settle(game);const renewed=game.activatableList(a).find(row=>row.card===card&&row.ability?.powerUp);assert.ok(renewed);assert.equal(await game.activateAbility(a,renewed),true);await settle(game);assert.equal(card.counters['+1/+1'],a.hand.length);assertGameStateInvariants(game);
 });
 test(role+': hybrid Power-up costs full price on later turns and a colored reduction can cover generic mana',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Brawn, Amadeus Cho','hand');await game.move(card,'battlefield',{ctrl:a});await settle(game);a.pool.C=2;a.pool.U=1;if(role==='human')choice(a,(g,q)=>q.aiHint?.paymentKind==='reductionV20'?'G':q.aiHint?.paymentKind==='hybrid'?'U':undefined);const action=game.activatableList(a).find(row=>row.card===card&&row.ability?.powerUp);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.C+a.pool.U,0);await settle(game);await game.move(card,'exile');await game.move(card,'battlefield',{ctrl:a});await settle(game);game.turnNo++;a.pool.C=3;assert.equal(game.activatableList(a).some(row=>row.card===card&&row.ability?.powerUp),false);a.pool.C=4;a.pool.U=1;const full=game.activatableList(a).find(row=>row.card===card&&row.ability?.powerUp);assert.ok(full);assert.equal(await game.activateAbility(a,full),true);assert.equal(a.pool.C+a.pool.U,0);await settle(game);assertGameStateInvariants(game);
 });

 test(role+': additional tapping reserves all four creatures against paying the spells mana',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Shared Discovery','hand'),donors=Array.from({length:4},()=>put(M,game,a,'Birds of Paradise'));assert.equal(game.castableList(a).some(row=>row.card===card),false);assert.equal(await game.castSpell(a,card,{from:'hand'}),false);assert.ok(donors.every(c=>!c.tapped));a.pool.U=1;assert.equal(game.castableList(a).some(row=>row.card===card),true);const before=a.hand.length;assert.equal(await game.castSpell(a,card,{from:'hand'}),true);assert.ok(donors.every(c=>c.tapped));assert.equal(a.pool.U,0);await settle(game);assert.equal(a.hand.length,before+2);assertGameStateInvariants(game);
 });
 test(role+': additional tapping keeps the printed colors and permits summoning-sick cost donors',async()=>{
  const {game,a,b}=context(M,role),card=put(M,game,a,'Gaze of Justice','hand'),target=put(M,game,b,'Grizzly Bears'),white=Array.from({length:2},()=>put(M,game,a,'Savannah Lions')),green=put(M,game,a,'Grizzly Bears');a.pool.W=1;assert.equal(await game.castSpell(a,card,{from:'hand'}),false);assert.equal(a.pool.W,1);assert.ok([...white,green].every(c=>!c.tapped));const third=put(M,game,a,'Savannah Lions');third.sick=true;assert.equal(await game.castSpell(a,card,{from:'hand'}),true);assert.ok([...white,third].every(c=>c.tapped));assert.equal(green.tapped,false);await settle(game);assert.equal(target.zone,'exile');assertGameStateInvariants(game);
 });
 test(role+': an additional tap donor that leaves and returns during a mana choice invalidates payment',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Shared Discovery','hand'),donors=Array.from({length:4},()=>put(M,game,a,'Grizzly Bears'));a.pool.U=1;const old=game.payMana;let mutated=false;game.payMana=async function(...args){if(!mutated&&args[2]?.card===card){mutated=true;await this.move(donors[0],'exile');await this.move(donors[0],'battlefield',{ctrl:a});}return old.apply(this,args);};assert.equal(await game.castSpell(a,card,{from:'hand'}),false);assert.equal(card.zone,'hand');assert.equal(a.pool.U,1);assert.ok(donors.every(c=>!c.tapped));assertGameStateInvariants(game);
 });

 test(role+': positive Suspend X pays its declared cost and the last counter creates an optional actual cast',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Benalish Commander','hand');a.pool.W=2;a.pool.C=2;choice(a,(g,q)=>q.type==='chooseX'?2:undefined);const action=game.activatableList(a).find(row=>row.card===card&&row.suspend);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.W+a.pool.C,0);assert.equal(card.counters.time,2);assert.equal(game.stack.length,0);game.removeCounters(card,'time',1);await settle(game);assert.equal(game.creatures(a).filter(c=>c.isToken&&c.hasSub('Soldier')).length,1);assert.equal(card.zone,'exile');game.removeCounters(card,'time',1);await settle(game);assert.equal(card.zone,'battlefield');assert.equal(game.creatures(a).filter(c=>c.isToken&&c.hasSub('Soldier')).length,2);assert.equal(card.power,3);assert.equal(card.kw('haste'),true);assertGameStateInvariants(game);
 });
 test(role+': Suspend X rejects zero and a stale hand object, and its final cast can be declined',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Benalish Commander','hand');fund(a);let mode='zero';choice(a,(g,q)=>{if(q.type==='chooseX'){if(mode==='stale')return g.move(card,'exile').then(()=>1);return mode==='zero'?0:1;}if(q.prompt?.startsWith('Suspend: cast'))return 'no';});const amount=()=>Object.values(a.pool).reduce((n,x)=>n+x,0),before=amount();assert.equal(await game.activateAbility(a,{card,suspend:true}),false);assert.equal(card.zone,'hand');assert.equal(amount(),before);mode='stale';assert.equal(await game.activateAbility(a,{card,suspend:true}),false);assert.equal(amount(),before);await game.move(card,'hand');mode='valid';assert.equal(await game.activateAbility(a,{card,suspend:true}),true);game.removeCounters(card,'time',1);await settle(game);assert.equal(card.zone,'exile');assert.equal(card.counters.time||0,0);assertGameStateInvariants(game);
 });
 test(role+': spell-only restricted mana cannot pay a Suspend special action',async()=>{
  const {game,a}=context(M,role),mana=put(M,game,a,'Abstract Paintmage'),card=put(M,game,a,'Detritivore','hand');await game.emit('precombatMain',{player:a});await settle(game);a.pool.C=5;assert.equal(a.pool.R,1);assert.equal(game.activatableList(a).some(row=>row.card===card&&row.suspend),false);assert.equal(await game.activateAbility(a,{card,suspend:true}),false);assert.equal(card.zone,'hand');assert.equal(a.pool.R,1);assert.equal(a.pool.C,5);assertGameStateInvariants(game);
 });

 test(role+': first creature reduction and flash permission are consumed by an actual cast even across zones',async()=>{
  const {game,a,b}=context(M,role);put(M,game,a,'Radagast of Rhosgobel');game.turnPlayer=b;game.phase='main1';const first=put(M,game,a,'Grizzly Bears','hand');a.pool.G=1;assert.equal(game.canCastTiming(a,first,{}),true);assert.equal(game.spellCost(a,first,{}).generic,0);assert.equal(await game.castSpell(a,first,{from:'hand'}),true);await settle(game);await game.move(first,'exile');const next=put(M,game,a,'Grizzly Bears','hand');assert.equal(game.canCastTiming(a,next,{}),false);assert.equal(game.spellCost(a,next,{}).generic,1);assertGameStateInvariants(game);
 });
 test(role+': Momo ignores Lemurs and preserves flying at the time the first qualifying spell was cast',async()=>{
  const {game,a}=context(M,role);put(M,game,a,'Momo, Friendly Flier');fund(a);const lemur=put(M,game,a,'Grizzly Bears','hand');lemur.def={...lemur.def,subtypes:['Lemur'],kws:['flying']};assert.equal(game.spellCost(a,lemur,{}).generic,1);assert.equal(await game.castSpell(a,lemur,{from:'hand'}),true);await settle(game);const flyer=put(M,game,a,'Serra Angel','hand');assert.equal(game.spellCost(a,flyer,{}).generic,2);assert.equal(await game.castSpell(a,flyer,{from:'hand'}),true);await settle(game);flyer.def={...flyer.def,kws:[]};await game.move(flyer,'exile');const next=put(M,game,a,'Serra Angel','hand');assert.equal(game.spellCost(a,next,{}).generic,3);assertGameStateInvariants(game);
 });
 test(role+': colored cost reduction applies to additional kicker symbols even when printed cost has no colors',async()=>{
  const {game,a}=context(M,role);put(M,game,a,'Ragemonger');const card=put(M,game,a,'Grizzly Bears','hand');card.def={...card.def,cost:'{0}',subtypes:['Minotaur'],kicker:{cost:'{B}{R}'}};choice(a,(g,q)=>q.aiHint?.kind==='kicker'?'yes':undefined);assert.equal(await game.castSpell(a,card,{from:'hand'}),true);assert.equal(game.stack.find(row=>row.card===card).castOpts._kicked,true);assert.equal(Object.values(a.pool).reduce((n,x)=>n+x,0),0);await settle(game);assertGameStateInvariants(game);
 });

 test(role+': colored spell reductions remove only matching colored payments, including declared hybrid choices',async()=>{
  const {game,a}=context(M,role);put(M,game,a,'Ragemonger');const make=(name,cost)=>{const c=put(M,game,a,'Grizzly Bears','hand');c.def={...c.def,name,cost,subtypes:['Minotaur']};return c;};
  const ordinary=make('V20 reduced Minotaur','{2}{B}{R}');a.pool.C=2;assert.equal(await game.castSpell(a,ordinary,{from:'hand'}),true);assert.equal(a.pool.C,0);await settle(game);
  const hybrid=make('V20 hybrid Minotaur','{B/G}{B/R}');assert.equal(await game.castSpell(a,hybrid,{from:'hand'}),true);await settle(game);assert.equal(hybrid.zone,'battlefield');
  const wrong=make('V20 green Minotaur','{2}{G}');a.pool.C=2;assert.equal(await game.castSpell(a,wrong,{from:'hand'}),false);assert.equal(a.pool.C,2);a.pool.G=1;assert.equal(await game.castSpell(a,wrong,{from:'hand'}),true);await settle(game);assertGameStateInvariants(game);
 });
 test(role+': colored reduction respects the announced generic bridge and Phyrexian life alternatives',async()=>{
  const {game,a}=context(M,role);put(M,game,a,'Ragemonger');const card=put(M,game,a,'Grizzly Bears','hand');card.def={...card.def,cost:'{2/B}{2/R}',subtypes:['Minotaur']};a.pool.C=4;
  if(role==='human')choice(a,(g,q)=>q.aiHint?.paymentKind==='twoBridge'?'generic':undefined);assert.equal(await game.castSpell(a,card,{from:'hand'}),true);assert.equal(a.pool.C,role==='human'?0:4);await settle(game);
  const phy=put(M,game,a,'Grizzly Bears','hand');phy.def={...phy.def,cost:'{B/P}{R/P}',subtypes:['Minotaur']};const life=a.life;if(role==='human')choice(a,(g,q)=>q.aiHint?.paymentKind==='phyrexian'?'life':undefined);assert.equal(await game.castSpell(a,phy,{from:'hand'}),true);assert.equal(a.life,life-(role==='human'?4:0));await settle(game);assertGameStateInvariants(game);
 });

 test(role+': restricted granted mana applies to each artifact and cannot pay hand spells or Room special actions',async()=>{
  const {game,a}=context(M,role);put(M,game,a,"Mm'menon, the Right Hand");const source=put(M,game,a,'Sol Ring'),hand=put(M,game,a,'Grizzly Bears','hand'),grave=put(M,game,a,'Brainstorm','graveyard');const action=game.activatableList(a).find(x=>x.card===source&&x.manaAbility&&x.manaSource?.m.restrict);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.U,1);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:hand,castOpts:{from:'hand'}}),false);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:grave,castOpts:{from:'graveyard'}}),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:grave,isSpecialAction:true,oracleUnlockRoomV20:true}),false);assertGameStateInvariants(game);
 });
 test(role+': Creeping Peeper permits printed Room and face-up special actions but rejects artifact spells',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Creeping Peeper'),artifact=put(M,game,a,'Sol Ring','hand');const action=game.activatableList(a).find(x=>x.card===source&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:artifact,castOpts:{}}),false);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:artifact,isSpecialAction:true,oracleUnlockRoomV20:true}),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:artifact,isAbility:true,turnFaceUp:true}),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:artifact,isSpecialAction:true}),false);assertGameStateInvariants(game);
 });
 test(role+': Burnt Offering produces the sacrificed creatures mana value using only the two printed colors',async()=>{
  const {game,a}=context(M,role),spell=put(M,game,a,'Burnt Offering','hand'),donor=put(M,game,a,'Serra Angel');a.pool.B=1;choice(a,(g,q)=>q.type==='chooseOption'&&q.prompt==='Choose mana'?'2':undefined);assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(donor.zone,'graveyard');await settle(game);assert.equal(a.pool.B,2);assert.equal(a.pool.R,3);for(const color of ['W','U','G','C'])assert.equal(a.pool[color],0);assertGameStateInvariants(game);
 });
 test(role+': triggered restricted mana keeps its spell restriction on the floating mana',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Abstract Paintmage'),spell=put(M,game,a,'Brainstorm','hand');await game.emit('precombatMain',{player:a});await settle(game);assert.equal(a.pool.U,1);assert.equal(a.pool.R,1);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:spell,castOpts:{}}),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:spell,isSpecialAction:true,oracleUnlockRoomV20:true}),false);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:spell,isAbility:true}),false);assertGameStateInvariants(game);
 });

 test(role+': graveyard self-casting pays every additional discard and binds the current graveyard card',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,"Rona, Sheoldred's Faithful",'graveyard');fund(a);assert.equal(game.castableList(a).some(row=>row.card===source),false);put(M,game,a,'Forest','hand');put(M,game,a,'Island','hand');const action=game.castableList(a).find(row=>row.card===source&&row.alt?.starterPermission==='oracle-v20');assert.ok(action);assert.equal(await game.castSpell(a,source,{from:'graveyard',alt:action.alt}),true);assert.equal(a.hand.length,0);assert.equal(a.graveyard.length,2);await settle(game);assert.equal(source.zone,'battlefield');assertGameStateInvariants(game);
 });
 test(role+': Noctis artifact permission pays life and puts the finality counter on the actual arriving artifact',async()=>{
  const {game,a}=context(M,role);put(M,game,a,'Noctis, Prince of Lucis');const card=put(M,game,a,'Sol Ring','graveyard');fund(a);const life=a.life,action=game.castableList(a).find(row=>row.card===card&&row.alt?.starterPermission==='oracle-v20');assert.ok(action);assert.equal(await game.castSpell(a,card,{from:'graveyard',alt:action.alt}),true);assert.equal(a.life,life-3);await settle(game);assert.equal(card.zone,'battlefield');assert.equal(card.counters.finality,1);await game.destroy(card);assert.equal(card.zone,'exile');assertGameStateInvariants(game);
 });
 test(role+': conditional graveyard casting observes an actual other-creature death and adds the printed entry counter',async()=>{
  const {game,a}=context(M,role),card=put(M,game,a,'Undead Sprinter','graveyard');fund(a);assert.equal(game.castableList(a).some(row=>row.card===card),false);const donor=put(M,game,a,'Grizzly Bears');await game.sacrifice(a,donor);await settle(game);const action=game.castableList(a).find(row=>row.card===card&&row.alt?.starterPermission==='oracle-v20');assert.ok(action);assert.equal(await game.castSpell(a,card,{from:'graveyard',alt:action.alt}),true);await settle(game);assert.equal(card.zone,'battlefield');assert.equal(card.counters['+1/+1'],1);assertGameStateInvariants(game);
 });
 test(role+': automatic mana conversion applies the same Training Grounds floor as manual activation',async()=>{
  const {game,a}=context(M,role);put(M,game,a,'Training Grounds');const source=put(M,game,a,'Pili-Pala'),spell=put(M,game,a,'Llanowar Elves','hand');source.tapped=true;a.pool.C=1;assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(source.tapped,false);assert.equal(a.pool.C,0);await settle(game);assert.equal(spell.zone,'battlefield');assertGameStateInvariants(game);
 });
 test(role+': Assist asks one other player, pays only generic mana, and combines actual payment evidence',async()=>{
  const {game,a,b}=context(M,role),spell=put(M,game,a,'Charging Binox','hand');a.pool.G=1;for(let i=0;i<7;i++)put(M,game,b,'Forest');choice(b,(g,q)=>q.aiHint?.kind==='oracleAssistV20'&&q.type==='chooseX'?q.max:undefined);if(role==='human')choice(a,(g,q)=>q.aiHint?.kind==='oracleAssistV20'&&q.type==='chooseOption'?String(b.idx):undefined);
  assert.equal(game.castableList(a).some(x=>x.card===spell),true);assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(game.stack.find(x=>x.card===spell).manaSpent,8);assert.equal(game.lands(b).filter(x=>x.tapped).length,7);assert.equal(a.pool.G,0);await settle(game);assert.equal(spell.zone,'battlefield');assertGameStateInvariants(game);
 });
 test(role+': declined or stale Assist payments do not tap lands or spend the caster mana',async()=>{
  const {game,a,b}=context(M,role),spell=put(M,game,a,'Charging Binox','hand');a.pool.G=1;for(let i=0;i<7;i++)put(M,game,b,'Forest');choice(a,(g,q)=>q.aiHint?.kind==='oracleAssistV20'&&q.type==='chooseOption'?String(b.idx):undefined);choice(b,(g,q)=>q.aiHint?.kind==='oracleAssistV20'&&q.type==='chooseX'?0:undefined);
  assert.equal(await game.castSpell(a,spell,{from:'hand'}),false);assert.equal(a.pool.G,1);assert.equal(game.lands(b).some(c=>c.tapped),false);assert.equal(spell.zone,'hand');
  choice(b,(g,q)=>{if(q.aiHint?.kind==='oracleAssistV20'&&q.type==='chooseX'){game.lands(b)[0].tapped=true;return q.max;}return undefined;});assert.equal(await game.castSpell(a,spell,{from:'hand'}),false);assert.equal(a.pool.G,1);assert.equal(game.lands(b).filter(c=>c.tapped).length,1);assert.equal(spell.zone,'hand');assertGameStateInvariants(game);
 });
 test(role+': Omniscience casts a hand spell without mana and rejects lost or forged permission',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Omniscience'),spell=put(M,game,a,'Grizzly Bears','hand');
  const action=game.castableList(a).find(x=>x.card===spell&&x.alt?.starterPermission==='oracle-v20');assert.ok(action);assert.equal(await game.castSpell(a,spell,{from:'hand',alt:{...action.alt,speed:'instant'}}),false);assert.equal(await game.castSpell(a,spell,{from:'hand',alt:action.alt}),true);await settle(game);assert.equal(spell.zone,'battlefield');assert.equal(Object.values(a.pool).reduce((x,y)=>x+y,0),0);
  const next=put(M,game,a,'Grizzly Bears','hand'),old=game.castableList(a).find(x=>x.card===next&&x.alt?.starterPermission==='oracle-v20');assert.ok(old);await game.move(source,'exile');assert.equal(await game.castSpell(a,next,{from:'hand',alt:old.alt}),false);assert.equal(next.zone,'hand');assertGameStateInvariants(game);
 });
 test(role+': Assemble the Players allows the top small creature once per turn and revalidates its top-card identity',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Assemble the Players'),spell=put(M,game,a,'Grizzly Bears','library');fund(a);const old=game.castableList(a).find(x=>x.card===spell&&x.alt?.starterPermission==='oracle-v20');assert.ok(old);const blocker=put(M,game,a,'Serra Angel','library');assert.equal(game.castableList(a).some(x=>x.card===blocker),false);assert.equal(await game.castSpell(a,spell,{from:'library',alt:old.alt}),false);await game.move(blocker,'hand');assert.equal(await game.castSpell(a,spell,{from:'library',alt:old.alt}),true);await settle(game);const next=put(M,game,a,'Grizzly Bears','library');assert.equal(game.castableList(a).some(x=>x.card===next),false);game.turnNo++;assert.equal(game.castableList(a).some(x=>x.card===next),true);M.OracleV8AbilityLoss.add(game,[source],{});assert.equal(game.castableList(a).some(x=>x.card===next),false);assertGameStateInvariants(game);
 });
 test(role+': graveyard and hand mana costs reserve exact cards and keep spending restrictions on floating mana',async()=>{
  const {game,a}=context(M,role),nest=put(M,game,a,"Titans' Nest"),material=put(M,game,a,'Forest','graveyard');const action=game.activatableList(a).find(x=>x.card===nest&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(material.zone,'exile');const plain=put(M,game,a,'Sol Ring','hand'),colored=put(M,game,a,'Grizzly Bears','hand');assert.equal(game.canPayMana(a,M.parseCost('{1}'),{card:plain,castOpts:{}}),false);assert.equal(game.canPayMana(a,M.parseCost('{1}'),{card:colored,castOpts:{}}),true);assert.equal(game.canPayMana(a,M.parseCost('{1}'),{card:colored,isAbility:true,ability:{}}),false);
  const bloom=put(M,game,a,'Cadaverous Bloom'),hand=put(M,game,a,'Forest','hand');choice(a,(g,q)=>q.type==='chooseCards'&&q.from.includes(hand)?[hand]:undefined);const use=game.activatableList(a).find(x=>x.card===bloom&&x.manaAbility);assert.ok(use);assert.equal(await game.activateAbility(a,use),true);assert.equal(hand.zone,'exile');assert.equal((a.pool.B||0)+(a.pool.G||0),2);assertGameStateInvariants(game);
 });
 test(role+': kicked and instant-only mana retain their exact payment permissions',async()=>{
  const {game,a}=context(M,role),druid=put(M,game,a,'Elfhame Druid'),creature=put(M,game,a,'Grizzly Bears','hand'),spell=put(M,game,a,'Brainstorm','hand');const source=game.manaSources(a,null,{includeRestricted:true}).find(x=>x.card===druid&&x.m.restrict);assert.ok(source);assert.equal(source.m.restrict(game,{card:creature,castOpts:{}},druid),false);assert.equal(source.m.restrict(game,{card:creature,castOpts:{_kicked:true}},druid),true);const observer=put(M,game,a,'Unblinking Observer'),action=game.activatableList(a).find(x=>x.card===observer&&x.manaAbility);assert.equal(await game.activateAbility(a,action),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:spell,castOpts:{}}),true);assert.equal(game.canPayMana(a,M.parseCost('{U}'),{card:creature,castOpts:{}}),false);assertGameStateInvariants(game);
 });
 test(role+': impending rejects altered and incomplete alternative costs before payment',async()=>{
  const {game,a}=context(M,role),c=put(M,game,a,'Overlord of the Boilerbilges','hand');fund(a);const action=game.castableList(a).find(x=>x.card===c&&x.alt?.oracleImpendingV20);assert.ok(action);const total=Object.values(a.pool).reduce((x,y)=>x+y,0);for(const alt of [{...action.alt,altCostStr:'{0}'},{...action.alt,free:true},{altCostStr:action.alt.altCostStr}])assert.equal(await game.castSpell(a,c,{from:'hand',alt}),false);assert.equal(c.zone,'hand');assert.equal(Object.values(a.pool).reduce((x,y)=>x+y,0),total);assertGameStateInvariants(game);
 });
 test(role+': hand mana exiles the exact Spirit Guide immediately and pays spells',async()=>{
  const {game,a}=context(M,role),c=put(M,game,a,'Simian Spirit Guide','hand');
  const action=game.activatableList(a).find(x=>x.card===c&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(c.zone,'exile');assert.equal(a.pool.R,1);assert.equal(game.stack.length,0);assert.equal(await game.activateAbility(a,action),false);assert.equal(a.pool.R,1);
  const e=put(M,game,a,'Elvish Spirit Guide','hand'),spell=put(M,game,a,'Llanowar Elves','hand');assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(e.zone,'exile');await settle(game);assert.equal(spell.zone,'battlefield');assertGameStateInvariants(game);
 });
 test(role+': Skirge mana reserves a different discarded card for every activation and cannot discard the spell being paid',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Skirge Familiar'),payment=put(M,game,a,'Forest','hand'),spell=put(M,game,a,'Grizzly Bears','hand');spell.def={...spell.def,cost:'{B}{B}'};
  assert.equal(await game.castSpell(a,spell,{from:'hand'}),false);assert.equal(payment.zone,'hand');assert.equal(a.pool.B,0);
  const second=put(M,game,a,'Island','hand');assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(payment.zone,'graveyard');assert.equal(second.zone,'graveyard');assert.equal(source.zone,'battlefield');await settle(game);assert.equal(spell.zone,'battlefield');assertGameStateInvariants(game);
 });
 test(role+': Bog Witch pays black, tap and discard before adding three black with no stack object',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Bog Witch'),payment=put(M,game,a,'Forest','hand');a.pool.B=1;
  const action=game.activatableList(a).find(x=>x.card===source&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(payment.zone,'graveyard');assert.equal(source.tapped,true);assert.equal(a.pool.B,3);assert.equal(game.stack.length,0);assertGameStateInvariants(game);
 });
 test(role+': untap mana requires a tapped nonsick creature and cannot use the same untap twice',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Pili-Pala');a.pool.C=4;assert.equal(game.activatableList(a).some(x=>x.card===source),false);
  source.tapped=true;source.sick=true;assert.equal(game.activatableList(a).some(x=>x.card===source),false);source.sick=false;
  choice(a,(g,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='manaColor'?'4':undefined);
  const action=game.activatableList(a).find(x=>x.card===source&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(source.tapped,false);assert.equal(a.pool.C,2);assert.equal(a.pool.G,1);assert.equal(await game.activateAbility(a,action),false);assert.equal(a.pool.C,2);assertGameStateInvariants(game);
 });
 test(role+': mana cancellation consumes neither black nor the source tap',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Bog Witch');put(M,game,a,'Forest','hand');put(M,game,a,'Island','hand');a.pool.B=1;choice(a,(g,q)=>q.type==='chooseCards'?[]:undefined);
  const action=game.activatableList(a).find(x=>x.card===source&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),false);assert.equal(source.tapped,false);assert.equal(a.pool.B,1);assert.equal(a.hand.length,2);assertGameStateInvariants(game);
 });
 test(role+': Bloom Tender adds each represented color exactly once and ignores opposing permanents',async()=>{
  const {game,a,b}=context(M,role),source=put(M,game,a,'Bloom Tender');put(M,game,a,'Grizzly Bears');put(M,game,a,'Serra Angel');put(M,game,b,'Bog Witch');const action=game.activatableList(a).find(x=>x.card===source&&x.manaAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(a.pool.G,1);assert.equal(a.pool.W,1);assert.equal(a.pool.B,0);assertGameStateInvariants(game);
 });
 test(role+': Training Grounds and Heartstone respect the one-mana floor, colored symbols, control and ability loss',()=>{
  const {game,a,b}=context(M,role),training=put(M,game,a,'Training Grounds'),own=put(M,game,a,'Grizzly Bears'),enemy=put(M,game,b,'Grizzly Bears');
  assert.equal(game.abilityManaCost(a,own,'{3}').generic,1);assert.equal(game.abilityManaCost(a,own,'{1}').generic,1);assert.equal(game.abilityManaCost(a,own,'{0}').generic,0);assert.equal(game.abilityManaCost(b,enemy,'{3}').generic,3);assert.equal(game.abilityManaCost(a,own,'{2}{G}').generic,0);M.OracleV8AbilityLoss.add(game,[training],{});assert.equal(game.abilityManaCost(a,own,'{3}').generic,3);put(M,game,a,'Heartstone');assert.equal(game.abilityManaCost(b,enemy,'{3}').generic,2);assertGameStateInvariants(game);
 });
 test(role+': library-top permission offers and casts the actual top card and disappears on source ability loss',async()=>{
  const {game,a}=context(M,role),source=put(M,game,a,'Magus of the Future'),spell=put(M,game,a,'Grizzly Bears','library');fund(a);let action=game.castableList(a).find(x=>x.card===spell&&x.from==='library');assert.ok(action);assert.equal(await game.castSpell(a,spell,{alt:action.alt,from:action.from}),true);await settle(game);assert.equal(spell.zone,'battlefield');M.OracleV8AbilityLoss.add(game,[source],{});const next=put(M,game,a,'Grizzly Bears','library');assert.equal(game.castableList(a).some(x=>x.card===next),false);assertGameStateInvariants(game);
 });
 test(role+': impending counts down from a noncreature enchantment and the full-cost cast has no time counters',async()=>{
  const {game,a}=context(M,role);fund(a);const c=put(M,game,a,'Overlord of the Boilerbilges','hand');const action=game.castableList(a).find(x=>x.card===c&&x.alt?.oracleImpendingV20);assert.ok(action);assert.equal(await game.castSpell(a,c,{alt:action.alt,from:'hand'}),true);await settle(game);assert.equal(c.is('Creature'),false);assert.equal(c.counters.time,4);for(let i=0;i<4;i++){await game.emit('endStep',{player:a});await settle(game);}assert.equal(c.counters.time,0);assert.equal(c.is('Creature'),true);const full=put(M,game,a,'Overlord of the Boilerbilges','hand');assert.equal(await game.castSpell(a,full,{from:'hand'}),true);await settle(game);assert.equal(full.is('Creature'),true);assert.equal(full.counters.time||0,0);assertGameStateInvariants(game);
 });
 test(role+': finality recursion preserves the graveyard object until resolution and does not follow a blinked graveyard card',async()=>{
  const {game,a}=context(M,role),c=put(M,game,a,'Relentless X-ATM092','graveyard');fund(a);let action=game.activatableList(a).find(x=>x.card===c&&x.gyAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);assert.equal(c.zone,'graveyard');await settle(game);assert.equal(c.zone,'battlefield');assert.equal(c.counters.finality,1);assert.equal(c.tapped,true);await game.move(c,'graveyard');if(c.zone==='exile')await game.move(c,'graveyard');action=game.activatableList(a).find(x=>x.card===c&&x.gyAbility);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);await game.move(c,'exile');await game.move(c,'graveyard');await settle(game);assert.equal(c.zone,'graveyard');assertGameStateInvariants(game);
 });
}
