import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v24-spells.json',import.meta.url))),M=loadEngine(),absent=rows.filter(card=>!M.DEFS[card.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9944,limit:absent.length,compilerVersion:24});assert.equal(plan.report.cards.length,absent.length);M.registerOracleBatch(plan.report);}M.initData(M.RAW_DATA);
const total=p=>Object.values(p.pool).reduce((n,value)=>n+value,0),fund=p=>{for(const color in p.pool)p.pool[color]=30;};
function choose(p,fn){const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>fn(g,q)??prior(g,q);}
function creature(f,p=f.a,{zone='battlefield',power='2',toughness='30',cost='{1}{G}',kws=[]}={}){const card=put(M,f.game,p,'Grizzly Bears',zone);card.def={...card.def,cost,power,toughness,kws};f.game.recalc();return card;}
function setup(role,name,picks){const f=context(M,role),source=put(M,f.game,f.a,name,'hand'),dual=source.def.oracleDualKickerV24;fund(f.a);fund(f.b);const enemy=creature(f,f.b,{power:'1',kws:['flying']}),own=creature(f);put(M,f.game,f.b,'Sol Ring');put(M,f.game,f.b,'Rancor');put(M,f.game,f.b,'Forest');for(let i=0;i<4;i++)put(M,f.game,f.b,'Forest','hand');choose(f.a,(g,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='kicker'&&dual?(picks.some(i=>q.prompt.includes('its '+dual[i]+' kicker'))?'yes':'no'):q.type==='chooseCards'&&q.prompt.includes('phase out')?q.from.slice(0,q.max):q.type==='chooseTargets'?(q.candidates.includes(enemy)?[enemy]:q.candidates.includes(f.b)?[f.b]:undefined):undefined);return {...f,source,enemy,own};}
test('v24 spell fixtures compile their complete printed rules and reject unknown suffixes',()=>{for(const card of rows){assert.ok(semanticClass(card,{compilerVersion:24}).semanticClass,card.name);assert.equal(semanticClass({...card,oracle_text:card.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:24}).semanticClass,undefined,card.name);}});
for(const role of ['human','ai']){
 test(role+': Burn at the Stake counts only its printed cost when Wort also grants Conspire',async()=>{
  const f=context(M,role),card=put(M,f.game,f.a,'Burn at the Stake','hand'),printed=creature(f,f.a,{cost:'{R}'}),conspirers=[creature(f,f.a,{cost:'{R}'}),creature(f,f.a,{cost:'{R}'})];put(M,f.game,f.a,'Wort, the Raidmother');fund(f.a);
  choose(f.a,(g,q)=>q.type==='chooseOption'&&q.prompt.startsWith('Conspire')?'yes':q.type==='chooseCards'&&q.prompt.startsWith('Conspire')?conspirers:q.type==='chooseCards'&&q.aiHint?.kind==='addlTap'?[printed]:q.type==='chooseTargets'?[f.b]:undefined);
  assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);const so=f.game.stack.find(so=>so.card===card);assert.equal(so.additionalTapped.length,3);assert.equal(so.castOpts.oracleTapPaymentCountV24,1);assert.ok([printed,...conspirers].every(c=>c.tapped));assert.ok(f.game.stack.some(so=>so.kind==='trigger'&&so.name.includes('Conspire')));await settle(f.game);assert.equal(f.b.life,34);assertGameStateInvariants(f.game);
 });
 test(role+': Devouring Greed counts only its printed Spirit sacrifice when Anhelo grants Casualty',async()=>{
  const f=context(M,role),card=put(M,f.game,f.a,'Devouring Greed','hand'),printed=creature(f),casualty=creature(f);printed.def={...printed.def,subtypes:['Spirit']};put(M,f.game,f.a,'Anhelo, the Painter');f.game.recalc();fund(f.a);
  choose(f.a,(g,q)=>q.type==='chooseOption'&&q.prompt.startsWith('Casualty')?'yes':q.type==='chooseCards'&&q.prompt.startsWith('Casualty')?[casualty]:q.type==='chooseCards'&&q.prompt.includes('sacrifice any number')?[printed]:q.type==='chooseTargets'?[f.b]:undefined);
  assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);const so=f.game.stack.find(so=>so.card===card);assert.equal(printed.zone,'graveyard');assert.equal(casualty.zone,'graveyard');assert.deepEqual(Array.from(so.castOpts.oracleAggregateSacIdsV24),[printed.iid]);assert.ok(f.game.stack.some(so=>so.kind==='trigger'&&so.name.includes('Casualty')));await settle(f.game);assert.equal(f.b.life,32);assert.equal(f.a.life,48);assertGameStateInvariants(f.game);
 });
 for(const name of ['Devouring Rage','Devouring Greed','Corpse Cobble','Vicious Betrayal','Burn at the Stake','Taste of Paradise'])for(const n of [0,1,2])test(role+': '+name+' retains its actual aggregate payment '+n+' on copied spells',async()=>{
  const f=context(M,role),card=put(M,f.game,f.a,name,'hand'),donors=Array.from({length:2},(_,i)=>creature(f,f.a,{power:String(i+2)})),target=creature(f,f.b),copies=[];donors.forEach(c=>c.def={...c.def,subtypes:['Spirit']});f.game.recalc();fund(f.a);let sourceX;
  choose(f.a,(g,q)=>q.type==='chooseCards'&&(q.prompt.includes('sacrifice any number')||q.prompt.includes('Tap creatures'))?donors.slice(0,n):q.type==='chooseX'&&q.prompt.includes('any number of times')?n:q.type==='chooseTargets'?(name==='Devouring Greed'||name==='Burn at the Stake'?[f.b]:[target]):undefined);
  if(name==='Burn at the Stake')choose(f.a,(g,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='addlTap'?donors.slice(0,n):undefined);
  const mana=total(f.a),base=M.parseCost(card.def.cost),versions=donors.map(c=>c.zoneVersion);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);const so=f.game.stack.find(so=>so.card===card);assert.equal(so.kicked,false);assert.equal(so.x,0);assert.equal(mana-total(f.a),base.generic+base.pips.length+(name==='Taste of Paradise'?2*n:0));
  if(['Devouring Rage','Devouring Greed','Corpse Cobble','Vicious Betrayal'].includes(name)){assert.equal(so.oracleV4AdditionalCost.sacrifices.length,n);for(let i=0;i<donors.length;i++){assert.equal(donors[i].zone,i<n?'graveyard':'battlefield');assert.equal(donors[i].zoneVersion,versions[i]+(i<n?1:0));}for(const donor of donors.slice(0,n)){await f.game.move(donor,'hand');donor.def={...donor.def,power:'20'};}}
  if(name==='Burn at the Stake'){assert.equal(so.additionalTapped.length,n);assert.equal(donors.filter(c=>c.tapped).length,n);}
  const copy=await f.game.copySpell(so,f.a,{mayNewTargets:false});await settle(f.game);
  if(name==='Devouring Greed'){assert.equal(f.b.life,40-2*(2+2*n));assert.equal(f.a.life,40+2*(2+2*n));}
  if(name==='Devouring Rage')assert.equal(target.power,2+2*(3+3*n));
  if(name==='Vicious Betrayal'){assert.equal(target.power,2+4*n);assert.equal(target.toughness,30+4*n);}
  if(name==='Burn at the Stake')assert.equal(f.b.life,40-6*n);
  if(name==='Taste of Paradise')assert.equal(f.a.life,40+2*(3+3*n));
  if(name==='Corpse Cobble'){const tokens=f.game.bf().filter(c=>c.isToken&&c.hasSub('Zombie'));assert.equal(tokens.length,n?2:0);assert.ok(tokens.every(c=>c.power===(n===1?2:5)&&c.toughness===(n===1?2:5)&&c.kw('menace')));}
  assertGameStateInvariants(f.game);
 });
 test(role+': an aggregate payment cannot select a duplicate, wrong subtype, or stale object',async()=>{for(const mode of ['duplicate','type','stale']){const f=context(M,role),card=put(M,f.game,f.a,'Devouring Greed','hand'),donor=creature(f),wrong=creature(f);donor.def={...donor.def,subtypes:['Spirit']};f.game.recalc();fund(f.a);choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('sacrifice any number')?(mode==='duplicate'?[donor,donor]:mode==='type'?[wrong]:(async()=>{await g.move(donor,'exile');await g.putPermanentOntoBattlefield(donor,f.a);return [donor];})()):q.type==='chooseTargets'?[f.b]:undefined);const mana=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),false);assert.equal(total(f.a),mana);assert.equal(card.zone,'hand');assert.equal(donor.zone,'battlefield');assertGameStateInvariants(f.game);}});
 test(role+': Corpse Cobble Flashback also pays its real additional sacrifice cost',async()=>{const f=context(M,role),card=put(M,f.game,f.a,'Corpse Cobble','graveyard'),donor=creature(f,f.a,{power:'4'});fund(f.a);choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('sacrifice any number')?[donor]:undefined);const offer=f.game.castableList(f.a).find(row=>row.card===card&&row.from==='graveyard'&&row.alt?.flashback);assert.ok(offer);const mana=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'graveyard',alt:offer.alt}),true);assert.equal(mana-total(f.a),5);assert.equal(donor.zone,'graveyard');await settle(f.game);assert.equal(card.zone,'exile');assert.ok(f.game.bf().some(c=>c.isToken&&c.hasSub('Zombie')&&c.power===4));assertGameStateInvariants(f.game);});
 test(role+': repeated additional mana rejects an unaffordable or forged count',async()=>{const f=context(M,role),card=put(M,f.game,f.a,'Taste of Paradise','hand');f.a.pool.G=1;f.a.pool.C=3;let questions=0;choose(f.a,(g,q)=>q.type==='chooseX'?(questions++,10):undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',alt:{oracleRepeatedAdditionalV24:10}}),true);assert.equal(questions,0);assert.equal(f.game.stack.at(-1).castOpts.oracleRepeatedAdditionalV24,0);await settle(f.game);assert.equal(f.a.life,43);assertGameStateInvariants(f.game);});
 for(const row of rows.filter(card=>/Kicker [^\n]+ and\/or /.test(card.oracle_text)))for(const picks of [[],[0],[1],[0,1]])test(role+': '+row.name+' pays the chosen dual kicker subset '+picks.join(','),async()=>{
  const f=setup(role,row.name,picks),{game,a,b,source,enemy}=f,cost=M.parseCost(source.def.cost),before=total(a),initialLife=a.life,initialHand=a.hand.length,initialGY=a.graveyard.length;
  assert.equal(await game.castSpell(a,source,{from:'hand',xVal:4}),true);const so=game.stack.find(so=>so.card===source);assert.deepEqual(Array.from(so.castOpts.oracleDualKickerV24),picks);assert.equal(so.kicked,!!picks.length);assert.equal(source.castMeta.paidTimes,picks.length);
  const expected=cost.generic+cost.pips.length+(cost.x||0)*4+picks.reduce((n,i)=>{const cost=M.parseCost(source.def.oracleDualKickerV24[i]);return n+cost.generic+cost.pips.length;},0);assert.equal(before-total(a),expected);
  await settle(game);
  const grants=source.def.oracleImplementation.filter(op=>op.kind==='dual-kicker-entry-v24');if(grants.length){assert.equal(source.counters['+1/+1']||0,grants.filter(op=>picks.includes(source.def.oracleDualKickerV24.indexOf(op.cost))).reduce((n,op)=>n+op.counters,0));for(const op of grants)for(const keyword of op.keywords)assert.equal(source.kw(keyword),picks.includes(source.def.oracleDualKickerV24.indexOf(op.cost)));}
  if(row.name==='Vodalian Mindsinger'){assert.equal(source.counters['+1/+1']||0,2*picks.length);assert.equal(enemy.ctrl,a);}
  if(row.name==='Stronghold Arena')assert.equal(a.life,initialLife+3*picks.length);
  if(row.name==='Urborg Lhurgoyf')assert.equal(a.graveyard.length-initialGY,3*picks.length);
  if(row.name==='Illuminate'){assert.equal(enemy.damage,4);assert.equal(b.life,picks.includes(0)?36:40);assert.equal(a.hand.length,initialHand-1+(picks.includes(1)?4:0));}
  if(row.name==='Temporal Firestorm'){assert.equal(game.battlefield.filter(card=>card.ctrl===a&&card.phasedOut).length,Math.min(picks.length,1));assert.equal(enemy.damage,5);}
  assertGameStateInvariants(game);
 });
 for(const row of rows.filter(card=>/^March of /.test(card.name)))for(const n of [0,1,2])test(role+': '+row.name+' really exiles '+n+' colored hand cards for its X reduction',async()=>{
  const f=context(M,role),card=put(M,f.game,f.a,row.name,'hand'),op=card.def.oracleHandExileReductionV24,donors=Array.from({length:2},()=>creature(f,f.a,{zone:'hand',cost:'{'+op.color+'}'})),enemy=creature(f,f.b),versions=donors.map(card=>card.zoneVersion);const copy=creature(f,f.a,{zone:'library'});f.a.pool[op.color]=1;f.a.pool.C=4-2*n;
  choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('exile colored hand cards')?donors.slice(0,n):q.type==='chooseCards'&&q.prompt.includes('same name')?[copy]:q.type==='chooseTargets'?[enemy]:undefined);
  assert.ok(f.game.castableList(f.a).some(row=>row.card===card));const before=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',xVal:4}),true);assert.equal(before-total(f.a),5-2*n);const so=f.game.stack.find(so=>so.card===card);assert.equal(so.x,4);assert.equal(so.oracleV4AdditionalCost?.handExiles.length||0,n);for(let i=0;i<2;i++){assert.equal(donors[i].zone,i<n?'exile':'hand');assert.equal(donors[i].zoneVersion,versions[i]+(i<n?1:0));}
  await settle(f.game);if(row.name==='March of Wretched Sorrow'){assert.equal(enemy.damage,4);assert.equal(f.a.life,44);}if(row.name==='March of Otherworldly Light')assert.equal(enemy.zone,'exile');if(row.name==='March of Swirling Mist')assert.equal(enemy.phasedOut,true);if(row.name==='March of Burgeoning Life'){assert.equal(copy.zone,'battlefield');assert.equal(copy.tapped,true);}assertGameStateInvariants(f.game);
 });
 test(role+': a dual kicker spell copy keeps both paid choices and entry grants after the original is countered',async()=>{const f=setup(role,'Rakavolver',[0,1]);assert.equal(await f.game.castSpell(f.a,f.source,{from:'hand'}),true);const original=f.game.stack.find(so=>so.card===f.source),copy=await f.game.copySpell(original,f.a,{mayNewTargets:false});assert.deepEqual(Array.from(copy.castOpts.oracleDualKickerV24),[0,1]);await f.game.counterStackObject(original);await settle(f.game);const token=f.game.bf().find(card=>card.isToken&&card.name==='Rakavolver');assert.ok(token);assert.equal(token.counters['+1/+1'],3);assert.equal(token.kw('flying'),true);const life=f.a.life;await f.game.damageAny(token,f.b,3);assert.equal(f.a.life,life);await settle(f.game);assert.equal(f.a.life,life+3);assertGameStateInvariants(f.game);});
 test(role+': kicked entry grants end on blink and do not become copiable permanent characteristics',async()=>{const f=setup(role,'Anavolver',[0,1]);assert.equal(await f.game.castSpell(f.a,f.source,{from:'hand'}),true);await settle(f.game);const [copy]=await f.game.copyPermanentToken(f.source,f.a);assert.equal(copy.kw('flying'),false);assert.equal(copy.counters['+1/+1']||0,0);await f.game.move(f.source,'exile');await f.game.putPermanentOntoBattlefield(f.source,f.a);assert.equal(f.source.kw('flying'),false);assert.equal(f.source.counters['+1/+1']||0,0);assertGameStateInvariants(f.game);});
 test(role+': the damage-life granted ability triggers after damage rather than during it',async()=>{const f=setup(role,'Necravolver',[1]);assert.equal(await f.game.castSpell(f.a,f.source,{from:'hand'}),true);await settle(f.game);const life=f.a.life;await f.game.damageAny(f.source,f.b,3);assert.equal(f.a.life,life);await settle(f.game);assert.equal(f.a.life,life+3);assertGameStateInvariants(f.game);});
 test(role+': March donor incarnation changes abort before mana payment',async()=>{const f=context(M,role),card=put(M,f.game,f.a,'March of Wretched Sorrow','hand'),donor=creature(f,f.a,{zone:'hand',cost:'{B}'}),enemy=creature(f,f.b);f.a.pool.B=1;choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('exile colored hand cards')?(async()=>{await g.move(donor,'exile');await g.move(donor,'hand');return [donor];})():q.type==='chooseTargets'?[enemy]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',xVal:2}),false);assert.equal(f.a.pool.B,1);assert.equal(card.zone,'hand');assert.equal(donor.zone,'hand');assertGameStateInvariants(f.game);});
 test(role+': March Burgeoning rejects equal mana value and accepts strict less-than X',async()=>{for(const x of [2,3]){const f=context(M,role),card=put(M,f.game,f.a,'March of Burgeoning Life','hand'),enemy=creature(f,f.b),found=creature(f,f.a,{zone:'library'});f.a.pool.G=1;f.a.pool.C=4;choose(f.a,(g,q)=>q.type==='chooseTargets'?[enemy]:q.type==='chooseCards'&&q.prompt.includes('same name')?[found]:q.type==='chooseCards'&&q.prompt.includes('exile colored hand cards')?[]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',xVal:x}),x>2);if(x>2){await settle(f.game);assert.equal(found.zone,'battlefield');assert.equal(found.tapped,true);}else{assert.equal(card.zone,'hand');assert.equal(f.a.pool.C,4);}assertGameStateInvariants(f.game);}});
 test(role+': a legal target that leaves and returns cannot be followed by the same-name search',async()=>{const f=context(M,role),card=put(M,f.game,f.a,'March of Burgeoning Life','hand'),enemy=creature(f,f.b),found=creature(f,f.a,{zone:'library'});fund(f.a);choose(f.a,(g,q)=>q.type==='chooseTargets'?[enemy]:q.type==='chooseCards'&&q.prompt.includes('exile colored hand cards')?[]:q.type==='chooseCards'&&q.prompt.includes('same name')?[found]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',xVal:3}),true);await f.game.move(enemy,'exile');await f.game.putPermanentOntoBattlefield(enemy,f.b);await settle(f.game);assert.equal(found.zone,'library');assertGameStateInvariants(f.game);});
 test(role+': insufficient mana cannot offer a dual kicker and forged choices do not activate its branch',async()=>{const f=context(M,role),card=put(M,f.game,f.a,'Stronghold Arena','hand');f.a.pool.B=1;f.a.pool.C=1;let prompts=0;choose(f.a,(g,q)=>q.type==='chooseOption'&&q.aiHint?.kind==='kicker'?(prompts++,'yes'):undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',alt:{oracleDualKickerV24:[0,1]}}),true);assert.equal(prompts,0);assert.deepEqual(Array.from(f.game.stack.at(-1).castOpts.oracleDualKickerV24),[]);await settle(f.game);assert.equal(f.a.life,40);assertGameStateInvariants(f.game);});
}
