import test from 'node:test';
import assert from 'node:assert/strict';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,settle} from './helpers/oracle-v8-fixtures.mjs';
import {def,put,permanent,choose,total} from './helpers/oracle-v30-permanents-proof.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const M=loadEngine();
for(const role of ['human','ai'])test(`${role}: Three Tree City offers and pays its mana conversion through the native manual action`,async()=>{
 const {game:g,a,b}=context(M,role);
 choose(a,q=>q.type==='chooseOption'&&q.options.some(o=>o.key==='Elf')?{...q,options:q.options.filter(o=>o.key==='Elf')}:q.type==='chooseOption'&&q.options.some(o=>o.mana?.G===2)?{...q,options:q.options.filter(o=>o.mana?.G===2)}:null);
 const city=put(M,a,'Three Tree City','hand');
 assert.equal(await g.playLand(a,city),true);await settle(g);
 for(const p of [a,a,b])permanent(M,g,p,def('Native mana visibility Elf',['Creature'],{subtypes:['Elf']}));
 const forest=permanent(M,g,a,M.DEFS.Forest),zeroFee=permanent(M,g,a,def('Native zero fee land',['Land'],{cost:null,mana:{cost:{tap:true,mana:'{0}'},produce:[{W:1}]}}));
 for(const color of ['W','U','B','R','G','C'])a.pool[color]=0;a.pool.C=2;
 const actions=g.activatableList(a),paid=actions.find(r=>r.card===city&&r.manaAbility&&r.manaSource.extraCost.mana==='{2}');
 assert.ok(paid,'the actual paid mana source appears on the card action list');
 assert.equal(actions.some(r=>r.card===forest&&r.manaAbility),false,'plain Forest retains normal automatic payment');
 assert.equal(actions.some(r=>r.card===zeroFee&&r.manaAbility),false,'a printed zero fee does not create a manual action');
 await g.move(zeroFee,'exile');
 a.pool.C=0;
 assert.equal(g.activatableList(a).some(r=>r.card===city&&r.manaAbility),false,'the tap source cannot fund its own fee');
 const before={...a.pool};
 assert.equal(await g.activateAbility(a,paid),false,'a stale listed action rechecks payment');
 assert.deepEqual({...a.pool},before);assert.equal(city.tapped,false);assert.equal(forest.tapped,false);assert.equal(zeroFee.tapped,false);
 a.pool.C=2;const current=g.activatableList(a).find(r=>r.card===city&&r.manaAbility),mana=total(a);
 assert.ok(current);assert.equal(await g.activateAbility(a,current),true);await settle(g);
 assert.equal(city.tapped,true);assert.equal(a.pool.G,2,'only the two controlled Elves contribute');assert.equal(a.pool.C,0);
 assert.equal(total(a),mana,'the two mana fee is paid before producing two green mana');
 assert.equal(forest.tapped,false);assert.equal(zeroFee.tapped,false);
 assert.equal(a.controller instanceof M.AIController,role==='ai');assertGameStateInvariants(g);
});
