import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{loadEngine}from'./helpers/load-engine.mjs';import{context,settle}from'./helpers/oracle-v8-fixtures.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';import{assertGameStateInvariants}from'./helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v26-permanents.json',import.meta.url),'utf8')),M=loadEngine();const plan=createImportPlan({cards:rows,bulk:{type:'oracle_cards'},sequence:9960,limit:rows.length,compilerVersion:26});assert.equal(plan.report.cards.length,rows.length);const absent=plan.report.cards.filter(entry=>!M.DEFS[entry.raw.name]);if(absent.length)M.registerOracleBatch({...plan.report,cards:absent});M.initData(M.RAW_DATA);
const fund=p=>{for(const color of ['W','U','B','R','G','C'])p.pool[color]=100;},total=p=>Object.values(p.pool).reduce((n,x)=>n+x,0);
const def=(name,types=['Creature'],extra={})=>({name,types,subtypes:[],super:[],oracle:'',cost:'{2}',power:'2',toughness:'4',...extra});
const put=(p,d,zone='library')=>{const c=new M.CardInst(typeof d==='string'?M.DEFS[d]:d,p);c.zone=zone;p[zone].push(c);return c;};
const permanent=(g,p,d)=>{const c=put(p,d,'hand');p.hand.splice(p.hand.indexOf(c),1);c.zone='battlefield';c.ctrl=p;c.sick=false;g.battlefield.push(c);g.recalc();return c;};
const choose=(p,fn)=>{const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>prior(g,fn(q)||q);};
const cards=(p,list)=>choose(p,q=>q.type==='chooseCards'&&q.from.some(c=>list.includes(c))?{...q,from:q.from.filter(c=>list.includes(c)),min:Math.min(q.max,list.length),max:Math.min(q.max,list.length)}:null);
const targets=(p,list)=>choose(p,q=>q.type==='chooseTargets'&&q.candidates.some(c=>list.includes(c))?{...q,candidates:q.candidates.filter(c=>list.includes(c)),min:1,max:1}:null);
async function source(f,name){const {game:g,a}=f,c=put(a,name,'hand'),before=total(a);if(c.is('Land'))assert.equal(await g.playLand(a,c),true);else{assert.equal(await g.castSpell(a,c,{from:'hand'}),true);assert.ok(total(a)<before);}await settle(g);return c;}
async function activate(f,c,index=0){const {game:g,a}=f,option=g.activatableList(a).filter(row=>row.card===c&&!row.manaAbility)[index];assert.ok(option,c.name+' activation');assert.equal(await g.activateAbility(a,option),true);await settle(g);}
test('complete26 linked candidates preserve unknown-rider closure',()=>{for(const c of rows){assert.ok(semanticClass(c,{compilerVersion:26}).semanticClass,c.name);assert.equal(semanticClass({...c,oracle_text:c.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:26}).semanticClass,undefined);}});
for(const role of['human','ai'])for(const card of rows)test(role+': '+card.name+' paid source and native effects',async()=>{
 const f=context(M,role),{game:g,a,b}=f;fund(a);fund(b);const name=card.name;
 if(name==='Invader Parasite'){const donor=permanent(g,b,'Forest');targets(a,[donor]);const c=await source(f,name);assert.equal(donor.zone,'exile');const before=b.life;const matching=put(b,'Forest','hand');await g.putPermanentOntoBattlefield(matching,b);await settle(g);assert.equal(b.life,before-2);const other=put(b,'Island','hand');await g.putPermanentOntoBattlefield(other,b);await settle(g);assert.equal(b.life,before-2);await g.move(c,'exile');const another=put(b,'Forest','hand');await g.putPermanentOntoBattlefield(another,b);await settle(g);assert.equal(b.life,before-2);}
 else if(name==='Kaho, Minamo Historian'){const donors=[2,3,4].map(n=>put(a,def('Kaho spell '+n,['Instant'],{cost:'{'+n+'}',resolve:async ctx=>{ctx.you.kahoResolved=n;}})));cards(a,donors);const c=await source(f,name);assert.ok(donors.every(card=>card.zone==='exile'));c.sick=false;choose(a,q=>q.type==='chooseX'?{...q,min:3,max:3}:q.type==='chooseCards'&&/You may cast/.test(q.prompt||'')?{...q,min:1}:null);const before=total(a);await activate(f,c);assert.equal(total(a),before-3);assert.equal(a.kahoResolved,3);assert.equal(donors[1].zone,'graveyard');assert.equal(donors[0].zone,'exile');assert.equal(donors[2].zone,'exile');}
 else if(name==='Extraplanar Lens'){const donor=permanent(g,a,'Forest');targets(a,[donor]);const c=await source(f,name);assert.equal(donor.zone,'exile');for(const p of[a,b]){const land=permanent(g,p,'Forest'),before=p.pool.G;const mana=g.manaSources(p).find(row=>row.card===land);assert.ok(mana);assert.equal(await g.activateManaSource(p,mana,{G:1}),true);assert.equal(p.pool.G,before+2);assert.equal(g.stack.length,0,'bonus mana is a mana ability');}const island=permanent(g,b,'Island'),before=b.pool.U;assert.equal(await g.activateManaSource(b,g.manaSources(b).find(row=>row.card===island),{U:1}),true);assert.equal(b.pool.U,before+1);await g.move(c,'exile');}
 else if(name==='Northampton Farm'){const first=permanent(g,a,def('Farm first')),second=permanent(g,a,def('Farm second')),c=await source(f,name);for(const donor of[first,second]){g.untap(c);targets(a,[donor]);const before=total(a);await activate(f,c);assert.equal(total(a),before-1);assert.equal(donor.zone,'exile');}g.untap(c);cards(a,[first]);await activate(f,c,0);assert.equal(c.zone,'graveyard');assert.equal(first.zone,'battlefield');assert.equal(second.zone,'hand');}
 else if(name==='Yggdrasil, Rebirth Engine'){const creature=put(a,def('Yggdrasil grave creature'),'graveyard'),other=put(a,'Forest','graveyard'),c=await source(f,name);assert.equal(creature.zone,'exile');assert.equal(other.zone,'graveyard');const tops=[put(a,def('Yggdrasil top creature')),put(a,'Forest'),put(a,'Island')];await activate(f,c);assert.ok(tops.every(card=>card.zone==='exile'));g.untap(c);cards(a,[creature]);await activate(f,c,1);assert.equal(creature.zone,'battlefield');assert.equal(creature.kw('haste'),true);assert.equal(tops[0].zone,'exile');}
 else if(name==="Colfenor's Plans"){const hidden=Array.from({length:6},(_,i)=>put(a,def('Plans spell '+i,['Artifact'],{cost:'{1}'})));hidden.push(put(a,'Forest'));const c=await source(f,name);for(const donor of hidden){assert.equal(donor.zone,'exile');assert.equal(donor.faceDown,true);assert.deepEqual(Array.from(donor.meta.revealedTo),[a.idx]);assert.equal(g.hasExilePlayPermission(a,donor),true);}assert.equal(g.castableList(a).some(row=>row.card===hidden[0]),false,'source cast already consumed this-turn spell limit');g.turnNo++;a.turnState=a.freshTurnState();g.phase='main1';const row=g.castableList(a).find(row=>row.card===hidden[0]);assert.ok(row);assert.equal(await g.castSpell(a,hidden[0],{from:row.from,alt:row.alt}),true);await settle(g);assert.equal(g.castableList(a).some(row=>row.card===hidden[1]),false);const before=a.library.length;g.priorityRound=async()=>settle(g);await g.runBeginningPhase(a);assert.equal(a.library.length,before,'draw step skipped');await g.move(c,'exile');assert.equal(g.hasExilePlayPermission(a,hidden[1]),false);}
 else if(name==='Nexus of Becoming'){const model=put(a,def('Nexus donor',['Artifact'],{subtypes:['Equipment'],cost:'{2}'}),'hand');cards(a,[model]);const c=await source(f,name);await g.emit('beginCombat',{player:a});await settle(g);assert.equal(model.zone,'exile');const token=g.bf().find(card=>card.isToken);assert.ok(token,JSON.stringify({zones:['hand','graveyard','exile'].flatMap(z=>a[z].filter(c=>c.isToken).map(c=>({name:c.name,zone:z,p:c.power,t:c.toughness,statics:c.def.statics?.length,types:c.def.types,subs:c.def.subtypes}))),log:g.log?.slice(-8)}));assert.equal(token.is('Artifact'),true);assert.equal(token.is('Creature'),true);assert.equal(token.hasSub('Equipment'),true);assert.equal(token.hasSub('Golem'),true);assert.equal(token.power,3);assert.equal(token.toughness,3);await g.move(c,'exile');}
 else if(name==='Painbringer'){const donor=Array.from({length:3},(_,i)=>put(a,def('Pain paid '+i),'graveyard')),witness=permanent(g,b,def('Pain target',['Creature'],{power:'8',toughness:'8'})),c=await source(f,name);c.sick=false;targets(a,[witness]);choose(a,q=>q.type==='chooseX'?{...q,min:3,max:3}:null);cards(a,donor);await activate(f,c);assert.equal(c.tapped,true);assert.ok(donor.every(card=>card.zone==='exile'));assert.equal(witness.power,5);assert.equal(witness.toughness,5);}
 else if(name==='Necropolis'){const donor=put(a,def('Necropolis paid',['Creature'],{cost:'{3}'}),'graveyard'),other=put(a,'Forest','graveyard'),c=await source(f,name);cards(a,[donor]);await activate(f,c);assert.equal(donor.zone,'exile');assert.equal(other.zone,'graveyard');assert.equal(c.counters['+0/+1'],3);assert.equal(c.toughness,4);assert.equal(c.kw('defender'),true);}
 else if(name==='Corpseweft'){const donor=[put(a,def('Corpse first'),'graveyard'),put(a,def('Corpse second'),'graveyard')],other=put(a,'Forest','graveyard'),c=await source(f,name);choose(a,q=>q.type==='chooseX'?{...q,min:2,max:2}:null);cards(a,donor);const before=total(a);await activate(f,c);assert.equal(total(a),before-2);assert.ok(donor.every(card=>card.zone==='exile'));assert.equal(other.zone,'graveyard');const token=g.bf().find(card=>card.isToken);assert.ok(token);assert.equal(token.power,4);assert.equal(token.toughness,4);assert.equal(token.tapped,true);assert.equal(token.hasSub('Zombie'),true);assert.equal(token.hasSub('Horror'),true);assert.deepEqual(Array.from(token.colors),['B']);}
 else if(name==='Dread Defiler'){const donor=put(a,def('Defiler paid',['Creature'],{power:'5',toughness:'7'}),'graveyard'),c=await source(f,name);cards(a,[donor]);targets(a,[b]);const before=total(a),life=b.life,option=g.activatableList(a).find(row=>row.card===c&&!row.manaAbility);assert.ok(option);assert.equal(await g.activateAbility(a,option),true);assert.equal(total(a),before-4);assert.equal(donor.zone,'exile');const so=g.stack.find(row=>row.srcCard===c);assert.ok(so);assert.equal(so.ctx.oracleExilePaidV26[0].snapshot.power,5);donor.def={...donor.def,power:'99'};await g.move(donor,'hand');const copy=await g.copyStackAbility(so,a);assert.ok(copy);assert.equal(copy.ctx.oracleExilePaidV26,so.ctx.oracleExilePaidV26);assert.equal(total(a),before-4,'copy does not repay exile or mana');await settle(g);assert.equal(b.life,life-10,'original and copy retain paid power after donor leaves exile');assert.equal(c.colors.length,0,'devoid');}
 else if(name==='Holistic Wisdom'){const donor=put(a,def('Wisdom hand',['Artifact']),'hand'),target=put(a,def('Wisdom grave',['Artifact']),'graveyard'),c=await source(f,name);cards(a,[donor]);targets(a,[target]);const before=total(a);await activate(f,c);assert.equal(total(a),before-2);assert.equal(donor.zone,'exile');assert.equal(target.zone,'hand');}
 else if(name==='Dollhouse of Horrors'){const donor=put(a,def('Dollhouse paid',['Creature'],{subtypes:['Zombie'],kws:['flying']}),'graveyard'),c=await source(f,name);cards(a,[donor]);const before=total(a);await activate(f,c);assert.equal(total(a),before-1);assert.equal(c.tapped,true);assert.equal(donor.zone,'exile');const token=g.bf().find(card=>card.isToken);assert.ok(token,JSON.stringify({zones:['hand','graveyard','exile'].flatMap(z=>a[z].filter(c=>c.isToken).map(c=>({name:c.name,zone:z,p:c.power,t:c.toughness,statics:c.def.statics?.length,types:c.def.types,subs:c.def.subtypes}))),log:g.log?.slice(-8)}));assert.equal(token.is('Artifact'),true);assert.equal(token.is('Creature'),true);assert.equal(token.hasSub('Construct'),true);assert.equal(token.hasSub('Zombie'),true);assert.equal(token.kw('flying'),true);assert.equal(token.kw('haste'),true);assert.equal(token.power,1);assert.equal(token.toughness,1);const another=permanent(g,a,def('Dollhouse additional Construct',['Artifact','Creature'],{subtypes:['Construct']}));assert.equal(token.power,2);assert.equal(token.toughness,2);g.priorityRound=async()=>settle(g);g.combatPhase=async()=>{};g.runAdditionalPhases=async()=>{};await g.runTurn();assert.equal(token.kw('haste'),false,'native cleanup removes granted haste');assert.equal(token.kw('flying'),true,'copied printed flying persists');assert.equal(token.power,2);}
 else throw Error('Unproved v26 whole row '+name);
 assertGameStateInvariants(g);assert.equal(a.controller instanceof M.AIController,role==='ai');
});

for(const role of['human','ai']){
 test(role+': zero-card exile cost leaves target unchanged',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const witness=permanent(g,b,def('Zero paid target',['Creature'],{power:'5',toughness:'5'})),c=await source(f,'Painbringer');c.sick=false;targets(a,[witness]);const prior=a.controller.decide.bind(a.controller);a.controller.decide=(g,q)=>q.type==='chooseCards'&&q.aiHint?.activationPaymentV20?[]:prior(g,q);await activate(f,c);assert.equal(c.tapped,true);assert.equal(witness.power,5);assert.equal(witness.toughness,5);assertGameStateInvariants(g);});
 test(role+': one-or-more creature cost has no zero-card activation',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);put(a,'Forest','graveyard');const c=await source(f,'Corpseweft');assert.equal(g.activatableList(a).some(row=>row.card===c),false);assertGameStateInvariants(g);});
 test(role+': cost choice that leaves and returns is rejected before mana or tap',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const donor=put(a,def('Stale corpse'),'graveyard'),c=await source(f,'Corpseweft'),prior=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>{if(q.type==='chooseCards'&&q.aiHint?.activationPaymentV20){await g.move(donor,'hand');await g.move(donor,'graveyard');return[donor];}return prior(g,q);};const before=total(a),option=g.activatableList(a).find(row=>row.card===c);assert.ok(option);assert.equal(await g.activateAbility(a,option),false);assert.equal(total(a),before);assert.equal(donor.zone,'graveyard');assert.equal(g.bf().some(c=>c.isToken),false);assertGameStateInvariants(g);});
 test(role+': paid hand card with no shared type does not return graveyard target',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const donor=put(a,'Forest','hand'),target=put(a,def('Wisdom unmatched grave'),'graveyard'),c=await source(f,'Holistic Wisdom');cards(a,[donor]);targets(a,[target]);const before=total(a);await activate(f,c);assert.equal(total(a),before-2);assert.equal(donor.zone,'exile');assert.equal(target.zone,'graveyard');assertGameStateInvariants(g);});
}
