import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v23-spells.json',import.meta.url))),M=loadEngine(),absent=rows.filter(card=>!M.DEFS[card.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9943,limit:absent.length,compilerVersion:23});assert.equal(plan.report.cards.length,absent.length);M.registerOracleBatch(plan.report);}M.initData(M.RAW_DATA);
const total=p=>Object.values(p.pool).reduce((sum,n)=>sum+n,0),fund=p=>{for(const color in p.pool)p.pool[color]=30;};
function choose(p,fn){const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>fn(g,q)??prior(g,q);}
function creature(f,p=f.a,{cost='{G}',subtypes=['Bear'],zone='battlefield',power='2',toughness='20'}={}){const card=put(M,f.game,p,'Grizzly Bears',zone);card.def={...card.def,cost,subtypes,power,toughness};f.game.recalc();return card;}
function carrier(f){const card=new M.CardInst({name:'V23 focused Arcane carrier',cost:'{1}',types:['Instant'],subtypes:['Arcane'],super:[],kws:[],resolve:async ctx=>{ctx.src.meta.baseRuns=(ctx.src.meta.baseRuns||0)+1;}},f.a);card.zone='hand';f.a.hand.push(card);return card;}
function source(f,name,zone='hand'){return put(M,f.game,f.a,name,zone);}
function spliceChoice(f,cards){choose(f.a,(g,q)=>q.aiHint?.kind==='splice-v11'?q.options.find(option=>cards.includes(option.card))?.key||'done':undefined);}
function alt(f,card){const result=f.game.castableList(f.a).find(row=>row.card===card&&row.alt?.oracleKeywordPayment==='flashback')?.alt;assert.ok(result,'actual Flashback offer');return result;}
function alternative(f,card){const result=f.game.castableList(f.a).find(row=>row.card===card&&row.alt?.oracleAlternativeCost&&!row.alt?.flashback)?.alt;assert.ok(result,'actual alternate payment offer');return result;}
function spliceDonors(f,name){
 if(name==="Horobi's Whisper")return Array.from({length:4},()=>creature(f,f.a,{zone:'graveyard'}));
 if(name==='Veil of Secrecy')return [creature(f,f.a,{cost:'{U}',power:'0'})];
 if(name==='Torrent of Stone')return [put(M,f.game,f.a,'Mountain'),put(M,f.game,f.a,'Mountain')];
 if(name==='Hundred-Talon Strike')return [creature(f,f.a,{cost:'{W}'})];
 return [];
}
test('v23 keyword payment fixtures compile all printed rules and reject unknown suffixes',()=>{for(const card of rows){assert.ok(semanticClass(card,{compilerVersion:23}).semanticClass,card.name);assert.equal(semanticClass({...card,oracle_text:card.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:23}).semanticClass,undefined,card.name);}});
for(const role of ['human','ai']){
 test(role+': a Shoal alternative also works through a real exile play permission',async()=>{const f=context(M,role),card=source(f,'Nourishing Shoal','library'),donor=creature(f,f.a,{zone:'hand',cost:'{G}{2}'}),reveal=source(f,'Light Up the Stage');f.a.pool.R=3;assert.equal(await f.game.castSpell(f.a,reveal,{from:'hand'}),true);await settle(f.game);assert.equal(card.zone,'exile');const permission=alternative(f,card);assert.equal(await f.game.castSpell(f.a,card,{from:'exile',alt:permission,xVal:3}),true);assert.equal(donor.zone,'exile');await settle(f.game);assert.equal(f.a.life,43);assertGameStateInvariants(f.game);});
 test(role+': energy reserved for Replicate cannot also power a mana ability; declining can pay that mana',async()=>{const f=context(M,role),card=source(f,'Reiterating Bolt'),hub=put(M,f.game,f.a,'Aether Hub'),target=creature(f,f.b);f.a.pool.C=2;f.a.counters.energy=3;let replicate=1;choose(f.a,(g,q)=>q.type==='chooseX'&&q.aiHint?.kind==='replicate'?replicate:q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),false);assert.equal(hub.tapped,false);assert.equal(f.a.counters.energy,3);assert.equal(f.a.pool.C,2);assert.equal(card.zone,'hand');replicate=0;assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);assert.equal(hub.tapped,true);assert.equal(f.a.counters.energy,2);await settle(f.game);assert.equal(target.damage,3);assertGameStateInvariants(f.game);});
 for(const name of ["Dragonlord's Prerogative",'Draconic Roar','Foul-Tongue Invocation',"Silumgar's Scorn"])for(const mode of ['decline','reveal','controlled'])test(role+': '+name+' captures its Dragon condition when casting finishes ('+mode+')',async()=>{const f=context(M,role),card=source(f,name),dragon=mode==='decline'?null:creature(f,f.a,{zone:mode==='reveal'?'hand':'battlefield',subtypes:['Dragon'],power:'5'}),target=creature(f,f.b),reveals=[];fund(f.a);fund(f.b);f.game.revealToHuman=async q=>reveals.push(q);let enemy;if(name==="Silumgar's Scorn"){const bolt=put(M,f.game,f.b,'Lightning Bolt','hand');choose(f.b,(g,q)=>q.type==='chooseTargets'?[f.a]:q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined);assert.equal(await f.game.castSpell(f.b,bolt,{from:'hand'}),true);enemy=f.game.stack.find(so=>so.card===bolt);}choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('optionally reveal')?(mode==='reveal'?[dragon]:[]):q.type==='chooseTargets'?[enemy|| (name==='Foul-Tongue Invocation'?f.b:target)]:undefined);const lifeA=f.a.life,lifeB=f.b.life,hand=f.a.hand.length;assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);const so=f.game.stack.find(so=>so.card===card);assert.equal(so.castOpts.oracleDragonCastV23,mode!=='decline');assert.equal(reveals.filter(q=>q.kind==='additionalCost').length,mode==='reveal'?1:0);if(mode==='controlled')await f.game.move(dragon,'graveyard');if(name==="Dragonlord's Prerogative"&&mode!=='decline'){const copy=await f.game.copySpell(so,f.a,{mayNewTargets:false});assert.equal(await f.game.counterStackObject(copy),false);assert.ok(f.game.stack.includes(copy));await f.game.resolveTop();assert.equal(await f.game.counterStackObject(so),false);assert.ok(f.game.stack.includes(so));}await settle(f.game);if(name==='Draconic Roar'){assert.equal(target.damage,3);assert.equal(f.b.life,lifeB-(mode==='decline'?0:3));}if(name==='Foul-Tongue Invocation'){assert.equal(target.zone,'graveyard');assert.equal(f.a.life,lifeA+(mode==='decline'?0:4));}if(name==="Silumgar's Scorn")assert.equal(f.a.life,lifeA-(mode==='decline'?3:0));if(name==="Dragonlord's Prerogative")assert.equal(f.a.hand.length,hand-1+(mode==='decline'?4:8));assertGameStateInvariants(f.game);});
 for(const mode of ['decline','hand','battlefield'])test(role+": Dragon's Fire reads the chosen Dragon's resolution power and last known information ("+mode+')',async()=>{const f=context(M,role),card=source(f,"Dragon's Fire"),dragon=mode==='decline'?null:creature(f,f.a,{zone:mode==='hand'?'hand':'battlefield',subtypes:['Dragon'],power:'5'}),target=creature(f,f.b);fund(f.a);choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('optionally reveal')?(dragon?[dragon]:[]):q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);if(dragon){dragon.def={...dragon.def,power:'7'};if(mode==='battlefield')f.game.recalc();await f.game.move(dragon,'exile');await f.game.move(dragon,mode==='hand'?'hand':'battlefield');dragon.def={...dragon.def,power:'12'};f.game.recalc();}await settle(f.game);assert.equal(target.damage,dragon?7:3);assertGameStateInvariants(f.game);});
 test(role+': a Dragon reveal that changes incarnation is rejected before any mana is paid',async()=>{const f=context(M,role),card=source(f,'Draconic Roar'),dragon=creature(f,f.a,{zone:'hand',subtypes:['Dragon']}),target=creature(f,f.b);fund(f.a);choose(f.a,(g,q)=>q.type==='chooseCards'&&q.prompt.includes('optionally reveal')?(async()=>{await g.move(dragon,'exile');await g.move(dragon,'hand');return[dragon];})():q.type==='chooseTargets'?[target]:undefined);const mana=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),false);assert.equal(total(f.a),mana);assert.equal(card.zone,'hand');assertGameStateInvariants(f.game);});
 test(role+': controlling a Dragon gained after casting does not turn on the captured bonus',async()=>{const f=context(M,role),card=source(f,'Draconic Roar'),target=creature(f,f.b);fund(f.a);choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);creature(f,f.a,{subtypes:['Dragon']});await settle(f.game);assert.equal(f.b.life,40);assert.equal(target.damage,3);assertGameStateInvariants(f.game);});
 for(const [name,color]of [['Blazing Shoal','R'],['Sickening Shoal','B'],['Nourishing Shoal','G'],['Disrupting Shoal','U']])test(role+': '+name+' exiles a real matching hand card and fixes X to its mana value',async()=>{const f=context(M,role),card=source(f,name),donor=creature(f,f.a,{zone:'hand',cost:'{'+color+'}{2}'}),wrong=creature(f,f.a,{zone:'hand',cost:'{'+color+'}{4}'}),target=creature(f,f.b);if(name==='Disrupting Shoal'){const enemy=put(M,f.game,f.b,'Lightning Bolt','hand');enemy.def={...enemy.def,cost:'{2}{R}'};fund(f.b);choose(f.b,(g,q)=>q.type==='chooseTargets'?[f.a]:undefined);assert.equal(await f.game.castSpell(f.b,enemy,{from:'hand'}),true);choose(f.a,(g,q)=>q.type==='chooseTargets'?[f.game.stack.find(so=>so.card===enemy)]:undefined);}else choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);const permission=alternative(f,card),life=f.a.life;assert.deepEqual(Array.from(f.game.legalXValues(f.a,card,permission,8)),[3,5]);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',alt:permission,xVal:3}),true);const so=f.game.stack.find(so=>so.card===card);assert.equal(so.x,3);assert.equal(so.oracleV4AdditionalCost.handExiles[0],donor.iid);assert.equal(donor.zone,'exile');assert.equal(wrong.zone,'hand');assert.equal(total(f.a),0);const copy=await f.game.copySpell(so,f.a,{mayNewTargets:false});assert.equal(copy.x,3);await f.game.counterStackObject(copy);await settle(f.game);if(name==='Nourishing Shoal')assert.equal(f.a.life,life+3);if(name==='Blazing Shoal')assert.equal(target.power,5);if(name==='Sickening Shoal')assert.equal(target.power,-1);if(name==='Disrupting Shoal')assert.equal(f.a.life,life);assertGameStateInvariants(f.game);});
 test(role+': Shoal rejects absent mana values and stale selected incarnations without consuming the spell',async()=>{for(const stale of [false,true]){const f=context(M,role),card=source(f,'Nourishing Shoal'),donor=creature(f,f.a,{zone:'hand',cost:'{G}{2}'}),permission=alternative(f,card);if(stale)choose(f.a,(g,q)=>q.type==='chooseCards'&&q.from.includes(donor)?(async()=>{await g.move(donor,'exile');await g.move(donor,'hand');return [donor];})():undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',alt:permission,xVal:stale?3:2}),false);assert.equal(card.zone,'hand');assert.equal(donor.zone,'hand');assert.equal(total(f.a),0);assertGameStateInvariants(f.game);}});
 test(role+': Disrupting Shoal preserves its target when the resolved mana value differs from X',async()=>{const f=context(M,role),card=source(f,'Disrupting Shoal');creature(f,f.a,{zone:'hand',cost:'{U}{2}'});const enemy=put(M,f.game,f.b,'Lightning Bolt','hand');fund(f.b);choose(f.b,(g,q)=>q.type==='chooseTargets'?[f.a]:undefined);assert.equal(await f.game.castSpell(f.b,enemy,{from:'hand'}),true);const target=f.game.stack.find(so=>so.card===enemy);choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',alt:alternative(f,card),xVal:3}),true);await f.game.resolveTop();assert.ok(f.game.stack.includes(target));await settle(f.game);assert.equal(f.a.life,37);assertGameStateInvariants(f.game);});
 test(role+': Foil discards distinct Island and other hand cards for its actual alternative cast',async()=>{const f=context(M,role),card=source(f,'Foil'),island=source(f,'Island'),other=source(f,'Forest'),enemy=put(M,f.game,f.b,'Lightning Bolt','hand');fund(f.b);choose(f.b,(g,q)=>q.type==='chooseTargets'?[f.a]:undefined);assert.equal(await f.game.castSpell(f.b,enemy,{from:'hand'}),true);const target=f.game.stack.find(so=>so.card===enemy);choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',alt:alternative(f,card)}),true);assert.equal(island.zone,'graveyard');assert.equal(other.zone,'graveyard');assert.deepEqual(new Set(f.game.stack.at(-1).oracleV4AdditionalCost.discards),new Set([island.iid,other.iid]));await settle(f.game);assert.equal(f.a.life,40);assertGameStateInvariants(f.game);});
 test(role+': Foil requires a second hand card even when its Island payment is available',()=>{const f=context(M,role),card=source(f,'Foil');source(f,'Island');assert.equal(f.game.castableList(f.a).some(row=>row.card===card&&row.alt?.oracleAlternativeCost),false);});
 for(const name of ['Devastating Summons','Infernal Harvest'])test(role+': '+name+' pays its independently announced typed X cost',async()=>{const f=context(M,role),card=source(f,name),donors=Array.from({length:3},()=>put(M,f.game,f.a,name==='Infernal Harvest'?'Swamp':'Forest')),target=creature(f,f.b);fund(f.a);choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',xVal:2}),true);assert.equal(f.game.stack.at(-1).x,2);assert.equal(donors.filter(c=>c.zone===(name==='Infernal Harvest'?'hand':'graveyard')).length,2);await settle(f.game);if(name==='Devastating Summons'){const tokens=f.game.bf().filter(c=>c.isToken&&c.hasSub('Elemental'));assert.equal(tokens.length,2);assert.ok(tokens.every(c=>c.power===2&&c.toughness===2));}else assert.equal(target.damage,2);assertGameStateInvariants(f.game);});
 for(const name of ["Horobi's Whisper",'Veil of Secrecy','Torrent of Stone','Hundred-Talon Strike','Roar of Jukai'])test(role+': '+name+' really pays its nonmana splice cost and preserves copied text',async()=>{
  const f=context(M,role),donors=spliceDonors(f,name),card=source(f,name),base=carrier(f),target=creature(f,f.b),reveals=[];put(M,f.game,f.a,'Swamp');put(M,f.game,f.a,'Forest');fund(f.a);spliceChoice(f,[card]);choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);f.game.revealToHuman=async q=>reveals.push(q);const before=total(f.a),life=f.b.life,versions=new Map(donors.map(c=>[c,c.zoneVersion]));
  assert.equal(await f.game.castSpell(f.a,base,{from:'hand'}),true);const so=f.game.stack.at(-1);assert.equal(before-total(f.a),1);assert.equal(card.zone,'hand');assert.equal(reveals.filter(q=>q.kind==='splice').length,1);assert.equal(so.oracleSpliceV11.parts[0].name,name);
  if(name==="Horobi's Whisper")for(const c of donors){assert.equal(c.zone,'exile');assert.equal(c.zoneVersion,versions.get(c)+1);}if(name==='Torrent of Stone')assert.ok(donors.every(c=>c.zone==='graveyard'));if(name==='Veil of Secrecy')assert.equal(donors[0].zone,'hand');if(name==='Hundred-Talon Strike')assert.equal(donors[0].tapped,true);if(name==='Roar of Jukai')assert.equal(f.b.life,life+5);
  const copy=await f.game.copySpell(so,f.a,{mayNewTargets:false});assert.equal(JSON.stringify(copy.oracleSpliceV11),JSON.stringify(so.oracleSpliceV11));await f.game.counterStackObject(copy);await settle(f.game);assert.equal(base.meta.baseRuns,1);assert.equal(card.zone,'hand');if(name==="Horobi's Whisper")assert.equal(target.zone,'graveyard');if(name==='Veil of Secrecy'){assert.equal(target.kw('shroud'),true);assert.equal(target.cur.unblockable,true);}if(name==='Hundred-Talon Strike'){assert.equal(target.kw('first strike'),true);assert.equal(target.power,3);}assertGameStateInvariants(f.game);
 });
 test(role+': declining splice pays no nonmana resources and reveals no card',async()=>{const f=context(M,role),card=source(f,'Torrent of Stone'),donors=spliceDonors(f,card.name),base=carrier(f),reveals=[];fund(f.a);choose(f.a,(g,q)=>q.aiHint?.kind==='splice-v11'?'done':undefined);f.game.revealToHuman=async q=>reveals.push(q);assert.equal(await f.game.castSpell(f.a,base,{from:'hand'}),true);assert.equal(f.game.stack.at(-1).oracleSpliceV11,undefined);await settle(f.game);assert.ok(donors.every(c=>c.zone==='battlefield'));assert.equal(card.zone,'hand');assert.equal(reveals.length,0);assertGameStateInvariants(f.game);});
 test(role+': a stale selected graveyard incarnation aborts splice without paying mana',async()=>{const f=context(M,role),card=source(f,"Horobi's Whisper"),donors=spliceDonors(f,card.name),base=carrier(f);creature(f,f.b);fund(f.a);spliceChoice(f,[card]);choose(f.a,(g,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='delve'?(async()=>{await g.move(donors[0],'exile');await g.move(donors[0],'graveyard');return donors;})():undefined);const mana=total(f.a);assert.equal(await f.game.castSpell(f.a,base,{from:'hand'}),false);assert.equal(total(f.a),mana);assert.equal(base.zone,'hand');assert.equal(card.zone,'hand');assert.ok(donors.every(c=>c.zone==='graveyard'));assertGameStateInvariants(f.game);});
 test(role+': one creature can tap and then return to pay separate splice costs',async()=>{const f=context(M,role),tap=source(f,'Hundred-Talon Strike'),bounce=source(f,'Veil of Secrecy'),donor=creature(f,f.a,{cost:'{W}{U}'}),target=creature(f,f.b),base=carrier(f);fund(f.a);spliceChoice(f,[tap,bounce]);choose(f.a,(g,q)=>q.type==='chooseTargets'?[target]:undefined);assert.equal(await f.game.castSpell(f.a,base,{from:'hand'}),true);const so=f.game.stack.at(-1);assert.equal(so.oracleSpliceV11.parts.length,2);assert.equal(so.oraclePaidSpecialV23[0].cards[0].iid,donor.iid);assert.equal(so.oracleV4AdditionalCost.returns[0],donor.iid);assert.equal(donor.zone,'hand');await settle(f.game);assert.equal(target.power,3);assert.equal(target.kw('shroud'),true);assert.equal(target.kw('first strike'),true);assertGameStateInvariants(f.game);});
 test(role+': a life gain prohibition excludes the nonmana splice payment',async()=>{const f=context(M,role),card=source(f,'Roar of Jukai'),base=carrier(f);fund(f.a);f.game.untilEffects.push({kind:'lifeGainProhibitionV9',players:[f.b],expires:'eot'});spliceChoice(f,[card]);assert.equal(await f.game.castSpell(f.a,base,{from:'hand'}),true);assert.equal(f.game.stack.at(-1).oracleSpliceV11,undefined);await settle(f.game);assert.equal(card.zone,'hand');assert.equal(f.b.life,40);assertGameStateInvariants(f.game);});
 for(const [name,kind]of [['Conflagrate','discard'],['Firecat Blitz','sacrifice'],['Flash of Insight','exile']])test(role+': '+name+' announces X from its real Flashback nonmana payment',async()=>{const f=context(M,role),card=source(f,name,'graveyard'),donors=Array.from({length:3},()=>kind==='sacrifice'?put(M,f.game,f.a,'Mountain'):creature(f,f.a,{zone:kind==='discard'?'hand':'graveyard',cost:'{U}'}));fund(f.a);if(kind==='discard')choose(f.a,(g,q)=>q.type==='chooseTargets'?[f.b]:undefined);const permission=alt(f,card),mana=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'graveyard',alt:permission,xVal:2}),true);const so=f.game.stack.at(-1);assert.equal(so.x,2);assert.equal(mana-total(f.a),2);const key={discard:'discards',sacrifice:'sacrifices',exile:'exiles'}[kind];assert.equal(so.oracleV4AdditionalCost[key].length,2);assert.equal(donors.filter(c=>c.zone===(kind==='exile'?'exile':'graveyard')).length,2);await settle(f.game);assert.equal(card.zone,'exile');if(kind==='discard')assert.equal(f.b.life,38);if(kind==='sacrifice')assert.equal(f.game.bf().filter(c=>c.isToken&&c.hasSub('Cat')).length,2);assertGameStateInvariants(f.game);});
 test(role+': a requested Flashback X above the real donor count is rejected before payment',async()=>{const f=context(M,role),card=source(f,'Firecat Blitz','graveyard'),donor=put(M,f.game,f.a,'Mountain');fund(f.a);const permission=alt(f,card),mana=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'graveyard',alt:permission,xVal:2}),false);assert.equal(card.zone,'graveyard');assert.equal(donor.zone,'battlefield');assert.equal(total(f.a),mana);assertGameStateInvariants(f.game);});
 test(role+': normal hand X casting does not require its alternative Flashback donors',async()=>{const f=context(M,role),card=source(f,'Firecat Blitz');fund(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'hand',xVal:4}),true);assert.equal(f.game.stack.at(-1).x,4);await settle(f.game);assert.equal(card.zone,'graveyard');assert.equal(f.game.bf().filter(c=>c.isToken&&c.hasSub('Cat')).length,4);assertGameStateInvariants(f.game);});
 test(role+': tap-only Flashback reserves all three creatures and creates its printed token',async()=>{const f=context(M,role),card=source(f,'Group Project','graveyard'),donors=Array.from({length:3},()=>creature(f));const permission=alt(f,card),mana=total(f.a);assert.equal(await f.game.castSpell(f.a,card,{from:'graveyard',alt:permission}),true);assert.equal(total(f.a),mana);assert.ok(donors.every(c=>c.tapped));assert.equal(f.game.stack.at(-1).oraclePaidSpecialV23[0].cards.length,3);await settle(f.game);assert.equal(card.zone,'exile');const token=f.game.bf().find(c=>c.isToken&&c.hasSub('Spirit'));assert.ok(token);assert.deepEqual(Array.from(token.colors),['R','W']);assertGameStateInvariants(f.game);});
 test(role+': Behold Flashback selects three distinct Elementals and reveals only the hand cards',async()=>{const f=context(M,role),card=source(f,'Kindle the Inner Flame','graveyard'),donors=[creature(f,f.a,{subtypes:['Elemental']}),creature(f,f.a,{subtypes:['Elemental'],zone:'hand'}),creature(f,f.a,{subtypes:['Elemental'],zone:'hand'})],reveals=[];fund(f.a);f.game.revealToHuman=async q=>reveals.push(q);const permission=alt(f,card);assert.equal(await f.game.castSpell(f.a,card,{from:'graveyard',alt:permission}),true);const record=f.game.stack.at(-1).oraclePaidSpecialV23[0];assert.equal(new Set(record.cards.map(row=>row.iid)).size,3);assert.equal(reveals.length,1);assert.equal(reveals[0].cards.length,2);assert.ok(reveals[0].cards.every(c=>donors.slice(1).includes(c)));await settle(f.game);assert.equal(card.zone,'exile');assert.equal(donors[0].zone,'battlefield');assert.ok(donors.slice(1).every(c=>c.zone==='hand'));assert.ok(f.game.bf().some(c=>c.isToken&&c.kw('haste')));assertGameStateInvariants(f.game);});
 test(role+': compound random Buyback pays life and one actual random discard; decline pays neither',async()=>{for(const pay of [true,false]){const f=context(M,role),card=source(f,'Flowstone Flood'),donors=[source(f,'Forest'),source(f,'Island')],land=put(M,f.game,f.b,'Forest');fund(f.a);choose(f.a,(g,q)=>q.aiHint?.kind==='kicker'?(pay?'yes':'no'):q.type==='chooseTargets'?[land]:undefined);const life=f.a.life;assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);const so=f.game.stack.at(-1);assert.equal(so.castOpts.buybackPaid===true,pay);assert.equal(f.a.life,life-(pay?3:0));assert.equal(donors.filter(c=>c.zone==='graveyard').length,pay?1:0);await settle(f.game);assert.equal(card.zone,pay?'hand':'graveyard');assert.equal(land.zone,'graveyard');assertGameStateInvariants(f.game);}});
 test(role+': nonmana Escalate discards once for every additional mode',async()=>{const f=context(M,role),card=source(f,'Collective Brutality'),donors=[source(f,'Forest'),source(f,'Island')],enemy=creature(f,f.b);source({game:f.game,a:f.b},'Doom Blade');fund(f.a);choose(f.a,(g,q)=>q.type==='chooseMulti'&&q.aiHint?.kind==='modes'?['0','1','2']:undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);const so=f.game.stack.at(-1);assert.deepEqual(Array.from(so.mode),[0,1,2]);assert.equal(so.oracleV4AdditionalCost.discards.length,2);assert.ok(donors.every(c=>c.zone==='graveyard'));await settle(f.game);assert.equal(f.b.life,38);assert.equal(enemy.power,0);assertGameStateInvariants(f.game);});
 test(role+': energy Replicate pays once and executes actual retargetable spell copies',async()=>{const f=context(M,role),card=source(f,'Reiterating Bolt'),enemy=creature(f,f.b,{toughness:'30'});fund(f.a);f.a.counters.energy=6;choose(f.a,(g,q)=>q.type==='chooseX'&&q.aiHint?.kind==='replicate'?2:q.type==='chooseTargets'?[enemy]:q.aiHint?.kind==='newTargets'?'no':undefined);assert.equal(await f.game.castSpell(f.a,card,{from:'hand'}),true);assert.equal(f.a.counters.energy,0);await settle(f.game);assert.equal(enemy.damage,9);assert.equal(card.zone,'graveyard');assert.equal(f.a.counters.energy,0);assertGameStateInvariants(f.game);});
}
