import test from'node:test';import assert from'node:assert/strict';import{loadEngine}from'./helpers/load-engine.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
const M=loadEngine(),fund=p=>{for(const key of['W','U','B','R','G','C'])p.pool[key]=30;};
function fixture(role){const f=context(M,role);for(const p of f.game.players)if(!p.isAI){const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:prior(g,q);}return f;}
async function cast(f,p,name,targets=[]){const c=put(M,f.game,p,name,'hand');fund(p);const before=Object.values(p.pool).reduce((a,b)=>a+b,0);assert.equal(await f.game.castSpell(p,c,{from:'hand',quickTargets:targets}),true);assert.ok(Object.values(p.pool).reduce((a,b)=>a+b,0)<before);return c;}
async function source(f){const c=await cast(f,f.a,'Glimmer Seeker');await settle(f.game);await cast(f,f.b,'Twiddle',[c]);await settle(f.game);assert.equal(c.tapped,true);return c;}
async function trigger(f){f.game.phase='main2';f.a.turnState.mainPhaseCount=1;await f.game.emitMainPhase(f.a);await f.game.flushTriggers();assert.equal(f.game.stack.length,1);}
for(const role of['human','ai']){
 for(const present of[false,true])test(`${role}: paid Glimmer Seeker ${present?'draws with a Glimmer':'creates a Glimmer without drawing'} at the second main phase`,async()=>{const f=fixture(role),c=await source(f);if(present){await cast(f,f.a,'Tunnel Surveyor');await settle(f.game);}const hand=f.a.hand.length,glimmers=f.game.creatures(f.a).filter(x=>x.hasSub('Glimmer')).length;await trigger(f);await settle(f.game);assert.equal(f.a.hand.length,hand+(present?1:0));const made=f.game.creatures(f.a).filter(x=>x.hasSub('Glimmer'));assert.equal(made.length,glimmers+(present?0:1));if(!present){const token=made[0];assert.equal(token.isToken,true);assert.equal(token.is('Enchantment'),true);assert.equal(token.power,1);assert.equal(token.toughness,1);}assert.equal(c.zone,'battlefield');});
 test(`${role}: removing the only Glimmer in response changes draw into token creation`,async()=>{const f=fixture(role);await source(f);await cast(f,f.a,'Tunnel Surveyor');await settle(f.game);const witness=f.game.creatures(f.a).find(c=>c.isToken&&c.hasSub('Glimmer'));assert.ok(witness);await trigger(f);await cast(f,f.b,'Wipe Away',[witness]);await f.game.resolveTop();const hand=f.a.hand.length;await settle(f.game);assert.equal(f.a.hand.length,hand);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Glimmer')).length,1);});
 test(`${role}: untapping Glimmer Seeker in response prevents both effects through its intervening condition`,async()=>{const f=fixture(role),c=await source(f);await trigger(f);const decide=f.b.controller.decide.bind(f.b.controller);f.b.controller.decide=(g,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='untap')?'untap':decide(g,q);await cast(f,f.b,'Twiddle',[c]);await f.game.resolveTop();assert.equal(c.tapped,false);const hand=f.a.hand.length;await settle(f.game);assert.equal(f.a.hand.length,hand);assert.equal(f.game.creatures(f.a).some(x=>x.hasSub('Glimmer')),false);});
}
