import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import{extractMainScript}from'../scripts/source-audit.mjs';import{context,settle}from'./helpers/oracle-v8-fixtures.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';import{assertGameStateInvariants}from'./helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v27-permanents.json',import.meta.url),'utf8')),sandbox={console,setTimeout,clearTimeout,fetch:globalThis.fetch,URL,URLSearchParams,structuredClone};sandbox.globalThis=sandbox;vm.createContext(sandbox);new vm.Script(extractMainScript().replaceAll('20|21|22|23|24|25|26','20|21|22|23|24|25|26|27')).runInContext(sandbox);if(!sandbox.MTG.OracleV27Permanents)new vm.Script(fs.readFileSync(new URL('../src/modules/oracle-v27-permanents.js',import.meta.url),'utf8')).runInContext(sandbox);new vm.Script(fs.readFileSync(new URL('../src/data.js',import.meta.url),'utf8')).runInContext(sandbox);const M=sandbox.MTG;M.initData(M.RAW_DATA);const plan=createImportPlan({cards:rows,bulk:{type:'oracle_cards'},sequence:9960,limit:rows.length,compilerVersion:27});assert.equal(plan.report.cards.length,rows.length);const absent=plan.report.cards.filter(entry=>!M.DEFS[entry.raw.name]);if(absent.length)M.registerOracleBatch({...plan.report,cards:absent});M.initData(M.RAW_DATA);
const fund=p=>{for(const color of ['W','U','B','R','G','C'])p.pool[color]=100;},total=p=>Object.values(p.pool).reduce((n,x)=>n+x,0);
const def=(name,types=['Creature'],extra={})=>({name,types,subtypes:[],super:[],oracle:'',cost:'{2}',power:'2',toughness:'4',...extra});
const put=(p,d,zone='library')=>{const c=new M.CardInst(typeof d==='string'?M.DEFS[d]:d,p);c.zone=zone;p[zone].push(c);return c;};
const permanent=(g,p,d)=>{const c=put(p,d,'hand');p.hand.splice(p.hand.indexOf(c),1);c.zone='battlefield';c.ctrl=p;c.sick=false;g.battlefield.push(c);g.recalc();return c;};
const choose=(p,fn)=>{const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>prior(g,fn(q)||q);};
const cards=(p,list)=>choose(p,q=>q.type==='chooseCards'&&q.from.some(c=>list.includes(c))?{...q,from:q.from.filter(c=>list.includes(c)),min:Math.min(q.max,list.length),max:Math.min(q.max,list.length)}:null);
const targets=(p,list)=>choose(p,q=>q.type==='chooseTargets'&&q.candidates.some(c=>list.includes(c))?{...q,candidates:q.candidates.filter(c=>list.includes(c)),min:1,max:1}:null);
async function source(f,name){const {game:g,a}=f,c=put(a,name,'hand'),before=total(a);if(c.is('Land'))assert.equal(await g.playLand(a,c),true);else{assert.equal(await g.castSpell(a,c,{from:'hand'}),true);assert.ok(total(a)<before);}await settle(g);return c;}
async function activate(f,c,index=0){const {game:g,a}=f,option=g.activatableList(a).find(row=>row.card===c&&!row.manaAbility&&(c.def.abilities?.[index]?row.ability===c.def.abilities[index]:true));assert.ok(option,c.name+' activation');assert.equal(await g.activateAbility(a,option),true);await settle(g);}

test('27 whole source closure',()=>{for(const c of rows){assert.ok(semanticClass(c,{compilerVersion:27}).semanticClass,c.name);assert.equal(semanticClass({...c,oracle_text:c.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:27}).semanticClass,undefined);}});
for(const role of['human','ai'])for(const card of rows)test(role+': '+card.name+' actual paid rules',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);fund(b);g.reviewCombatWithHuman=async()=>{};const name=card.name;
 if(name==='Circle of Confinement'){const donor=permanent(g,b,def('Circle exiled vampire',['Creature'],{cost:'{3}',subtypes:['Vampire']})),large=permanent(g,b,def('Circle too large',['Creature'],{cost:'{4}'})),own=permanent(g,a,def('Circle own creature',['Creature'],{cost:'{1}'}));targets(a,[donor]);const c=await source(f,name),spec=c.def.triggers[0].targets[0];assert.equal(g.legalTargets(spec,c,a).includes(large),false);assert.equal(g.legalTargets(spec,c,a).includes(own),false);assert.equal(donor.zone,'exile');g.turnPlayer=b;for(const [d,match]of[[donor.def,true],[def('Circle different vampire',['Creature'],{subtypes:['Vampire']}),false],[{...donor.def,subtypes:['Human']},false]]){const spell=put(b,d,'hand'),life=a.life;assert.equal(await g.castSpell(b,spell,{from:'hand'}),true);await settle(g);assert.equal(a.life,life+(match?2:0));}await g.move(c,'exile');await settle(g);assert.equal(donor.zone,'battlefield');assert.equal(donor.ctrl,b);const same=put(b,donor.def,'hand'),life=a.life;assert.equal(await g.castSpell(b,same,{from:'hand'}),true);await settle(g);assert.equal(a.life,life);}
 else if(name==='Toluz, Clever Conductor'){const discarded=put(a,def('Toluz discarded',['Artifact']),'hand');choose(a,q=>q.type==='chooseCards'&&q.aiHint?.kind==='addlDiscard'?{...q,from:[discarded],min:1,max:1}:null);const c=await source(f,name);assert.equal(discarded.zone,'exile');assert.equal(c.counters['+1/+1'],1);const pair=[put(a,def('Toluz batch one',['Instant']),'hand'),put(a,'Forest','hand')];await g.discard(a,pair);await settle(g);assert.ok(pair.every(card=>card.zone==='exile'));await g.sacrifice(a,c);await settle(g);assert.equal(discarded.zone,'hand');assert.ok(pair.every(card=>card.zone==='hand'));}
 else if(name==='Mindreaver'){const models=Array.from({length:3},(_,i)=>put(b,def('Heroic matching '+i,['Instant'],{cost:'{1}',resolve:async ctx=>{ctx.you.heroicResolved=true;}}),'library')),c=await source(f,name);targets(a,[b]);const heroic=put(a,def('Heroic actual targeting instant',['Instant'],{cost:'{1}',targets:[{what:'creature',zone:'battlefield',min:1}],resolve:async()=>{}}),'hand');assert.equal(await g.castSpell(a,heroic,{from:'hand',quickTargets:[c]}),true);await settle(g);assert.ok(models.every(card=>card.zone==='exile'));g.turnPlayer=b;const wrong=put(b,def('Heroic wrong name',['Instant'],{cost:'{1}',resolve:async ctx=>{ctx.you.wrongResolved=true;}}),'hand');assert.equal(await g.castSpell(b,wrong,{from:'hand'}),true);assert.equal(g.activatableList(a).some(row=>row.card===c),false);const same=put(b,models[0].def,'hand');assert.equal(await g.castSpell(b,same,{from:'hand'}),true);const so=g.stack.find(row=>row.card===same);targets(a,[so]);const before=total(a);await activate(f,c);assert.equal(total(a),before-2);assert.equal(c.zone,'graveyard');assert.equal(same.zone,'graveyard');assert.equal(b.heroicResolved,undefined);assert.equal(b.wrongResolved,true);}
 else if(name==='Wall of Nets'){const c=await source(f,name),attacker=permanent(g,b,def('Net attacker',['Creature'],{power:'1',toughness:'10'})),priorB=b.controller.decide.bind(b.controller),priorA=a.controller.decide.bind(a.controller);b.controller.decide=(g,q)=>q.type==='attackers'?[{card:attacker,target:a}]:priorB(g,q);a.controller.decide=(g,q)=>q.type==='blockers'?(role==='human'?[{blocker:c,attacker}]:priorA(g,{...q,attackers:[attacker],potential:[c]})):priorA(g,q);g.turnPlayer=b;g.priorityRound=async()=>settle(g);await g.combatPhase(b);await settle(g);assert.equal(attacker.zone,'exile');assert.equal(c.kw('defender'),true);await g.move(c,'exile');await settle(g);assert.equal(attacker.zone,'battlefield');assert.equal(attacker.ctrl,b);}
 else if(name==='Purgatory'){const c=await source(f,name),donor=permanent(g,a,def('Purgatory owned creature'));donor.ctrl=b;g.recalc();await g.sacrifice(b,donor);await settle(g);assert.equal(donor.zone,'exile');cards(a,[donor]);const before=total(a),life=a.life;await g.emit('upkeep',{player:a});await settle(g);assert.equal(total(a),before-4);assert.equal(a.life,life-2);assert.equal(donor.zone,'battlefield');assert.equal(donor.ctrl,a);await g.move(c,'exile');}
 else if(name==='Thought Prison'){const donor=put(b,def('Prison imprint',['Instant'],{cost:'{2}{R}',resolve:async()=>{}}),'hand');targets(a,[b]);cards(a,[donor]);const c=await source(f,name);assert.equal(donor.zone,'exile');g.turnPlayer=b;const life=b.life;for(const [suffix,cost,match]of[['color','{R}',true],['mv','{3}',true],['neither','{2}',false]]){const spell=put(b,def('Prison '+suffix,['Instant'],{cost,resolve:async()=>{}}),'hand');const before=b.life;assert.equal(await g.castSpell(b,spell,{from:'hand'}),true);await settle(g);assert.equal(b.life,before-(match?2:0));}assert.equal(b.life,life-4);await g.move(c,'exile');}
 else if(name==='Ellie and Alan, Paleontologists'){const donor=put(a,def('Discover paid creature',['Creature'],{cost:'{3}'}),'graveyard'),eligible=put(a,def('Discover actual spell',['Artifact'],{cost:'{2}'}),'library'),land=put(a,'Forest','library'),large=put(a,def('Discover too large',['Artifact'],{cost:'{4}'}),'library'),c=await source(f,name);c.sick=false;cards(a,[donor]);choose(a,q=>q.type==='chooseCards'&&/You may cast/.test(q.prompt||'')?{...q,min:1}:null);const before=total(a);await activate(f,c);assert.equal(c.tapped,true);assert.equal(total(a),before);assert.equal(donor.zone,'exile');assert.equal(eligible.zone,'battlefield');assert.equal(large.zone,'library');assert.equal(land.zone,'library');}
 else if(name==='The Temporal Anchor'){const c=await source(f,name);for(let i=0;i<8;i++)permanent(g,a,'Forest');for(let i=0;i<8;i++)put(a,'Forest','hand');const models=[put(a,def('Anchor bad first',['Instant'],{cost:'{1}',resolve:async()=>{}}),'library'),put(a,def('Anchor bad second',['Instant'],{cost:'{1}',resolve:async()=>{}}),'library')],prior=a.controller.decide.bind(a.controller);a.controller.decide=(g,q)=>q.type==='scry'&&role==='human'?{top:[],bottom:q.cards}:prior(g,q);await g.emit('upkeep',{player:a});await settle(g);assert.ok(models.every(card=>card.zone==='exile'));assert.equal(g.hasExilePlayPermission(a,models[0]),true);g.turnPlayer=b;assert.equal(g.hasExilePlayPermission(a,models[0]),false);assert.equal(await g.castSpell(a,models[0],{from:'exile'}),false);g.turnPlayer=a;fund(a);const row=g.castableList(a).find(row=>row.card===models[0]);assert.ok(row);const before=total(a);assert.equal(await g.castSpell(a,models[0],{from:row.from,alt:row.alt}),true);assert.equal(total(a),before-1);await settle(g);assert.equal(models[0].zone,'graveyard');await g.move(c,'exile');assert.equal(g.hasExilePlayPermission(a,models[1]),false);}
 else if(name==='Sutured Ghoul'){const donors=[put(a,def('Ghoul first',['Creature'],{power:'4',toughness:'2'}),'graveyard'),put(a,def('Ghoul second',['Creature'],{power:'2',toughness:'5'}),'graveyard')],other=put(a,'Forest','graveyard');cards(a,donors);const c=await source(f,name);assert.ok(donors.every(card=>card.zone==='exile'));assert.equal(other.zone,'graveyard');assert.equal(c.power,6);assert.equal(c.toughness,7);assert.equal(c.kw('trample'),true);await g.move(donors[0],'hand');assert.equal(c.power,2);assert.equal(c.toughness,5);await g.move(c,'hand');assert.equal(c.power,0);assert.equal(c.toughness,0);}

 else if(['Royal Herbalist','Arc-Slogger','Storm Elemental'].includes(name)){const c=await source(f,name),donors=Array.from({length:name==='Arc-Slogger'?10:1},(_,i)=>put(a,'Forest','library'));let flying;if(name==='Storm Elemental'){flying=permanent(g,b,def('Initial storm flyer',['Creature'],{kws:['flying']}));targets(a,[flying]);}else targets(a,[b]);const before=total(a),life=name==='Royal Herbalist'?a.life:b.life;await activate(f,c);assert.ok(donors.every(card=>card.zone==='exile'));assert.equal(total(a),before-(name==='Royal Herbalist'?2:1));if(name==='Royal Herbalist')assert.equal(a.life,life+1);if(name==='Arc-Slogger')assert.equal(b.life,life-2);if(name==='Storm Elemental'){const flyer=permanent(g,b,def('Storm flying target',['Creature'],{kws:['flying']}));c.sick=false;targets(a,[flyer]);put(a,'Forest','library');await activate(f,c,0);assert.equal(flyer.tapped,true);const snow=put(a,def('Paid snow land',['Land'],{super:['Snow'],cost:'',power:undefined,toughness:undefined}),'library'),power=c.power;await activate(f,c,1);assert.equal(snow.zone,'exile');assert.equal(c.power,power+1);put(a,'Forest','library');await activate(f,c,1);assert.equal(c.power,power+1);}}
 else if(name==='Illuminated Folio'||name==='Sphinx of the Chimes'){const c=await source(f,name),donors=[put(a,def('Shared cost pair',['Instant'],{cost:'{R}'}),'hand'),put(a,def(name==='Illuminated Folio'?'Different red card':'Shared cost pair',['Instant'],{cost:'{R}'}),'hand')],other=put(a,def('Ineligible blue',['Instant'],{cost:'{U}'}),'hand');cards(a,donors);const hand=a.hand.length,before=total(a);let revealed=[];g.revealToHuman=async q=>{revealed=q.cards;};await activate(f,c);assert.equal(total(a),before-(name==='Illuminated Folio'?1:0));assert.equal(a.hand.length,hand+(name==='Illuminated Folio'?1:2));assert.equal(other.zone,'hand');if(name==='Illuminated Folio'){assert.ok(donors.every(card=>card.zone==='hand'));assert.deepEqual(new Set(revealed),new Set(donors));assert.equal(c.tapped,true);}else assert.ok(donors.every(card=>card.zone==='graveyard'));}
 else if(name==="Jandor's Ring"){const c=await source(f,name),earlier=put(a,def('Earlier drawn'),'library');await g.draw(a,1,c);assert.equal(earlier.zone,'hand');const last=put(a,def('Last drawn'),'library');await g.draw(a,1,c);assert.equal(last.zone,'hand');const hand=a.hand.length,before=total(a);await activate(f,c);assert.equal(total(a),before-2);assert.equal(last.zone,'graveyard');assert.equal(earlier.zone,'hand');assert.equal(a.hand.length,hand);}
 else if(name==='Knollspine Invocation'){const c=await source(f,name),donor=put(a,def('Invocation paid card',['Instant'],{cost:'{3}'}),'hand'),wrong=put(a,def('Wrong mana value',['Instant'],{cost:'{2}'}),'hand');cards(a,[donor]);targets(a,[b]);choose(a,q=>q.type==='chooseX'?{...q,min:3,max:3,preferredXValues:[3]}:null);const life=b.life,before=total(a);await activate(f,c);assert.equal(total(a),before-3);assert.equal(donor.zone,'graveyard');assert.equal(wrong.zone,'hand');assert.equal(b.life,life-3);}

 else if(name==='Mirror of Life Trapping'){const c=await source(f,name),first=put(a,def('Mirror first creature',['Creature'],{cost:'{2}',triggers:[{on:'etb',filter:(g,s,d)=>d.card===s,run:async ctx=>{ctx.you.mirrorEntries=(ctx.you.mirrorEntries||0)+1;}}]}),'hand');assert.equal(await g.castSpell(a,first,{from:'hand'}),true);await settle(g);assert.equal(first.zone,'exile');g.turnPlayer=b;const second=put(b,def('Mirror second creature'),'hand');assert.equal(await g.castSpell(b,second,{from:'hand'}),true);await settle(g);assert.equal(second.zone,'exile');assert.equal(first.zone,'battlefield');assert.equal(first.ctrl,a);assert.equal(a.mirrorEntries,2);const uncast=put(b,def('Mirror uncast creature'),'graveyard');await g.putPermanentOntoBattlefield(uncast,b);await settle(g);assert.equal(uncast.zone,'battlefield');assert.equal(second.zone,'exile');await g.move(c,'exile');}
 else if(name==='Ghost Vacuum'){const c=await source(f,name),donor=put(b,def('Vacuum captured creature',['Artifact','Creature'],{power:'4',toughness:'5',subtypes:['Elf'],kws:['trample']}),'graveyard'),other=put(a,def('Vacuum noncreature',['Artifact']),'graveyard');for(const card of[donor,other]){c.tapped=false;targets(a,[card]);await activate(f,c,0);assert.equal(card.zone,'exile');}c.tapped=false;const before=total(a);await activate(f,c,1);assert.equal(total(a),before-6);assert.equal(c.zone,'graveyard');assert.equal(donor.zone,'battlefield');assert.equal(donor.ctrl,a);assert.equal(donor.power,1);assert.equal(donor.toughness,1);assert.equal(donor.hasSub('Spirit'),true);assert.equal(donor.hasSub('Elf'),true);assert.equal(donor.is('Artifact'),true);assert.equal(donor.counters.flying,1);assert.equal(donor.kw('flying'),true);assert.equal(donor.kw('trample'),true);assert.equal(other.zone,'exile');await g.move(donor,'hand');assert.equal(donor.power,4);assert.equal(donor.hasSub('Spirit'),false);}
 else if(name==="Magewright's Stone"){const c=await source(f,name),host=permanent(g,a,def('Stone tapped creature',['Creature'],{abilities:[{cost:{tap:true},run:async()=>{}}]})),wrong=permanent(g,a,def('Stone no tap ability'));g.tap(host);const adef=c.def.abilities[0];assert.equal(g.legalTargets(adef.targets[0],c,a).includes(wrong),false);assert.equal(g.legalTargets(adef.targets[0],c,a).includes(host),true);targets(a,[host]);const before=total(a);await activate(f,c);assert.equal(total(a),before-1);assert.equal(c.tapped,true);assert.equal(host.tapped,false);}
 else if(name==='Diplomatic Escort'){const c=await source(f,name);c.sick=false;const host=permanent(g,a,def('Escort targeted creature')),donor=put(a,def('Escort discard cost',['Artifact']),'hand');cards(a,[donor]);g.turnPlayer=b;const spell=put(b,def('Escort target spell',['Instant'],{cost:'{1}',targets:[{what:'creature',zone:'battlefield',min:1}],resolve:async()=>{b.escortResolved=true;}}),'hand');assert.equal(await g.castSpell(b,spell,{from:'hand',quickTargets:[host]}),true);const so=g.stack.find(row=>row.card===spell);targets(a,[so]);const before=total(a);await activate(f,c);assert.equal(total(a),before-1);assert.equal(donor.zone,'graveyard');assert.equal(c.tapped,true);assert.equal(spell.zone,'graveyard');assert.equal(b.escortResolved,undefined);}
 else if(name==='Planar Void'){const c=await source(f,name),drawn=put(a,def('Void discarded card'),'hand');await g.discard(a,[drawn]);await settle(g);assert.equal(drawn.zone,'exile');const milled=put(b,def('Void milled card'),'library');await g.mill(b,1);await settle(g);assert.equal(milled.zone,'exile');const creature=permanent(g,b,def('Void sacrificed creature'));await g.sacrifice(b,creature);await settle(g);assert.equal(creature.zone,'exile');await g.sacrifice(a,c);await settle(g);assert.equal(c.zone,'graveyard');}
 else if(name==='Wardscale Dragon'){const c=await source(f,name);c.sick=false;const instant=put(b,def('Defender instant',['Instant'],{cost:'{1}',resolve:async()=>{}}),'hand'),prior=a.controller.decide.bind(a.controller);a.controller.decide=(g,q)=>q.type==='attackers'?[{card:c,target:b}]:prior(g,q);let checked=false;g.priorityRound=async()=>{if(c.attacking===b){checked=true;assert.equal(await g.castSpell(b,instant,{from:'hand'}),false);}await settle(g);};await g.combatPhase(a);assert.equal(checked,true);assert.equal(c.kw('flying'),true);assert.equal(await g.castSpell(b,instant,{from:'hand'}),true);await settle(g);}
 else if(name==='Glissa Sunseeker'){const c=await source(f,name);c.sick=false;for(const color of['W','U','B','R','G','C'])a.pool[color]=0;for(let i=0;i<3;i++){const land=permanent(g,a,'Forest'),row=g.manaSources(a).find(row=>row.card===land);assert.equal(await g.activateManaSource(a,row,{G:1}),true);}const host=permanent(g,b,def('Glissa correct artifact',['Artifact'],{cost:'{3}'})),wrong=permanent(g,b,def('Glissa wrong artifact',['Artifact'],{cost:'{2}'}));targets(a,[host]);await activate(f,c);assert.equal(host.zone,'graveyard');assert.equal(total(a),3);c.tapped=false;targets(a,[wrong]);await activate(f,c);assert.equal(wrong.zone,'battlefield');assert.equal(c.kw('first strike'),true);}
 else if(name==='Doubling Cube'){const c=await source(f,name),before=total(a),stack=g.stack.length,row=g.activatableList(a).find(row=>row.card===c&&row.manaAbility);assert.ok(row);assert.equal(await g.activateAbility(a,row),true);assert.equal(c.tapped,true);assert.equal(total(a),(before-3)*2);assert.equal(g.stack.length,stack);}

 else if(name==='Mana Maze'){const c=await source(f,name);g.turnPlayer=b;const red=put(b,def('Maze red',['Instant'],{cost:'{R}',resolve:async()=>{}}),'hand');assert.equal(await g.castSpell(b,red,{from:'hand'}),true);await settle(g);const same=put(a,def('Maze same red',['Instant'],{cost:'{R}',resolve:async()=>{}}),'hand'),different=put(a,def('Maze different blue',['Instant'],{cost:'{U}',resolve:async()=>{}}),'hand');assert.equal(await g.castSpell(a,same,{from:'hand'}),false);assert.equal(await g.castSpell(a,different,{from:'hand'}),true);await settle(g);assert.equal(await g.castSpell(a,same,{from:'hand'}),true);await settle(g);g.turnNo++;const another=put(b,red.def,'hand');assert.equal(await g.castSpell(b,another,{from:'hand'}),true);await settle(g);await g.move(c,'exile');}
 else if(name==="Cosi's Trickster"){const c=await source(f,name);g.turnPlayer=b;g.phase='main1';put(b,'Forest','library');const fetch=put(b,'Evolving Wilds','hand');assert.equal(await g.playLand(b,fetch),true);await settle(g);const row=g.activatableList(b).find(row=>row.card===fetch);assert.ok(row);assert.equal(await g.activateAbility(b,row),true);await settle(g);assert.equal(c.counters['+1/+1'],1);const prior=c.counters['+1/+1'];M.shuffle(a.library,g.rnd);await settle(g);assert.equal(c.counters['+1/+1'],prior);}
 else throw Error('Unproved whole source '+name);assertGameStateInvariants(g);assert.equal(a.controller instanceof M.AIController,role==='ai');
});

for(const role of ['human','ai']){
 test(role+': shared-color reveal rejects a stale reincarnation before mana or tap',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const donors=[put(a,def('Stale red one',['Instant'],{cost:'{R}'}),'hand'),put(a,def('Stale red two',['Instant'],{cost:'{R}'}),'hand')],c=await source(f,'Illuminated Folio'),prior=a.controller.decide.bind(a.controller);let count=0;a.controller.decide=async(g,q)=>{if(q.type==='chooseCards'&&q.aiHint?.activationPaymentV20){const picked=donors[count++];if(count===2){await g.move(donors[0],'graveyard');await g.move(donors[0],'hand');}return[picked];}return prior(g,q);};const before=total(a),row=g.activatableList(a).find(row=>row.card===c);assert.ok(row);assert.equal(await g.activateAbility(a,row),false);assert.equal(total(a),before);assert.equal(c.tapped,false);assert.ok(donors.every(c=>c.zone==='hand'));assertGameStateInvariants(g);});
 test(role+': mismatched hand pairs never offer activation',async()=>{for(const name of['Illuminated Folio','Sphinx of the Chimes']){const f=context(M,role),{game:g,a}=f;fund(a);put(a,def('Pair red',['Instant'],{cost:'{R}'}),'hand');put(a,def('Pair blue',['Instant'],{cost:'{U}'}),'hand');const c=await source(f,name);assert.equal(g.activatableList(a).some(row=>row.card===c),false);assertGameStateInvariants(g);}});
 test(role+': top-ten library cost needs ten actual cards',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const c=await source(f,'Arc-Slogger');while(a.library.length>9)await g.move(a.library.at(-1),'hand');targets(a,[b]);assert.equal(g.activatableList(a).some(row=>row.card===c),false);assertGameStateInvariants(g);});
 test(role+': last drawn card is unavailable after leaving and returning',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const c=await source(f,"Jandor's Ring"),donor=put(a,def('Reentered last draw'),'library');await g.draw(a,1,c);await g.move(donor,'graveyard');await g.move(donor,'hand');assert.equal(g.activatableList(a).some(row=>row.card===c),false);assertGameStateInvariants(g);});
}
