import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {proveSpellV26,proveSpellEdgeV26,edgeCasesV26} from './helpers/oracle-v26-spells-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v26-spells.json',import.meta.url))),M=loadEngine(),absent=rows.filter(c=>!M.DEFS[c.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9956,limit:absent.length,compilerVersion:26});assert.equal(plan.report.cards.length,absent.length);M.registerOracleBatch(plan.report);}M.initData(M.RAW_DATA);
test('36 v26 whole sources retain all lines and reject unsupported suffixes',()=>{assert.equal(rows.length,36);for(const row of rows){assert.ok(semanticClass(row,{compilerVersion:26}).semanticClass,row.name);assert.equal(semanticClass({...row,oracle_text:row.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:26}).semanticClass,undefined,row.name);}});
for(const role of ['human','ai'])for(const row of rows)for(const positive of [false,true])test(role+': '+row.name+' '+positive,()=>proveSpellV26(M,row,role,positive));
for(const role of ['human','ai'])for(const [name,scenarios]of Object.entries(edgeCasesV26))for(const scenario of scenarios)test(role+': '+name+' '+scenario,()=>proveSpellEdgeV26(M,name,role,scenario));
