import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import{extractMainScript}from'../scripts/source-audit.mjs';import{context,settle}from'./helpers/oracle-v8-fixtures.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';import{assertGameStateInvariants}from'./helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v28-permanents.json',import.meta.url),'utf8')),sandbox={console,setTimeout,clearTimeout,fetch:globalThis.fetch,URL,URLSearchParams,structuredClone};sandbox.globalThis=sandbox;vm.createContext(sandbox);new vm.Script(extractMainScript()).runInContext(sandbox);if(!sandbox.MTG.OracleV28Permanents)new vm.Script(fs.readFileSync(new URL('../src/modules/oracle-v28-permanents.js',import.meta.url),'utf8')).runInContext(sandbox);new vm.Script(fs.readFileSync(new URL('../src/data.js',import.meta.url),'utf8')).runInContext(sandbox);const M=sandbox.MTG;M.initData(M.RAW_DATA);const plan=createImportPlan({cards:rows,bulk:{type:'oracle_cards'},sequence:9960,limit:rows.length,compilerVersion:28});assert.equal(plan.report.cards.length,rows.length);const absent=plan.report.cards.filter(entry=>!M.DEFS[entry.raw.name]);if(absent.length)M.registerOracleBatch({...plan.report,cards:absent});M.initData(M.RAW_DATA);
const fund=p=>{for(const color of ['W','U','B','R','G','C'])p.pool[color]=100;},total=p=>Object.values(p.pool).reduce((n,x)=>n+x,0);
const def=(name,types=['Creature'],extra={})=>({name,types,subtypes:[],super:[],oracle:'',cost:'{2}',power:'2',toughness:'4',...extra});
const put=(p,d,zone='library')=>{const c=new M.CardInst(typeof d==='string'?M.DEFS[d]:d,p);c.zone=zone;p[zone].push(c);return c;};
const permanent=(g,p,d)=>{const c=put(p,d,'hand');p.hand.splice(p.hand.indexOf(c),1);c.zone='battlefield';c.ctrl=p;c.sick=false;g.battlefield.push(c);g.recalc();return c;};
const choose=(p,fn)=>{const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>prior(g,fn(q)||q);};
const cards=(p,list)=>choose(p,q=>q.type==='chooseCards'&&q.from.some(c=>list.includes(c))?{...q,from:q.from.filter(c=>list.includes(c)),min:Math.min(q.max,list.length),max:Math.min(q.max,list.length)}:null);
const targets=(p,list)=>choose(p,q=>q.type==='chooseTargets'&&q.candidates.some(c=>list.includes(c))?{...q,candidates:q.candidates.filter(c=>list.includes(c)),min:1,max:1}:null);
async function source(f,name){const {game:g,a}=f,c=put(a,name,'hand'),before=total(a);if(c.is('Land'))assert.equal(await g.playLand(a,c),true);else{assert.equal(await g.castSpell(a,c,{from:'hand'}),true);assert.ok(total(a)<before);}await settle(g);return c;}
async function activate(f,c,index=0){const {game:g,a}=f,option=g.activatableList(a).find(row=>row.card===c&&!row.manaAbility&&(c.def.abilities?.[index]?row.ability===c.def.abilities[index]:true));assert.ok(option,c.name+' activation');assert.equal(await g.activateAbility(a,option),true);await settle(g);}
test('28 complete source closure',()=>{for(const c of rows){assert.ok(semanticClass(c,{compilerVersion:28}).semanticClass,c.name);assert.equal(semanticClass({...c,oracle_text:c.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:28}).semanticClass,undefined,c.name);}});
for(const role of ['human','ai'])for(const card of rows)test(role+': '+card.name+' actual paid whole source',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);fund(b);g.reviewCombatWithHuman=async()=>{};const name=card.name;if(name==='Weight of Conscience')permanent(g,b,def('Actual enchanted target'));if(name==="Necromancer's Magemark")permanent(g,a,def('Actual enchanted friendly'));if(name==='Bloodfire Infusion')permanent(g,a,def('Bloodfire actual host',['Creature'],{power:'4',toughness:'10'}));if(name==='Betrothed of Fire')permanent(g,a,def('Betrothed actual host'));const c=await source(f,name);c.sick=false;
 const donor=(extra={})=>permanent(g,a,def('Actual paid donor',['Creature'],{cost:'{3}',power:'4',toughness:'4',subtypes:['Human'],...extra}));
 if(['Falkenrath Torturer','Falkenrath Aristocrat','Thallid Omnivore','Boneyard Desecrator','Agency Coroner',"Witch's Oven",'Lyzolda, the Blood Witch','Sanguine Praetor'].includes(name)){const q=donor({subtypes:[name==='Thallid Omnivore'?'Saproling':name==='Boneyard Desecrator'?'Pirate':'Human'],colorsOverride:name==='Lyzolda, the Blood Witch'?['R','B']:[]});if(name==='Agency Coroner')q.meta.suspected=true;cards(a,[q]);targets(a,[b]);const hand=a.hand.length,life=a.life,enemy=b.life,power=c.power,tough=c.toughness,match=permanent(g,b,def('Praetor matching creature',['Creature'],{cost:'{3}',toughness:'10'})),other=permanent(g,b,def('Praetor different creature',['Creature'],{cost:'{2}',toughness:'10'}));await activate(f,c);assert.equal(q.zone,'graveyard');if(name==='Falkenrath Torturer'){assert.equal(c.kw('flying'),true);assert.equal(c.counters['+1/+1'],1);}if(name==='Falkenrath Aristocrat'){assert.equal(c.kw('indestructible'),true);assert.equal(c.counters['+1/+1'],1);}if(name==='Thallid Omnivore'){assert.equal(c.power,power+2);assert.equal(c.toughness,tough+2);assert.equal(a.life,life+2);}if(name==='Boneyard Desecrator'){assert.equal(c.counters['+1/+1'],1);assert.equal(g.bf().filter(x=>x.ctrl===a&&x.hasSub('Treasure')).length,1);}if(name==='Agency Coroner')assert.equal(a.hand.length,hand+2);if(name==="Witch's Oven")assert.equal(g.bf().filter(x=>x.ctrl===a&&x.hasSub('Food')).length,2);if(name==='Lyzolda, the Blood Witch'){assert.equal(b.life,enemy-2);assert.equal(a.hand.length,hand+1);}if(name==='Sanguine Praetor'){assert.equal(match.zone,'graveyard');assert.equal(other.zone,'battlefield');}}
 else if(['Priest of Yawgmoth','Slobad, Iron Goblin','Soldevi Adnate'].includes(name)){const q=donor({types:['Artifact','Creature'],colorsOverride:['B']}),row=g.activatableList(a).find(x=>x.card===c&&x.manaAbility);assert.ok(row);cards(a,[q]);const color=name==='Slobad, Iron Goblin'?'R':'B',before=a.pool[color],stack=g.stack.length;assert.equal(await g.activateAbility(a,row),true);assert.equal(q.zone,'graveyard');assert.equal(a.pool[color],before+3);assert.equal(g.stack.length,stack);assert.equal(c.tapped,true);if(name==='Slobad, Iron Goblin'){const meta=a.poolMeta.find(r=>r.source===c&&r.color==='R');assert.ok(meta);assert.equal(meta.n,3);assert.equal(meta.restrict(g,{card:put(a,def('Slobad creature',['Creature']),'hand')},c),false);}}
 else if(['Impelled Giant','Keldon Battlewagon','Unerring Sling','Radiant, Serra Archangel'].includes(name)){const q=donor({colorsOverride:['R'],kws:['flying']}),power=c.power;cards(a,[q]);if(name==='Unerring Sling'){const enemy=permanent(g,b,def('Sling flying combat creature',['Creature'],{kws:['flying'],toughness:'10'}));enemy.attacking=a;targets(a,[enemy]);await activate(f,c);assert.equal(enemy.damage,4);}else{await activate(f,c);if(name==='Radiant, Serra Archangel')assert.ok(c.cur.protectionFrom?.length>0);else assert.equal(c.power,power+4);}assert.equal(q.tapped,true);if(name==='Keldon Battlewagon'){assert.equal(c.kw('trample'),true);assert.equal(c.cur.cantBlock,true);}}
 else if(name==='Tangle Tumbler'){const host=donor(),token1=donor(),token2=donor();token1.isToken=token2.isToken=true;targets(a,[host]);await activate(f,c,0);assert.equal(host.counters['+1/+1'],1);c.tapped=false;cards(a,[token1,token2]);await activate(f,c,1);assert.equal(c.is('Creature'),true);assert.equal(c.kw('vigilance'),true);assert.ok(token1.tapped&&token2.tapped);}
 else if(name==='Weight of Conscience'){const q=donor(),r=donor(),host=g.byIid(c.attachedTo);assert.ok(host);cards(a,[q,r]);await activate(f,c);assert.equal(host.zone,'exile');assert.ok(q.tapped&&r.tapped);}
 else if(name==='Cryptic Gateway'){const q=donor({subtypes:['Elf','Warrior']}),r=donor({subtypes:['Elf','Wizard']}),shared=put(a,def('Gateway shared Elf',['Creature'],{subtypes:['Elf']}),'hand'),wrong=put(a,def('Gateway wrong Human',['Creature'],{subtypes:['Human']}),'hand');cards(a,[q,r,shared]);choose(a,q=>q.type==='chooseCards'&&q.from.includes(shared)?{...q,min:1,max:1}:null);await activate(f,c);assert.ok(q.tapped&&r.tapped);assert.equal(shared.zone,'battlefield');assert.equal(wrong.zone,'hand');}
 else if(name==='Crackleburr'){const red=[donor({colorsOverride:['R']}),donor({colorsOverride:['R']})];cards(a,red);targets(a,[b]);const life=b.life;await activate(f,c,0);assert.equal(b.life,life-3);assert.ok(red.every(x=>x.tapped));assert.equal(c.tapped,true);const blue=[donor({colorsOverride:['U']}),donor({colorsOverride:['U']})];blue.forEach(x=>g.tap(x));cards(a,blue);targets(a,[red[0]]);await activate(f,c,1);assert.equal(red[0].zone,'hand');assert.ok(blue.every(x=>!x.tapped));assert.equal(c.tapped,false);}
 else if(name==='Baylen, the Haymaker'){for(const [index,n]of[[0,2],[0,3],[1,4]]){const tokens=Array.from({length:n},()=>{const q=donor();q.isToken=true;return q;});cards(a,tokens);if(n===2){const row=g.activatableList(a).find(x=>x.card===c&&x.manaAbility);assert.ok(row);const before=total(a);assert.equal(await g.activateAbility(a,row),true);assert.equal(total(a),before+1);}else{const hand=a.hand.length;await activate(f,c,index);if(n===3)assert.equal(a.hand.length,hand+1);else{assert.equal(c.counters['+1/+1'],3);assert.equal(c.kw('trample'),true);}}assert.ok(tokens.every(x=>x.tapped));}}
 else if(name.startsWith('Martyr of')){const color=name==='Martyr of Sands'?'W':name==='Martyr of Spores'?'G':name==='Martyr of Frost'?'U':'R',revealed=[put(a,def('Revealed first',['Instant'],{colorsOverride:[color]}),'hand'),put(a,def('Revealed second',['Instant'],{colorsOverride:[color]}),'hand')],wrong=put(a,def('Wrong revealed color',['Instant'],{colorsOverride:['B']}),'hand');cards(a,revealed);let observed=[];g.revealToHuman=async q=>{observed=q.cards;};const life=a.life,host=donor({toughness:'10'}),power=host.power;if(name==='Martyr of Spores')targets(a,[host]);let spell;if(name==='Martyr of Frost'){g.turnPlayer=b;spell=put(b,def('Actual martyr counter target',['Instant'],{cost:'{1}',resolve:async()=>{b.martyrResolved=true;}}),'hand');assert.equal(await g.castSpell(b,spell,{from:'hand'}),true);targets(a,[g.stack.find(o=>o.card===spell)]);choose(b,q=>q.type==='chooseOption'&&q.options.some(o=>o.key==='no')?{...q,options:q.options.filter(o=>o.key==='no')}:null);}await activate(f,c);assert.equal(c.zone,'graveyard');assert.equal(JSON.stringify(observed.map(x=>x.iid).sort()),JSON.stringify(revealed.map(x=>x.iid).sort()));assert.equal(wrong.zone,'hand');if(name==='Martyr of Sands')assert.equal(a.life,life+6);if(name==='Martyr of Spores')assert.equal(host.power,power+2);if(name==='Martyr of Ashes')assert.equal(host.damage,2);if(name==='Martyr of Frost'){assert.equal(spell.zone,'graveyard');assert.equal(b.martyrResolved,undefined);}}
 else if(name==='Rift Elemental'){const q=donor();g.addCounters(q,'time',2);cards(a,[q]);const power=c.power;await activate(f,c);assert.equal(q.counters.time,1);assert.equal(c.power,power+2);}
 else if(name==='Nivmagus Elemental'){const spell=put(a,def('Actually exiled uncounterable spell',['Instant'],{cost:'{1}',uncounterable:true,resolve:async()=>{a.nivResolved=true;}}),'hand');assert.equal(await g.castSpell(a,spell,{from:'hand'}),true);cards(a,[spell]);await activate(f,c);assert.equal(spell.zone,'exile');assert.equal(a.nivResolved,undefined);assert.equal(c.counters['+1/+1'],2);}
 else if(name==='Planar Guide'){const first=donor(),second=permanent(g,b,def('Other blinked creature')),oldFirst=first.zoneVersion;await activate(f,c);assert.equal(c.zone,'exile');assert.equal(first.zone,'exile');assert.equal(second.zone,'exile');await g.emit('endStep',{player:a});await settle(g);assert.equal(first.zone,'battlefield');assert.equal(second.zone,'battlefield');assert.equal(first.zoneVersion,oldFirst+2);assert.equal(c.zone,'exile');}
 else if(name==='Void Maw'){const q=donor(),power=c.power;await g.sacrifice(a,q);await settle(g);assert.equal(q.zone,'exile');assert.equal(M.OracleV25Permanents.linked(g,c,'permanent-linked-v25').length,1);cards(a,[q]);await activate(f,c);assert.equal(q.zone,'graveyard');assert.equal(c.power,power+2);await g.sacrifice(a,c);await settle(g);assert.equal(c.zone,'graveyard');}
 else if(name==='Gisa, Glorious Resurrector'){const q=permanent(g,b,def('Gisa opposing creature')),mine=donor();await g.sacrifice(b,q);await settle(g);assert.equal(q.zone,'exile');await g.sacrifice(a,mine);await settle(g);assert.equal(mine.zone,'graveyard');await g.emit('upkeep',{player:a});await settle(g);assert.equal(q.zone,'battlefield');assert.equal(q.ctrl.idx,a.idx);assert.equal(q.kw('decayed'),true);assert.equal(g.canBlock(q,donor()),false);}
 else if(name==='Liesa, Forgotten Archangel'){const q=donor(),opponent=permanent(g,b,def('Liesa opposing creature')),token=donor();token.isToken=true;await g.sacrifice(b,opponent);await g.sacrifice(a,q);await g.sacrifice(a,token);await settle(g);assert.equal(opponent.zone,'exile');assert.equal(q.zone,'graveyard');await g.emit('endStep',{player:a});await settle(g);assert.equal(q.zone,'hand');assert.equal(c.kw('flying'),true);assert.equal(c.kw('lifelink'),true);}
 else if(name==="Necromancer's Magemark"){const host=g.byIid(c.attachedTo),power=host.power;assert.ok(g.snapshot(host).enchanted);await g.destroy(host);await settle(g);assert.equal(host.zone,'hand');assert.equal(c.zone,'graveyard');assert.equal(host.power,power-1);}
 else if(name==='Betrothed of Fire'){const host=g.byIid(c.attachedTo),q=donor(),wrong=donor(),ally=donor(),enemy=permanent(g,b,def('Betrothed opposing creature'));assert.ok(host);g.tap(wrong);const hostPower=host.power,allyPower=ally.power,wrongPower=wrong.power,enemyPower=enemy.power,before=total(a);cards(a,[q]);await activate(f,c,0);assert.equal(q.zone,'graveyard');assert.equal(wrong.zone,'battlefield');assert.equal(wrong.tapped,true);assert.equal(host.power,hostPower+2);assert.equal(ally.power,allyPower);assert.equal(enemy.power,enemyPower);assert.equal(c.zone,'battlefield');assert.equal(total(a),before);cards(a,[host]);await activate(f,c,1);assert.equal(host.zone,'graveyard');assert.equal(c.zone,'graveyard');assert.equal(ally.power,allyPower+2);assert.equal(wrong.power,wrongPower+2);assert.equal(enemy.power,enemyPower);assert.equal(total(a),before);}
 else if(name==='Bloodfire Infusion'){const host=g.byIid(c.attachedTo),mine=donor({toughness:'10'}),enemy=permanent(g,b,def('Bloodfire surviving enemy',['Creature'],{toughness:'10'})),before=total(a);assert.equal(host.power,4);await activate(f,c);assert.equal(total(a),before-1);assert.equal(host.zone,'graveyard');assert.equal(c.zone,'graveyard');assert.equal(mine.damage,4);assert.equal(enemy.damage,4);}
 else if(name==="Jhoira's Timebug"){const q=donor(),suspended=put(a,def('Actual suspended creature'),'exile'),notSuspended=put(a,def('Not suspended creature'),'exile'),foreign=permanent(g,b,def('Foreign permanent'));suspended.meta.suspended=true;g.addCounters(q,'time',2);g.addCounters(suspended,'time',2);const spec=c.def.abilities[0].targets[0];assert.equal(g.legalTargets(spec,c,a).includes(notSuspended),false);assert.equal(g.legalTargets(spec,c,a).includes(foreign),false);targets(a,[q]);choose(a,q=>q.type==='chooseOption'&&q.options.some(o=>o.key==='add')?{...q,options:q.options.filter(o=>o.key==='add')}:null);await activate(f,c);assert.equal(q.counters.time,3);c.tapped=false;targets(a,[suspended]);choose(a,q=>q.type==='chooseOption'&&q.options.some(o=>o.key==='remove')?{...q,options:q.options.filter(o=>o.key==='remove')}:null);await activate(f,c);assert.equal(suspended.counters.time,1);assert.equal(suspended.zone,'exile');}
 else if(name==='Vodalian War Machine'){const first=donor({subtypes:['Merfolk']}),second=donor({subtypes:['Merfolk']}),wrong=donor({subtypes:['Human']}),power=c.power;assert.equal(g.canAttackAtAll(c),false);cards(a,[first]);await activate(f,c,0);assert.equal(first.tapped,true);assert.equal(g.canAttackAtAll(c),true);cards(a,[second]);await activate(f,c,1);assert.equal(second.tapped,true);assert.equal(c.power,power+2);await g.sacrifice(a,c);await settle(g);assert.equal(first.zone,'graveyard');assert.equal(second.zone,'graveyard');assert.equal(wrong.zone,'battlefield');}
 else if(name==='The Darkness Crystal'){const black=put(a,def('Crystal discounted black',['Instant'],{cost:'{2}{B}',resolve:async()=>{a.crystalResolved=true;}}),'hand'),before=total(a);assert.equal(await g.castSpell(a,black,{from:'hand'}),true);assert.equal(total(a),before-2);await settle(g);assert.equal(a.crystalResolved,true);const q=permanent(g,b,def('Crystal actual linked enemy',['Creature'],{power:'4',toughness:'5'})),unlinked=put(b,def('Crystal unrelated exile'),'exile'),token=permanent(g,b,def('Crystal token'));token.isToken=true;const life=a.life;await g.sacrifice(b,q);await settle(g);assert.equal(q.zone,'exile');assert.equal(a.life,life+2);await g.sacrifice(b,token);await settle(g);assert.equal(a.life,life+2);const spec=c.def.abilities[0].targets[0];assert.equal(g.legalTargets(spec,c,a).includes(unlinked),false);targets(a,[q]);const mana=total(a);await activate(f,c);assert.equal(total(a),mana-6);assert.equal(c.tapped,true);assert.equal(q.zone,'battlefield');assert.equal(q.ctrl.idx,a.idx);assert.equal(q.tapped,true);assert.equal(q.counters['+1/+1'],2);assert.equal(q.power,6);}
 else throw Error('Missing whole proof '+name);assertGameStateInvariants(g);assert.equal(a.controller instanceof M.AIController,role==='ai');
});


for(const role of ['human','ai']){
 test(role+': tapped power is captured once and ability copies do not repay',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const c=await source(f,'Impelled Giant'),q=permanent(g,a,def('Copied paid power',['Creature'],{power:'4',colorsOverride:['R']}));c.sick=false;cards(a,[q]);const power=c.power,row=g.activatableList(a).find(x=>x.card===c&&!x.manaAbility);assert.ok(row);assert.equal(await g.activateAbility(a,row),true);assert.equal(q.tapped,true);const so=g.stack.find(x=>x.srcCard===c);assert.ok(so);assert.equal(so.ctx.oracleActivationPaymentV28.rows[0].snapshot.power,4);q.def={...q.def,power:'99'};await g.move(q,'hand');const copy=await g.copyStackAbility(so,a);assert.ok(copy);assert.equal(copy.ctx.oracleActivationPaymentV28,so.ctx.oracleActivationPaymentV28);await settle(g);assert.equal(c.power,power+8);assert.equal(q.zone,'hand');assertGameStateInvariants(g);});
 test(role+': stale shared tappers are rejected before mana or tap',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const c=await source(f,'Cryptic Gateway'),q=permanent(g,a,def('Stale shared Elf',['Creature'],{subtypes:['Elf']})),r=permanent(g,a,def('Other shared Elf',['Creature'],{subtypes:['Elf']})),prior=a.controller.decide.bind(a.controller);let n=0;a.controller.decide=async(g,query)=>{if(query.type==='chooseCards'&&query.aiHint?.activationPaymentV20){if(n++){await g.move(q,'hand');await g.putPermanentOntoBattlefield(q,a);}return prior(g,{...query,from:[n===1?q:r],min:1,max:1});}return prior(g,query);};const before=total(a),row=g.activatableList(a).find(x=>x.card===c);assert.ok(row);assert.equal(await g.activateAbility(a,row),false);assert.equal(total(a),before);assert.equal(q.tapped,false);assert.equal(r.tapped,false);assertGameStateInvariants(g);});
 test(role+': tapped donors cannot also pay the activation mana',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const c=await source(f,'Unerring Sling'),q=permanent(g,a,def('Only mana and tap donor',['Creature'],{mana:[{produce:[{C:1}],cost:{tap:true}}]})),enemy=permanent(g,b,def('Actual flying attacker',['Creature'],{kws:['flying'],toughness:'10'}));enemy.attacking=a;for(const color of Object.keys(a.pool))a.pool[color]=0;cards(a,[q]);targets(a,[enemy]);assert.equal(g.activatableList(a).some(x=>x.card===c),false);assert.equal(q.tapped,false);assert.equal(c.tapped,false);assert.equal(enemy.damage,0);assertGameStateInvariants(g);});
 test(role+': zero revealed cards pay the printed cost and gain zero',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const c=await source(f,'Martyr of Sands'),life=a.life,before=total(a);await activate(f,c);assert.equal(c.zone,'graveyard');assert.equal(a.life,life);assert.equal(total(a),before-1);assertGameStateInvariants(g);});
 test(role+': Liesa and Planar Guide ignore a card that left and returned',async()=>{for(const name of['Liesa, Forgotten Archangel','Planar Guide']){const f=context(M,role),{game:g,a}=f;fund(a);const c=await source(f,name),q=permanent(g,a,def('Reincarnated delayed creature'));c.sick=false;if(name==='Planar Guide')await activate(f,c);else{await g.sacrifice(a,q);await settle(g);}const zone=q.zone;await g.move(q,'hand');await g.move(q,zone);await g.emit('endStep',{player:a});await settle(g);assert.equal(q.zone,zone);assertGameStateInvariants(g);}});
 test(role+': simultaneous destruction retains Liesa replacement and suppressed sources do not replace',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const c=await source(f,'Liesa, Forgotten Archangel'),enemy=permanent(g,b,def('Simultaneous opposing creature'));await g.destroyMany([c,enemy]);await settle(g);assert.equal(c.zone,'graveyard');assert.equal(enemy.zone,'exile');const v=await source(f,'Void Maw'),q=permanent(g,b,def('Disabled replacement victim'));M.OracleV8AbilityLoss.add(g,[v],{temporary:true});assert.equal(v.cur.abilitiesDisabled,true);await g.sacrifice(b,q);await settle(g);assert.equal(q.zone,'graveyard');assertGameStateInvariants(g);});
 test(role+': ordered exile replacements link to the chosen source only',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const v=await source(f,'Void Maw'),c=await source(f,'Gisa, Glorious Resurrector'),q=permanent(g,b,def('Ordered replacement creature'));choose(b,query=>query.type==='chooseOption'&&query.options.some(o=>String(o.label).startsWith(c.name+' —'))?{...query,options:query.options.filter(o=>String(o.label).startsWith(c.name+' —'))}:null);await g.sacrifice(b,q);await settle(g);assert.equal(q.zone,'exile');assert.equal(M.OracleV25Permanents.linked(g,c,'permanent-linked-v25').includes(q),true);assert.equal(M.OracleV25Permanents.linked(g,v,'permanent-linked-v25').includes(q),false);await g.move(c,'hand');await g.putPermanentOntoBattlefield(c,a);await g.emit('upkeep',{player:a});await settle(g);assert.equal(q.zone,'exile');assertGameStateInvariants(g);});
 test(role+': Slobad mana pays artifact spells and artifact abilities only',async()=>{const f=context(M,role),{game:g,a}=f;fund(a);const c=await source(f,'Slobad, Iron Goblin'),q=permanent(g,a,def('Restricted mana donor',['Artifact'],{cost:'{3}'}));c.sick=false;for(const color of Object.keys(a.pool))a.pool[color]=0;cards(a,[q]);const row=g.activatableList(a).find(x=>x.card===c&&x.manaAbility);assert.ok(row);assert.equal(await g.activateAbility(a,row),true);assert.equal(a.pool.R,3);const wrong=put(a,def('Forbidden restricted creature',['Creature'],{cost:'{1}'}),'hand');assert.equal(await g.castSpell(a,wrong,{from:'hand'}),false);const wrongAbility=permanent(g,a,def('Forbidden creature activation',['Creature'],{abilities:[{cost:{mana:'{1}'},run:async()=>{a.wrongRestricted=true;}}]}));assert.equal(g.activatableList(a).some(x=>x.card===wrongAbility),false);const artifact=put(a,def('Allowed restricted artifact',['Artifact'],{cost:'{2}',abilities:[{cost:{mana:'{1}'},run:async()=>{a.paidRestricted=true;}}]}),'hand');assert.equal(await g.castSpell(a,artifact,{from:'hand'}),true);await settle(g);assert.equal(a.pool.R,1);const activation=g.activatableList(a).find(x=>x.card===artifact);assert.ok(activation);assert.equal(await g.activateAbility(a,activation),true);await settle(g);assert.equal(a.paidRestricted,true);assert.equal(a.wrongRestricted,undefined);assert.equal(a.pool.R,0);assertGameStateInvariants(g);});
}
test('28 paid bodies reject missing donor bindings',()=>{for(const oracle_text of ['{T}: This creature gets +X/+0 until end of turn, where X is the power of the creature tapped this way.','{T}: This creature gains indestructible until end of turn. If the sacrificed creature was a Human, put a +1/+1 counter on this creature.'])assert.equal(semanticClass({name:'Unbound paid body',mana_cost:'{G}',type_line:'Creature — Elf',oracle_text,power:'2',toughness:'2',layout:'normal'},{compilerVersion:28}).semanticClass,undefined);});
