import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {loadEngine} from './helpers/load-engine.mjs';const M=loadEngine();import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';import {assertGameStateInvariants}from './helpers/game-state-invariants.mjs';
const report=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v26-layouts-runtime.json',import.meta.url),'utf8')).batches[0];const absent=report.cards.filter(c=>!M.DEFS[c.raw.name]);if(absent.length){M.registerOracleBatch({...report,cards:absent});M.initData(M.RAW_DATA);}
const fund=p=>{for(const c of ['W','U','B','R','G','C'])p.pool[c]=40;},total=p=>Object.values(p.pool).reduce((s,n)=>s+n,0),ids=cards=>Array.from(cards,c=>c.iid);
const choose=(p,predicate,value)=>{const old=p.controller.decide.bind(p.controller);p.controller.decide=async(g,q)=>predicate(q)?value(q,g):old(g,q);};
const card=(f,name,types=['Creature'],cost='{2}',subtypes=[],owner=f.a)=>{const c=put(M,f.game,owner,'Grizzly Bears','library');c.def={...c.def,name,types,cost,subtypes,super:[],kws:[],power:'3',toughness:'7',colorsOverride:[]};f.game.recalc();return c;};
const cast=async(f,name,opts={})=>{
 fund(f.a);const from=opts.from||'hand',source=put(M,f.game,f.a,name,from),mana=total(f.a);
 const offered=opts.alt&&f.game.castableList(f.a).find(row=>row.card===source&&row.from===from&&Object.entries(opts.alt).every(([key,value])=>row.alt?.[key]===value));
 if(opts.alt)assert.ok(offered,name+': requested printed alternative is actually offered');
 assert.equal(await f.game.castSpell(f.a,source,{from,...opts,...(offered?{alt:offered.alt}:{})}),true,name);
 await settle(f.game);assert.ok(total(f.a)<mana,name+': printed cost paid');return source;
};
const activate=async(f,source)=>{const row=f.game.activatableList(f.a).find(r=>r.card===source&&r.ability?.oracleOperation?.effects?.some(e=>JSON.stringify(e).includes('-v26')));assert.ok(row,source.name+': printed activation offered');const mana=total(f.a);assert.equal(await f.game.activateAbility(f.a,row),true);await settle(f.game);assert.ok(total(f.a)<mana);return row;};
for(const role of ['human','ai']){
 test(role+': Bison Whistle retains one inspected object through independent Bison and creature conditions',async()=>{for(const [types,subs,entry,hand,destination]of [[['Creature'],['Bison'],true,true,'battlefield'],[['Creature'],['Bison'],false,true,'hand'],[['Creature'],[],false,true,'hand'],[['Land'],[],false,false,'graveyard']]){const f=context(M,role),top=card(f,'Actual inspected',types,'{3}',subs);choose(f.a,q=>q.type==='chooseOption'&&/^Move the inspected card/.test(q.prompt||''),q=>q.prompt.includes('battlefield')?(entry?'yes':'no'):'yes');choose(f.a,q=>q.type==='chooseOption'&&q.prompt==='Reveal the inspected card?',()=>hand?'yes':'no');const source=await cast(f,'Bison Whistle'),version=top.zoneVersion;await activate(f,source);assert.equal(top.zone,destination);assert.equal(top.zoneVersion,version+1);assert.ok(top.owner===f.a);assertGameStateInvariants(f.game);}});
 test(role+': Delver paid front, optional reveal, actual transform and flying back share the physical object',async()=>{for(const [type,accept,back]of [['Instant',true,true],['Instant',false,false],['Land',true,false]]){const f=context(M,role),top=card(f,'Delver observed',[type]),source=await cast(f,'Delver of Secrets // Insectile Aberration'),faces=source.oracleFaces,version=source.zoneVersion;choose(f.a,q=>q.prompt==='Reveal the inspected card?',()=>accept?'yes':'no');const shown=[];f.game.revealToHuman=async q=>shown.push(q);await f.game.emit('upkeep',{player:f.a});await settle(f.game);assert.equal(source.oracleFace,back?'back':'front');assert.equal(source.kw('flying'),back);assert.equal(source.zoneVersion,version);assert.ok(source.oracleFaces===faces);assert.equal(shown.length,accept?1:0);if(accept)assert.ok(shown[0].cards[0]===top);assert.equal(top.zone,'library');assertGameStateInvariants(f.game);}});
 test(role+': Believe pays aftermath and puts the same card in hand after a declined or ineligible battlefield choice',async()=>{for(const [type,accept,destination]of [['Creature',true,'battlefield'],['Creature',false,'hand'],['Land',true,'hand']]){const f=context(M,role),top=card(f,'Believe observed',[type]);choose(f.a,q=>q.prompt==='Move the inspected card to battlefield?',()=>accept?'yes':'no');const source=await cast(f,'Reason // Believe',{from:'graveyard',alt:{splitHalf:'right'}});assert.equal(source.zone,'exile');assert.equal(top.zone,destination);assert.ok(top.owner===f.a);assertGameStateInvariants(f.game);}});
 test(role+': Impromptu Raid gives the exact entered creature haste and guards its delayed sacrifice across a zone change',async()=>{for(const bounce of [false,true]){const f=context(M,role),top=card(f,'Raid observed'),source=await cast(f,'Impromptu Raid');await activate(f,source);assert.equal(top.zone,'battlefield');assert.equal(top.kw('haste'),true);if(bounce){await f.game.move(top,'hand');await f.game.putPermanentOntoBattlefield(top,f.a);}await f.game.emit('endStep',{player:f.b});await settle(f.game);assert.equal(top.zone,bounce?'battlefield':'graveyard');assertGameStateInvariants(f.game);}});
 test(role+': Owlbear checks the actual defending player land count and enters its inspected creature attacking that player',async()=>{for(const lands of [7,8]){const f=context(M,role),top=card(f,'Owlbear inspected');for(let i=0;i<7;i++)card(f,'Owlbear rest '+i,['Land'],'');for(let i=0;i<lands;i++)put(M,f.game,f.b,'Forest');const source=await cast(f,'Owlbear Cub');source.sick=false;choose(f.a,q=>q.type==='attackers',()=>[{card:source,target:f.b}]);choose(f.a,q=>q.prompt==='Choose library cards for battlefield',q=>q.from.includes(top)?[top]:[]);const old=f.game.putPermanentOntoBattlefield,entered=[];f.game.putPermanentOntoBattlefield=async function(c,p,opts){const result=await old.call(this,c,p,opts);if(c===top)entered.push({attacking:c.attacking,tapped:c.tapped,ctrl:c.ctrl,options:opts});return result;};f.game.priorityRound=async()=>settle(f.game);await f.game.combatPhase(f.a);await settle(f.game);assert.equal(entered.length,lands===8?1:0);if(lands===8){assert.ok(entered[0].attacking===f.b);assert.ok(entered[0].ctrl===f.a);assert.equal(entered[0].tapped,true);}else assert.equal(top.zone,'library');assertGameStateInvariants(f.game);}});
 test(role+': Turntimber counters apply during entry from the actual mana value; its back land pays life or enters tapped',async()=>{for(const mv of [3,4]){const f=context(M,role),top=card(f,'Turntimber observed',['Creature'],'{'+mv+'}');choose(f.a,q=>q.prompt==='Choose library cards for battlefield',q=>q.from.includes(top)?[top]:[]);const old=f.game.putPermanentOntoBattlefield,observed=[];f.game.putPermanentOntoBattlefield=async function(c,p,opts){const result=await old.call(this,c,p,opts);if(c===top)observed.push(c.counters['+1/+1']||0);return result;};await cast(f,'Turntimber Symbiosis // Turntimber, Serpentine Wood');assert.deepEqual(observed,[mv<=3?3:0]);assert.equal(top.counters['+1/+1']||0,mv<=3?3:0);assertGameStateInvariants(f.game);}for(const pay of [false,true]){const f=context(M,role),source=put(M,f.game,f.a,'Turntimber Symbiosis // Turntimber, Serpentine Wood','hand');choose(f.a,q=>q.type==='chooseOption'&&q.options?.some(o=>/Pay 3 life/i.test(o.label)),()=>pay?'pay':'tapped');assert.equal(await f.game.playLand(f.a,source,{oracleFace:'back'}),true);await settle(f.game);assert.equal(source.oracleFace,'back');assert.equal(source.tapped,!pay);assert.equal(f.a.life,pay?37:40);assertGameStateInvariants(f.game);}});
 test(role+': revealed and actually milled mana values drive paid damage, including graveyard replacement',async()=>{for(const name of ['Erratic Explosion','Riddle of Lightning','Goblin Charbelcher',"Heretic's Punishment"]){const f=context(M,role);choose(f.a,q=>q.type==='chooseTargets'&&q.candidates.includes(f.b),()=>[f.b]);if(name==='Goblin Charbelcher'){card(f,'Mountain stop',['Land'],'',['Mountain']);for(let i=0;i<3;i++)card(f,'Nonland prefix '+i,['Artifact'],'{2}');}else if(name==="Heretic's Punishment"){put(M,f.game,f.b,'Rest in Peace');for(const n of [2,8,4])card(f,'Actual mill '+n,['Artifact'],'{'+n+'}');}else{card(f,'Actual observed mana',['Artifact'],'{5}');if(name==='Erratic Explosion')for(let i=0;i<2;i++)card(f,'Nonland-search prefix '+i,['Land'],'');}const source=await cast(f,name);if(source.zone==='battlefield')await activate(f,source);assert.equal(f.b.life,40-(name==='Goblin Charbelcher'?6:name==="Heretic's Punishment"?8:5));if(name==="Heretic's Punishment")assert.equal(f.a.exile.filter(c=>c.name.startsWith('Actual mill')).length,3);assertGameStateInvariants(f.game);}});
 test(role+': Calibrated Blast creates a separate targeted damage trigger and never substitutes a newly revealed card',async()=>{const f=context(M,role),top=card(f,'Calibrated actual',['Artifact'],'{7}');for(let i=0;i<2;i++)card(f,'Blast prefix '+i,['Land'],'');choose(f.a,q=>q.type==='chooseTargets'&&q.candidates.includes(f.b),()=>[f.b]);const source=await cast(f,'Calibrated Blast');assert.equal(source.zone,'graveyard');assert.equal(f.b.life,33);assert.equal(top.zone,'library');assert.equal(f.game.stack.length,0);assertGameStateInvariants(f.game);});
 test(role+': Sanity Grinding counts literal blue symbols in hybrid costs and Amplifire captures printed library stats',async()=>{let f=context(M,role);for(let i=0;i<6;i++)card(f,'Uncoloured revealed '+i,['Artifact'],'{5}');for(let i=0;i<2;i++)card(f,'Four blue symbols '+i,['Artifact'],'{U}{U/P}{2/U}{G/U}');for(let i=0;i<2;i++)card(f,'X is not a blue symbol '+i,['Artifact'],'{X}{U}');choose(f.a,q=>q.type==='chooseTargets'&&q.candidates.includes(f.b),()=>[f.b]);await cast(f,'Sanity Grinding');assert.equal(f.b.library.length,20);assertGameStateInvariants(f.game);f=context(M,role);const top=card(f,'Amplifier actual');top.def={...top.def,power:'3',toughness:'7'};for(let i=0;i<2;i++)card(f,'Amplifier prefix '+i,['Land'],'');const source=await cast(f,'Amplifire');await f.game.emit('upkeep',{player:f.a});await settle(f.game);assert.equal(source.power,6);assert.equal(source.toughness,14);const record=f.game.untilEffects.find(e=>e.kind==='oracleBasePT'&&e.iid===source.iid);assert.equal(record.expires,'untilTurnOf');assert.ok(record.whoTurn===f.a);assert.equal(top.zone,'library');assertGameStateInvariants(f.game);});
}
for(const role of ['human','ai']){
 test(role+': public piles, an opponent-selected creature and face-down piles use exactly the captured cohort',async()=>{for(const name of ['Truth or Tale','Animal Magnetism','Curator of Destinies','Intrude on the Mind']){const f=context(M,role),n=5,cohort=[];for(let i=0;i<n;i++)cohort.push(card(f,'Pile observed '+i,i%3===0?['Artifact']:['Creature'],'{'+(i+1)+'}'));const inspected=cohort.slice().reverse(),unseen=f.a.library.slice(0,-n),privateViews=[],publicViews=[],options=[];choose(f.a,q=>q.type==='cardReveal',q=>(privateViews.push(q),null));f.game.revealToHuman=async q=>publicViews.push(q);choose(f.a,q=>q.type==='chooseCards'&&/^Choose (?:the face-down|the first inspected) pile$/.test(q.prompt||''),q=>q.from.slice(0,2));choose(f.b,q=>q.prompt==='Choose one inspected pile',q=>(options.push(q),'one'));choose(f.b,q=>q.prompt==='Choose one inspected creature card',q=>q.from.slice(0,1));choose(f.a,q=>q.prompt==='Choose one card from the chosen pile',q=>q.from.slice(0,1));await cast(f,name);if(name==='Truth or Tale'){assert.equal(inspected[0].zone,'hand');assert.ok(inspected.slice(1).every(c=>c.zone==='library'));}else if(name==='Animal Magnetism'){const eligible=inspected.filter(c=>c.def.types.includes('Creature'));assert.equal(eligible[0].zone,'battlefield');assert.ok(inspected.filter(c=>c!==eligible[0]).every(c=>c.zone==='graveyard'));}else{assert.ok(inspected.slice(0,2).every(c=>c.zone==='hand'));assert.ok(inspected.slice(2).every(c=>c.zone==='graveyard'));}if(name==='Curator of Destinies'){if(role==='human'){assert.equal(privateViews.length,1);assert.equal(privateViews[0].private,true);assert.deepEqual(ids(privateViews[0].cards),ids(inspected));}assert.deepEqual(ids(publicViews[0].cards),ids(inspected.slice(2)));assert.equal(options[0].options[0].label,'Face-down pile (2 cards)');assert.equal(options[0].cards,undefined);assert.equal(options[0].from,undefined);}if(name==='Intrude on the Mind'){const token=f.game.creatures(f.a).find(c=>c.isToken&&c.hasSub('Thopter'));assert.ok(token);assert.equal(token.counters['+1/+1'],3);assert.equal(token.power,3);}assert.deepEqual(ids(f.a.library.filter(c=>unseen.includes(c))),ids(unseen));assertGameStateInvariants(f.game);}});
 test(role+': piles with no eligible creature or a chosen empty pile still move the printed remainder',async()=>{for(const name of ['Animal Magnetism','Epiphany at the Drownyard']){const f=context(M,role),cohort=[];for(let i=0;i<(name==='Animal Magnetism'?5:1);i++)cohort.push(card(f,'No eligible '+i,['Artifact'],'{3}'));choose(f.a,q=>q.prompt==='Choose the first inspected pile',()=>[]);choose(f.b,q=>q.prompt==='Choose one inspected pile',()=> 'one');await cast(f,name,{xVal:0});assert.ok(cohort.every(c=>c.zone==='graveyard'));assertGameStateInvariants(f.game);}});
 test(role+': library choices follow captured object versions when a presentation callback changes the top card',async()=>{const f=context(M,role),next=card(f,'Uninspected successor'),top=card(f,'Inspected version'),source=await cast(f,'Bison Whistle');const before=top.zoneVersion;const change=async()=>{await f.game.move(top,'hand');await f.game.move(top,'library');return null;};if(role==='human')choose(f.a,q=>q.type==='cardReveal',change);else{choose(f.a,q=>q.prompt==='Move the inspected card to hand?',()=> 'yes');f.game.revealToHuman=change;}await activate(f,source);assert.equal(top.zone,'library');assert.equal(top.zoneVersion,before+2);assert.equal(next.zone,'library');assert.ok(f.a.library.at(-1)===top);assertGameStateInvariants(f.game);});
 test(role+': land Deceivers pay their printed activation and enforce once each turn on the granted consequence',async()=>{for(const name of ['Harsh Deceiver','Cruel Deceiver']){const f=context(M,role);card(f,'Revealed land',['Land'],'');const source=await cast(f,name),power=source.power;source.tapped=true;const ability=f.game.activatableList(f.a).find(r=>r.card===source&&r.ability?.oracleOperation?.effects?.some(e=>e.action==='library-top-card-v26'&&e.visibility==='reveal'));assert.ok(ability);const mana=total(f.a);assert.equal(await f.game.activateAbility(f.a,ability),true);await settle(f.game);assert.equal(total(f.a),mana-2);assert.equal(f.game.activatableList(f.a).some(r=>r.card===source&&r.ability?.oracleOperation===ability.ability.oracleOperation),false);if(name==='Harsh Deceiver'){assert.equal(source.tapped,false);assert.equal(source.power,power+1);}else{const enemy=put(M,f.game,f.b,'Grizzly Bears');enemy.def={...enemy.def,toughness:'20'};f.game.recalc();await f.game.damageCreature(source,enemy,1);await settle(f.game);assert.equal(enemy.zone,'graveyard');}assertGameStateInvariants(f.game);}});
}

for(const role of ['human','ai'])test(role+': Rulik creates its Goblin only when no inspected card entered, including an empty library',async()=>{for(const [type,accept,empty,tokens]of [['Land',true,false,0],['Land',false,false,1],['Creature',true,false,1],['Land',true,true,1]]){const f=context(M,role),top=card(f,'Rulik observed',[type],type==='Land'?'':'{2}');const source=await cast(f,'Rulik Mons, Warren Chief');if(empty)for(const c of f.a.library.slice())await f.game.move(c,'exile');choose(f.a,q=>q.prompt==='Move the inspected card to battlefield?',()=>accept?'yes':'no');source.sick=false;choose(f.a,q=>q.type==='attackers',()=>[{card:source,target:f.b}]);f.game.priorityRound=async()=>settle(f.game);await f.game.combatPhase(f.a);await settle(f.game);const made=f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Goblin'));assert.equal(made.length,tokens);for(const c of made){assert.equal(c.power,1);assert.equal(c.toughness,1);}if(!empty)assert.equal(top.zone,type==='Land'&&accept?'battlefield':'library');assertGameStateInvariants(f.game);}});
