import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{loadEngine}from'./helpers/load-engine.mjs';import{context,settle}from'./helpers/oracle-v8-fixtures.mjs';import{semanticClass,createImportPlan}from'../scripts/import-oracle-batch.mjs';import{proveWholeV29,fund,total,def,put,permanent,choose,cards,targets,source,activate}from'./helpers/oracle-v29-permanents-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v29-permanents.json',import.meta.url),'utf8')),M=loadEngine(),plan=createImportPlan({cards:rows,bulk:{type:'oracle_cards'},sequence:9981,limit:rows.length,compilerVersion:29});assert.equal(plan.report.cards.length,rows.length);const absent=plan.report.cards.filter(e=>!M.DEFS[e.raw.name]);if(absent.length)M.registerOracleBatch({...plan.report,cards:absent});M.initData(M.RAW_DATA);
test('29 complete source closure',()=>{for(const c of rows){assert.ok(semanticClass(c,{compilerVersion:29}).semanticClass,c.name);assert.equal(semanticClass({...c,oracle_text:c.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:29}).semanticClass,undefined,c.name);}});
for(const role of['human','ai'])for(const c of rows)test(role+': '+c.name+' actual paid whole source',async()=>{const f=context(M,role);f.role=role;await proveWholeV29(M,f,c.name,settle);});

import{assertGameStateInvariants}from'./helpers/game-state-invariants.mjs';

for(const role of['human','ai']){
 const setup=()=>{const f=context(M,role);f.role=role;fund(f.a);fund(f.b);return f;};
 test(role+': paid discard snapshots survive card changes and ability copies',async()=>{const f=setup(),{game:g,a}=f,c=await source(M,f,'Volrath the Fallen',settle),q=put(M,a,def('Actual immutable discarded value',['Creature'],{cost:'{5}'}),'hand');c.sick=false;cards(a,[q]);const before=total(a),power=c.power,row=g.activatableList(a).find(x=>x.card===c);assert.equal(await g.activateAbility(a,row),true);const so=g.stack.find(x=>x.srcCard===c);assert.equal(so.ctx.discardedSnapshots[0].mv,5);assert.equal(q.zone,'graveyard');q.def={...q.def,cost:'{99}'};await g.move(q,'exile');assert.ok(await g.copyStackAbility(so,a));await settle(g);assert.equal(c.power,power+10);assert.equal(total(a),before-2);assert.equal(q.zone,'exile');assertGameStateInvariants(g);});
 test(role+': random discard value is fixed before replacement and copies do not repay',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Pyromancy',settle),q=put(M,a,def('Actual immutable random discard',['Instant'],{cost:'{5}'}),'hand');targets(a,[b]);const life=b.life,before=total(a),row=g.activatableList(a).find(x=>x.card===c);assert.equal(await g.activateAbility(a,row),true);const so=g.stack.find(x=>x.srcCard===c);assert.equal(so.ctx.oraclePaidDiscardV29[0].mv,5);q.def={...q.def,cost:'{99}'};await g.move(q,'hand');assert.ok(await g.copyStackAbility(so,a));await settle(g);assert.equal(b.life,life-10);assert.equal(total(a),before-3);assert.equal(q.zone,'hand');assertGameStateInvariants(g);});
 test(role+': mismatched discarded mana value does not counter',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Hisoka, Minamo Sensei',settle),q=put(M,a,def('Actual mismatched discard',['Instant'],{cost:'{2}'}),'hand'),spell=put(M,b,def('Actual surviving spell',['Instant'],{cost:'{3}',resolve:async()=>{b.mismatchResolved=true;}}),'hand');g.turnPlayer=b;assert.equal(await g.castSpell(b,spell,{from:'hand'}),true);cards(a,[q]);targets(a,[g.stack.find(x=>x.card===spell)]);await activate(f,c,settle);assert.equal(b.mismatchResolved,true);assert.equal(q.zone,'graveyard');assertGameStateInvariants(g);});
 test(role+': non-Zombie paid creature draws without a token',async()=>{const f=setup(),{game:g,a}=f,c=await source(M,f,"Necromancer's Stockpile",settle),q=put(M,a,def('Actual non-Zombie discard'),'hand'),hand=a.hand.length;cards(a,[q]);await activate(f,c,settle);assert.equal(q.zone,'graveyard');assert.equal(a.hand.length,hand);assert.equal(g.bf().filter(x=>x.hasSub('Zombie')).length,0);assertGameStateInvariants(g);});
 test(role+': monocolor random discard uses printed two-damage branch',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Stormscale Anarch',settle),q=put(M,a,def('Actual monocolor random discard',['Instant'],{colorsOverride:['R']}),'hand');targets(a,[b]);const life=b.life;await activate(f,c,settle);assert.equal(q.zone,'graveyard');assert.equal(b.life,life-2);assertGameStateInvariants(g);});
 test(role+': Clue history captures a token after its source incarnation ends',async()=>{const f=setup(),{game:g,a}=f,c=await source(M,f,'Briarbridge Patrol',settle),q=put(M,a,def('Actual optional hand creature'),'hand');cards(a,[q]);for(let i=0;i<2;i++)await g.sacrifice(a,permanent(M,g,a,def('Actual counted Clue '+i,['Artifact'],{subtypes:['Clue']})));await g.emit('endStep',{player:a});await settle(g);assert.equal(q.zone,'hand');const third=permanent(M,g,a,def('Actual third Clue',['Artifact'],{subtypes:['Clue']}));await g.sacrifice(a,third);third.def={...third.def,subtypes:['Food']};await g.emit('endStep',{player:a});await settle(g);assert.equal(q.zone,'battlefield');assertGameStateInvariants(g);});
 test(role+': current Goblin entry snapshot survives changed type and control',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Hobgoblin Bandit Lord',settle),q=put(M,a,def('Actual history Goblin',['Creature'],{subtypes:['Goblin']}),'hand');c.sick=false;await g.putPermanentOntoBattlefield(q,a);q.def={...q.def,subtypes:['Elf']};M.OracleV8Control.gain(g,q,b,{temporary:true});g.recalc();targets(a,[b]);const life=b.life;await activate(f,c,settle);assert.equal(b.life,life-2);assertGameStateInvariants(g);});
 test(role+': damage batch investigates once and player damage does not investigate',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Briarbridge Patrol',settle),first=permanent(M,g,b,def('Actual first damage recipient',['Creature'],{toughness:'10'})),second=permanent(M,g,b,def('Actual second damage recipient',['Creature'],{toughness:'10'}));await g.damageBatch([{src:c,target:first,n:1},{src:c,target:second,n:1},{src:c,target:b,n:1}],{deferSBA:true});await settle(g);assert.equal(g.bf().filter(x=>x.hasSub('Clue')).length,1);await g.damageBatch([{src:c,target:b,n:1}],{deferSBA:true});await settle(g);assert.equal(g.bf().filter(x=>x.hasSub('Clue')).length,1);assertGameStateInvariants(g);});
 test(role+': Lightmine counts tokens put into combat but damages only declared attackers',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Lightmine Field',settle),first=permanent(M,g,b,def('Actual declared attacker',['Creature'],{toughness:'10'}));first.attacking=a;await g.emit('attackersDeclared',{player:b,attackers:[first]});const token=permanent(M,g,b,def('Actual token put attacking',['Creature'],{toughness:'10'}));token.isToken=true;token.attacking=a;await settle(g);assert.equal(first.damage,2);assert.equal(token.damage,0);assertGameStateInvariants(g);});
 test(role+': Bonecache Food history gates the paid life and draw branch',async()=>{const f=setup(),{game:g,a}=f,c=await source(M,f,'Bonecache Overseer',settle);c.sick=false;await g.sacrifice(a,permanent(M,g,a,def('Actual irrelevant Clue',['Artifact'],{subtypes:['Clue']})));assert.equal(g.activatableList(a).some(x=>x.card===c),false);await g.sacrifice(a,permanent(M,g,a,def('Actual paid Food',['Artifact'],{subtypes:['Food']})));const hand=a.hand.length,life=a.life;await activate(f,c,settle);assert.equal(a.life,life-1);assert.equal(a.hand.length,hand+1);assertGameStateInvariants(g);});
 test(role+': life discount captures the resolution value and requires sorcery timing',async()=>{const f=setup(),{game:g,a}=f,c=await source(M,f,'Rowan, Scion of War',settle);c.sick=false;await g.loseLife(a,2,c);g.phase='upkeep';assert.equal(g.activatableList(a).some(x=>x.card===c),false);g.phase='main1';await activate(f,c,settle);await g.loseLife(a,3,c);const spell=put(M,a,def('Actual later black spell',['Instant'],{cost:'{5}{B}',resolve:async()=>{}}),'hand'),before=total(a);assert.equal(await g.castSpell(a,spell,{from:'hand'}),true);assert.equal(total(a),before-4);await settle(g);assertGameStateInvariants(g);});
 test(role+': Power Surge retains beginning count for extra upkeep after untap',async()=>{const f=setup(),{game:g,a,b}=f,c=await source(M,f,'Power Surge',settle),first=permanent(M,g,b,M.DEFS.Forest),second=permanent(M,g,b,M.DEFS.Forest);g.tap(second);g.turnPlayer=b;const life=b.life;await g.runBeginningPhase(b);await settle(g);assert.equal(b.life,life-1);await g.emit('upkeep',{player:b});await settle(g);assert.equal(b.life,life-2);assert.equal(second.tapped,false);assertGameStateInvariants(g);});
}
test('29 paid bodies reject unbound donors',()=>{for(const oracle_text of["{1}: This creature gets +X/+X until end of turn, where X is the discarded card's mana value.","{T}: Counter target spell if it has the same mana value as the discarded card.","{1}: Draw a card. If the discarded card was a Zombie card, create a tapped 2/2 black Zombie creature token."])assert.equal(semanticClass({name:'Unbound paid test',mana_cost:'{G}',type_line:'Creature — Elf',power:'2',toughness:'2',layout:'normal',oracle_text},{compilerVersion:29}).semanticClass,undefined);});

for(const role of['human','ai'])test(role+': native combat declaration triggers Lightmine before combat damage',async()=>{const f=context(M,role),{game:g,a,b}=f;fund(a);const c=await source(M,f,'Lightmine Field',settle),first=permanent(M,g,a,def('Actual first combat attacker',['Creature'],{power:'1',toughness:'10'})),second=permanent(M,g,a,def('Actual second combat attacker',['Creature'],{power:'1',toughness:'10'})),prior=a.controller.decide.bind(a.controller);a.controller.decide=(g,q)=>q.type==='attackers'?[{card:first,target:b},{card:second,target:b}]:prior(g,q);g.priorityRound=async()=>settle(g);g.reviewCombatWithHuman=async()=>{};const life=b.life;await g.combatPhase(a);await settle(g);assert.equal(first.damage,2);assert.equal(second.damage,2);assert.equal(b.life,life-2);assert.equal(first.meta._attackedTurn,g.turnNo);assert.equal(second.meta._attackedTurn,g.turnNo);assert.equal(a.controller instanceof M.AIController,role==='ai');assertGameStateInvariants(g);});
