import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createFixturePlan,registerCanonicalFixturePlan} from './helpers/oracle-fixture-plan.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {names,proveExtraV73} from './helpers/oracle-v73-extra-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v73-extra.json',import.meta.url)));
const plan=createFixturePlan(rows,73,9973),M=loadEngine();registerCanonicalFixturePlan(M,plan);
test('v73 extra rejects unknown full-card clauses',()=>{assert.equal(plan.report.cards.length,15);for(const row of rows)assert.equal(plan.classify({...row,oracle_text:row.oracle_text+'\nPerform an unsupported action.'}).semanticClass,undefined,row.name);});
for(const role of ['human','ai'])for(const name of names)for(const positive of [true,false])test(`${role}: ${name} complete paid rules ${positive}`,()=>proveExtraV73(M,name,role,positive));
