import fs from 'node:fs';

import test from 'node:test';
import assert from 'node:assert/strict';
import {loadEngine} from './helpers/load-engine.mjs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v24-layouts.json',import.meta.url),'utf8'));
const M=loadEngine(),absent=rows.filter(c=>!M.DEFS[c.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9959,limit:absent.length,compilerVersion:24});assert.equal(plan.report.cards.length,absent.length,JSON.stringify(plan.report.rejected));M.registerOracleBatch(plan.report);M.initData(M.RAW_DATA);}
const fund=p=>{for(const c of ['W','U','B','R','G','C'])p.pool[c]=40;};
const choose=(p,predicate,value)=>{const prior=p.controller.decide.bind(p.controller);p.controller.decide=async(g,q)=>{const answer=await prior(g,q);return predicate(q)?value(q,g):answer;};};
const witness=(f,name,cost,types=['Creature'],zone='library')=>{const card=put(M,f.game,f.a,'Grizzly Bears',zone);card.def={...card.def,name,cost,types,kws:[]};f.game.recalc();return card;};
const chapter=async(f,source,n)=>{f.game.addCounters(source,'lore',n-source.counters.lore,false,source.ctrl);await settle(f.game);};
test('v24 layouts consume every printed rule and reject an unknown extra paragraph',()=>{for(const row of rows){assert.ok(semanticClass(row,{compilerVersion:24}).semanticClass,row.name);assert.equal(semanticClass({...row,oracle_text:row.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:24}).semanticClass,undefined,row.name);}});
for(const role of ['human','ai']){
 test(role+': paid X qualifies exact hand cards and Mercadian Lift removes the paid counters',async()=>{
  for(const name of ['Metathran Aerostat','Mercadian Lift'])for(const accepted of [false,true]){const f=context(M,role),{game,a}=f;fund(a);const source=put(M,game,a,name),good=witness(f,'Paid X three','{3}',['Creature'],'hand'),bad=witness(f,'Paid X four','{4}',['Creature'],'hand');if(name==='Mercadian Lift')source.counters.winch=5;choose(a,q=>q.type==='chooseX',()=>3);choose(a,q=>q.prompt==='Choose a qualified permanent card from your hand',q=>{assert.ok(q.from.includes(good));assert.equal(q.from.includes(bad),false);return accepted?[good]:[];});const action=game.activatableList(a).find(row=>row.card===source&&row.ability.oracleOperation?.effects?.some(e=>e.action==='put-qualified-hand-v24'));assert.ok(action);const before=Object.values(a.pool).reduce((n,x)=>n+x,0);assert.equal(await game.activateAbility(a,action),true);assert.equal(before-Object.values(a.pool).reduce((n,x)=>n+x,0),name==='Metathran Aerostat'?4:0);if(name==='Mercadian Lift'){assert.equal(source.counters.winch,2);assert.equal(source.tapped,true);}await settle(game);assert.equal(good.zone,accepted?'battlefield':'hand');assert.equal(bad.zone,'hand');assert.equal(source.zone,name==='Metathran Aerostat'&&accepted?'hand':'battlefield');assertGameStateInvariants(game);}
 });
 test(role+': Meek Attack applies the summed printed power/toughness bound, haste, and an exact delayed sacrifice',async()=>{
  for(const changed of [false,true]){const f=context(M,role),{game,a,b}=f;fund(a);const source=put(M,game,a,'Meek Attack'),good=put(M,game,a,'Grizzly Bears','hand'),bad=witness(f,'Six total','{2}',['Creature'],'hand');good.def={...good.def,power:'2',toughness:'3'};bad.def={...bad.def,power:'3',toughness:'3'};game.recalc();choose(a,q=>q.prompt==='Choose a qualified permanent card from your hand',q=>{assert.ok(q.from.includes(good));assert.equal(q.from.includes(bad),false);return [good];});const before=Object.values(a.pool).reduce((n,x)=>n+x,0);assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source)),true);assert.equal(before-Object.values(a.pool).reduce((n,x)=>n+x,0),2);await settle(game);assert.equal(good.zone,'battlefield');assert.equal(good.kw('haste'),true);if(changed){await game.move(good,'hand');await game.move(good,'battlefield',{ctrl:a});assert.equal(good.kw('haste'),false);}await game.emit('endStep',{player:b});await settle(game);assert.equal(good.zone,changed?'battlefield':'graveyard');assertGameStateInvariants(game);}
 });
 test(role+': Zimone uses the live eight-land count after its first optional entry and repeats at most once',async()=>{
  for(const [lands,accept,draws]of [[6,true,1],[7,true,2],[8,false,2]]){const f=context(M,role),{game,a,b}=f;fund(a);const source=put(M,game,a,'Zimone and Dina'),donor=put(M,game,a,'Grizzly Bears');for(let i=0;i<lands;i++)put(M,game,a,'Forest');const cards=[put(M,game,a,'Forest','hand'),put(M,game,a,'Forest','hand')];let selected=0;choose(a,q=>q.prompt==='Choose a qualified permanent card from your hand',()=>accept?[cards[selected++]]:[]);const events=[],emit=game.emit;game.emit=function(name,data,...args){if(name==='draw'&&data.player===a)events.push(data.card);return emit.call(this,name,data,...args);};const life=a.life,enemyLife=b.life;assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source)),true);assert.equal(donor.zone,'graveyard');assert.equal(source.tapped,true);await settle(game);assert.equal(events.length,draws);assert.equal(cards.filter(c=>c.zone==='battlefield').length,accept?draws:0);assert.ok(cards.filter(c=>c.zone==='battlefield').every(c=>c.tapped));assert.equal(a.life,life+(draws===2?2:0));assert.equal(b.life,enemyLife-(draws===2?2:0));assertGameStateInvariants(game);}
 });
 test(role+': Urza’s third chapter permits two actual loyalty activations and expires with the turn',async()=>{
  const f=context(M,role),{game,a}=f;fund(a);const walker=put(M,game,a,'Elspeth, Knight-Errant','hand');assert.equal(await game.castSpell(a,walker,{from:'hand'}),true);await settle(game);assert.equal(walker.counters.loyalty,4);choose(a,q=>q.aiHint?.kind==='readAhead',()=> '3');const source=put(M,game,a,'Urza Assembles the Titans','hand');assert.equal(await game.castSpell(a,source,{from:'hand'}),true);await settle(game);assert.equal(source.zone,'graveyard');assert.equal(a.turnState.oracleLoyaltyTwiceV24Turn,game.turnNo);for(let i=0;i<2;i++){const action=game.activatableList(a).find(r=>r.card===walker&&r.ability.loyalty!==undefined);assert.ok(action,JSON.stringify({i,phase:game.phase,step:game.step,can:game.canActivateLoyalty(walker),used:walker.meta.lcLoyaltyCount,zone:walker.zone,loyalty:walker.counters.loyalty,stack:game.stack.length}));assert.equal(await game.activateAbility(a,action),true);await settle(game);}assert.equal(game.activatableList(a).some(r=>r.card===walker&&r.ability.loyalty!==undefined),false);game.turnNo++;assert.equal(a.turnState.oracleLoyaltyTwiceV24Turn===game.turnNo,false);const next=game.activatableList(a).find(r=>r.card===walker&&r.ability.loyalty!==undefined);assert.ok(next);assert.equal(await game.activateAbility(a,next),true);await settle(game);assert.equal(game.activatableList(a).some(r=>r.card===walker&&r.ability.loyalty!==undefined),false);assertGameStateInvariants(game);
 });
 test(role+': Avacyn performs real paid chapter progression with both all-or-none destinations',async()=>{
  for(const accepted of [false,true]){const f=context(M,role),{game,a}=f;fund(a);const cards=[witness(f,'Avacyn creature','{2}'),witness(f,'Avacyn artifact','{5}',['Artifact']),witness(f,'Avacyn instant','{3}',['Instant'])];let next=0;choose(a,q=>q.search,()=>[cards[next++]]);choose(a,q=>q.prompt==='Put all linked permanent cards onto the battlefield?',()=>accepted?'yes':'no');const source=put(M,game,a,'The Creation of Avacyn','hand');assert.equal(await game.castSpell(a,source,{from:'hand'}),true);await settle(game);assert.equal(cards[0].zone,'exile');assert.equal(cards[0].faceDown,true);
   for(let i=0;i<2;i++){game.removeCounters(source,'lore',1);game.addCounters(source,'lore',1,false,a);await settle(game);}assert.ok(cards.every(c=>c.zone==='exile'&&c.faceDown));const life=a.life;await chapter(f,source,2);assert.equal(a.life,life-10);assert.ok(cards.every(c=>!c.faceDown));await chapter(f,source,3);assert.equal(cards[0].zone,accepted?'battlefield':'hand');assert.equal(cards[1].zone,accepted?'battlefield':'hand');assert.equal(cards[2].zone,'hand');assert.equal(source.zone,'graveyard');assertGameStateInvariants(game);
  }
 });
 test(role+': Avacyn skips all battlefield choices when its third chapter runs before the face-down cards are revealed',async()=>{
  const f=context(M,role),{game,a}=f;fund(a);const card=witness(f,'Unrevealed creature','{2}');choose(a,q=>q.search,()=>[card]);choose(a,q=>q.prompt==='Put all linked permanent cards onto the battlefield?',()=>{throw Error('No characteristics while face down');});const source=put(M,game,a,'The Creation of Avacyn','hand');assert.equal(await game.castSpell(a,source,{from:'hand'}),true);await settle(game);assert.equal(card.faceDown,true);source.counters.lore=2;game.addCounters(source,'lore',1,false,a);await settle(game);assert.equal(card.zone,'hand');assertGameStateInvariants(game);
 });
 test(role+': Princess chapter links retain ownership and reject a later exile incarnation',async()=>{
  for(const changed of [false,true]){const f=context(M,role),{game,a,b}=f;fund(a);const victim=put(M,game,b,'Grizzly Bears');choose(a,q=>q.type==='chooseTargets'&&q.candidates.includes(victim),()=>[victim]);const source=put(M,game,a,'The Princess Takes Flight','hand');assert.equal(await game.castSpell(a,source,{from:'hand'}),true);await settle(game);assert.equal(victim.zone,'exile');if(changed){await game.move(victim,'hand');await game.move(victim,'exile');}await chapter(f,source,3);assert.equal(victim.zone,changed?'exile':'battlefield');if(!changed)assert.equal(victim.ctrl,b);assertGameStateInvariants(game);}
 });
 test(role+': Aether Vial filters by its live charge count and supports declining the qualified card',async()=>{
  for(const accepted of [false,true]){const f=context(M,role),{game,a}=f,source=put(M,game,a,'Aether Vial'),good=witness(f,'Vial two mana witness','{2}',['Creature'],'hand'),bad=witness(f,'Vial three mana witness','{3}',['Creature'],'hand');source.counters.charge=2;choose(a,q=>q.prompt==='Choose a qualified permanent card from your hand',q=>{assert.ok(q.from.includes(good));assert.equal(q.from.includes(bad),false);return accepted?[good]:[];});const action=game.activatableList(a).find(row=>row.card===source);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);await settle(game);assert.equal(source.tapped,true);assert.equal(good.zone,accepted?'battlefield':'hand');assert.equal(bad.zone,'hand');assertGameStateInvariants(game);}
 });
}
