import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{loadEngine}from'./helpers/load-engine.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
import{semanticClass}from'../scripts/import-oracle-batch.mjs';
import{extensionCondition}from'../scripts/oracle-extensions-v8.mjs';
const M=loadEngine(),raws=JSON.parse(readFileSync(new URL('./fixtures/oracle-conditional-prefix-source.json',import.meta.url)));
const cards=raws.map((c,index)=>{const result=semanticClass(c,{compilerVersion:8});assert.ok(result.semanticClass,c.name+': '+result.reason);const[type,subtypes='']=c.type_line.split(' — '),words=type.split(' '),supers=['Legendary','Snow','Basic'];return {position:index+1,oracleId:c.oracle_id,scryfallId:c.id,...result,raw:{name:c.name,cost:c.mana_cost,oracle:c.oracle_text,types:words.filter(w=>!supers.includes(w)),super:words.filter(w=>supers.includes(w)),subtypes:subtypes.split(' ').filter(Boolean),power:c.power,toughness:c.toughness,_ci:c.color_identity},catalog:{typeLine:c.type_line,commanderLegality:'legal'}};});
const missing=cards.filter(c=>!M.DEFS[c.raw.name]);if(missing.length){M.registerOracleBatch({id:'oracle-conditional-prefix-source',sequence:9997,cards:missing});M.initData(M.RAW_DATA);}
const fund=p=>{for(const k of['W','U','B','R','G','C'])p.pool[k]=30;},total=p=>Object.values(p.pool).reduce((a,b)=>a+b,0);
function fixture(role){const f=context(M,role);for(const p of f.game.players)if(!p.isAI){const decide=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:decide(g,q);}return f;}
function witness(f,p,{color='G',type='Creature',subtype='Bear',power=2,toughness=20}={}){const c=new M.CardInst({name:'Independent '+subtype+' witness',cost:'{'+color+'}',types:[type],subtypes:[subtype],super:[],power:String(power),toughness:String(toughness),triggers:[]},p);c.zone='battlefield';c.sick=false;f.game.battlefield.push(c);f.game.recalc();return c;}
async function cast(f,p,name,targets=[],opts={}){const from=opts.from||'hand',c=put(M,f.game,p,name,from);fund(p);const before=total(p);const alt=from==='graveyard'?f.game.castableList(p).find(row=>row.card===c&&row.alt?.flashback)?.alt:null;if(from==='graveyard')assert.ok(alt,name+': printed flashback is offered');assert.equal(await f.game.castSpell(p,c,{from,quickTargets:targets,...(alt?{alt}:{}),...opts}),true,name+': legal paid cast');assert.ok(total(p)<before);return c;}
const flashback=[['Plunder the Trollshaws','draw',1,2],['Secrets of the Key','clue',1,2],['Increasing Savagery','counter',5,10],['Increasing Devotion','human',5,10]];
for(const role of['human','ai'])for(const grave of[false,true])for(const[name,action,normal,changed]of flashback)test(`${role}: ${name} pays its ${grave?'printed flashback':'hand cost'} and selects only that origin's effect`,async()=>{const f=fixture(role),target=action==='counter'?witness(f,f.a):null,source=await cast(f,f.a,name,target?[target]:[],{from:grave?'graveyard':'hand'}),object=f.game.stack.find(so=>so.card===source);assert.ok(object);assert.equal(object.castMeta?.from||source.castMeta.from,grave?'graveyard':'hand');const before=f.a.hand.length,n=grave?changed:normal;await settle(f.game);assert.equal(source.zone,grave?'exile':'graveyard');if(action==='draw')assert.equal(f.a.hand.length-before,n);if(action==='counter')assert.equal(target.counters['+1/+1'],n);if(action==='clue')assert.equal(f.game.bf().filter(c=>c.ctrl===f.a&&c.isToken&&c.hasSub('Clue')).length,n);if(action==='human')assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Human')&&c.power===1&&c.toughness===1).length,n);});
const addendum=[['Precognitive Perception','scry',0,3],['Careful Consideration','draw-discard',1,2],['Summary Judgment','damage',3,5],['Might of Old Krosa','pump',2,4],['Haunting Hymn','discard',2,4],['Sulfurous Blast','group-damage',2,3]];
for(const role of['human','ai'])for(const main of[false,true])for(const[name,action,normal,changed]of addendum)test(`${role}: ${name} uses its ${main?'main-phase':'combat-phase'} outcome after an actual cast`,async()=>{const f=fixture(role),target=['damage','group-damage'].includes(action)?witness(f,f.b):action==='pump'?witness(f,f.a):action==='discard'||action==='draw-discard'?f.b:null;
 if(target instanceof M.Player)for(const p of f.game.players)for(let n=0;n<6;n++)put(M,f.game,p,'Forest','hand');if(action==='damage')target.tapped=true;f.game.phase=main?'main1':'combat';f.game.step=main?'main':'attackers';
 const source=await cast(f,f.a,name,target?[target]:[]),so=f.game.stack.find(row=>row.card===source),chosen=so.targets.flat()[0]||target,hand=(chosen instanceof M.Player?chosen:f.a).hand.length,power=chosen?.power,ownLife=f.a.life,otherLife=f.b.life;await settle(f.game);const expected=main?changed:normal;
 if(action==='damage'||action==='group-damage')assert.equal(chosen.damage,expected);if(action==='group-damage'){assert.equal(ownLife-f.a.life,expected);assert.equal(otherLife-f.b.life,expected);}if(action==='pump')assert.equal(chosen.power-power,expected);if(action==='discard')assert.equal(hand-chosen.hand.length,expected);if(action==='draw-discard')assert.equal(chosen.hand.length-hand,expected);if(action==='scry'){assert.equal(f.a.hand.length-hand,3);const scries=f.trace.filter(x=>x.q.type==='scry');assert.equal(scries.length,main?1:0);if(main)assert.equal(scries[0].q.cards.length,3);}
});
const sanctuaries=[['Raka Sanctuary','W','U','damage',1,3],['Necra Sanctuary','G','W','lose',1,3],['Ceta Sanctuary','R','G','draw-discard',0,1],['Ana Sanctuary','U','B','pump',1,5],['Dega Sanctuary','B','R','gain',2,4]];
async function upkeep(f){f.game.phase='upkeep';await f.game.emit('upkeep',{player:f.a});await f.game.flushTriggers();assert.equal(f.game.stack.length,1);}
for(const role of['human','ai'])for(const both of[false,true])for(const[name,first,second,action,normal,changed]of sanctuaries)test(`${role}: paid ${name} distinguishes one qualifying color from both`,async()=>{const f=fixture(role);witness(f,f.a,{color:first,type:'Artifact'});if(both)witness(f,f.a,{color:second,type:'Artifact'});const target=action==='damage'?witness(f,f.b):action==='pump'?witness(f,f.a):null;if(role==='human'&&target){const decide=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.candidates.includes(target)?[target]:decide(g,q);}
 const source=await cast(f,f.a,name);await settle(f.game);await upkeep(f);const selected=f.game.stack[0].targets.flat()[0]||target,hand=f.a.hand.length,life=(selected instanceof M.Player?selected:f.a).life,power=selected?.power;await settle(f.game);const expected=both?changed:normal;assert.equal(source.zone,'battlefield');if(action==='damage')assert.equal(selected.damage,expected);if(action==='pump')assert.equal(selected.power-power,expected);if(action==='lose')assert.equal(life-selected.life,expected);if(action==='gain')assert.equal(f.a.life-life,expected);if(action==='draw-discard')assert.equal(f.a.hand.length-hand,expected);
});
for(const role of['human','ai'])for(const response of['replacement color','last qualifying color'])test(`${role}: removing ${response} from Raka Sanctuary changes only its live resolution conditions`,async()=>{const f=fixture(role),white=witness(f,f.a,{color:'W',type:'Artifact'}),blue=response==='replacement color'?witness(f,f.a,{color:'U',type:'Artifact'}):null,target=witness(f,f.b);const source=await cast(f,f.a,'Raka Sanctuary');await settle(f.game);await upkeep(f);const chosen=f.game.stack[0].targets[0];assert.equal(chosen.iid,target.iid);await cast(f,f.b,'Wipe Away',[blue||white]);await f.game.resolveTop();await settle(f.game);assert.equal(chosen.damage,response==='replacement color'?1:0);assert.equal(source.zone,'battlefield');});
test('leading instead conditions consume the whole clause and preserve original target announcement',()=>{const c={name:'Conditional boundary',layout:'normal',mana_cost:'{1}',type_line:'Sorcery'};for(const oracle_text of['Draw a card. If you control a dream, instead draw two cards.','Draw a card. If you control an artifact, instead draw two cards. Then do something unknown.','Destroy target creature. If you control an artifact, instead exile target artifact.','Destroy target creature. If you control an artifact, instead gain 2 life.','Draw a card. If you control an artifact, instead draw X cards.'])assert.equal(semanticClass({...c,oracle_text},{compilerVersion:8}).semanticClass,undefined,oracle_text);});

test('v8 permanent-presence conditions require a printed type or subtype',()=>{assert.equal(extensionCondition('you control a dream'),null);for(const noun of['artifact','Elf','Treasure','token'])assert.ok(extensionCondition('you control a '+noun),noun);});

for(const role of['human','ai'])for(const red of[1,3])test(`${role}: Slaying Fire derives adamant from ${red} actually paid red mana`,async()=>{
 const f=fixture(role),target=witness(f,f.b),source=put(M,f.game,f.a,'Slaying Fire','hand');
 for(const color of['W','U','B','R','G','C'])f.a.pool[color]=0;f.a.pool.R=red;f.a.pool.C=3-red;
 assert.equal(await f.game.castSpell(f.a,source,{from:'hand',quickTargets:[target]}),true);
 const object=f.game.stack.find(so=>so.card===source);assert.equal(object.paymentColorCounts.R,red);assert.equal(total(f.a),0);const selected=object.targets.flat()[0],before=selected instanceof M.Player?selected.life:selected.damage;
 await settle(f.game);assert.equal(selected instanceof M.Player?before-selected.life:selected.damage-before,red===3?4:3);
});
for(const role of['human','ai'])test(`${role}: a paid Reverberate copy of Precognitive Perception does not inherit a cast-main-phase condition`,async()=>{
 const f=fixture(role),source=await cast(f,f.a,'Precognitive Perception'),original=f.game.stack.find(so=>so.card===source);await cast(f,f.b,'Reverberate',[original]);
 await f.game.resolveTop();const copy=f.game.stack.at(-1);assert.equal(copy.isCopy,true);assert.equal(copy.ctrl,f.b);const opponentHand=f.b.hand.length;await f.game.resolveTop();assert.equal(f.b.hand.length-opponentHand,3);assert.equal(f.trace.filter(x=>x.q.type==='scry').length,0);
 const ownHand=f.a.hand.length;await settle(f.game);assert.equal(f.a.hand.length-ownHand,3);assert.equal(f.trace.filter(x=>x.q.type==='scry').length,1);
});
for(const role of['human','ai'])for(const lands of[5,6])test(`${role}: Scute Swarm resolves the printed ${lands}-land outcome after a legal land play`,async()=>{
 const f=fixture(role);for(let n=1;n<lands;n++)put(M,f.game,f.a,'Forest');const source=await cast(f,f.a,'Scute Swarm');await settle(f.game);
 const land=put(M,f.game,f.a,'Forest','hand');assert.equal(await f.game.playLand(f.a,land),true);await settle(f.game);
 const tokens=f.game.creatures(f.a).filter(c=>c.isToken);assert.equal(tokens.length,1);assert.equal(tokens[0].name,lands===6?source.name:'Insect Token');assert.equal(tokens[0].hasSub('Insect'),true);assert.equal(tokens[0].power,1);assert.equal((tokens[0].def.triggers||[]).length,lands===6?source.def.triggers.length:0);
});
for(const role of['human','ai'])test(`${role}: Scute Swarm still copies its last known characteristics after paid Wipe Away responds to landfall`,async()=>{
 const f=fixture(role);for(let n=1;n<6;n++)put(M,f.game,f.a,'Forest');const source=await cast(f,f.a,'Scute Swarm');await settle(f.game);const land=put(M,f.game,f.a,'Forest','hand');assert.equal(await f.game.playLand(f.a,land),true);await f.game.flushTriggers();assert.equal(f.game.stack.length,1);
 await cast(f,f.b,'Wipe Away',[source]);await f.game.resolveTop();assert.equal(source.zone,'hand');await settle(f.game);const tokens=f.game.creatures(f.a).filter(c=>c.isToken);assert.equal(tokens.length,1);assert.equal(tokens[0].name,'Scute Swarm');assert.equal(tokens[0].def.triggers.length,source.def.triggers.length);
});
for(const role of['human','ai'])for(const coven of[false,true])test(`${role}: Ritual of Hope counts distinct powers before applying the ${coven?'coven':'ordinary'} group bonus`,async()=>{
 const f=fixture(role),squad=[1,2,coven?3:2].map(power=>witness(f,f.a,{power})),before=squad.map(c=>[c.power,c.toughness]);await cast(f,f.a,'Ritual of Hope');await settle(f.game);squad.forEach((c,i)=>{assert.equal(c.power-before[i][0],coven?2:1);assert.equal(c.toughness-before[i][1],1);});
});
