import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createFixturePlan,registerCanonicalFixturePlan} from './helpers/oracle-fixture-plan.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {names,proveStaticV74} from './helpers/oracle-v74-static-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v74-static.json',import.meta.url)));
const plan=createFixturePlan(rows,74,9974),M=loadEngine();registerCanonicalFixturePlan(M,plan);
test('static legends require every full source clause',()=>{for(const row of rows)assert.equal(plan.classify({...row,oracle_text:row.oracle_text+'\nPerform an unsupported action.'}).semanticClass,undefined,row.name);});
for(const role of ['human','ai'])for(const name of names)for(const positive of [true,false])test(`${role}: ${name} paid full static rules ${positive}`,()=>proveStaticV74(M,name,role,positive));
