import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{loadEngine}from'./helpers/load-engine.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
import{semanticClass}from'../scripts/import-oracle-batch.mjs';
const M=loadEngine(),raws=JSON.parse(readFileSync(new URL('./fixtures/oracle-conditional-effects-source.json',import.meta.url)));
const cards=raws.map((c,index)=>{const result=semanticClass(c,{compilerVersion:8});assert.ok(result.semanticClass,c.name+': '+result.reason);const[type,subtypes='']=c.type_line.split(' — '),words=type.split(' '),supers=['Legendary','Snow','Basic'];return {position:index+1,oracleId:c.oracle_id,scryfallId:c.id,...result,raw:{name:c.name,cost:c.mana_cost,oracle:c.oracle_text,types:words.filter(w=>!supers.includes(w)),super:words.filter(w=>supers.includes(w)),subtypes:subtypes.split(' ').filter(Boolean),power:c.power,toughness:c.toughness,_ci:c.color_identity},catalog:{typeLine:c.type_line,commanderLegality:'legal'}};});
const missing=cards.filter(c=>!M.DEFS[c.raw.name]);if(missing.length){M.registerOracleBatch({id:'oracle-conditional-effects-source',sequence:9996,cards:missing});M.initData(M.RAW_DATA);}
const fund=p=>{for(const k of['W','U','B','R','G','C'])p.pool[k]=30;};
function fixture(role){const f=context(M,role);for(const p of f.game.players)if(!p.isAI){const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:prior(g,q);}return f;}
async function cast(f,p,name,targets=[]){const c=put(M,f.game,p,name,'hand');fund(p);const before=Object.values(p.pool).reduce((s,n)=>s+n,0);assert.equal(await f.game.castSpell(p,c,{from:'hand',quickTargets:targets}),true);assert.ok(Object.values(p.pool).reduce((s,n)=>s+n,0)<before);return c;}
function creature(f,p,{subtype='Bear',color='G',power=2,toughness=20}={}){const c=put(M,f.game,p,'Grizzly Bears');c.def={...c.def,name:'Independent '+subtype+' witness',subtypes:[subtype],cost:color?'{'+color+'}':'{2}',colorsOverride:color?[color]:[],power:String(power),toughness:String(toughness)};f.game.recalc();return c;}
async function turnReady(f){const emit=f.game.emit,stop=new Error('upkeep reached');f.game.emit=async function(name,data){if(name==='upkeep')throw stop;return emit.call(this,name,data);};try{await assert.rejects(f.game.runTurn(),e=>e===stop);}finally{f.game.emit=emit;}f.game.phase='main1';}
async function attack(f,attacker){if(!f.a.isAI){const prior=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=(g,q)=>q.type==='attackers'?[{card:attacker,target:f.b}]:prior(g,q);}f.game.priorityRound=async()=>settle(f.game);await f.game.combatPhase(f.a);f.game.phase='main2';f.game.step='main';f.game.priorityRound=async()=>{};assert.ok(f.a.turnState.attacked);}
async function publicCondition(f,kind,on){
 if(kind==='death'){if(on){const c=creature(f,f.b);await f.game.destroy(c);}}
 else if(kind==='raid'){if(on){const c=creature(f,f.a);await attack(f,c);}}
 else if(kind==='threshold')for(let n=0;n<(on?7:6);n++)put(M,f.game,f.a,'Forest','graveyard');
 else if(kind==='types')for(const name of ['Forest','Grizzly Bears','Sol Ring',...(on?['Glorious Anthem']:[])])put(M,f.game,f.a,name,'graveyard');
 else if(kind==='hellbent'){if(!on)put(M,f.game,f.a,'Forest','hand');}
 else if(kind==='artifacts')for(let n=0;n<(on?3:2);n++)put(M,f.game,f.a,'Sol Ring');
 else if(kind==='chandra'&&on){const name=Object.keys(M.DEFS).find(n=>M.DEFS[n].types.includes('Planeswalker')&&M.DEFS[n].subtypes?.includes('Chandra'));assert.ok(name);const card=put(M,f.game,f.a,name);card.counters.loyalty=5;f.game.recalc();}
 else if(kind==='ferocious')creature(f,f.a,{power:on?4:2});
}
for(const role of['human','ai']){
 test(`${role}: Disenchant can turn off metalcraft after Galvanic Blast was paid and targeted`,async()=>{const f=fixture(role);await publicCondition(f,'artifacts',true);const target=creature(f,f.b),blast=await cast(f,f.a,'Galvanic Blast',[target]);const selected=f.game.stack.find(so=>so.card===blast).targets.flat()[0];const before=selected instanceof M.Player?selected.life:selected.damage;
  await cast(f,f.b,'Disenchant',[f.game.bf().find(c=>c.ctrl===f.a&&c.is('Artifact'))]);await f.game.resolveTop();assert.equal(f.game.bf().filter(c=>c.ctrl===f.a&&c.is('Artifact')).length,2);await settle(f.game);assert.equal(selected instanceof M.Player?before-selected.life:selected.damage-before,2);
 });
 test(`${role}: Vision Skeins changes hellbent while Cackling Flames is on the Stack`,async()=>{const f=fixture(role),target=creature(f,f.b),spell=await cast(f,f.a,'Cackling Flames',[target]);const selected=f.game.stack.find(so=>so.card===spell).targets.flat()[0],before=selected instanceof M.Player?selected.life:selected.damage;assert.equal(f.a.hand.length,0);
  await cast(f,f.b,'Vision Skeins');await f.game.resolveTop();assert.equal(f.a.hand.length,2);await settle(f.game);assert.equal(selected instanceof M.Player?before-selected.life:selected.damage-before,3);
 });
 test(`${role}: Twiddle changes Sphinx Sovereign's end-step branch in response`,async()=>{const f=fixture(role),source=await cast(f,f.a,'Sphinx Sovereign');await settle(f.game);await f.game.emit('endStep',{player:f.a});await f.game.flushTriggers();assert.equal(f.game.stack.length,1);await cast(f,f.b,'Twiddle',[source]);await f.game.resolveTop();assert.equal(source.tapped,true);const own=f.a.life,enemy=f.b.life;await settle(f.game);assert.equal(f.a.life,own);assert.equal(f.b.life,enemy-3);});
 test(`${role}: Cloudshift invalidates the original counter-spell target even when its physical card returns`,async()=>{const f=fixture(role),target=creature(f,f.a);const spell=await cast(f,f.a,'Hunger of the Howlpack',[target]);await cast(f,f.a,'Cloudshift',[target]);await f.game.resolveTop();assert.equal(target.zone,'battlefield');await settle(f.game);assert.equal(target.counters['+1/+1']||0,0);assert.equal(spell.zone,'graveyard');});
}
test('conditional composition rejects unknown predicates, appended actions and changed target requirements',()=>{
 const card={name:'Conditional grammar boundary',layout:'normal',mana_cost:'{1}',type_line:'Sorcery'};
 for(const oracle_text of['Draw a card if an opponent dances.','Draw a card unless you control a dream.','Draw a card if you control an artifact. Then do something unknown.',
  'Destroy target creature. Exile target artifact instead if you control an artifact.','Destroy target creature. Gain 2 life instead if you control an artifact.'])assert.equal(semanticClass({...card,oracle_text},{compilerVersion:8}).semanticClass,undefined,oracle_text);
});
const spells=[
 ['Hunger of the Howlpack','death','counters',1,3],['Thermal Blast','threshold','damage',3,5],['Might Beyond Reason','types','counters',2,3],
 ['Firecannon Blast','raid','damage',3,6],["Predator's Howl",'death','tokens',1,3],['Cackling Flames','hellbent','damage',3,5],
 ['Unholy Heat','types','damage',2,6],["Chandra's Triumph",'chandra','damage',3,5],['Brimstone Volley','death','damage',3,5],['Galvanic Blast','artifacts','damage',2,4],['Feed the Clan','ferocious','life',5,10],
];
for(const role of['human','ai'])for(const on of[false,true])for(const[name,condition,outcome,normal,replacement]of spells)test(`${role}: paid ${name} chooses only the printed ${on?'conditional':'ordinary'} result`,async()=>{
 const f=fixture(role);await publicCondition(f,condition,on);const target=outcome==='damage'?creature(f,f.b):outcome==='counters'?creature(f,f.a):null;
 const life=f.a.life,beforeTokens=f.game.bf().filter(c=>c.isToken).length,source=await cast(f,f.a,name,target?[target]:[]);const so=f.game.stack.find(row=>row.card===source);assert.ok(so);const selected=so.targets.flat()[0],before=selected instanceof M.Player?selected.life:selected?.damage||0;
 await settle(f.game);const n=on?replacement:normal;if(outcome==='damage')assert.equal(selected instanceof M.Player?before-selected.life:selected.damage-before,n);else if(outcome==='counters')assert.equal(selected.counters['+1/+1'],n);else if(outcome==='tokens')assert.equal(f.game.bf().filter(c=>c.isToken&&c.hasSub('Wolf')).length-beforeTokens,n);else assert.equal(f.a.life-life,n);
});
for(const role of['human','ai'])for(const on of[false,true]){
 test(`${role}: Tainted Indulgence ${on?'keeps both cards':'discards one'} from distinct graveyard mana values`,async()=>{const f=fixture(role);for(const name of['Forest','Sol Ring','Grizzly Bears','Cultivate',...(on?['Wrath of God']:[])])put(M,f.game,f.a,name,'graveyard');await cast(f,f.a,'Tainted Indulgence');const hand=f.a.hand.length;await settle(f.game);assert.equal(f.a.hand.length-hand,on?2:1);});
 test(`${role}: The Spot's Portal uses ${on?'a Villain':'the no-Villain life penalty'} after the target moves`,async()=>{const f=fixture(role),target=creature(f,f.b);if(on)creature(f,f.a,{subtype:'Villain'});const life=f.a.life;await cast(f,f.a,"The Spot's Portal",[target]);await settle(f.game);assert.equal(target.zone,'library');assert.equal(f.b.library[0],target);assert.equal(life-f.a.life,on?0:2);});
 test(`${role}: Splitskin Doll excludes itself when testing another small creature (${on})`,async()=>{const f=fixture(role);if(on)creature(f,f.a);const source=await cast(f,f.a,'Splitskin Doll');await f.game.resolveTop();assert.equal(source.zone,'battlefield');const hand=f.a.hand.length;await settle(f.game);assert.equal(f.a.hand.length-hand,on?1:0);});
 test(`${role}: Fathom Fleet Boarder excludes itself when testing another Pirate (${on})`,async()=>{const f=fixture(role);if(on)creature(f,f.a,{subtype:'Pirate'});const life=f.a.life;await cast(f,f.a,'Fathom Fleet Boarder');await settle(f.game);assert.equal(life-f.a.life,on?0:2);});
 test(`${role}: Bellowing Saddlebrute checks the actual prior attack (${on})`,async()=>{const f=fixture(role);await publicCondition(f,'raid',on);const life=f.a.life;await cast(f,f.a,'Bellowing Saddlebrute');await settle(f.game);assert.equal(life-f.a.life,on?0:4);});
 test(`${role}: Ravenous Necrotitan uses an opponent's poison count (${on})`,async()=>{const f=fixture(role);f.b.poison=on?3:2;const source=await cast(f,f.a,'Ravenous Necrotitan');await settle(f.game);assert.equal(source.zone,on?'battlefield':'graveyard');});
 test(`${role}: HYDRA Troopers chooses one branch at resolution (${on})`,async()=>{const f=fixture(role);for(let n=0;n<(on?2:1);n++)put(M,f.game,f.a,'Grizzly Bears','graveyard');await cast(f,f.a,'HYDRA Troopers');await f.game.resolveTop();const gy=f.a.graveyard.length;await settle(f.game);const tokens=f.game.bf().filter(c=>c.isToken);assert.equal(tokens.length,on?1:0);assert.equal(f.a.graveyard.length-gy,on?0:2);if(on){assert.equal(tokens[0].hasSub('Villain'),true);assert.equal(tokens[0].tapped,true);assert.equal(tokens[0].power,2);assert.equal(tokens[0].toughness,1);assert.equal(tokens[0].kw('menace'),true);}});
 test(`${role}: Gravelighter resolves the ${on?'morbid draw':'each-player sacrifice'} branch`,async()=>{const f=fixture(role);await publicCondition(f,'death',on);const source=await cast(f,f.a,'Gravelighter');await f.game.resolveTop();const hand=f.a.hand.length;await settle(f.game);assert.equal(source.zone,on?'battlefield':'graveyard');assert.equal(f.a.hand.length-hand,on?1:0);});
 test(`${role}: Sphinx Sovereign checks its tapped state after its trigger is on the Stack (${on})`,async()=>{const f=fixture(role),source=await cast(f,f.a,'Sphinx Sovereign');await settle(f.game);await f.game.emit('endStep',{player:f.a});await f.game.flushTriggers();assert.equal(f.game.stack.length,1);source.tapped=!on;const life=f.a.life,enemy=f.b.life;await settle(f.game);assert.equal(f.a.life-life,on?3:0);assert.equal(enemy-f.b.life,on?0:3);});
 test(`${role}: Vampire Lacerator uses an opponent's life threshold (${on})`,async()=>{const f=fixture(role);await cast(f,f.a,'Vampire Lacerator');await settle(f.game);f.b.life=on?10:11;const life=f.a.life;await f.game.emit('upkeep',{player:f.a});await settle(f.game);assert.equal(life-f.a.life,on?0:1);});
 test(`${role}: Reaver Drone excludes itself from another colorless creature (${on})`,async()=>{const f=fixture(role);await cast(f,f.a,'Reaver Drone');await settle(f.game);if(on)creature(f,f.a,{color:null});const life=f.a.life;await f.game.emit('upkeep',{player:f.a});await settle(f.game);assert.equal(life-f.a.life,on?0:1);});
 test(`${role}: Mindwrack Demon uses card types after the printed four-card mill (${on})`,async()=>{const f=fixture(role);await cast(f,f.a,'Mindwrack Demon');await settle(f.game);assert.equal(f.a.graveyard.length,4);if(on)for(const name of['Grizzly Bears','Sol Ring','Glorious Anthem'])put(M,f.game,f.a,name,'graveyard');const life=f.a.life;await f.game.emit('upkeep',{player:f.a});await settle(f.game);assert.equal(life-f.a.life,on?0:4);});
 test(`${role}: Cosmos Elixir compares to starting life at resolution (${on})`,async()=>{const f=fixture(role);await cast(f,f.a,'Cosmos Elixir');await settle(f.game);await f.game.emit('endStep',{player:f.a});await f.game.flushTriggers();f.a.life=on?41:40;const life=f.a.life,hand=f.a.hand.length;await settle(f.game);assert.equal(f.a.life-life,on?0:2);assert.equal(f.a.hand.length-hand,on?1:0);});
 test(`${role}: Tragedy Feaster's end step uses actual life gained this turn (${on})`,async()=>{const f=fixture(role);put(M,f.game,f.a,'Forest');await cast(f,f.a,'Tragedy Feaster');await settle(f.game);if(on)await f.game.gainLife(f.a,1);const bf=f.game.bf().length;await f.game.emit('endStep',{player:f.a});await settle(f.game);assert.equal(bf-f.game.bf().length,on?0:1);});
 test(`${role}: Regal Sliver checks monarch before choosing its granted ETB result (${on})`,async()=>{const f=fixture(role);if(on)f.game.monarch=f.a;const source=await cast(f,f.a,'Regal Sliver');await f.game.resolveTop();const power=source.power;await settle(f.game);assert.equal(f.game.monarch,f.a);assert.equal(source.power-power,on?1:0);});
 test(`${role}: Chakra Meditation's paid instant triggers draw then the Lesson condition (${on})`,async()=>{const f=fixture(role);await cast(f,f.a,'Chakra Meditation');await settle(f.game);const name=Object.keys(M.DEFS).find(n=>M.DEFS[n].subtypes?.includes('Lesson'));assert.ok(name);for(let n=0;n<(on?3:2);n++)put(M,f.game,f.a,name,'graveyard');await cast(f,f.a,'Shock',[f.b]);const hand=f.a.hand.length;await settle(f.game);assert.equal(f.a.hand.length-hand,on?1:0);});
 test(`${role}: Shoreline Looter resolves its draw/discard after actual combat (${on})`,async()=>{const f=fixture(role),source=await cast(f,f.a,'Shoreline Looter');await settle(f.game);await turnReady(f);await publicCondition(f,'threshold',on);const hand=f.a.hand.length,life=f.b.life;await attack(f,source);assert.equal(life-f.b.life,source.power);assert.equal(f.a.hand.length-hand,on?1:0);});
 test(`${role}: Moon-Circuit Hacker's actual combat draw checks whether it entered this turn (${on})`,async()=>{const f=fixture(role),source=await cast(f,f.a,'Moon-Circuit Hacker');await settle(f.game);if(on){await cast(f,f.a,'Expedite',[source]);await settle(f.game);}else await turnReady(f);const hand=f.a.hand.length,life=f.b.life;await attack(f,source);assert.equal(life-f.b.life,source.power);assert.equal(f.a.hand.length-hand,on?1:0);});
}
