import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v21-spells.json',import.meta.url),'utf8'));
const M=loadEngine(),absent=rows.filter(c=>!M.DEFS[c.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9941,limit:absent.length,compilerVersion:21});assert.equal(plan.report.cards.length,absent.length);M.registerOracleBatch(plan.report);}M.initData(M.RAW_DATA);
function choose(p,fn){const old=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>fn(g,q)??old(g,q);}
function fund(p){for(const k of ['W','U','B','R','G','C'])p.pool[k]=50;}
async function cast(f,name,targets=[],{kicked=false,...opts}={}){const c=put(M,f.game,f.a,name,'hand');fund(f.a);choose(f.a,(g,q)=>q.aiHint?.kind==='kicker'?(kicked?'yes':'no'):q.type==='chooseTargets'?targets.filter(t=>q.candidates.includes(t)).slice(0,q.max??q.count??1):undefined);const before=Object.values(f.a.pool).reduce((a,b)=>a+b,0);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',...opts}),true,name);const so=f.game.stack.find(o=>o.card===c);return {c,so,paid:before-Object.values(f.a.pool).reduce((a,b)=>a+b,0)};}
function permanent(f,p,{name='Grizzly Bears',power=3,toughness=20,types=['Creature'],subtypes=['Bear'],cost='{2}',kws=[],super:superTypes=[]}={}){const c=put(M,f.game,p,name);c.def={...c.def,power:String(power),toughness:String(toughness),types,subtypes,cost,kws,super:superTypes};f.game.recalc();return c;}

test('v21 spell families require the full Oracle source',()=>{for(const card of rows){assert.ok(semanticClass(card,{compilerVersion:21}).semanticClass,card.name);assert.equal(semanticClass({...card,oracle_text:card.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:21}).semanticClass,undefined,card.name);}});
for(const role of ['human','ai']){
 test(role+': kicked modal token size uses the recipient hand after earlier modes resolve',async()=>{for(const kicked of [false,true]){const f=context(M,role),victim=permanent(f,f.b);for(let i=0;i<3;i++){put(M,f.game,f.b,'Forest','hand');put(M,f.game,f.a,'Forest','hand');}const op=M.DEFS['Inscription of Insight'].oracleImplementation.find(o=>o.kind==='spell-modal-generic'),printed=kicked?[0,1,2]:[2],mode=op.modes.findIndex(m=>JSON.stringify(m.printedModesV21)===JSON.stringify(printed));choose(f.a,(g,q)=>q.aiHint?.kind==='mode'?String(mode):undefined);const {so,paid}=await cast(f,'Inscription of Insight',kicked?[victim,f.b]:[f.b],{kicked});assert.equal(so.kicked,kicked);assert.equal(paid,kicked?8:4);await settle(f.game);const token=f.game.bf().find(c=>c.isToken&&c.hasSub('Illusion'));assert.ok(token);assert.equal(token.ctrl,f.b);assert.equal(token.power,kicked?4:3);assert.equal(token.toughness,kicked?4:3);assert.equal(victim.zone,kicked?'hand':'battlefield');assertGameStateInvariants(f.game);}});
 test(role+': conditional reanimation counters enter with the creature in both branches',async()=>{for(const name of ['Necromantic Summons','Vigor Mortis'])for(const positive of [false,true]){const f=context(M,role),victim=put(M,f.game,name==='Necromantic Summons'?f.b:f.a,'Grizzly Bears','graveyard'),source=put(M,f.game,f.a,name,'hand');if(name==='Necromantic Summons'&&positive){put(M,f.game,f.a,'Shock','graveyard');put(M,f.game,f.a,'Lightning Bolt','graveyard');}for(const k in f.a.pool)f.a.pool[k]=0;f.a.pool.B=2;f.a.pool.C=name==='Vigor Mortis'?(positive?1:2):3;if(name==='Vigor Mortis'&&positive)f.a.pool.G=1;choose(f.a,(g,q)=>q.type==='chooseTargets'?[victim]:undefined);let options;const enter=f.game.putPermanentOntoBattlefield;f.game.putPermanentOntoBattlefield=async function(card,player,opts){if(card===victim)options=opts;return enter.call(this,card,player,opts);};assert.equal(await f.game.castSpell(f.a,source,{from:'hand'}),true);await settle(f.game);assert.equal(victim.zone,'battlefield');assert.equal(victim.ctrl,f.a);const count=positive?(name==='Necromantic Summons'?2:1):0;assert.equal(victim.counters['+1/+1']||0,count);assert.equal(options.additionalCounters?.['+1/+1']||0,count);assertGameStateInvariants(f.game);}});
 test(role+': exiled-target controller may accept or decline the permanent from hand',async()=>{for(const accept of [false,true]){const f=context(M,role),victim=permanent(f,f.a),gift=put(M,f.game,f.b,'Grizzly Bears','hand');victim.ctrl=f.b;f.game.recalc();choose(f.b,(g,q)=>q.type==='chooseCards'&&q.from.includes(gift)?(accept?[gift]:[]):undefined);await cast(f,'Divine Gambit',[victim]);await settle(f.game);assert.equal(victim.zone,'exile');assert.equal(gift.zone,accept?'battlefield':'hand');assert.equal(gift.ctrl,f.b);assertGameStateInvariants(f.game);}});
 test(role+': split mana-color clauses apply independently and together from actual payments',async()=>{for(const colors of ['U','R','UR']){const f=context(M,role),ours=permanent(f,f.a),theirs=permanent(f,f.b),source=put(M,f.game,f.a,'Unnerving Assault','hand');for(const k in f.a.pool)f.a.pool[k]=0;for(const color of colors)f.a.pool[color]=1;f.a.pool.C=3-colors.length;assert.equal(await f.game.castSpell(f.a,source,{from:'hand'}),true);await settle(f.game);assert.equal(ours.power,colors.includes('R')?4:3);assert.equal(theirs.power,colors.includes('U')?2:3);assertGameStateInvariants(f.game);}});
 test(role+': optional target offers enforce life and permanent costs and decline X kicker previews',()=>{for(const kind of ['life','sacrifice','x']){const f=context(M,role),victim=permanent(f,f.b),source=put(M,f.game,f.a,kind==='sacrifice'?'Magma Burst':'Shock','hand');fund(f.a);const script={targets:()=>[{...M.T.creature(),filter:()=>false}],oracleKickerTargetsV21:()=>[M.T.creature()]};if(kind==='life')M.OracleV8KeywordPayments.install(script,{kind:'mechanic-keyword-payment-v8',contract:'mechanic-keyword-payment-v8',keyword:'kicker',mana:'{0}',costs:[{id:'kicker-life',kind:'payLife',amount:{kind:'number',value:5}}],label:'Pay 5 life'});if(kind==='x')script.kicker={cost:'{X}'};source.def={...source.def,...script};if(kind==='life'){f.a.life=4;assert.equal(f.game.castableList(f.a).some(row=>row.card===source),false);f.a.life=5;assert.equal(f.game.castableList(f.a).some(row=>row.card===source),true);}else if(kind==='sacrifice'){put(M,f.game,f.a,'Forest');assert.equal(f.game.castableList(f.a).some(row=>row.card===source),false);put(M,f.game,f.a,'Forest');assert.equal(f.game.castableList(f.a).some(row=>row.card===source),true);}else assert.equal(f.game.castableList(f.a).some(row=>row.card===source),false);assert.equal(victim.zone,'battlefield');}});
 test(role+': Get Lost gives Maps to the destroyed target controller',async()=>{const f=context(M,role),victim=permanent(f,f.b);await cast(f,'Get Lost',[victim]);await settle(f.game);assert.equal(victim.zone,'graveyard');const maps=f.game.bf().filter(c=>c.isToken&&c.hasSub('Map'));assert.equal(maps.length,2);assert.ok(maps.every(c=>c.ctrl===f.b));assertGameStateInvariants(f.game);});
 test(role+': mixed player and planeswalker consequences lock the affected controller',async()=>{for(const walker of [false,true]){const f=context(M,role),victim=walker?permanent(f,f.b,{types:['Planeswalker'],toughness:0}):f.b;if(walker){victim.counters.loyalty=1;f.game.recalc();}for(let i=0;i<4;i++)put(M,f.game,f.b,'Forest','hand');await cast(f,"Rakdos's Return",[victim],{xVal:2});await settle(f.game);assert.equal(f.b.hand.length,2);assert.equal(f.a.hand.length,0);if(walker)assert.equal(victim.zone,'graveyard');else assert.equal(f.b.life,38);assertGameStateInvariants(f.game);}});
 test(role+': simultaneous player burn includes the controller creature group',async()=>{for(const walker of [false,true]){const f=context(M,role),victim=walker?permanent(f,f.b,{types:['Planeswalker']}):f.b;if(walker){victim.counters.loyalty=10;f.game.recalc();}const damaged=permanent(f,f.b),safe=permanent(f,f.a);await cast(f,"Chandra's Fury",[victim]);await settle(f.game);assert.equal(damaged.damage,1);assert.equal(safe.damage,0);assert.equal(f.b.life,walker?40:36);if(walker)assert.equal(victim.counters.loyalty,6);assertGameStateInvariants(f.game);}});
 test(role+': graveyard shuffling snapshots the number before moving cards',async()=>{const f=context(M,role);for(let i=0;i<3;i++)put(M,f.game,f.a,'Forest','graveyard');const library=f.a.library.length;await cast(f,'Psychic Spiral',[f.b]);await settle(f.game);assert.equal(f.b.graveyard.length,3);assert.equal(f.a.library.length,library+3);assertGameStateInvariants(f.game);});
 test(role+': least power is a resolution condition and includes tied creatures',async()=>{for(const low of [false,true]){const f=context(M,role),victim=permanent(f,f.b,{power:low?1:5});permanent(f,f.a,{power:1});await cast(f,'Wretched Banquet',[victim]);await settle(f.game);assert.equal(victim.zone,low?'graveyard':'battlefield');assertGameStateInvariants(f.game);}});
 test(role+': reanimation adds the printed counters as creatures enter',async()=>{const f=context(M,role);const dead=[];for(const p of [f.a,f.b]){const c=put(M,f.game,p,'Grizzly Bears','graveyard');c.def={...c.def,power:'4',toughness:'4'};dead.push(c);}await cast(f,'Pyrrhic Revival');await settle(f.game);for(const c of dead){assert.equal(c.zone,'battlefield');assert.equal(c.counters['-1/-1'],1);assert.equal(c.power,3);assert.equal(c.toughness,3);}assertGameStateInvariants(f.game);});
 test(role+': nontoken deaths determine the Zombie count',async()=>{const f=context(M,role);f.game.diedThisTurn.push({types:['Creature'],isToken:false},{types:['Creature'],isToken:false},{types:['Creature'],isToken:true},{types:['Artifact'],isToken:false});await cast(f,'Rise of the Dread Marn');await settle(f.game);assert.equal(f.game.bf().filter(c=>c.isToken&&c.hasSub('Zombie')).length,2);assertGameStateInvariants(f.game);});
 test(role+': kicker damage changes announcements and pays its actual additional mana',async()=>{for(const kicked of [false,true]){const f=context(M,role),victims=[permanent(f,f.b),permanent(f,f.b)];choose(f.a,(g,q)=>q.type==='chooseX'&&q.allocation?5:undefined);const {so,paid}=await cast(f,'Fight with Fire',kicked?victims:victims.slice(0,1),{kicked});assert.equal(so.kicked,kicked);assert.equal(so.targets.flat().length,kicked?2:1);assert.equal(paid,kicked?9:3);await settle(f.game);assert.equal(victims[0].damage,5);assert.equal(victims[1].damage,kicked?5:0);assertGameStateInvariants(f.game);}});
 test(role+': an additional kicked target is absent from the unpaid announcement',async()=>{for(const kicked of [false,true]){const f=context(M,role),victims=[permanent(f,f.b),permanent(f,f.b)];const {so,paid}=await cast(f,'Jilt',kicked?victims:victims.slice(0,1),{kicked});assert.equal(so.targets.length,kicked?2:1);assert.equal(paid,kicked?4:2);await settle(f.game);assert.equal(victims[0].zone,'hand');assert.equal(victims[1].damage,kicked?2:0);assertGameStateInvariants(f.game);}});
 test(role+': kicked unrestricted target offers require affordable mana',async()=>{const f=context(M,role),victim=permanent(f,f.b,{cost:'{5}'}),source=put(M,f.game,f.a,"Bloodchief's Thirst",'hand');for(const k in f.a.pool)f.a.pool[k]=0;f.a.pool.B=1;assert.equal(f.game.castableList(f.a).some(row=>row.card===source),false);f.a.pool.B=2;f.a.pool.C=2;assert.equal(f.game.castableList(f.a).some(row=>row.card===source),true);choose(f.a,(g,q)=>q.aiHint?.kind==='kicker'?'yes':q.type==='chooseTargets'?[victim]:undefined);assert.equal(await f.game.castSpell(f.a,source,{from:'hand'}),true);const so=f.game.stack.find(o=>o.card===source);assert.equal(so.kicked,true);assert.equal(so.targets[0],victim);assert.equal(Object.values(f.a.pool).reduce((a,b)=>a+b,0),0);await settle(f.game);assert.equal(victim.zone,'graveyard');assertGameStateInvariants(f.game);});
 test(role+': unpaid mana-value restrictions apply to both sides of a creature-or-planeswalker union',async()=>{const f=context(M,role),victim=permanent(f,f.b,{cost:'{5}'}),source=put(M,f.game,f.a,"Bloodchief's Thirst",'hand');const spec=f.game.spellTargetSpecs(source,{},f.a)[0];assert.equal(f.game.legalTargets(spec,source,f.a).includes(victim),false);victim.def={...victim.def,cost:'{2}'};f.game.recalc();assert.equal(f.game.legalTargets(spec,source,f.a).includes(victim),true);});
 test(role+': any number of kicked targets includes zero and exceeds three',async()=>{for(const n of [0,4]){const f=context(M,role),victims=Array.from({length:n},()=>permanent(f,f.a));const {so,paid}=await cast(f,'Divine Resilience',victims,{kicked:true});assert.equal(so.targets.flat().length,n);assert.equal(paid,4);await settle(f.game);for(const c of victims)assert.ok(c.kw('indestructible'));assertGameStateInvariants(f.game);}});
 test(role+': conditional destruction tests mana value at resolution',async()=>{for(const kicked of [false,true])for(const mv of [2,4,6]){const f=context(M,role),victim=permanent(f,f.b,{types:['Artifact'],cost:'{'+mv+'}'});await cast(f,'Overload',[victim],{kicked});await settle(f.game);assert.equal(victim.zone,mv<=(kicked?5:2)?'graveyard':'battlefield');assertGameStateInvariants(f.game);}});
 test(role+': nonmana kicker can pay exactly two lands and announces a distinct second target',async()=>{for(const kicked of [false,true]){const f=context(M,role),victims=[permanent(f,f.b),permanent(f,f.b)],lands=[put(M,f.game,f.a,'Forest'),put(M,f.game,f.a,'Forest')];choose(f.a,(g,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='sacCost'?lands:undefined);const {so}=await cast(f,'Magma Burst',kicked?victims:victims.slice(0,1),{kicked});assert.equal(so.kicked,kicked);assert.equal(so.targets.length,kicked?2:1);if(kicked)assert.notEqual(so.targets[0],so.targets[1]);await settle(f.game);for(const c of lands)assert.equal(c.zone,kicked?'graveyard':'battlefield');assert.equal(victims[0].damage,3);assert.equal(victims[1].damage,kicked?3:0);assertGameStateInvariants(f.game);}});
 test(role+': a Map can sacrifice itself for a real targeted explore activation',async()=>{const f=context(M,role),victim=permanent(f,f.b);await cast(f,'Get Lost',[victim]);await settle(f.game);const map=f.game.bf().find(c=>c.isToken&&c.hasSub('Map')),explorer=permanent(f,f.b),top=f.b.library.at(-1);f.game.turnPlayer=f.b;fund(f.b);choose(f.b,(g,q)=>q.type==='chooseTargets'?[explorer]:undefined);const action=f.game.activatableList(f.b).find(row=>row.card===map);assert.ok(action);assert.equal(await f.game.activateAbility(f.b,action),true);assert.equal(map.zone,'ceased');await settle(f.game);assert.equal(top.zone,'hand');assert.equal(top.owner,f.b);assertGameStateInvariants(f.game);});
 test(role+': paid reanimation changes the exact number of graveyard targets',async()=>{for(const kicked of [false,true]){const f=context(M,role),victims=[put(M,f.game,f.a,'Grizzly Bears','graveyard'),put(M,f.game,f.a,'Grizzly Bears','graveyard')];const {so,paid}=await cast(f,'Blood Beckoning',kicked?victims:victims.slice(0,1),{kicked});assert.equal(so.targets.flat().length,kicked?2:1);assert.equal(paid,kicked?4:1);await settle(f.game);assert.equal(f.a.hand.length,kicked?2:1);assertGameStateInvariants(f.game);}});
 test(role+': variable modal permissions are checked while casting and preserved through responses',async()=>{for(const wizard of [false,true]){const f=context(M,role),artifact=permanent(f,f.b,{types:['Artifact']}),source=wizard?permanent(f,f.a,{subtypes:['Wizard']}):null;const def=M.DEFS['Flame of Anor'];const descriptor=def.oracleImplementation.find(op=>op.kind==='spell-modal-generic');const plan=wizard?[0,1]:[0],mode=descriptor.modes.findIndex(m=>JSON.stringify(m.printedModesV21)===JSON.stringify(plan));choose(f.a,(g,q)=>q.aiHint?.kind==='mode'?String(mode):undefined);const {so}=await cast(f,'Flame of Anor',wizard?[f.a,artifact]:[f.a]);assert.equal(so.mode.length,1);if(source)await f.game.move(source,'graveyard');await settle(f.game);assert.equal(f.a.hand.length,2);assert.equal(artifact.zone,wizard?'graveyard':'battlefield');assertGameStateInvariants(f.game);}});
 test(role+': modal combinations are unavailable without the printed cast condition',async()=>{const f=context(M,role),artifact=permanent(f,f.b,{types:['Artifact']}),spell=put(M,f.game,f.a,'Flame of Anor','hand');fund(f.a);const op=spell.def.oracleImplementation.find(o=>o.kind==='spell-modal-generic'),mode=op.modes.findIndex(m=>m.printedModesV21.length===2);let offered;choose(f.a,(g,q)=>{if(q.aiHint?.kind==='mode'){offered=q.options.map(o=>o.key);return String(mode);}if(q.type==='chooseTargets')return [f.a,artifact].filter(t=>q.candidates.includes(t));});assert.equal(await f.game.castSpell(f.a,spell,{from:'hand'}),false);assert.equal(offered.includes(String(mode)),false);assert.equal(spell.zone,'hand');assertGameStateInvariants(f.game);});
}
