import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createImportPlan,semanticClass} from '../scripts/import-oracle-batch.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v22-spells.json',import.meta.url),'utf8')),M=loadEngine(),absent=rows.filter(c=>!M.DEFS[c.name]);
if(absent.length){const plan=createImportPlan({cards:absent,bulk:{type:'oracle_cards'},sequence:9942,limit:absent.length,compilerVersion:22});assert.equal(plan.report.cards.length,absent.length);M.registerOracleBatch(plan.report);}M.initData(M.RAW_DATA);
const total=p=>Object.values(p.pool).reduce((a,b)=>a+b,0),fund=p=>{for(const c in p.pool)p.pool[c]=30;};
function choose(p,fn){const old=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>fn(g,q)??old(g,q);}
function dead(f,{mv=1,name='Dead '+f.a.graveyard.length,types=['Creature'],subtypes=['Bear']}={}){const c=put(M,f.game,f.a,'Grizzly Bears','graveyard');c.def={...c.def,cost:'{'+mv+'}',name,types,subtypes};return c;}
function mode(f,name,printed){const op=M.DEFS[name].oracleImplementation.find(op=>op.kind==='spell-modal-generic'),index=op.modes.findIndex(mode=>JSON.stringify(Array.from(mode.printedModesV22||[]))===JSON.stringify(printed));assert.ok(index>=0);choose(f.a,(g,q)=>q.aiHint?.kind==='mode'?String(index):undefined);return index;}
async function cast(f,name,targets,{forced=false,...opts}={}){fund(f.a);let cursor=0;if(targets&&(forced||!(f.a.controller instanceof M.AIController)))choose(f.a,(g,q)=>{if(q.type!=='chooseTargets')return undefined;const count=q.max??1,start=count===1?cursor++:0;return targets.slice(start,start+count).filter(c=>q.candidates.includes(c));});const source=put(M,f.game,f.a,name,'hand'),before=total(f.a);assert.equal(await f.game.castSpell(f.a,source,{from:'hand',...opts}),true);const so=f.game.stack.at(-1);return {source,so,paid:before-total(f.a)};}
test('v22 spell fixtures compile complete Oracle rules and reject appended unknown instructions',()=>{for(const card of rows){assert.ok(semanticClass(card,{compilerVersion:22}).semanticClass,card.name);assert.equal(semanticClass({...card,oracle_text:card.oracle_text+'\nDo an unsupported thing.'},{compilerVersion:22}).semanticClass,undefined,card.name);}});
test('modal repetition plans enforce count, paw budget, and printed order',()=>{for(const card of rows){const op=semanticClass(card,{compilerVersion:22}).implementation.find(op=>op.contract==='spell-repeat-modes-v22');if(!op)continue;const weights=card.oracle_text.split('\n').slice(1).map(line=>(line.match(/\{P\}/g)||[]).length||1),exact=/^Choose (three|four)\./.exec(card.oracle_text),max=exact?({three:3,four:4}[exact[1]]):/up to four/.test(card.oracle_text)?4:5;const seen=new Set();for(const mode of op.modes){const plan=mode.printedModesV22,spent=plan.reduce((sum,index)=>sum+weights[index],0);assert.ok(spent<=max);if(exact)assert.equal(spent,max);assert.deepEqual(plan,[...plan].sort((a,b)=>a-b));assert.equal(seen.has(JSON.stringify(plan)),false);seen.add(JSON.stringify(plan));}assert.ok(op.modes.some(mode=>mode.printedModesV22.filter(i=>i===0).length>=3));}});
for(const role of ['human','ai']){
 test(role+': total mana value constrains real optional target announcements',async()=>{const f=context(M,role),cards=[dead(f,{mv:1}),dead(f,{mv:2}),dead(f,{mv:4})];const {so,paid}=await cast(f,'Patch Up',cards.slice(0,2));assert.equal(paid,3);assert.ok(so.targets[0].length>0);assert.ok(so.targets[0].reduce((n,c)=>n+c.mv,0)<=3);await settle(f.game);assert.equal(cards[2].zone,'graveyard');for(const c of so.targets[0])assert.equal(c.zone,'battlefield');assertGameStateInvariants(f.game);});
 test(role+': illegal aggregate targets are rejected before any mana is paid',async()=>{const f=context(M,role),cards=[dead(f,{mv:2}),dead(f,{mv:2})],source=put(M,f.game,f.a,'Patch Up','hand');fund(f.a);choose(f.a,(g,q)=>q.type==='chooseTargets'?cards:undefined);const before=total(f.a);assert.equal(await f.game.castSpell(f.a,source,{from:'hand'}),false);assert.equal(source.zone,'hand');assert.equal(total(f.a),before);assertGameStateInvariants(f.game);});
 test(role+': an unbounded Ally target group can announce more than three targets',async()=>{const f=context(M,role),cards=Array.from({length:5},()=>dead(f,{subtypes:['Ally']}));const {so}=await cast(f,'March from the Tomb',cards);assert.equal(so.targets[0].length,5);await settle(f.game);assert.ok(cards.every(c=>c.zone==='battlefield'));assertGameStateInvariants(f.game);});
 test(role+': up to six cards require distinct names and preserve all announced objects',async()=>{const f=context(M,role),cards=Array.from({length:6},(_,i)=>dead(f,{name:'Distinct '+i}));dead(f,{name:'Distinct 0'});const {so}=await cast(f,'Behold the Sinister Six!',cards);assert.equal(so.targets[0].length,6);assert.equal(new Set(so.targets[0].map(c=>c.name)).size,6);await settle(f.game);assert.ok(so.targets[0].every(c=>c.zone==='battlefield'));assert.equal(f.a.graveyard.filter(c=>c.is('Creature')).length,1);assertGameStateInvariants(f.game);});
 test(role+': changed group names make relational targets illegal',async()=>{const f=context(M,role),cards=[dead(f),dead(f)];const {so}=await cast(f,'Behold the Sinister Six!',cards,{forced:true});assert.equal(so.targets[0].length,2);cards[1].def={...cards[1].def,name:cards[0].name};await settle(f.game);assert.ok(cards.every(c=>c.zone==='graveyard'));assertGameStateInvariants(f.game);});
 test(role+': stale graveyard incarnation does not prevent the other total-MV target from returning',async()=>{const f=context(M,role),cards=[dead(f),dead(f)];await cast(f,'Scout for Survivors',cards,{forced:true});await f.game.move(cards[0],'exile');await f.game.move(cards[0],'graveyard');await settle(f.game);assert.equal(cards[0].zone,'graveyard');assert.equal(cards[0].counters['+1/+1']||0,0);assert.equal(cards[1].zone,'battlefield');assert.equal(cards[1].counters['+1/+1'],1);assertGameStateInvariants(f.game);});
 test(role+': shared-type modes cannot be offered without an actual matching pair',async()=>{const f=context(M,role),cards=[dead(f,{subtypes:['Bear']}),dead(f,{subtypes:['Elf']})],source=put(M,f.game,f.a,'Raise the Draugr','hand');fund(f.a);choose(f.a,(g,q)=>q.aiHint?.kind==='mode'?'1':undefined);assert.equal(await f.game.castSpell(f.a,source,{from:'hand'}),false);assert.equal(source.zone,'hand');assert.ok(cards.every(c=>c.zone==='graveyard'));assertGameStateInvariants(f.game);});
 test(role+': shared-type relation uses the departed partner type at departure',async()=>{for(const changedBeforeDeparture of [false,true]){const f=context(M,role),cards=[dead(f),dead(f)];choose(f.a,(g,q)=>q.aiHint?.kind==='mode'?'1':q.type==='chooseTargets'?cards:undefined);await cast(f,'Raise the Draugr',cards,{forced:true});if(changedBeforeDeparture)cards[0].def={...cards[0].def,subtypes:['Elf']};await f.game.move(cards[0],'exile');cards[0].def={...cards[0].def,subtypes:['Elf']};await f.game.move(cards[0],'graveyard');await settle(f.game);assert.equal(cards[0].zone,'graveyard');assert.equal(cards[1].zone,changedBeforeDeparture?'graveyard':'hand');assertGameStateInvariants(f.game);}});
 test(role+': copied shared-type spell consults retained target LKI while preserving copied choices',async()=>{const f=context(M,role),cards=[dead(f),dead(f)];choose(f.a,(g,q)=>q.aiHint?.kind==='mode'?'1':q.type==='chooseTargets'?cards:undefined);const {so}=await cast(f,'Return from Extinction',cards,{forced:true});await f.game.move(cards[0],'exile');await f.game.copySpell(so,f.a,{mayNewTargets:false});const copy=f.game.stack.at(-1);assert.equal(copy.isCopy,true);assert.deepEqual(Array.from(copy.mode),[1]);assert.equal(copy.targets[0].length,2);await f.game.resolveTop();assert.equal(cards[1].zone,'hand');assert.equal(cards[0].zone,'exile');await settle(f.game);assertGameStateInvariants(f.game);});
 test(role+': Call of the Death-Dweller places independently chosen keyword counters after entry',async()=>{const f=context(M,role),cards=[dead(f),dead(f)],entries=[],emit=f.game.emit;f.game.emit=async function(event,data){if(event==='etb'&&cards.includes(data.card))entries.push({card:data.card,counters:{...data.card.counters}});return emit.call(this,event,data);};choose(f.a,(g,q)=>q.type==='chooseCards'&&/counter on a returned creature/.test(q.prompt)?[q.prompt.includes('deathtouch')?cards[0]:cards[1]]:undefined);await cast(f,'Call of the Death-Dweller',cards,{forced:true});await settle(f.game);assert.equal(entries.length,2);assert.ok(entries.every(row=>!row.counters.deathtouch&&!row.counters.menace));assert.equal(cards[0].counters.deathtouch,1);assert.equal(cards[1].counters.menace,1);assertGameStateInvariants(f.game);});
 test(role+': resolution graveyard choices obey combined mana value and Spree payments',async()=>{const f=context(M,role),cards=[dead(f,{mv:2}),dead(f,{mv:2}),dead(f,{mv:5})];choose(f.a,(g,q)=>q.type==='chooseMulti'&&q.aiHint?.kind==='modes'?['1']:q.type==='chooseCards'&&q.aiHint?.kind==='oracleNameSearch'?cards.slice(0,2):undefined);const {so,paid}=await cast(f,'Lively Dirge');assert.deepEqual(Array.from(so.mode),[1]);assert.equal(paid,4);assert.equal(so.targets.length,0);await settle(f.game);assert.equal(cards[0].zone,'battlefield');assert.equal(cards[1].zone,'battlefield');assert.equal(cards[2].zone,'graveyard');assertGameStateInvariants(f.game);});
 test(role+': Gruesome Menagerie chooses one of each exact mana value without targeting',async()=>{const f=context(M,role),cards=[1,2,3,4].map(mv=>dead(f,{mv}));const {so}=await cast(f,'Gruesome Menagerie');assert.equal(so.targets.length,0);await settle(f.game);assert.ok(cards.slice(0,3).every(c=>c.zone==='battlefield'));assert.equal(cards[3].zone,'graveyard');assertGameStateInvariants(f.game);});
 test(role+': Seasons Past returns distinct mana values and puts the resolving card on the library bottom',async()=>{const f=context(M,role),cards=[0,1,1,2].map(mv=>dead(f,{mv}));choose(f.a,(g,q)=>q.type==='chooseCards'&&q.aiHint?.kind==='oracleNameSearch'?[cards[0],cards[1],cards[3]]:undefined);const {source}=await cast(f,'Seasons Past');await settle(f.game);assert.equal(source.zone,'library');assert.equal(f.a.library[0],source);assert.equal(cards[2].zone,'graveyard');assert.equal(f.a.hand.length,3);assertGameStateInvariants(f.game);});
 test(role+': repeated spell modes announce distinct target slots and may choose no modes',async()=>{for(const printed of [[],[1,1,1,1]]){const f=context(M,role),cards=Array.from({length:4},()=>dead(f)),index=mode(f,'Moment of Reckoning',printed);const {so,paid}=await cast(f,'Moment of Reckoning',cards,{forced:true});assert.deepEqual(Array.from(so.mode),[index]);assert.equal(so.targets.length,printed.length);assert.equal(paid,7);await settle(f.game);if(printed.length)assert.ok(cards.every(c=>c.zone==='battlefield'));else assert.ok(cards.every(c=>c.zone==='graveyard'));assertGameStateInvariants(f.game);}});
 test(role+': paw-budget repetitions execute their printed effect count',async()=>{const f=context(M,role);mode(f,'Season of the Burrow',[0,0,0,0,0]);const {paid}=await cast(f,'Season of the Burrow');assert.equal(paid,5);await settle(f.game);assert.equal(f.game.bf().filter(c=>c.isToken&&c.hasSub('Rabbit')).length,5);assertGameStateInvariants(f.game);});
 test(role+': all-colors Citizens retain every color across repeated modes',async()=>{const f=context(M,role);mode(f,'Planewide Celebration',[0,0,0,0]);await cast(f,'Planewide Celebration');await settle(f.game);const tokens=f.game.bf().filter(c=>c.isToken&&c.hasSub('Citizen'));assert.equal(tokens.length,4);for(const c of tokens)assert.deepEqual(Array.from(c.colors),['W','U','B','R','G']);assertGameStateInvariants(f.game);});
 test(role+': entry keyword counters are present before the returned permanent ETB event',async()=>{const f=context(M,role),card=dead(f),entries=[],emit=f.game.emit;f.game.emit=async function(event,data){if(event==='etb'&&data.card===card)entries.push({...card.counters});return emit.call(this,event,data);};await cast(f,'Perennation',[card]);await settle(f.game);assert.equal(entries.length,1);assert.equal(entries[0].hexproof,1);assert.equal(entries[0].indestructible,1);assert.equal(card.kw('hexproof'),true);assert.equal(card.kw('indestructible'),true);assertGameStateInvariants(f.game);});
 test(role+': Gifts Ungiven permits one or two finds and the opponent must put all into the graveyard',async()=>{for(const n of [1,2,4]){const f=context(M,role),cards=Array.from({length:4},(_,i)=>{const c=put(M,f.game,f.a,'Grizzly Bears','library');c.def={...c.def,name:'Gifts '+i};return c;});choose(f.a,(g,q)=>q.type==='chooseCards'&&q.search?cards.slice(0,n):undefined);const {paid}=await cast(f,'Gifts Ungiven',[f.b]);assert.equal(paid,4);await settle(f.game);for(const [i,c]of cards.entries())assert.equal(c.zone,i<Math.min(n,2)?'graveyard':i<n?'hand':'library');assertGameStateInvariants(f.game);}});
 test(role+': land partition searches apply the printed hand or tapped battlefield destination',async()=>{for(const name of ['Realms Uncharted','Elemental Teachings']){const f=context(M,role),cards=Array.from({length:4},(_,i)=>{const c=put(M,f.game,f.a,'Forest','library');c.def={...c.def,name:'Distinct land '+i};return c;});choose(f.a,(g,q)=>q.type==='chooseCards'&&q.search?cards:undefined);await cast(f,name);await settle(f.game);assert.ok(cards.slice(0,2).every(c=>c.zone==='graveyard'));for(const c of cards.slice(2)){assert.equal(c.zone,name==='Elemental Teachings'?'battlefield':'hand');if(name==='Elemental Teachings')assert.equal(c.tapped,true);}assertGameStateInvariants(f.game);}});
 test(role+': Ecological Appreciation searches both zones, obeys actual X, shuffles the chosen pair and exiles itself',async()=>{const f=context(M,role),cards=Array.from({length:4},(_,i)=>{const c=put(M,f.game,f.a,'Grizzly Bears',i<2?'library':'graveyard');c.def={...c.def,cost:'{2}',name:'Ecological '+i};return c;}),high=dead(f,{mv:3});choose(f.a,(g,q)=>{if(q.type==='chooseCards'&&q.search){assert.equal(q.from.includes(high),false);return cards;}});const {so,source,paid}=await cast(f,'Ecological Appreciation',undefined,{xVal:2});assert.equal(so.targets.length,0);assert.equal(paid,5);await settle(f.game);assert.ok(cards.slice(0,2).every(c=>c.zone==='library'));assert.ok(cards.slice(2).every(c=>c.zone==='battlefield'));assert.equal(high.zone,'graveyard');assert.equal(source.zone,'exile');assertGameStateInvariants(f.game);});
 test(role+': partition resolution ignores a card incarnation moved away during the opponent choice',async()=>{const f=context(M,role),cards=Array.from({length:4},(_,i)=>{const c=put(M,f.game,f.a,'Grizzly Bears','library');c.def={...c.def,name:'Partition identity '+i};return c;});choose(f.a,(g,q)=>q.type==='chooseCards'&&q.search?cards:undefined);choose(f.b,(g,q)=>q.aiHint?.kind==='oraclePartitionV22'?(async()=>{await g.move(cards[2],'exile');return cards.slice(0,2);})():undefined);await cast(f,'Gifts Ungiven',[f.b]);await settle(f.game);assert.equal(cards[2].zone,'exile');assert.equal(cards[3].zone,'hand');assertGameStateInvariants(f.game);});
 test(role+': a library search prohibition does not expose cards to the selection',async()=>{const f=context(M,role),card=put(M,f.game,f.a,'Grizzly Bears','library');f.game.searchableLibrary=()=>[];let offered;choose(f.a,(g,q)=>{if(q.type==='chooseCards'&&q.search){offered=q.from.length;return [];}});await cast(f,'Gifts Ungiven',[f.b]);await settle(f.game);assert.equal(offered,0);assert.equal(card.zone,'library');assert.equal(f.a.hand.length,0);assertGameStateInvariants(f.game);});
 test(role+': current graveyard origin excludes a departed and re-entered incarnation',async()=>{for(const name of ['Faith\'s Reward','Brought Back']){const f=context(M,role),cards=[put(M,f.game,f.a,'Grizzly Bears'),put(M,f.game,f.a,'Grizzly Bears')],never=dead(f);for(const c of cards)await f.game.sacrifice(f.a,c);await f.game.move(cards[0],'exile');await f.game.move(cards[0],'graveyard');const {so}=await cast(f,name,name==='Brought Back'?[cards[1]]:undefined);if(name==='Brought Back')assert.equal(so.targets[0].length,1);await settle(f.game);assert.equal(cards[0].zone,'graveyard');assert.equal(never.zone,'graveyard');assert.equal(cards[1].zone,'battlefield');if(name==='Brought Back')assert.equal(cards[1].tapped,true);assertGameStateInvariants(f.game);}});
 test(role+': Shadow of the Grave returns real cycling and discard costs, with exact current-zone history',async()=>{const f=context(M,role),cycled=put(M,f.game,f.a,'Tranquil Thicket','hand'),discarded=put(M,f.game,f.a,'Grizzly Bears','hand'),stale=put(M,f.game,f.a,'Grizzly Bears','hand'),untouched=dead(f);fund(f.a);const action=f.game.activatableList(f.a).find(row=>row.card===cycled&&row.cycling);assert.ok(action);assert.equal(await f.game.activateAbility(f.a,action),true);await settle(f.game);await f.game.discard(f.a,[discarded,stale]);await f.game.move(stale,'exile');await f.game.move(stale,'graveyard');await cast(f,'Shadow of the Grave');await settle(f.game);assert.equal(cycled.zone,'hand');assert.equal(discarded.zone,'hand');assert.equal(stale.zone,'graveyard');assert.equal(untouched.zone,'graveyard');assertGameStateInvariants(f.game);});
 test(role+': Season of Loss samples creature cards after earlier sacrifices',async()=>{const f=context(M,role);for(let i=0;i<3;i++){put(M,f.game,f.a,'Grizzly Bears');put(M,f.game,f.b,'Grizzly Bears');}dead(f);mode(f,'Season of Loss',[0,0,2]);await cast(f,'Season of Loss');await settle(f.game);assert.equal(f.a.graveyard.filter(c=>c.is('Creature')).length,3);assert.equal(f.b.life,37);assert.equal(f.game.creatures(f.a).length,1);assert.equal(f.game.creatures(f.b).length,1);assertGameStateInvariants(f.game);});
 test(role+': repeated type choices may independently sweep artifacts and enchantments',async()=>{const f=context(M,role),artifact=put(M,f.game,f.b,'Sol Ring'),enchantment=put(M,f.game,f.b,'Grizzly Bears');enchantment.def={...enchantment.def,types:['Enchantment']};f.game.recalc();let n=0;choose(f.a,(g,q)=>q.prompt==='Choose a permanent type'?(n++?'enchantment':'artifact'):undefined);mode(f,'Season of Gathering',[1,1]);await cast(f,'Season of Gathering');await settle(f.game);assert.equal(n,2);assert.equal(artifact.zone,'graveyard');assert.equal(enchantment.zone,'graveyard');assertGameStateInvariants(f.game);});
 test(role+': repeated Cave animation affects the chosen land rather than the resolving spell',async()=>{const f=context(M,role),cave=put(M,f.game,f.a,'Forest'),animations=[],add=f.game.addOracleAnimation;cave.def={...cave.def,subtypes:['Cave']};f.game.recalc();f.game.addOracleAnimation=function(card,effect){animations.push({card,effect});return add.call(this,card,effect);};mode(f,'Cosmium Confluence',[1,1,1]);const {source,paid}=await cast(f,'Cosmium Confluence');assert.equal(paid,5);await settle(f.game);assert.equal(animations.length,3);assert.ok(animations.every(row=>row.card===cave));assert.equal(cave.counters['+1/+1'],9);assert.equal(cave.cur.basePower,0);assert.equal(cave.cur.baseToughness,0);assert.equal(cave.power,9);assert.equal(cave.is('Land'),true);assert.equal(cave.is('Creature'),true);assert.equal(cave.hasSub('Elemental'),true);assert.equal(cave.kw('haste'),true);assert.equal(source.zone,'graveyard');assertGameStateInvariants(f.game);});
}
