import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {semanticClass} from '../scripts/import-oracle-batch.mjs';import {loadEngine} from './helpers/load-engine.mjs';import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
const M=loadEngine(),raw=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-land-setting-source.json',import.meta.url))),entries=raw.map((card,i)=>{const parsed=semanticClass(card),types=card.type_line.split(' — ')[0].split(' ');assert.ok(parsed.semanticClass,card.name);return {position:i+1,oracleId:card.oracle_id,scryfallId:card.id,...parsed,raw:{name:card.name,oracle:card.oracle_text,cost:card.mana_cost,types:types.filter(t=>!['Legendary','Snow','Basic'].includes(t)),super:types.filter(t=>['Legendary','Snow','Basic'].includes(t)),subtypes:card.type_line.split(' — ')[1]?.split(' ')||[],power:card.power,toughness:card.toughness,_ci:card.color_identity},catalog:{typeLine:card.type_line,commanderLegality:'legal'}};});
M.registerOracleBatch({id:'land-setting-source-draft',sequence:9990,cards:entries.filter(e=>!M.DEFS[e.raw.name])});M.initData(M.RAW_DATA);
const fund=p=>{for(const c of ['W','U','B','R','G','C'])p.pool[c]=100;},total=p=>Object.values(p.pool).reduce((n,v)=>n+v,0);
function setup(role){const ctx=context(M,role);ctx.choice={target:null,type:'Island'};const decide=ctx.a.controller.decide.bind(ctx.a.controller);ctx.a.controller.decide=async(g,q)=>{if(role==='human'&&q.type==='chooseTargets'&&ctx.choice.target&&q.candidates.includes(ctx.choice.target))return [ctx.choice.target];if(role==='human'&&q.aiHint?.kind==='basicLandType')return ctx.choice.type;return decide(g,q);};return ctx;}
async function cast(ctx,name,{target=null}={}){fund(ctx.a);ctx.choice.target=target;const card=put(M,ctx.game,ctx.a,name,'hand'),before=total(ctx.a);assert.equal(await ctx.game.castSpell(ctx.a,card,{from:'hand'}),true);await settle(ctx.game);assert.ok(total(ctx.a)<before);return card;}
async function activate(ctx,card){fund(ctx.a);card.sick=false;const action=ctx.game.activatableList(ctx.a).find(row=>row.card===card&&row.ability.oracleCompiled),before=total(ctx.a);assert.ok(action,card.name);assert.equal(await ctx.game.activateAbility(ctx.a,action),true);await settle(ctx.game);return action;}
for(const role of ['human','ai']){
 test(`${role}: a paid basic land type effect replaces printed mana while keeping the land nonbasic`,async()=>{const ctx=setup(role),{game,a,b}=ctx,land=put(M,game,b,'Command Tower'),source=await cast(ctx,'Tidal Warrior');ctx.choice.target=land;await activate(ctx,source);const chosen=game.bf().find(c=>c.is('Land')&&c.cur.oracleLandTypeAbilitiesRemoved);assert.ok(chosen);assert.equal(chosen.hasSub('Island'),true);assert.equal(chosen.cur.super.includes('Basic'),false);const mana=game.manaSources(chosen.ctrl).filter(row=>row.card===chosen);assert.ok(mana.length);assert.equal(mana.length,1);assert.deepEqual(JSON.parse(JSON.stringify(mana[0].produce)),[{U:1}]);});
 test(`${role}: Aura replacement removes mana and printed triggered abilities and ends when the Aura leaves`,async()=>{const ctx=setup(role),{game,a,b}=ctx,land=put(M,game,b,'Rupture Spire'),aura=await cast(ctx,'Spreading Seas',{target:land});const actual=game.byIid(aura.attachedTo);assert.ok(actual?.is('Land'));assert.equal(actual.hasSub('Island'),true);assert.equal(actual.cur.abilitiesDisabled,true);const original=actual.def;await game.move(aura,'graveyard');assert.equal(actual.def,original);assert.equal(actual.cur.abilitiesDisabled,false);assert.equal(actual.hasSub('Island'),false);});
 test(`${role}: type-setting keeps external mana and activated abilities, even when their source predates the setting`,async()=>{const ctx=setup(role),{game,a}=ctx,land=put(M,game,a,'Command Tower');const grant=put(M,game,a,'Sol Ring');grant.def={...grant.def,statics:[{phase:2,apply(g,self){land.cur.extraMana.push({cost:{tap:true},produce:[{G:1}],key:'external-mana'});land.cur.extraAbilities.push({cost:{mana:'{1}'},run:async c=>c.g.gainLife(c.you,1,c.src)});}}]};game.recalc();const aura=await cast(ctx,'Evil Presence',{target:land});assert.equal(land.hasSub('Swamp'),true);assert.equal(land.cur.abilitiesDisabled,true);const sources=game.manaSources(a).filter(row=>row.card===land);assert.ok(sources.some(row=>row.produce.some(output=>output.B===1)));assert.ok(sources.some(row=>row.produce.some(output=>output.G===1)));const ability=game.activatableList(a).find(row=>row.card===land);assert.ok(ability);const life=a.life;assert.equal(await game.activateAbility(a,ability),true);await settle(game);assert.equal(a.life,life+1);});
 test(`${role}: basic land type setting removes all land subtypes and keeps unrelated types and subtypes`,async()=>{const ctx=setup(role),{game,a}=ctx,land=put(M,game,a,'Treetop Village');await activate(ctx,land);land.def={...land.def,subtypes:['Gate','Desert']};game.recalc();await cast(ctx,'Lush Growth',{target:land});assert.equal(land.is('Creature'),true);assert.equal(land.hasSub('Ape'),true);assert.equal(land.hasSub('Gate'),false);assert.equal(land.hasSub('Desert'),false);for(const type of ['Mountain','Forest','Plains'])assert.equal(land.hasSub(type),true);assert.equal(game.manaSources(a).filter(row=>row.card===land).length,3);});
 test(`${role}: replacing Urborg's land abilities defeats its type grant regardless of timestamp`,async()=>{for(const order of ['land-first','moon-first']){const ctx=setup(role),{game,a,b}=ctx;let urborg,moon;if(order==='land-first'){urborg=put(M,game,a,'Urborg, Tomb of Yawgmoth');moon=await cast(ctx,'Blood Moon');}else{moon=await cast(ctx,'Blood Moon');urborg=put(M,game,a,'Urborg, Tomb of Yawgmoth');}const basic=put(M,game,b,'Forest');game.recalc();assert.equal(urborg.hasSub('Mountain'),true);assert.equal(urborg.hasSub('Swamp'),false);assert.equal(basic.hasSub('Swamp'),false);assert.equal(basic.hasSub('Forest'),true);await game.move(moon,'exile');assert.equal(basic.hasSub('Swamp'),true);assert.equal(urborg.cur.abilitiesDisabled,false);}});
 test(`${role}: Blood Moon applies before Vesuva, shockland and Dark Depths entry replacements`,async()=>{const ctx=setup(role),{game,a}=ctx;await cast(ctx,'Blood Moon');const life=a.life;for(const name of ['Vesuva','Temple Garden','Dark Depths']){const card=put(M,game,a,name,'hand');await game.putPermanentOntoBattlefield(card,a);await settle(game);assert.equal(card.name,name);assert.equal(card.hasSub('Mountain'),true);assert.equal(card.tapped,false);assert.equal(card.counters.ice||0,0);assert.equal(card.zone,'battlefield');assert.equal(a.life,life);}assert.equal(game.bf().some(c=>c.name==='Marit Lage'),false);});
 test(`${role}: subsequent layer-six loss removes intrinsic mana from an animated type-set land`,async()=>{const ctx=setup(role),{game,a}=ctx,land=put(M,game,a,'Treetop Village');await activate(ctx,land);await cast(ctx,'Evil Presence',{target:land});const aura=put(M,game,a,'Lignify','hand');await game.move(aura,'battlefield',{attachTo:land});assert.equal(land.hasSub('Swamp'),true);assert.equal(land.cur.abilitiesDisabled,true);assert.equal(game.manaSources(a).filter(row=>row.card===land).length,0);});
}
for(const role of ['human','ai'])for(const entry of entries)test(`${role}: exact ${entry.raw.name} paid source sets land characteristics and intrinsic mana`,async()=>{
 const ctx=setup(role),{game,a,b}=ctx,target=put(M,game,b,'Command Tower');for(let i=0;i<4;i++)put(M,game,a,i%2?'Forest':'Island');put(M,game,a,'Grizzly Bears');const zombie=put(M,game,a,'Grizzly Bears');zombie.def={...zombie.def,subtypes:['Zombie']};game.recalc();put(M,game,a,'Forest','hand');
 const decide=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>{if(role==='human'&&q.type==='chooseX')return Math.min(2,q.max??2);if(role==='human'&&q.type==='chooseTargets'&&(q.min||0)>1)return q.candidates.slice(0,q.min);return decide(g,q);};
 const source=await cast(ctx,entry.raw.name,{target});source.sick=false;
 const printed=entry.implementation.find(op=>op.effects?.some(effect=>effect.action==='set-basic-land-types-v8'));
 if(printed?.kind==='generic-ability'||entry.raw.name==='Sealock Monster'){
  const operation=printed?.kind==='generic-ability'?printed:entry.implementation.find(op=>op.kind==='generic-ability'&&op.effects.some(effect=>effect.action==='monstrosity-v8'));
  const index=entry.implementation.filter(op=>op.kind==='generic-ability').indexOf(operation),ability=source.def.abilities.filter(row=>row.oracleCompiled)[index],action=game.activatableList(a).find(row=>row.card===source&&row.ability===ability);assert.ok(action,entry.raw.name);fund(a);assert.equal(await game.activateAbility(a,action),true);await settle(game);
 }
 if(entry.raw.name==='Graceful Antelope'){const decide=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>role==='human'&&q.type==='attackers'?[{card:source,target:b}]:decide(g,q);await game.combatPhase(a);await settle(game);}
 const record=game.untilEffects.find(effect=>effect.kind==='oracleLandTypes'),staticOperation=entry.implementation.find(op=>op.kind==='v8-land-types');
 if(!staticOperation&&entry.raw.name==='Tide Shaper'&&!source.castMeta.kicked){assert.equal(record,undefined);return;}
 assert.ok(record||staticOperation,entry.raw.name+': actual type-setting effect');const affected=record?game.byIid(record.iid):staticOperation.attached?game.byIid(source.attachedTo):target,types=record?.types||staticOperation.types;
 assert.ok(affected?.is('Land'));for(const type of types)assert.equal(affected.hasSub(type),true);
 const production=game.manaSources(affected.ctrl).filter(row=>row.card===affected);if(affected.tapped)game.untap(affected);assert.ok(production.length||game.manaSources(affected.ctrl).some(row=>row.card===affected));
 if((record?.retain??staticOperation?.retain)===false)assert.equal(affected.cur.abilitiesDisabled,true);
 assert.equal((game.aiDecisionLog||[]).some(row=>row.fallback),false);
});
for(const role of ['human','ai']){
 test(`${role}: the new intrinsic mana pays for a real blue spell and the lost printed colors cannot pay`,async()=>{const ctx=setup(role),{game,a}=ctx,land=put(M,game,a,'Command Tower'),source=await cast(ctx,'Tidal Warrior');ctx.choice.target=land;await activate(ctx,source);for(const color of Object.keys(a.pool))a.pool[color]=0;assert.equal(game.canPayMana(a,M.parseCost('{R}')),false);assert.equal(game.canPayMana(a,M.parseCost('{U}')),true);const spell=put(M,game,a,'Opt','hand');assert.equal(await game.castSpell(a,spell,{from:'hand'}),true);assert.equal(land.tapped,true);assert.equal(total(a),0);await settle(game);assert.equal(spell.zone,'graveyard');});
 test(`${role}: EOT land setting expires in real cleanup while indefinite setting survives source departure and saves`,async()=>{const ctx=setup(role),{game,a}=ctx,land=put(M,game,a,'Command Tower'),source=await cast(ctx,'Tidal Warrior');let done=false;game.mainPhase=async()=>{if(done)return;done=true;ctx.choice.target=land;await activate(ctx,source);assert.equal(land.hasSub('Island'),true);};game.combatPhase=async()=>{};await game.runTurn();assert.equal(done,true);assert.equal(land.hasSub('Island'),false);assert.equal(land.cur.abilitiesDisabled,false);await game.runTurn();assert.equal(game.turnPlayer,a);game.phase='main1';game.step='main';const monk=await cast(ctx,'Thelonite Monk');put(M,game,a,'Grizzly Bears');ctx.choice.target=land;await activate(ctx,monk);assert.equal(land.hasSub('Forest'),true);await game.move(monk,'exile');assert.equal(land.hasSub('Forest'),true);const clone=M.cloneGameForAISimulation(game,999);assert.equal(clone.byIid(land.iid).hasSub('Forest'),true);const saved=M.captureGameState(game);assert.ok(saved,JSON.stringify(M.gameStateSnapshotBlockers(game)));const restored=setup(role).game;M.restoreGameState(restored,JSON.parse(JSON.stringify(saved)));assert.equal(restored.byIid(land.iid).hasSub('Forest'),true);await game.move(land,'exile');await game.putPermanentOntoBattlefield(land,a);assert.equal(land.hasSub('Forest'),false);});
 test(`${role}: source battlefield duration ends on phasing, while until-leaves duration survives phasing`,async()=>{for(const name of ['Tide Shaper','Graceful Antelope']){const ctx=setup(role),{game,a,b}=ctx,land=put(M,game,b,'Command Tower');if(name==='Tide Shaper'){const decide=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>q.aiHint?.kind==='kicker'?'yes':decide(g,q);}const source=await cast(ctx,name,{target:land});if(name==='Graceful Antelope'){const decide=a.controller.decide.bind(a.controller);a.controller.decide=async(g,q)=>role==='human'&&q.type==='attackers'?[{card:source,target:b}]:decide(g,q);source.sick=false;await game.combatPhase(a);await settle(game);}const record=game.untilEffects.find(row=>row.kind==='oracleLandTypes'),target=game.byIid(record.iid),type=record.types[0];assert.equal(target.hasSub(type),true);game.phaseOut(source);assert.equal(target.hasSub(type),name==='Graceful Antelope');game.phaseInFor(a);assert.equal(target.hasSub(type),name==='Graceful Antelope');await game.move(source,'exile');assert.equal(target.hasSub(type),false);}});
 test(`${role}: Blood Moon lets a zero-counter Dark Depths wait until its ability returns`,async()=>{const ctx=setup(role),{game,a}=ctx,moon=await cast(ctx,'Blood Moon'),depths=put(M,game,a,'Dark Depths','hand');await game.putPermanentOntoBattlefield(depths,a);await settle(game);assert.equal(depths.counters.ice||0,0);assert.equal(depths.zone,'battlefield');await game.move(moon,'exile');await settle(game);assert.equal(depths.zone,'graveyard');assert.ok(game.bf().some(card=>card.name==='Marit Lage'&&card.power===20));});
 test(`${role}: simultaneous Blood Moon and Dark Depths use the earlier entry snapshot`,async()=>{const ctx=setup(role),{game,a}=ctx,moon=put(M,game,a,'Blood Moon','hand'),depths=put(M,game,a,'Dark Depths','hand');await game.moveBattlefieldBatch([moon,depths]);await settle(game);assert.equal(depths.counters.ice,10);assert.equal(depths.hasSub('Mountain'),true);assert.equal(depths.cur.abilitiesDisabled,true);});
 test(`${role}: a type-setting effect removes only printed keywords, retaining an earlier animation grant`,async()=>{const ctx=setup(role),{game,a}=ctx,land=put(M,game,a,'Treetop Village');await activate(ctx,land);assert.equal(land.kw('trample'),true);await cast(ctx,'Spreading Seas',{target:land});assert.equal(land.kw('trample'),true);assert.equal(land.is('Creature'),true);assert.equal(land.hasSub('Ape'),true);assert.equal(land.hasSub('Island'),true);});
}
test('basic land type descriptors reject ambiguous sets, fields and durations',()=>{for(const extra of [{retain:'no'},{types:['Island','Island']},{types:['Gate']},{unparsed:'draw a card'}])assert.throws(()=>M.OracleV8LandTypes.compile({kind:'v8-land-types',attached:true,retain:false,types:['Island'],contract:'continuous-basic-land-types',...extra},{}));});
test('land type checkpoints reject invalid subtype/duration/incarnation data before mutating the running game',async()=>{const ctx=setup('human'),{game,a}=ctx,land=put(M,game,a,'Command Tower'),monk=await cast(ctx,'Thelonite Monk');put(M,game,a,'Grizzly Bears');ctx.choice.target=land;await activate(ctx,monk);const saved=M.captureGameState(game);assert.ok(saved);assert.equal(saved.landTypeEffects.length,1);for(const patch of [{types:['Gate']},{types:['Island','Island']},{timestamp:Number.MAX_SAFE_INTEGER},{zoneVersion:-1},{expires:'indefinitely'},{unparsedEffect:'draw'}]){const malformed=JSON.parse(JSON.stringify(saved));Object.assign(malformed.landTypeEffects[0],patch);const before=M.gameStateFingerprint(game);assert.throws(()=>M.restoreGameState(game,malformed),/land type/);assert.equal(M.gameStateFingerprint(game),before);}});
test('an indefinite type-setting record remains portable while its target is phased out',async()=>{const ctx=setup('human'),{game,a}=ctx,land=put(M,game,a,'Command Tower'),monk=await cast(ctx,'Thelonite Monk');put(M,game,a,'Grizzly Bears');ctx.choice.target=land;await activate(ctx,monk);game.phaseOut(land);const saved=M.captureGameState(game);assert.ok(saved);const restored=setup('human').game;M.restoreGameState(restored,JSON.parse(JSON.stringify(saved)));const card=restored.battlefield.find(c=>c.iid===land.iid);assert.equal(card.phasedOut,true);restored.phaseInFor(restored.players[0]);assert.equal(card.hasSub('Forest'),true);assert.equal(restored.manaSources(restored.players[0]).filter(row=>row.card===card).length,1);});
test('a source-bound land type checkpoint retains its real phase expiry rather than becoming indefinite',async()=>{const ctx=setup('human'),{game,a,b}=ctx,land=put(M,game,b,'Command Tower'),source=await cast(ctx,'Tide Shaper',{target:land});assert.equal(source.castMeta.kicked,true);const saved=M.captureGameState(game);assert.ok(saved);assert.equal(saved.landTypeEffects[0].sourceDuration.mode,'battlefield');assert.equal(saved.landTypeEffects[0].sourceDuration.controller,undefined);const restored=setup('human').game;M.restoreGameState(restored,JSON.parse(JSON.stringify(saved)));const target=restored.byIid(land.iid);assert.equal(target.hasSub('Island'),true);restored.phaseOut(restored.byIid(source.iid));assert.equal(target.hasSub('Island'),false);});
