import fs from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,put,settle} from './helpers/oracle-v8-fixtures.mjs';
import {proveGishathV25,proveOjerKaslemV25} from './helpers/oracle-v25-layouts-proof.mjs';
import {assertGameStateInvariants} from './helpers/game-state-invariants.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v25-layouts.json',import.meta.url),'utf8')),M=loadEngine();
const report=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v25-layouts-runtime.json',import.meta.url),'utf8')).batches[0];
assert.equal(report.cards.length,rows.length);const absent=report.cards.filter(c=>!M.DEFS[c.raw.name]);if(absent.length){M.registerOracleBatch({...report,cards:absent});M.initData(M.RAW_DATA);}
const fund=p=>{for(const c of ['W','U','B','R','G','C'])p.pool[c]=40;};
const choose=(p,predicate,value)=>{const old=p.controller.decide.bind(p.controller);p.controller.decide=async(g,q)=>{const result=await old(g,q);return predicate(q)?value(q,g):result;};};
const witness=(f,name,types=['Creature'],cost='{2}',subtypes=[],zone='library')=>{const c=put(M,f.game,f.a,'Grizzly Bears',zone);c.def={...c.def,name,cost,types,subtypes,super:[],kws:[],power:'2',toughness:'3',colorsOverride:[]};f.game.recalc();return c;};
const cast=async(f,name,opts={})=>{fund(f.a);const c=put(M,f.game,f.a,name,'hand');assert.equal(await f.game.castSpell(f.a,c,{from:'hand',...opts}),true,name);await settle(f.game);return c;};
const clear=p=>{for(const c of p.library.splice(0)){c.zone='graveyard';p.graveyard.push(c);}};
for(const role of ['human','ai']){
 test(role+': Winota enters a qualified Human attacking through the actual declaration without creating another attack trigger',async()=>{
  for(const accept of [false,true]){const f=context(M,role),{game,a,b}=f;const source=await cast(f,'Winota, Joiner of Forces'),bear=put(M,game,a,'Grizzly Bears');source.sick=false;bear.sick=false;const human=witness(f,'Inspected Human',['Creature'],'{3}',['Human']),wrong=witness(f,'Inspected Elf',['Creature'],'{3}',['Elf']);let queries=0,entry;choose(a,q=>q.type==='attackers',()=>[{card:bear,target:b}]);choose(a,q=>q.prompt==='Choose library cards for battlefield',q=>{queries++;assert.ok(q.from.includes(human));assert.equal(q.from.includes(wrong),false);return accept?[human]:[];});const emit=game.emit;game.emit=async function(event,data,...args){if(event==='etb'&&data.card===human)entry={tapped:human.tapped,attacking:human.attacking};return emit.call(this,event,data,...args);};game.priorityRound=async()=>settle(game);await game.combatPhase(a);await settle(game);assert.equal(queries,1);assert.equal(human.zone,accept?'battlefield':'library');if(accept){assert.equal(entry.tapped,true);assert.ok(entry.attacking===b);assert.equal(human.kw('indestructible'),true);game.untilEffects=game.untilEffects.filter(e=>e.expires!=='eot');game.recalc();assert.equal(human.kw('indestructible'),false);}assertGameStateInvariants(game);}
 });
 test(role+': Abundant Harvest terminates at the chosen kind and handles a wholly missing kind and an empty library',async()=>{
  for(const [kind,hit]of [['land',true],['nonland',true],['nonland',false],['land',false]]){const f=context(M,role),{game,a}=f;clear(a);const low=witness(f,'Untouched lower card',['Land'],'',[]),wanted=hit?witness(f,'Harvest hit',kind==='land'?['Land']:['Creature'],kind==='land'?'':'{2}'):null,wrong=witness(f,'Wrong top kind',kind==='land'?['Creature']:['Land'],kind==='land'?'{2}':'');if(!hit&&kind==='land')clear(a);choose(a,q=>q.prompt==='Choose the card kind to reveal',()=>kind);await cast(f,'Abundant Harvest');if(wanted)assert.equal(wanted.zone,'hand');else assert.equal(a.hand.length,0);if(hit)assert.equal(wrong.zone,'library');assertGameStateInvariants(game);}
 });
 test(role+': Madcap Experiment uses every actually revealed card for damage even when no artifact exists',async()=>{
  for(const artifact of [true,false]){const f=context(M,role),{game,a}=f;clear(a);const selected=artifact?witness(f,'Artifact hit',['Artifact'],'{4}'):null;for(let i=0;i<3;i++)witness(f,'Nonartifact '+i,['Land'],'');const life=a.life;await cast(f,'Madcap Experiment');assert.equal(a.life,life-(artifact?4:3));if(selected)assert.equal(selected.zone,'battlefield');assert.equal(a.library.length,3);assertGameStateInvariants(game);}
 });
 test(role+': Planar Genesis accepts a land entry or chooses one exact hand card after declining it',async()=>{
  for(const accept of [false,true]){const f=context(M,role),{game,a}=f;const land=witness(f,'Genesis land',['Land'],''),creature=witness(f,'Genesis creature');choose(a,q=>q.prompt==='Choose library cards for battlefield',()=>accept?[land]:[]);choose(a,q=>q.prompt==='Choose library cards for hand',()=>[creature]);await cast(f,'Planar Genesis');assert.equal(land.zone,accept?'battlefield':'library');assert.equal(creature.zone,accept?'library':'hand');if(accept)assert.equal(land.tapped,true);assertGameStateInvariants(game);}
 });
 test(role+': Astor preserves printed equip and crew abilities while granting independently paid alternatives',async()=>{
  const f=context(M,role),{game,a}=f;await cast(f,'Astor, Bearer of Blades');const host=put(M,game,a,'Grizzly Bears'),equipment=put(M,game,a,'Sol Ring');equipment.def={...equipment.def,subtypes:['Equipment'],equip:'{0}'};const vehicle=put(M,game,a,'Sol Ring');vehicle.def={...vehicle.def,name:'Astor test Vehicle',subtypes:['Vehicle'],crew:4,power:'4',toughness:'4'};game.recalc();fund(a);assert.equal(equipment.def.equip,'{0}');assert.equal(game.vehicleCrewCost(vehicle),4);assert.ok(game.activatableList(a).some(r=>r.card===equipment&&r.equip));const equip=game.activatableList(a).find(r=>r.card===equipment&&r.ability?.label==='Equip {1}');assert.ok(equip);choose(a,q=>q.type==='chooseTargets',()=>[host]);const before=Object.values(a.pool).reduce((s,n)=>s+n,0);assert.equal(await game.activateAbility(a,equip),true);await settle(game);assert.equal(Object.values(a.pool).reduce((s,n)=>s+n,0),before-1);assert.equal(equipment.attachedTo,host.iid);choose(a,q=>q.aiHint?.kind==='crew',()=>[host]);const crew=game.activatableList(a).find(r=>r.card===vehicle&&r.oracleGrantedCrewV25===1);assert.ok(crew);assert.equal(await game.activateAbility(a,crew),true);await settle(game);assert.equal(host.tapped,true);assert.equal(vehicle.is('Creature'),true);assert.equal(game.vehicleCrewCost(vehicle),4);assertGameStateInvariants(game);
 });
 test(role+': Adventure mill choices retain exact cards across a real Rest in Peace replacement',async()=>{
  for(const exile of [false,true]){const f=context(M,role),{game,a}=f;if(exile)put(M,game,a,'Rest in Peace');clear(a);const creature=witness(f,'Study creature'),bad=witness(f,'Study artifact',['Artifact']);for(let i=0;i<3;i++)witness(f,'Study land '+i,['Land'],'');choose(a,q=>q.prompt==='Choose cards from the actual milled cohort',q=>{assert.ok(q.from.includes(creature));assert.equal(q.from.includes(bad),false);return [creature];});const source=await cast(f,'Monster Manual // Zoological Study',{alt:{adventure:true}});assert.equal(creature.zone,'hand');assert.equal(bad.zone,exile?'exile':'graveyard');assert.equal(source.zone,'exile');assert.ok(a.exile.includes(source));assert.equal(game.castableList(a).some(r=>r.card===source&&!r.adventure),true);assertGameStateInvariants(game);}
 });
}

for(const role of ['human','ai']){
 test(role+': categories use exact two-color pairs and never reuse a card for two card types',async()=>{
  for(const name of ['Niv-Mizzet Reborn','Atraxa, Grand Unifier']){const f=context(M,role),{game,a}=f;clear(a);const dual=witness(f,'Two category witness',['Artifact','Creature'],'{2}'),second=witness(f,'Second category witness',['Creature'],'{2}'),single=witness(f,'One color negative',['Sorcery'],'{2}'),triple=witness(f,'Three color negative',['Instant'],'{2}');dual.def={...dual.def,colorsOverride:['W','U']};second.def={...second.def,colorsOverride:['W','B']};single.def={...single.def,colorsOverride:['U']};triple.def={...triple.def,colorsOverride:['W','U','B']};game.recalc();const chosen=new Set();choose(a,q=>q.prompt==='Choose library cards for hand',q=>{assert.equal(q.from.some(c=>chosen.has(c)),false);if(name==='Niv-Mizzet Reborn'){assert.equal(q.from.includes(single),false);assert.equal(q.from.includes(triple),false);}const card=q.from.find(c=>c===dual||c===second);if(card)chosen.add(card);return card?[card]:[];});await cast(f,name);assert.equal(dual.zone,'hand');assert.equal(second.zone,'hand');if(name==='Niv-Mizzet Reborn'){assert.equal(single.zone,'library');assert.equal(triple.zone,'library');}assertGameStateInvariants(game);}
 });
 test(role+': Paradox Surveyor requires a literal X mana symbol while Discerning Taste uses only actually buried creature power',async()=>{
  const f=context(M,role),{game,a}=f;clear(a);const x=witness(f,'Literal X card',['Sorcery'],'{X}{G}'),bad=witness(f,'No X negative',['Sorcery'],'{2}');choose(a,q=>q.prompt==='Choose library cards for hand',q=>{assert.ok(q.from.includes(x));assert.equal(q.from.includes(bad),false);return [x];});await cast(f,'Paradox Surveyor');assert.equal(x.zone,'hand');assert.equal(bad.zone,'library');
  for(const exile of [false,true]){const t=context(M,role);clear(t.a);if(exile)put(M,t.game,t.a,'Rest in Peace');const keep=witness(t,'Keep artifact',['Artifact'],'{2}'),creature=witness(t,'Buried power nine',['Creature'],'{2}');creature.def={...creature.def,power:'9',toughness:'10'};t.game.recalc();choose(t.a,q=>q.prompt==='Choose library cards for hand',()=>[keep]);const life=t.a.life;await cast(t,'Discerning Taste');assert.equal(keep.zone,'hand');assert.equal(creature.zone,exile?'exile':'graveyard');assert.equal(t.a.life,life+(exile?0:9));assertGameStateInvariants(t.game);}
 });
 test(role+': Elspeth places one selected keyword counter and a shield counter before a selected permanent enters',async()=>{
  for(const keyword of ['flying','first strike','lifelink','vigilance']){const f=context(M,role),{game,a}=f;const source=await cast(f,'Elspeth Resplendent'),host=put(M,game,a,'Grizzly Bears');choose(a,q=>q.type==='chooseTargets',()=>[host]);choose(a,q=>q.prompt==='Choose the keyword counter',()=>keyword);const action=game.activatableList(a).find(r=>r.card===source&&r.ability.loyalty===1);assert.ok(action);assert.equal(await game.activateAbility(a,action),true);await settle(game);assert.equal(source.counters.loyalty,6);assert.equal(host.counters['+1/+1'],1);assert.equal(host.counters[keyword],1);assert.equal(host.kw(keyword),true);assertGameStateInvariants(game);}
  const f=context(M,role),{game,a}=f;const source=await cast(f,'Elspeth Resplendent'),good=witness(f,'Shielded three',['Creature'],'{3}'),bad=witness(f,'Four mana negative',['Creature'],'{4}');choose(a,q=>q.prompt==='Choose library cards for battlefield',q=>{assert.ok(q.from.includes(good));assert.equal(q.from.includes(bad),false);return [good];});let entry;const emit=game.emit;game.emit=async function(event,data,...args){if(event==='etb'&&data.card===good)entry=good.counters.shield;return emit.call(this,event,data,...args);};assert.equal(await game.activateAbility(a,game.activatableList(a).find(r=>r.card===source&&r.ability.loyalty===-3)),true);await settle(game);assert.equal(source.counters.loyalty,2);assert.equal(good.zone,'battlefield');assert.equal(entry,1);assertGameStateInvariants(game);
 });
 test(role+': Thassa wins with empty or short libraries and checks the printed devotion after its source leaves',async()=>{
  for(const [size,leave,won]of [[0,false,true],[2,false,true],[3,false,false],[1,true,false],[0,true,true]]){const f=context(M,role),{game,a,b}=f;clear(a);for(let i=0;i<size;i++)witness(f,'Oracle library '+i,['Land'],'');fund(a);const source=put(M,game,a,"Thassa's Oracle",'hand');assert.equal(await game.castSpell(a,source,{from:'hand'}),true);await game.resolveTop();if(leave)await game.move(source,'graveyard');await settle(game);assert.equal(game.gameOver,won);assert.equal(b.lost,won);assert.equal(a.library.length,size);assertGameStateInvariants(game);}
 });
 test(role+': Wild Magic Surge uses the destroyed permanent types and also reveals when it survives destruction',async()=>{
  for(const indestructible of [false,true]){const f=context(M,role),{game,a,b}=f;clear(b);const target=put(M,game,b,'Sol Ring');if(indestructible){target.def={...target.def,kws:['indestructible']};game.recalc();}const hit=put(M,game,b,'Sol Ring','library'),wrong=put(M,game,b,'Grizzly Bears','library');choose(a,q=>q.type==='chooseTargets',()=>[target]);await cast(f,'Wild Magic Surge');assert.equal(target.zone,indestructible?'battlefield':'graveyard');assert.equal(hit.zone,'battlefield');assert.ok(hit.ctrl===b);assert.equal(wrong.zone,'library');assertGameStateInvariants(game);}
 });
 test(role+': Random Encounter returns exact reanimated objects at the next end step and skips a later incarnation',async()=>{
  const f=context(M,role),{game,a,b}=f;clear(a);const creatures=[witness(f,'Random cohort one'),witness(f,'Random cohort two')];for(let i=0;i<2;i++)witness(f,'Random rest '+i,['Land'],'');await cast(f,'Random Encounter');assert.ok(creatures.every(c=>c.zone==='battlefield'));assert.ok(creatures.every(c=>c.kw('haste')));await game.move(creatures[0],'hand');await game.putPermanentOntoBattlefield(creatures[0],a);await game.emit('endStep',{player:b});await settle(game);assert.equal(creatures[0].zone,'battlefield');assert.equal(creatures[0].kw('haste'),false);assert.equal(creatures[1].zone,'hand');assertGameStateInvariants(game);
 });
}

for(const role of ['human','ai'])test(role+': Gishath inspects the actual combat damage amount and may put every revealed Dinosaur onto the battlefield',async()=>{for(const accept of [false,true]){const f=context(M,role);await proveGishathV25(M,f,accept);assertGameStateInvariants(f.game);}});

const extraReport=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v25-layouts-extra-runtime.json',import.meta.url),'utf8')).batches[0];const extraAbsent=extraReport.cards.filter(c=>!M.DEFS[c.raw.name]);if(extraAbsent.length){M.registerOracleBatch({...extraReport,cards:extraAbsent});M.initData(M.RAW_DATA);}
for(const role of ['human','ai'])test(role+': Ojer Kaslem chooses one creature and one land independently, returns transformed after dying, and pays its gated land activation',async()=>{for(const mode of ['none','creature','land','both','dual']){const f=context(M,role);await proveOjerKaslemV25(M,f,mode);assertGameStateInvariants(f.game);}});
