import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createFixturePlan,registerCanonicalFixturePlan} from './helpers/oracle-fixture-plan.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {names,proveCommonV73} from './helpers/oracle-v73-common-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v73-common.json',import.meta.url)));
const plan=createFixturePlan(rows,73,9973),M=loadEngine();registerCanonicalFixturePlan(M,plan);
test('v73 complete sources remain closed to unsupported text',()=>{for(const row of rows)assert.equal(plan.classify({...row,oracle_text:row.oracle_text+'\nPerform an unsupported action.'}).semanticClass,undefined,row.name);});
for(const role of ['human','ai'])for(const name of names)for(const positive of [true,false])test(`${role}: ${name} complete rules ${positive}`,()=>proveCommonV73(M,name,role,positive));
