import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{loadEngine}from'./helpers/load-engine.mjs';import{semanticClass}from'../scripts/import-oracle-batch.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
const rows=JSON.parse(readFileSync(new URL('./fixtures/oracle-state-trigger-source.json',import.meta.url))).map(card=>({card,result:semanticClass(card,{compilerVersion:8})})),M=loadEngine();
const cards=rows.map(({card:c,result},i)=>{const[type,subs='']=c.type_line.split(' — '),words=type.split(' ');return{position:i+1,oracleId:c.oracle_id,scryfallId:c.id,...result,raw:{name:c.name,cost:c.mana_cost,oracle:c.oracle_text,types:words.filter(w=>w!=='Legendary'),super:words.includes('Legendary')?['Legendary']:[],subtypes:subs.split(' ').filter(Boolean),power:c.power,toughness:c.toughness,_ci:c.color_identity},catalog:{typeLine:c.type_line,commanderLegality:'legal'}};});const missing=cards.filter(card=>!M.DEFS[card.raw.name]);if(missing.length){M.registerOracleBatch({id:'oracle-state-trigger-source',sequence:9995,cards:missing});M.initData(M.RAW_DATA);}
const fund=p=>{for(const k of['W','U','B','R','G','C'])p.pool[k]=30;};
async function cast(f,p,name,targets=[]){const source=put(M,f.game,p,name,'hand');fund(p);const before=Object.values(p.pool).reduce((a,b)=>a+b,0);assert.equal(await f.game.castSpell(p,source,{from:'hand',quickTargets:targets}),true);assert.ok(Object.values(p.pool).reduce((a,b)=>a+b,0)<before);return source;}
function healthy(f,name){
 if(name==='Opal Avenger'){f.a.life=12;return[];}if(name==='Lurking Jackals'){f.b.life=12;return[];}if(name==='Deadly Designs'){for(let n=0;n<2;n++)put(M,f.game,f.b,'Grizzly Bears');return[];}
 if(name==='Lurebound Scarecrow')return ['W','U','B','R','G'].map(color=>{const c=new M.CardInst({...M.DEFS['Sol Ring'],name:'Color witness '+color,cost:'{'+color+'}',triggers:[],mana:null},f.a);c.zone='battlefield';f.game.battlefield.push(c);f.game.recalc();return c;});
 const card=['Tethered Griffin'].includes(name)?'Glorious Anthem':['Synod Centurion','Covetous Dragon'].includes(name)?'Sol Ring':['Emperor Crocodile','Task Mage Assembly'].includes(name)?'Grizzly Bears':['Barbarian Outcast','Bog Serpent'].includes(name)?'Swamp':name==='Gorilla Pack'?'Forest':name==='Ronom Serpent'?'Snow-Covered Island':'Island';
 return[put(M,f.game,f.a,card)];
}
for(const role of['human','ai'])for(const {card:raw}of rows)test(`${role}: paid ${raw.name} watches the printed live state and resolves its own independent trigger`,async()=>{
 const f=context(M,role);for(const player of[f.a,f.b])if(!player.isAI){const decide=player.controller.decide.bind(player.controller);player.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:decide(g,q);}if(role==='human'){const prior=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=async(g,q)=>q.type==='chooseTargets'&&q.min===0?q.candidates.slice(0,q.max):prior(g,q);}
 const witnesses=healthy(f,raw.name),source=await cast(f,f.a,raw.name);await settle(f.game);assert.equal(source.zone,'battlefield');assert.equal(f.game.stack.length,0);
 if(raw.name==='Opal Avenger'||raw.name==='Lurking Jackals'){await cast(f,raw.name==='Opal Avenger'?f.b:f.a,'Shock',[raw.name==='Opal Avenger'?f.a:f.b]);await f.game.resolveTop();}
 else if(raw.name==='Deadly Designs'){fund(f.a);for(let n=0;n<5;n++){const entry=f.game.activatableList(f.a).find(row=>row.card===source&&row.ability);assert.ok(entry);assert.equal(await f.game.activateAbility(f.a,entry),true);await f.game.resolveTop();assert.equal(source.counters.plot,n+1);}}
 else {const witness=raw.name==='Lurebound Scarecrow'?witnesses.find(c=>c.colors.includes(source.meta.oracleChosenColor)):witnesses[0];assert.ok(witness);await cast(f,f.b,'Wipe Away',[witness]);await f.game.resolveTop();assert.equal(witness.zone,'hand');}
 assert.equal(source.zone,'battlefield','condition causes a trigger before any sacrifice or animation');assert.equal(f.game.stack.length,1);const trigger=f.game.stack[0];assert.equal(trigger.kind,'trigger');assert.equal(trigger.srcCard,source);const targets=trigger.targets.flat().filter(Boolean);await settle(f.game);
 if(raw.name==='Opal Avenger'||raw.name==='Lurking Jackals'){assert.equal(source.zone,'battlefield');assert.equal(source.is('Creature'),true);assert.equal(source.is('Enchantment'),false);assert.equal(source.power,3);assert.equal(source.toughness,raw.name==='Opal Avenger'?5:2);assert.equal(source.hasSub(raw.name==='Opal Avenger'?'Soldier':'Jackal'),true);}
 else {assert.equal(source.zone,'graveyard');if(raw.name==='Deadly Designs'){assert.ok(targets.length);for(const target of targets)assert.equal(target.zone,'graveyard');}}
});
test('unrecognized state qualities, unbound X and unsupported bodies remain closed',()=>{const card=rows.find(row=>row.card.name==='Emperor Crocodile').card;for(const oracle_text of['When you control no dreams, sacrifice this creature.','When you control no other creatures, you gain X life.','When you control no other creatures, become the monarch twice.'])assert.equal(semanticClass({...card,oracle_text},{compilerVersion:8}).semanticClass,undefined,oracle_text);});
for(const role of['human','ai']){
 test(`${role}: the original absence trigger still sacrifices after a supporting permanent returns`,async()=>{const f=context(M,role),land=put(M,f.game,f.a,'Island');const source=await cast(f,f.a,'Dandân');await settle(f.game);await f.game.move(land,'hand');await f.game.flushTriggers();assert.equal(f.game.stack.length,1);await f.game.move(land,'battlefield');await settle(f.game);assert.equal(source.zone,'graveyard','the state predicate is not an intervening-if resolution check');});
 test(`${role}: global creature absence waits for the opponent's last creature too`,async()=>{const f=context(M,role),own=put(M,f.game,f.a,'Grizzly Bears'),opponent=put(M,f.game,f.b,'Grizzly Bears');const source=await cast(f,f.a,'Task Mage Assembly');await settle(f.game);await f.game.move(own,'hand');await f.game.flushTriggers();assert.equal(f.game.stack.length,0);assert.equal(source.zone,'battlefield');await f.game.move(opponent,'hand');await f.game.flushTriggers();assert.equal(f.game.stack.length,1);await settle(f.game);assert.equal(source.zone,'graveyard');});
 test(`${role}: an opponent's Island never satisfies the source controller's Island condition`,async()=>{const f=context(M,role),own=put(M,f.game,f.a,'Island');put(M,f.game,f.b,'Island');const source=await cast(f,f.a,'Dandân');await settle(f.game);await f.game.move(own,'hand');await settle(f.game);assert.equal(source.zone,'graveyard');});
 test(`${role}: non-snow lands do not satisfy Ronom Serpent's snow-land state`,async()=>{const f=context(M,role),snow=put(M,f.game,f.a,'Snow-Covered Island');put(M,f.game,f.a,'Island');put(M,f.game,f.b,'Snow-Covered Island');const source=await cast(f,f.a,'Ronom Serpent');await settle(f.game);await f.game.move(snow,'hand');await settle(f.game);assert.equal(source.zone,'graveyard');});
 test(`${role}: source control changes bind each separate state trigger to its original controller`,async()=>{const f=context(M,role),source=await cast(f,f.a,'Emperor Crocodile');await f.game.resolveTop();assert.equal(f.game.stack.length,1);const first=f.game.stack[0];M.OracleV8Control.gain(f.game,source,f.b);f.game.recalc();assert.equal(first.ctrl,f.a);await f.game.resolveTop();assert.equal(source.zone,'battlefield');assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].ctrl,f.b);await settle(f.game);assert.equal(source.zone,'graveyard');});
}
for(const role of['human','ai'])test(`${role}: Stilt-Man's actual sacrifice prohibition creates a mandatory draw with Task Mage Assembly`,async()=>{
 const f=context(M,role),stilt=await cast(f,f.a,'Stilt-Man, Towering Terror');await settle(f.game);f.game.turnPlayer=f.b;const assembly=await cast(f,f.b,'Task Mage Assembly');await settle(f.game);f.game.turnPlayer=f.a;
 const emit=f.game.emit,stop=new Error('upkeep reached');f.game.emit=async function(name,data){if(name==='upkeep')throw stop;return emit.call(this,name,data);};try{await assert.rejects(f.game.runTurn(),error=>error===stop);}finally{f.game.emit=emit;}
 if(role==='human'){const decide=f.a.controller.decide.bind(f.a.controller);f.a.controller.decide=async(g,q)=>q.type==='attackers'?[{card:stilt,target:f.b}]:decide(g,q);}
 f.game.priorityRound=async()=>settle(f.game);await f.game.combatPhase(f.a);assert.equal(assembly.ctrl,f.a);assert.equal(assembly.cur.cantSacrifice,true);assert.ok(f.b.life<40);
 f.game.priorityRound=async()=>{};await cast(f,f.b,'Murder',[stilt]);await f.game.resolveTop();assert.equal(stilt.zone,'graveyard');assert.equal(f.game.stack.length,1);assert.equal(assembly.zone,'battlefield');await f.game.resolveTop();assert.equal(assembly.zone,'battlefield');assert.equal(f.game.gameOver,true);assert.equal(f.game.winner,null);assert.equal(f.game.drawReason,'mandatory-state-trigger-loop');
});
for(const role of['human','ai'])for(const response of['state becomes false','ability is disabled'])test(`${role}: a prohibited sacrifice is not a mandatory loop when the ${response}`,async()=>{
 const f=context(M,role),island=put(M,f.game,f.a,'Island'),source=await cast(f,f.a,'Dandân');await settle(f.game);await f.game.move(island,'hand');await f.game.flushTriggers();assert.equal(f.game.stack.length,1);
 f.game.untilEffects.push({apply:()=>{source.cur.cantSacrifice=true;if(response==='ability is disabled')source.cur.abilitiesDisabled=true;}});if(response==='state becomes false')await f.game.move(island,'battlefield');f.game.recalc();
 await f.game.resolveTop();assert.equal(source.zone,'battlefield');assert.equal(f.game.gameOver,false);assert.equal(f.game.stack.length,0);assert.equal(f.game.pendingTriggers.length,0);
});
