import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{loadEngine}from'./helpers/load-engine.mjs';import{semanticClass}from'../scripts/import-oracle-batch.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
const raw=JSON.parse(readFileSync(new URL('./fixtures/oracle-dark-depths-source.json',import.meta.url))),result=semanticClass(raw,{compilerVersion:8}),M=loadEngine();
assert.equal(result.semanticClass,'land-mana-template');if(!M.DEFS[raw.name]){M.registerOracleBatch({id:'oracle-dark-depths-source',sequence:9995,cards:[{position:1,oracleId:raw.oracle_id,scryfallId:raw.id,...result,raw:{name:raw.name,cost:raw.mana_cost,oracle:raw.oracle_text,types:['Land'],super:['Legendary','Snow'],subtypes:[],_ci:[]},catalog:{typeLine:raw.type_line,commanderLegality:'legal'}}]});M.initData(M.RAW_DATA);}
const fund=p=>{for(const k of['W','U','B','R','G','C'])p.pool[k]=30;},total=p=>Object.values(p.pool).reduce((s,n)=>s+n,0);
function game(role){const f=context(M,role);for(const p of f.game.players)if(!p.isAI){const prior=p.controller.decide.bind(p.controller);p.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.quickTarget?[q.quickTarget]:prior(g,q);}return f;}
async function cast(f,p,name,targets=[]){const c=put(M,f.game,p,name,'hand');fund(p);const before=total(p);assert.equal(await f.game.castSpell(p,c,{from:'hand',quickTargets:targets}),true);assert.ok(total(p)<before);return c;}
async function play(f){const source=put(M,f.game,f.a,'Dark Depths','hand'),before=f.a.landsPlayed;assert.equal(await f.game.playLand(f.a,source),true);assert.equal(f.a.landsPlayed,before+1);assert.equal(source.zone,'battlefield');assert.equal(source.counters.ice,10);assert.equal(f.game.stack.length,0);assert.equal(f.game.pendingTriggers.length,0);return source;}
async function remove(f,source){fund(f.a);const action=f.game.activatableList(f.a).find(row=>row.card===source&&row.ability);assert.ok(action);const before=total(f.a);assert.equal(await f.game.activateAbility(f.a,action),true);assert.equal(before-total(f.a),3);assert.equal(f.game.stack.at(-1).kind,'ability');}
async function awaken(f,source,n=10){for(let i=10;i>10-n;i--){await remove(f,source);await f.game.resolveTop();assert.equal(source.counters.ice||0,i-1);if(i>1)assert.equal(f.game.stack.length,0);}if(n===10){assert.equal(source.zone,'battlefield');assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].kind,'trigger');assert.equal(f.game.stack[0].srcCard,source);assert.ok(f.game.stack[0].oracleStateTrigger);assert.equal(f.game.bf().some(c=>c.isToken),false);}}
function token(f){const tokens=f.game.bf().filter(c=>c.isToken);assert.equal(tokens.length,1);const t=tokens[0];assert.equal(t.ctrl,f.a);assert.equal(t.name,'Marit Lage');assert.equal(t.power,20);assert.equal(t.toughness,20);assert.deepEqual([...t.colors],['B']);assert.deepEqual([...t.cur.super],['Legendary']);assert.equal(t.hasSub('Avatar'),true);assert.equal(t.kw('flying'),true);assert.equal(t.kw('indestructible'),true);}
for(const role of['human','ai']){
 test(`${role}: Dark Depths is legally played, pays thirty mana over ten activations, then creates its printed token after responses`,async()=>{const f=game(role),source=await play(f);await awaken(f,source);await settle(f.game);assert.equal(source.zone,'graveyard');token(f);});
 test(`${role}: Stifle on the last ice-removal activation leaves one counter and no state trigger`,async()=>{const f=game(role),source=await play(f);await awaken(f,source,9);await remove(f,source);await cast(f,f.b,'Stifle',[f.game.stack.at(-1)]);await settle(f.game);assert.equal(source.counters.ice,1);assert.equal(source.zone,'battlefield');assert.equal(f.game.bf().some(c=>c.isToken),false);});
 test(`${role}: Stifle answers Dark Depths' state trigger, which then triggers again because the same land still has no ice`,async()=>{const f=game(role),source=await play(f);await awaken(f,source);const first=f.game.stack[0];await cast(f,f.b,'Stifle',[first]);await f.game.resolveTop();assert.equal(f.game.stack.length,1);assert.notEqual(f.game.stack[0],first);assert.equal(source.zone,'battlefield');assert.equal(f.game.bf().some(c=>c.isToken),false);await settle(f.game);token(f);});
 test(`${role}: Wipe Away in response prevents Dark Depths' sacrifice and conditional token`,async()=>{const f=game(role),source=await play(f);await awaken(f,source);await cast(f,f.b,'Wipe Away',[source]);await settle(f.game);assert.equal(source.zone,'hand');assert.equal(f.game.bf().some(c=>c.isToken),false);});
 test(`${role}: Ghostly Flicker makes a new Dark Depths with ten ice, which the old state trigger cannot sacrifice`,async()=>{const f=game(role),island=put(M,f.game,f.a,'Island'),source=await play(f);await awaken(f,source);const old=source.zoneVersion,prior=f.a.controller.decide.bind(f.a.controller);if(role==='human')f.a.controller.decide=(g,q)=>q.type==='chooseTargets'&&q.max===2?[source,island]:prior(g,q);await cast(f,f.a,'Ghostly Flicker');await f.game.resolveTop();assert.ok(source.zoneVersion>old);assert.equal(source.counters.ice,10);await settle(f.game);assert.equal(source.zone,'battlefield');assert.equal(source.counters.ice,10);assert.equal(f.game.bf().some(c=>c.isToken),false);});
}
