import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createFixturePlan,registerCanonicalFixturePlan} from './helpers/oracle-fixture-plan.mjs';
import {loadEngine} from './helpers/load-engine.mjs';
import {context,settle} from './helpers/oracle-v8-fixtures.mjs';
import {fund,total,def,put} from './helpers/oracle-v30-permanents-proof.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('./fixtures/oracle-v74-static.json',import.meta.url))).filter(c=>['Winter, Misanthropic Guide','Reed Richards, Smartest Man'].includes(c.name));
const plan=createFixturePlan(rows,74,9979),M=loadEngine();registerCanonicalFixturePlan(M,plan);
function table(role){const f=context(M,role);for(const p of f.game.players)fund(p);f.game.spotlight=async()=>{};for(const name of ['Sol Ring','Llanowar Elves','Counterspell','Cultivate'])put(M,f.a,name,'graveyard');return f;}
async function cast(g,p,name){g.turnPlayer=p;g.phase='main1';const c=put(M,p,name,'hand'),mana=total(p);assert.equal(await g.castSpell(p,c,{from:'hand'}),true);assert.ok(total(p)<mana);await settle(g);return c;}
async function tower(g,p){g.turnPlayer=p;g.phase='main1';const c=put(M,p,'Reliquary Tower','hand');assert.equal(await g.playLand(p,c),true);return c;}
for(const role of ['human','ai']){
 test(`${role}: Winter, Tower, and Reed use timestamps of their battlefield objects`,async()=>{const {game:g,a,b}=table(role);const old=await tower(g,b),winter=await cast(g,a,'Winter, Misanthropic Guide');assert.equal(g.maximumHandSize(b),3);const reed=await cast(g,b,'Reed Richards, Smartest Man');assert.equal(g.maximumHandSize(b),Infinity);await g.move(reed,'graveyard');assert.equal(g.maximumHandSize(b),3);await g.move(old,'exile');await g.putPermanentOntoBattlefield(old,b);assert.equal(g.maximumHandSize(b),Infinity);await g.move(winter,'exile');await g.putPermanentOntoBattlefield(winter,a);assert.equal(g.maximumHandSize(b),3);});
 test(`${role}: Winter orders finite setters, modifiers, and lasting reductions`,async()=>{const {game:g,a,b}=table(role);const art=(name,extra)=>def(name,['Artifact'],{cost:'{1}',...extra});await cast(g,b,art('Earlier size six',{oracleHandSizeSetV21:{n:6}}));await cast(g,b,art('Earlier plus two',{oracleHandSizeRules:[{who:'you',n:2}]}));g.reduceMaximumHandSizeV64(b,1);await cast(g,a,'Winter, Misanthropic Guide');assert.equal(g.maximumHandSize(b),3,'earlier additions and reductions are overwritten');await cast(g,b,art('Later plus two',{oracleHandSizeRules:[{who:'you',n:2}]}));assert.equal(g.maximumHandSize(b),5);await cast(g,b,art('Later size ten',{oracleHandSizeSetV21:{n:10}}));assert.equal(g.maximumHandSize(b),10);g.reduceMaximumHandSizeV64(b,2);assert.equal(g.maximumHandSize(b),8);});
 test(`${role}: lasting and until effects retain creation timestamps around Winter`,async()=>{const {game:g,a,b}=table(role);await cast(g,b,"Praetor's Counsel");const winter=await cast(g,a,'Winter, Misanthropic Guide');assert.equal(g.maximumHandSize(b),3);const before=b.noMaxHandTimestampV74;await cast(g,b,"Praetor's Counsel");assert.ok(b.noMaxHandTimestampV74>before);assert.equal(g.maximumHandSize(b),Infinity);await g.move(winter,'exile');await g.putPermanentOntoBattlefield(winter,a);assert.equal(g.maximumHandSize(b),3);g.untilEffects.push({kind:'no-max-hand-v55',ctrl:b,expires:'yourNext'});assert.equal(g.maximumHandSize(b),Infinity);await g.move(winter,'exile');await g.putPermanentOntoBattlefield(winter,a);assert.equal(g.maximumHandSize(b),3,'later Winter overwrites older until-effect');g.grantNoMaximumHandSizeV74(b);assert.equal(g.maximumHandSize(b),Infinity);});
}
test('saved lasting hand-size effects retain timestamps and legacy saves use zero',async()=>{const {game:g,a,b}=table('human');await cast(g,b,"Praetor's Counsel");await cast(g,a,'Winter, Misanthropic Guide');g.reduceMaximumHandSizeV64(b,1);assert.equal(g.maximumHandSize(b),2);const snapshot=M.captureGameState(g);assert.ok(snapshot,JSON.stringify(M.gameStateSnapshotBlockers(g)));const fresh=context(M).game;M.restoreGameState(fresh,JSON.parse(JSON.stringify(snapshot)));assert.equal(fresh.maximumHandSize(fresh.players[1]),2);assert.equal(fresh.players[1].noMaxHandTimestampV74,b.noMaxHandTimestampV74);fresh.grantNoMaximumHandSizeV74(fresh.players[1]);assert.equal(fresh.maximumHandSize(fresh.players[1]),Infinity);const legacy=JSON.parse(JSON.stringify(snapshot));for(const p of legacy.players){delete p.noMaxHandTimestampV74;delete p.maximumHandSizeEffectsV74;}const old=context(M).game;M.restoreGameState(old,legacy);assert.equal(old.maximumHandSize(old.players[1]),3,'legacy effects precede timestamped Winter');});
