import test from'node:test';import assert from'node:assert/strict';
import{loadEngine}from'./helpers/load-engine.mjs';import{context,put,settle}from'./helpers/oracle-v8-fixtures.mjs';
const M=loadEngine(),fund=p=>{for(const k of['W','U','B','R','G','C'])p.pool[k]=30;};
async function cast(f,p,name,targets=[]){const c=put(M,f.game,p,name,'hand');fund(p);const before=Object.values(p.pool).reduce((a,b)=>a+b,0);assert.equal(await f.game.castSpell(p,c,{from:'hand',quickTargets:targets}),true);assert.ok(Object.values(p.pool).reduce((a,b)=>a+b,0)<before);return c;}
async function charged(role){const f=context(M,role),source=await cast(f,f.a,'Darksteel Reactor');await settle(f.game);source.counters.charge=18;const tapper=await cast(f,f.a,'Coretapper');await settle(f.game);const activation=f.game.activatableList(f.a).find(row=>row.card===tapper&&row.ability?.cost?.sacSelf);assert.ok(activation);assert.equal(await f.game.activateAbility(f.a,activation,[source]),true);assert.equal(tapper.zone,'graveyard');await f.game.resolveTop();assert.equal(source.counters.charge,20);assert.equal(f.game.gameOver,false);assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].kind,'trigger');return{...f,source};}
for(const role of['human','ai']){
 test(`${role}: externally paid twentieth counter makes an answerable Reactor trigger, then wins only on resolution`,async()=>{const f=await charged(role);f.game.recalc();await f.game.emit('upkeep',{player:f.b});assert.equal(f.game.pendingTriggers.length,0);assert.equal(f.game.stack.length,1);await f.game.resolveTop();assert.equal(f.game.gameOver,true);assert.equal(f.game.winner,f.a);});
 test(`${role}: actual Stifle counters Reactor, whose still-true condition immediately triggers again`,async()=>{const f=await charged(role),first=f.game.stack[0];await cast(f,f.b,'Stifle',[first]);await f.game.resolveTop();assert.equal(f.game.gameOver,false);assert.equal(f.game.stack.length,1);assert.notEqual(f.game.stack[0],first);assert.equal(f.game.stack[0].srcCard,f.source);assert.equal(f.game.pendingTriggers.length,0);});
 test(`${role}: bounce response plus Stifle answers Reactor permanently`,async()=>{const f=await charged(role),first=f.game.stack[0];await cast(f,f.b,'Into the Roil',[f.source]);await f.game.resolveTop();assert.equal(f.source.zone,'hand');assert.equal(f.game.gameOver,false);assert.equal(f.game.stack[0],first);await cast(f,f.b,'Stifle',[first]);await settle(f.game);assert.equal(f.game.gameOver,false);});
 test(`${role}: the Reactor ability is independent after its source leaves`,async()=>{const f=await charged(role);await cast(f,f.b,'Into the Roil',[f.source]);await f.game.resolveTop();assert.equal(f.source.zone,'hand');await f.game.resolveTop();assert.equal(f.game.winner,f.a);});
 test(`${role}: returning the physical Reactor permits a new incarnation while its old trigger is outstanding`,async()=>{const f=await charged(role),old=f.game.stack[0];await f.game.move(f.source,'exile');await f.game.move(f.source,'battlefield');f.game.addCounters(f.source,'charge',20);await f.game.flushTriggers();assert.equal(f.game.stack.length,2);assert.notEqual(f.game.stack[1].ctx.sourceZoneVersion,old.ctx.sourceZoneVersion);});
}
function witness(f,{type='Artifact',predicate,run,targets}={}){const c=new M.CardInst({...M.DEFS['Sol Ring'],name:'State lifecycle witness',types:[type],subtypes:[],power:'3',toughness:'3',triggers:[{on:'state',desc:'Observe state',stateTest:predicate,run,targets}]},f.a);c.zone='battlefield';f.game.battlefield.push(c);f.game.recalc();return c;}
test('temporary empty hand during a resolving instruction triggers, and later drawing does not erase it',async()=>{const f=context(M),hand=put(M,f.game,f.a,'Island','hand');let fired=0;witness(f,{predicate:(g,c)=>!c.ctrl.hand.length,run:async()=>fired++});await f.game.discard(f.a,[hand]);assert.equal(f.game.pendingTriggers.length,1);await f.game.draw(f.a,1);assert.equal(f.game.pendingTriggers.length,1);await settle(f.game);assert.equal(fired,1);});
test('a resolving state ability cannot trigger itself again midway, but retriggers when it finishes',async()=>{const f=context(M);let runs=0;const source=witness(f,{predicate:(g,c)=>(c.counters.charge||0)>=2,run:async ctx=>{runs++;ctx.g.recalc();await ctx.g.emit('upkeep',{player:f.b});assert.equal(ctx.g.pendingTriggers.length,0);if(runs===2)ctx.g.removeCounters(ctx.src,'charge',2);}});f.game.addCounters(source,'charge',2);await f.game.flushTriggers();await f.game.resolveTop();assert.equal(runs,1);assert.equal(f.game.stack.length,1);await settle(f.game);assert.equal(runs,2);});
test('simultaneous departure cannot observe a partially removed board or a departing source',async()=>{const f=context(M),other=put(M,f.game,f.a,'Grizzly Bears');let fired=0;const source=witness(f,{type:'Creature',predicate:(g,c)=>!g.creatures(c.ctrl).some(other=>other!==c),run:async()=>fired++});await f.game.destroyMany([other,source]);assert.equal(f.game.pendingTriggers.length,0);await settle(f.game);assert.equal(fired,0);});
test('simultaneous entrants do not create a false no-other-creatures state',async()=>{const f=context(M);const source=witness(f,{type:'Creature',predicate:(g,c)=>!g.creatures(c.ctrl).some(other=>other!==c),run:async()=>{}});f.game.pendingTriggers=[];await f.game.move(source,'hand');const bear=put(M,f.game,f.a,'Grizzly Bears','hand');await f.game.withBattlefieldEntryBatch(async()=>{await f.game.move(source,'battlefield');await f.game.move(bear,'battlefield');});assert.equal(f.game.pendingTriggers.length,0);});
test('a state made true by a completed simultaneous departure is captured before the next instruction',async()=>{const f=context(M),bear=put(M,f.game,f.a,'Grizzly Bears');let fired=0;witness(f,{predicate:(g,c)=>!g.creatures(c.ctrl).length,run:async()=>fired++});await f.game.destroyMany([bear]);assert.equal(f.game.pendingTriggers.length,1);await f.game.move(bear,'battlefield');await settle(f.game);assert.equal(fired,1);});
test('AI clones keep the outstanding ability identity and never create a duplicate trigger',async()=>{const f=await charged('ai'),clone=M.cloneGameForAISimulation(f.game,511);assert.equal(clone.stack.length,1);assert.equal(clone.pendingTriggers.length,0);const again=M.cloneGameForAISimulation(clone,512);assert.equal(again.stack.length,1);assert.equal(again.pendingTriggers.length,0);assert.equal(f.game.pendingTriggers.length,0);});
test('a controller change preserves the queued controller; only a later trigger belongs to the new one',async()=>{const f=await charged('human'),old=f.game.stack[0];M.OracleV8Control.gain(f.game,f.source,f.b);f.game.recalc();assert.equal(f.source.ctrl,f.b);assert.equal(f.game.stack[0].ctrl,f.a);await f.game.counterStackObject(old);await f.game.flushTriggers();assert.equal(f.game.stack.length,1);assert.equal(f.game.stack[0].ctrl,f.b);});
test('copying a state ability does not keep the original ability locked after the original is countered',async()=>{const f=await charged('human'),original=f.game.stack[0],copy=await f.game.copyStackAbility(original,f.a);assert.equal(copy.oracleStateTrigger,undefined);await f.game.counterStackObject(original);assert.equal(f.game.pendingTriggers.length,1);await f.game.flushTriggers();assert.equal(f.game.stack.length,2);assert.ok(f.game.stack.includes(copy));});
test('native trigger doublers apply once to a state-triggered creature ability',async()=>{const f=context(M);put(M,f.game,f.a,'Harmonic Prodigy');let fired=0;const source=witness(f,{type:'Creature',predicate:(g,c)=>(c.counters.charge||0)>=2,run:async ctx=>{fired++;ctx.g.removeCounters(ctx.src,'charge',2);}});source.def.subtypes=['Wizard'];f.game.addCounters(source,'charge',2);assert.equal(f.game.pendingTriggers.length,2);await settle(f.game);assert.equal(fired,2);});
test('a leaving type-changing source cannot create a false state using stale derived types',async()=>{const f=context(M),bear=put(M,f.game,f.a,'Grizzly Bears');const suppressor=new M.CardInst({...M.DEFS['Grizzly Bears'],name:'Type-changing source',statics:[{phase:1,apply:(_g,self,bf)=>{for(const c of bf)if(c===bear)c.cur.types=['Artifact'];}}]},f.a);suppressor.zone='battlefield';f.game.battlefield.push(suppressor);f.game.recalc();let fired=0;witness(f,{predicate:(g,c)=>!g.creatures(c.ctrl).length,run:async()=>fired++});assert.equal(bear.is('Creature'),false);await f.game.move(suppressor,'exile');assert.equal(bear.is('Creature'),true);assert.equal(f.game.pendingTriggers.length,0);await settle(f.game);assert.equal(fired,0);});
test('a discard replacement with no graveyard entries still exposes a temporarily empty hand',async()=>{const f=context(M),card=put(M,f.game,f.a,'Forest','hand');card.def={...card.def,madness:'{R}'};let fired=0;witness(f,{predicate:(g,c)=>!c.ctrl.hand.length,run:async()=>fired++});await f.game.discard(f.a,[card]);assert.equal(card.zone,'exile');assert.equal(f.game.pendingTriggers.filter(row=>row.oracleStateTrigger).length,1);await f.game.draw(f.a,1);await settle(f.game);assert.equal(fired,1);});
