import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {loadEngine} from './helpers/load-engine.mjs';
import {buildIntake,sourceDir,precons} from '../scripts/import-voc-ncc-precons.mjs';
const M=loadEngine(),intake=JSON.parse(fs.readFileSync(sourceDir+'/intake.json')),i=buildIntake(M);
test('ten original lists retain all 1000 cards and reuse 490 of 655 unique definitions',()=>{assert.equal(i.decks.length,10);assert.equal(i.names.length,655);assert.equal(i.newNames.length,0);assert.equal(intake.newCards,165);assert.equal(intake.reusedCards,490);for(const d of i.decks){assert.deepEqual(JSON.parse(JSON.stringify(M.DECKS[d.name].cards)),d.cards);assert.equal(d.cards.reduce((n,c)=>n+c.n,0),100);}});
test('original Upgrades Unleashed retains its two Mossfire Valleys and explains the printed exception',()=>{const d=M.DECKS['Upgrades Unleashed'];assert.equal(d.cards.find(c=>c.name==='Mossfire Valley').n,2);assert.match(M.DECK_GUIDES[d.name].tip,/two Mossfire Valley/);});
test('Heads I Win defaults to both printed partners across selection, AI and game creation',()=>{const d=M.DECKS['Heads I Win, Tails You Lose'],expected=['Zndrsplt, Eye of Wisdom','Okaun, Eye of Chaos'];assert.deepEqual(Array.from(M.defaultCommanders(d)),expected);assert.ok(M.validateCommanders(d,expected).ok);const g=M.newGame({humanDeck:d.name,aiDecks:['Buckle Up'],paced:false,seed:11165});const p=g.players.find(p=>p.deckName===d.name);assert.deepEqual(Array.from(p.commanders,c=>c.name),expected);assert.equal(p.library.length+p.hand.length+p.command.length,100);});
test('all additions have native scripts, all decks have list-specific guides, and both partners have art',()=>{for(const n of intake.newNames){assert.ok(M.SCRIPTS[n],n);assert.equal(!!M.DEFS[n].autoScripted,false,n);assert.equal(!!M.DEFS[n].simplified,false,n);}for(const d of precons){assert.ok(M.DECK_META[d.name]&&M.DECK_GUIDES[d.name]);for(const n of M.DECK_GUIDES[d.name].keys)assert.ok(M.DECKS[d.name].cards.some(c=>c.name===n),d.name+': '+n);for(const n of [d.commander,d.partner].filter(Boolean))assert.ok(fs.existsSync(M.CARD_ART_PATHS[n]),n);}});
test('cold landing summary matches the live eligible catalog and selectable deck count',()=>{assert.equal(M.CATALOG_SUMMARY.decks,100);assert.equal(M.CATALOG_SUMMARY.decks,Object.keys(M.DECKS).length);assert.equal(M.CATALOG_SUMMARY.importableCards,Object.values(M.CARD_CATALOG).filter(c=>c.deckImportEligible).length);});
