import test from 'node:test';import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,settle,fuel,mana} from './helpers/voc-ncc-fixtures.mjs';
for(const role of ['human','ai']){
 test(role+': Mogg Assassin delegates the second actual target to the first target’s controller',async()=>{const f=setup(role),m=await play(f,'Mogg Assassin'),a=body(f),b=body(f,f.b);m.sick=false;const seats=[];f.game.rnd=()=>0;f.decide=(p,q)=>{if(q.type==='chooseTargets'){seats.push(p);return[p===f.a?b:a];}if(q.type==='chooseOption'&&q.options.some(o=>o.key==='heads'))return 'heads';};await activate(f,m);assert.deepEqual(seats,[f.a,f.b]);assert.equal(b.zone,'graveyard');assert.equal(a.zone,'battlefield');});
 test(role+': Frenetic Sliver returns the same exiled card only at the next end step',async()=>{const f=setup(role),s=await play(f,'Frenetic Sliver');f.game.rnd=()=>0;f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='heads')?'heads':undefined;await activate(f,s,e=>e.ability.label.startsWith('Flip:'));assert.equal(s.zone,'exile');await event(f,'endStep',{player:f.b});assert.equal(s.zone,'battlefield');assert.equal(s.ctrl,f.a);});
 test(role+': Impulsive Maneuvers doubles the whole next simultaneous combat event only',async()=>{const f=setup(role),m=await play(f,'Impulsive Maneuvers'),a=body(f),b=card(f,'Colossal Dreadmaw','battlefield',f.b);f.game.rnd=()=>0;f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='heads')?'heads':undefined;a.attacking=f.b;await event(f,'attacks',{card:a,player:f.a});const life=f.b.life;await f.game.damageBatch([{src:a,target:f.b,n:1},{src:a,target:b,n:1}],{combat:true});assert.equal(f.b.life,life-2);assert.equal(b.damage,2);await f.game.damagePlayer(a,f.b,1,{combat:true});assert.equal(f.b.life,life-3);});
 test(role+': Risky Move detects a control change and its lost flip gives away a creature',async()=>{const f=setup(role),r=await play(f,'Risky Move'),b=body(f,f.b);f.game.rnd=()=>0.9;f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='heads')?'heads':q.type==='chooseCards'&&q.prompt.startsWith('Risky Move')?[b]:undefined;await event(f,'upkeep',{player:f.b});assert.equal(r.ctrl,f.b);assert.notEqual(b.ctrl,f.b);});
 test(role+': Donal copies a flying spell as a 1/1 Spirit only once when accepted',async()=>{const f=setup(role);await play(f,'Donal, Herald of Wings');f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await play(f,'Vampire Nighthawk');const tokens=()=>f.game.creatures(f.a).filter(c=>c.isToken);assert.equal(tokens().length,1);assert.equal(tokens()[0].power,1);assert.equal(tokens()[0].toughness,1);assert.ok(tokens()[0].hasSub('Spirit'));await play(f,'Vampire Nighthawk');assert.equal(tokens().length,1);});
 test(role+': Parnesse triggers for a player target and counters after refusal to pay life',async()=>{const f=setup(role);await play(f,'Parnesse, the Subtle Brush');const bolt=card(f,'Lightning Bolt','hand',f.b);fuel(f.b);f.decide=(p,q)=>q.type==='chooseTargets'?[f.a]:q.type==='chooseOption'&&q.prompt.includes('Parnesse')?'no':undefined;const life=f.a.life;assert.equal(await f.game.castSpell(f.b,bolt,{from:'hand'}),true);await settle(f.game);assert.equal(f.a.life,life);assert.equal(bolt.zone,'graveyard');});
 test(role+': Falkenrath Gorger supplies madness even when the discarded card has no printed madness',async()=>{const f=setup(role);await play(f,'Falkenrath Gorger');const c=card(f,'Vampire Nighthawk','hand');fuel(f.a);const before=mana(f.a);f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await f.game.discard(f.a,[c]);await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(before-mana(f.a),3);});
 test(role+': Shadowgrange’s madness pays its eight life as well as three mana',async()=>{const f=setup(role),c=card(f,'Shadowgrange Archfiend','hand');fuel(f.a);const before=mana(f.a),life=f.a.life;f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await f.game.discard(f.a,[c]);await settle(f.game);assert.equal(c.zone,'battlefield');assert.equal(before-mana(f.a),3);assert.equal(f.a.life,life-8);});
 test(role+': Skyway Robber links only cards paid for its escape',async()=>{const f=setup(role),c=card(f,'Skyway Robber','graveyard'),spell=card(f,'Opt','graveyard');for(let i=0;i<4;i++)card(f,'Forest','graveyard');fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c&&r.alt?.escape);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:offer.alt}),true);await settle(f.game);assert.equal(spell.zone,'exile');assert.equal(M.VN.linked(M.VN.linkState(c,'vnSkyway')).length,5);f.decide=(p,q)=>q.type==='chooseCards'&&q.from.includes(spell)?[spell]:undefined;await event(f,'damageToPlayer',{src:c,player:f.b,combat:true,n:3});assert.equal(spell.zone,'graveyard');});
 test(role+': Skyclave Shade’s landfall permission permits a genuinely paid kicker',async()=>{const f=setup(role),c=card(f,'Skyclave Shade','graveyard'),land=card(f,'Forest','hand');await f.game.playLand(f.a,land);await settle(f.game);fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.startsWith('Kicker')?'yes':undefined;assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:offer.alt}),true);await settle(f.game);assert.equal(c.counters['+1/+1'],2);assert.equal(c.castMeta.manaSpent,5);assert.ok(c.cur.cantBlock);});
 test(role+': The Beamtown Bullies gives the active opponent a creature and exiles the same object later',async()=>{const f=setup(role),b=await play(f,'The Beamtown Bullies'),c=card(f,'Colossal Dreadmaw','graveyard');f.game.turnPlayer=f.b;f.decide=(p,q)=>q.type==='chooseTargets'?[q.candidates.includes(f.b)?f.b:c]:undefined;await activate(f,b);assert.equal(c.ctrl,f.b);assert.ok(c.kw('haste'));await event(f,'endStep',{player:f.b});assert.equal(c.zone,'exile');});
 test(role+': Timothar’s Bat returns its linked Vampire after combat damage',async()=>{const f=setup(role);await play(f,'Timothar, Baron of Bats');const c=card(f,'Vampire Nighthawk');fuel(f.a);f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await f.game.destroy(c);await settle(f.game);assert.equal(c.zone,'exile');const bat=f.game.creatures(f.a).find(c=>c.isToken&&c.hasSub('Bat'));assert.ok(bat);await event(f,'damageToPlayer',{src:bat,player:f.b,combat:true,n:1});assert.equal(c.zone,'battlefield');assert.ok(c.tapped);assert.notEqual(bat.zone,'battlefield');});
 test(role+': One with the Kami uses the modified dead creature’s last power',async()=>{const f=setup(role),host=body(f),other=body(f);f.decide=(p,q)=>q.type==='chooseTargets'?[host]:undefined;await play(f,'One with the Kami');f.game.addCounters(other,'+1/+1',2);await f.game.destroy(other);await settle(f.game);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Spirit')).length,4);});
 test(role+': Concord can choose all three modes while announcing only the counter target',async()=>{const f=setup(role),h=body(f);f.game.addCounters(h,'+1/+1',1);f.decide=(p,q)=>q.type==='chooseTargets'?[h]:undefined;const eq=await play(f,'Swiftfoot Boots');f.game.attach(eq,h);await play(f,'Rancor');await play(f,'Concord with the Kami');f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt.includes('choose one or more')?'7':q.type==='chooseTargets'?[h]:undefined;const hand=f.a.hand.length;await event(f,'endStep',{player:f.a});assert.equal(h.counters['+1/+1'],2);assert.equal(f.a.hand.length,hand+1);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken).length,1);});
 test(role+': Dance of the Manse at six returns selected noncreature artifacts as 4/4 creatures',async()=>{const f=setup(role),c=card(f,'Sol Ring','graveyard');f.decide=(p,q)=>q.type==='chooseTargets'?[c]:undefined;await play(f,'Dance of the Manse',{xVal:6});assert.equal(c.zone,'battlefield');assert.ok(c.is('Artifact')&&c.is('Creature'));assert.equal(c.power,4);assert.equal(c.toughness,4);});
 test(role+': Wandering Fumarole switches after subsequent power bonuses',async()=>{const f=setup(role),c=card(f,'Wandering Fumarole');await activate(f,c);assert.equal(c.power,1);assert.equal(c.toughness,4);await activate(f,c,e=>e.ability.label.startsWith('Switch'));M.E.pumpUntilEOT(f.game,c,2,0);f.game.recalc();assert.equal(c.power,4);assert.equal(c.toughness,3);});
}
