import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,settle,fuel,mana} from './helpers/c21-fixtures.mjs';
import {assertGameStateInvariants,assertRecalculationStable} from './helpers/game-state-invariants.mjs';
const ctx=(f,c)=>({g:f.game,you:f.a,src:c,sourceMeta:c.meta,sourceZoneVersion:c.zoneVersion});
for(const role of ['human','ai']){
 test(`${role}: The Five Doctors shows and pays kicker, returns Doctors together, and may search only the graveyard`,async()=>{
  for(const mode of ['kicked','ordinary','unaffordable','free','graveyard']){
   const f=setup(role),grave=card(f,'The Tenth Doctor','graveyard'),library=card(f,'The Eleventh Doctor','library'),spell=card(f,'The Five Doctors','hand'),prompts=[];
   for(const key of Object.keys(f.a.pool))f.a.pool[key]=0;
   f.a.pool.G=mode==='free'?0:1;f.a.pool.C=mode==='unaffordable'||mode==='free'?5:10;
   f.decide=(p,q)=>{if(q.prompt)prompts.push(q.prompt);if(q.type==='chooseOption'&&q.prompt.includes('Kicker'))return mode==='ordinary'?'no':'yes';if(q.type==='chooseOption'&&q.prompt.includes('Search your library'))return mode==='graveyard'?'no':'yes';if(q.type==='chooseCards')return q.from.filter(c=>c===grave||c===library);};
   assert.equal(await f.game.castSpell(f.a,spell,{from:'hand',...(mode==='free'?{free:true}:{})}),true);
   const kicked=!['ordinary','unaffordable'].includes(mode);assert.equal(spell.castMeta.kicked,kicked);
   assert.equal(spell.castMeta.manaSpent,mode==='free'?5:kicked?11:6);
   await settle(f.game);assert.equal(grave.zone,kicked?'battlefield':'hand');assert.equal(library.zone,mode==='graveyard'?'library':kicked?'battlefield':'hand');
   assert.equal(prompts.some(p=>/undefined|NaN|\[object/.test(p)),false);if(mode!=='unaffordable')assert.ok(prompts.some(p=>p.includes('Kicker {5}')));
   if(mode==='graveyard')assert.equal(prompts.some(p=>p.includes('The Five Doctors: search your library')),false);
   assertGameStateInvariants(f.game);
  }
 });
 test(`${role}: Ashad casualty copies only the first nonlegendary artifact and pays a creature`,async()=>{const f=setup(role),a=card(f,'Ashad, the Lone Cyberman'),b=body(f);f.decide=(p,q)=>q.type==='chooseOption'&&q.prompt?.includes('Casualty')?'yes':q.type==='chooseCards'&&q.prompt?.includes('Casualty')?[b]:undefined;await play(f,'Sol Ring');assert.equal(b.zone,'graveyard');assert.equal(a.counters['+1/+1'],1);assert.equal(f.game.bf().filter(c=>c.name==='Sol Ring').length,2);await play(f,'Arcane Signet');assert.equal(f.game.bf().filter(c=>c.name==='Arcane Signet').length,1);});
 test(`${role}: Exterminate replicate taps real Daleks and creates paid copies`,async()=>{const f=setup(role),source=body(f),[dalek]=await f.game.makeTokens(M.WLM.dalek,f.a),a=body(f,f.b),b=body(f,f.b);f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('tap Daleks')?[dalek]:q.type==='chooseTargets'&&q.candidates.includes(a)?[a]:undefined;const spell=card(f,'Exterminate!','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,spell,{from:'hand'}),true);assert.ok(dalek.tapped);assert.ok(f.game.stack.some(s=>/replicate/.test(s.name)));await settle(f.game);assert.equal(a.zone,'graveyard');assert.equal(b.zone,'battlefield');assert.ok(source);});
 test(`${role}: Ian pays a Saga's full colored replicate cost`,async()=>{const f=setup(role);card(f,'Ian Chesterton');f.decide=(p,q)=>q.type==='chooseX'&&q.prompt.includes('Ian Chesterton')?1:undefined;const c=await play(f,'An Unearthly Child');assert.equal(c.castMeta.manaSpent,6);assert.equal(f.game.bf().filter(c=>c.name==='An Unearthly Child').length,2);});
 test(`${role}: Peri grants convoke to the first historic spell`,()=>{const f=setup(role);card(f,'Peri Brown');const c=card(f,'Sol Ring','hand');assert.ok(M.CDK.convoke(f.game,f.a,c,{}));f.a.turnState.wlmHistoric=1;assert.ok(!M.CDK.convoke(f.game,f.a,c,{}));});
 test(`${role}: Twelfth Doctor demonstrate is granted only to the first outside-hand spell`,async()=>{const f=setup(role),d=card(f,'The Twelfth Doctor'),c=card(f,'Sol Ring','exile');M.WLM.playGrant(ctx(f,d),c);fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.equal(await f.game.castSpell(f.a,c,{from:'exile',alt:offer.alt}),true);assert.equal(f.game.stack.filter(s=>/Demonstrate/.test(s.name)).length,1);await settle(f.game);const next=card(f,'Arcane Signet','exile');M.WLM.playGrant(ctx(f,d),next);const row=f.game.castableList(f.a).find(r=>r.card===next);assert.equal(await f.game.castSpell(f.a,next,{from:'exile',alt:row.alt}),true);assert.equal(f.game.stack.filter(s=>/Demonstrate/.test(s.name)).length,0);});
 test(`${role}: Return the Past grants flashback only during your turn and exiles the spell`,async()=>{const f=setup(role);card(f,'Return the Past');const c=card(f,'Divination','graveyard');fuel(f.a);const row=f.game.castableList(f.a).find(r=>r.card===c&&r.alt.wlmKind==='past');assert.ok(row);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:row.alt}),true);await settle(f.game);assert.equal(c.zone,'exile');});
 test(`${role}: Mission Briefing permits exactly the selected graveyard object for this turn`,async()=>{const f=setup(role),c=card(f,'Divination','graveyard');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.includes('Choose a spell')?[c]:undefined;await play(f,'Mission Briefing');fuel(f.a);const r=f.game.castableList(f.a).find(r=>r.card===c&&r.alt.wlmKind==='grant');assert.ok(r);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:r.alt}),true);await f.game.counterStackObject(f.game.stack.find(s=>s.card===c));assert.equal(c.zone,'exile');});
 test(`${role}: Eye offers surveilled lands and spells but cannot pay life below zero`,async()=>{const f=setup(role);card(f,'Eye of Duskmantle');const c=card(f,'Divination','library'),l=card(f,'Island','library');f.decide=(p,q)=>q.type==='scry'?{top:[],bottom:q.cards}:undefined;await M.E.surveil(f.game,f.a,2);assert.equal(c.zone,'graveyard');assert.ok(f.game.playableLands(f.a).includes(l));const r=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(r);assert.equal(r.alt.lifeCost,3);f.a.life=2;assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:r.alt}),false);});
 test(`${role}: don't blink replaces direct exile entries and cast-from-exile creatures`,async()=>{const f=setup(role),c=card(f,'Grizzly Bears','exile');await play(f,"Don't Blink");await f.game.putPermanentOntoBattlefield(c,f.a);assert.equal(c.zone,'library');const d=card(f,'Grizzly Bears','exile');M.WLM.playGrant(ctx(f,card(f,'Yasmin Khan')),d);fuel(f.a);const r=f.game.castableList(f.a).find(r=>r.card===d);assert.equal(await f.game.castSpell(f.a,d,{from:'exile',alt:r.alt}),true);await settle(f.game);assert.equal(d.zone,'library');});
 test(`${role}: Diary imprints a resolved spell and ignores countered spells`,async()=>{const f=setup(role),d=card(f,"River Song's Diary"),c=await play(f,'Divination');assert.equal(c.zone,'exile');assert.ok(d.meta.wlmExiled.some(r=>r.iid===c.iid));const b=card(f,'Divination','hand');fuel(f.a);await f.game.castSpell(f.a,b,{from:'hand'});await f.game.counterStackObject(f.game.stack.find(s=>s.card===b));await settle(f.game);assert.equal(b.zone,'graveyard');});
 test(`${role}: The Master, Multiplied protects tokens from your triggered exile, not spells`,async()=>{const f=setup(role),m=card(f,'The Master, Multiplied'),[t]=await f.game.makeTokens(M.WLM.snapshotCopy(m),f.a);await f.game.checkSBA();assert.equal(t.zone,'battlefield');f.game.queueTrigger({src:m,ctrl:f.a,name:'Test delayed exile',data:{target:t},run:ctx=>ctx.g.move(ctx.data.target,'exile')});await settle(f.game);assert.equal(t.zone,'battlefield');await f.game.move(t,'exile');assert.notEqual(t.zone,'battlefield');});
 test(`${role}: Zygon copy ends on untap and does not retain copied abilities`,async()=>{const f=setup(role),z=card(f,'Zygon Infiltrator'),c=body(f,f.b);await activate(f,z);assert.equal(z.name,'Grizzly Bears');assert.equal(c.counters.stun,1);f.game.untap(c);assert.equal(z.name,'Grizzly Bears');f.game.untap(c);assert.equal(z.name,'Zygon Infiltrator');});
 test(`${role}: Sound of Drums doubles combat damage but not noncombat damage`,async()=>{const f=setup(role),c=body(f),d=card(f,'The Sound of Drums');await f.game.attach(d,c);const n=f.b.life;await f.game.damageAny(c,f.b,2,{combat:true});assert.equal(f.b.life,n-4);await f.game.damageAny(c,f.b,2);assert.equal(f.b.life,n-6);});
 test(`${role}: Weeping Angel prevents damage and shuffles a blocking creature`,async()=>{const f=setup(role),a=card(f,'Weeping Angel'),b=body(f,f.b);await f.game.damageAny(a,b,2,{combat:true});assert.equal(b.zone,'library');assert.equal(b.damage,0);});
 test(`${role}: afflict and mentor use real combat events`,async()=>{const f=setup(role),c=card(f,'Neheb, the Eternal'),d=card(f,'Danny Pink'),b=body(f);c.attacking=d.attacking=b.attacking=f.b;const n=f.b.life;await event(f,'becomesBlocked',{attacker:c,blockers:[]});assert.equal(f.b.life,n-3);await event(f,'attacks',{card:d,player:f.a,defender:f.b});assert.equal(b.counters['+1/+1'],1);});
 test(`${role}: Carpet of Flowers is available in either main but only produces mana once`,async()=>{const f=setup(role);card(f,'Carpet of Flowers');card(f,'Island','battlefield',f.b);f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key==='yes')?'yes':undefined;await event(f,'mainPhase',{player:f.a});assert.equal(mana(f.a),1);await event(f,'mainPhase',{player:f.a});assert.equal(mana(f.a),1);});
 test(`${role}: Rin and Seri respond to cast Cats and Dogs, not token creation`,async()=>{const f=setup(role);card(f,'Rin and Seri, Inseparable');await play(f,'Feline Sovereign');assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Dog')).length,1);await f.game.makeTokens(M.WLM.token('Cat',['Cat'],2,2,['G']),f.a);await settle(f.game);assert.equal(f.game.creatures(f.a).filter(c=>c.isToken&&c.hasSub('Dog')).length,1);});
 test(`${role}: Regal Behemoth's mana trigger is included in automatic payment`,async()=>{const f=setup(role);card(f,'Regal Behemoth');card(f,'Forest');await f.game.becomeMonarch(f.a);const c=card(f,'Arcane Signet','hand');assert.ok(f.game.castableList(f.a).some(r=>r.card===c));assert.equal(await f.game.castSpell(f.a,c,{from:'hand'}),true);await settle(f.game);assert.equal(c.zone,'battlefield');});
 test(`${role}: Twice Upon a Time requires two Doctors; its blue Adventure does not`,async()=>{const f=setup(role),c=card(f,'Twice Upon a Time','hand');fuel(f.a);assert.equal(await f.game.castSpell(f.a,c,{from:'hand'}),false);const r=f.game.castableList(f.a).find(r=>r.card===c&&r.alt?.adventure);assert.ok(r);assert.equal(await f.game.castSpell(f.a,c,{from:'hand',alt:r.alt}),true);await settle(f.game);assert.equal(c.castMeta.manaSpent,3);assert.equal(c.zone,'exile');});
 test(`${role}: recalculation preserves the new continuous effects without accumulating bonuses`,async()=>{const f=setup(role);card(f,'Xenagos, God of Revels');card(f,'Danny Pink');card(f,'Dan Lewis');card(f,'Gemcutter Buccaneer');card(f,'Clara Oswald');card(f,'Cybermen Squadron');card(f,'Sol Ring');assertRecalculationStable(f.game);assertGameStateInvariants(f.game);});
}
