import test from 'node:test';
import assert from 'node:assert/strict';
import {M,setup,card,body,play,activate,event,settle,fuel,mana} from './helpers/c21-fixtures.mjs';

const ctx=(f,c)=>({g:f.game,you:f.a,src:c,sourceMeta:c.meta,sourceZoneVersion:c.zoneVersion});
const count=(f,name)=>f.game.bf().filter(c=>c.name.replace(/ Token$/,'')===name).length;
const option=(f,key)=>{f.decide=(p,q)=>q.type==='chooseOption'&&q.options.some(o=>o.key===key)?key:undefined;};
for(const role of ['human','ai']){
 test(`${role}: Paradox counts command/exile casts, excludes hand and copies`,async()=>{
  const f=setup(role),d=card(f,'The Thirteenth Doctor');body(f);const c=card(f,'Sol Ring','exile');M.WLM.playGrant(ctx(f,d),c,{turn:f.game.turnNo});fuel(f.a);
  const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'exile',alt:offer.alt}),true);await settle(f.game);assert.equal(f.a.turnState.wlmParadox,1);assert.equal(f.game.creatures(f.a).reduce((n,c)=>n+(c.counters['+1/+1']||0),0),1);
  await play(f,'Arcane Signet');assert.equal(f.a.turnState.wlmParadox,1);
 });
 test(`${role}: Yasmin permission expires at the next own end step`,async()=>{const f=setup(role),d=card(f,'Yasmin Khan'),c=card(f,'Sol Ring','library');await activate(f,d);assert.ok(f.game.castableList(f.a).some(r=>r.card===c));await event(f,'endStep',{player:f.b});assert.ok(f.game.castableList(f.a).some(r=>r.card===c));await event(f,'endStep',{player:f.a});assert.ok(!f.game.castableList(f.a).some(r=>r.card===c));});
 test(`${role}: Davros checks opponents' aggregate life loss and repeats villainous choices`,async()=>{const f=setup(role);card(f,'Davros, Dalek Creator');card(f,'The Valeyard');f.b.turnState.lifeLost=3;option(f,'draw');const n=f.a.hand.length;await event(f,'endStep',{player:f.a});assert.equal(count(f,'Dalek'),1);assert.equal(f.a.hand.length,n+2);});
 test(`${role}: Pantlaza discovers once only after accepting and resets next turn`,async()=>{const f=setup(role);option(f,'yes');card(f,'Pantlaza, Sun-Favored');card(f,'Sol Ring','library');await play(f,'Dinosaur Egg');assert.equal(f.a.turnState.wlmParadox||0,1);await play(f,'Ripjaw Raptor');assert.equal(f.a.turnState.wlmParadox||0,1);});
 test(`${role}: Hakbal explores every Merfolk and Topography repeats exploration`,async()=>{const f=setup(role),h=card(f,'Hakbal of the Surging Soul');card(f,'Topography Tracker');card(f,'Emperor Mihail II');const n=f.a.hand.length;await event(f,'beginCombat',{player:f.a});assert.equal(f.a.hand.length,n+6);assert.equal(h.counters['+1/+1']||0,0);});
 test(`${role}: Clavileño blessing survives its source and triggers on death`,async()=>{const f=setup(role),c=card(f,'Clavileño, First of the Blessed'),v=card(f,'Dusk Legion Zealot');v.attacking=f.b;await event(f,'attackersDeclared',{player:f.a,attackers:[v]});assert.ok(v.hasSub('Demon'));await f.game.move(c,'exile');const n=f.a.hand.length;await f.game.destroy(v);await settle(f.game);assert.equal(f.a.hand.length,n+1);assert.equal(count(f,'Vampire Demon'),1);assert.ok(f.game.bf().find(c=>c.name.replace(/ Token$/,'')==='Vampire Demon').tapped);});
 test(`${role}: Admiral Brass returns a 4/4 Pirate with haste and finality`,async()=>{const f=setup(role);card(f,'Admiral Brass, Unsinkable');const c=card(f,'Storm Fleet Negotiator','graveyard');option(f,'yes');await event(f,'beginCombat',{player:f.a});assert.equal(c.zone,'battlefield');assert.equal(c.power,4);assert.equal(c.toughness,4);assert.ok(c.kw('haste'));assert.equal(c.counters.finality,1);await f.game.destroy(c);await settle(f.game);assert.equal(c.zone,'exile');});
 test(`${role}: Mirko surveils, grows and reanimates a strictly smaller creature`,async()=>{const f=setup(role),m=card(f,'Mirko, Obsessive Theorist'),b=card(f,'Llanowar Elves','graveyard');await M.E.surveil(f.game,f.a,1);await settle(f.game);assert.equal(m.counters['+1/+1'],1);option(f,'yes');await event(f,'endStep',{player:f.a});assert.equal(b.zone,'battlefield');assert.equal(b.counters.finality,1);});
 test(`${role}: Kaust turns an attacking creature face up and draws on damage`,async()=>{const f=setup(role),k=card(f,'Kaust, Eyes of the Glade'),c=card(f,'Grizzly Bears','hand');await f.game.putFaceDown(f.a,c,'manifest');c.attacking=f.b;await activate(f,k);assert.equal(c.faceDown,false);const n=f.a.hand.length;await f.game.damageAny(c,f.b,2,{combat:true});await settle(f.game);assert.equal(f.a.hand.length,n+1);});
 test(`${role}: Fourth Doctor plays top historic cards once and rejects stale offers`,async()=>{const f=setup(role),d=card(f,'The Fourth Doctor'),c=card(f,'Sol Ring','library');fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c&&r.alt.wlmKind==='fourth');assert.ok(offer);await f.game.move(d,'hand');assert.equal(await f.game.castSpell(f.a,c,{from:'library',alt:offer.alt}),false);await f.game.putPermanentOntoBattlefield(d,f.a);const next=f.game.castableList(f.a).find(r=>r.card===c&&r.alt.wlmKind==='fourth');assert.ok(next);assert.equal(await f.game.castSpell(f.a,c,{from:'library',alt:next.alt}),true);await settle(f.game);assert.equal(count(f,'Food'),1);const a=card(f,'Arcane Signet','library');assert.ok(!f.game.castableList(f.a).some(r=>r.card===a));});
 test(`${role}: Eighth Doctor exile-on-leave applies only to the played object`,async()=>{const f=setup(role);card(f,'The Eighth Doctor');const c=card(f,'Sol Ring','graveyard');fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c&&r.alt.wlmKind==='eighth');assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:offer.alt}),true);await settle(f.game);await f.game.move(c,'hand');assert.equal(c.zone,'exile');await f.game.putPermanentOntoBattlefield(c,f.a);await f.game.move(c,'hand');assert.equal(c.zone,'hand');});
 test(`${role}: Me retains counters through exile and graveyard but clears in hand`,async()=>{const f=setup(role),c=card(f,'Me, the Immortal');f.game.addCounters(c,'vigilance',1);await f.game.move(c,'graveyard');assert.equal(c.counters.vigilance,1);await f.game.move(c,'exile');assert.equal(c.counters.vigilance,1);await f.game.putPermanentOntoBattlefield(c,f.a);assert.ok(c.kw('vigilance'));await f.game.move(c,'hand');assert.equal(c.counters.vigilance||0,0);});
 test(`${role}: Me pays two distinct hand cards, never a free graveyard cast`,async()=>{const f=setup(role),c=card(f,'Me, the Immortal','graveyard');fuel(f.a);assert.ok(!f.game.castableList(f.a).some(r=>r.card===c));const a=card(f,'Forest','hand'),b=card(f,'Island','hand'),n=mana(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:offer.alt}),true);await settle(f.game);assert.equal(a.zone,'graveyard');assert.equal(b.zone,'graveyard');assert.ok(mana(f.a)<n);});
 test(`${role}: Lunar escape exiles a land and five other graveyard cards`,async()=>{const f=setup(role),c=card(f,'Lunar Hatchling','graveyard'),land=card(f,'Forest');const costs=Array.from({length:5},()=>card(f,'Forest','graveyard'));fuel(f.a);const offer=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(offer);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:offer.alt}),true);await settle(f.game);assert.equal(land.zone,'exile');assert.ok(costs.every(c=>c.zone==='exile'));assert.equal(c.zone,'battlefield');});
 test(`${role}: temporary escape grants expire and reject altered costs`,async()=>{const f=setup(role),d=card(f,'Confession Dial'),c=card(f,'Mirko, Obsessive Theorist','graveyard');Array.from({length:3},()=>card(f,'Forest','graveyard'));await activate(f,d);fuel(f.a);const r=f.game.castableList(f.a).find(r=>r.card===c);assert.ok(r);assert.equal(await f.game.castSpell(f.a,c,{from:'graveyard',alt:{...r.alt,free:true}}),false);f.game.turnNo++;assert.ok(!f.game.castableList(f.a).some(r=>r.card===c));});
 test(`${role}: discover may put the revealed nonland in hand, remaining lands go to bottom`,async()=>{const f=setup(role),s=body(f),hit=card(f,'Arcane Signet','library');const l=card(f,'Forest','library');f.decide=(p,q)=>q.type==='chooseCards'&&q.prompt.startsWith('You may cast')?[]:undefined;await M.WLM.discover(ctx(f,s),2);assert.equal(hit.zone,'hand');assert.equal(l.zone,'library');assert.equal(f.a.library[0],l);});
 test(`${role}: Displaced Dinosaurs changes copiable base stats before ETB`,async()=>{const f=setup(role);card(f,'Displaced Dinosaurs');const c=await play(f,'Sol Ring');assert.ok(c.is('Artifact')&&c.is('Creature')&&c.hasSub('Dinosaur'));assert.equal(c.power,7);assert.equal(c.toughness,7);const [copy]=await f.game.makeTokens(M.WLM.snapshotCopy(c),f.a);assert.equal(copy.power,7);});
 test(`${role}: Cyber Conversion removes printed abilities and does not grant manifest face-up`,async()=>{const f=setup(role),c=body(f,f.b);await play(f,'Cyber Conversion');assert.ok(c.faceDown&&c.is('Artifact')&&c.hasSub('Cyberman'));assert.equal(c.power,2);assert.equal(f.game.faceUpCosts(c).length,0);});
 test(`${role}: Veiled Ascension gives a flying counter on entry before turn-face-up`,async()=>{const f=setup(role);card(f,'Veiled Ascension');const c=card(f,'Grizzly Bears','hand');await f.game.putFaceDown(f.a,c,'cloak');assert.equal(c.counters.flying,1);assert.ok(c.kw('flying'));await M.WLM.forceFaceUp(ctx(f,c),c);assert.ok(c.kw('flying'));});
 test(`${role}: Barbara read ahead skips earlier Saga chapters`,async()=>{const f=setup(role);card(f,'Barbara Wright');option(f,'3');const before=f.a.hand.length;await play(f,'The Caves of Androzani');assert.equal(f.a.hand.length,before);assert.equal(f.game.bf().find(c=>c.name==='The Caves of Androzani').counters.lore,3);});
 test(`${role}: counter doublers and Danny Pink see one first counter event`,async()=>{const f=setup(role),c=body(f);card(f,'Danny Pink');card(f,'Branching Evolution');const n=f.a.hand.length;f.game.addCounters(c,'+1/+1',1);f.game.addCounters(c,'vigilance',1);await settle(f.game);assert.equal(c.counters['+1/+1'],2);assert.equal(f.a.hand.length,n+1);});
 test(`${role}: Skeleton Crew triggers once for a graveyard departure batch`,async()=>{const f=setup(role);card(f,'Skeleton Crew');const a=card(f,'Grizzly Bears','graveyard'),b=card(f,'Dusk Legion Zealot','graveyard');await f.game.moveGraveyardBatch([a,b],'exile');await settle(f.game);assert.equal(count(f,'Skeleton Pirate'),1);});
 test(`${role}: Skeleton Crew can activate from graveyard and returns tapped`,async()=>{const f=setup(role),c=card(f,'Skeleton Crew','graveyard');await activate(f,c,e=>e.gyAbility);assert.equal(c.zone,'battlefield');assert.ok(c.tapped);});
 test(`${role}: Animate Dead targets either graveyard and sacrifices its exact linked creature on leaving`,async()=>{const f=setup(role),c=card(f,'Grizzly Bears','graveyard',f.b),a=await play(f,'Animate Dead');assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);assert.equal(c.power,1);assert.equal(a.attachedTo,c.iid);await f.game.move(a,'exile');await settle(f.game);assert.equal(c.zone,'graveyard');});
 test(`${role}: Necromancy attaches and its removal sacrifices the reanimated creature`,async()=>{const f=setup(role),c=card(f,'Grizzly Bears','graveyard',f.b),a=await play(f,'Necromancy');assert.equal(c.zone,'battlefield');assert.equal(c.ctrl,f.a);assert.equal(a.attachedTo,c.iid);await f.game.move(a,'exile');await settle(f.game);assert.equal(c.zone,'graveyard');});
 test(`${role}: Jinnie Fay replaces only its controller's tokens`,async()=>{const f=setup(role);card(f,"Jinnie Fay, Jetmir's Second");option(f,'dog');await f.game.makeTokens(M.TOKENS.treasure,f.a,{n:2});assert.equal(count(f,'Dog'),2);await f.game.makeTokens(M.TOKENS.treasure,f.b);assert.equal(count(f,'Treasure'),1);});
 test(`${role}: Quartzwood sums simultaneous trample damage to each player`,async()=>{const f=setup(role),q=card(f,'Quartzwood Crasher'),b=body(f);M.WLM.grant(ctx(f,q),b,['trample'],'eot');await f.game.damageBatch([{src:q,target:f.b,n:3},{src:b,target:f.b,n:2}],{combat:true});await settle(f.game);const cs=f.game.bf().filter(c=>c.name.replace(/ Token$/,'')==='Dinosaur Beast');assert.equal(cs.length,1);assert.equal(cs[0].power,5);});
 test(`${role}: Malcolm groups simultaneous Pirate damage`,async()=>{const f=setup(role),a=card(f,'Malcolm, Keen-Eyed Navigator'),b=card(f,'Storm Fleet Negotiator');await f.game.damageBatch([{src:a,target:f.b,n:1},{src:b,target:f.b,n:1}],{combat:true});await settle(f.game);assert.equal(count(f,'Treasure'),1);});
 test(`${role}: Become the Pilot changes controller and releases on removal`,async()=>{const f=setup(role),c=body(f,f.b),a=await play(f,'Become the Pilot');assert.equal(c.ctrl,f.a);assert.equal(c.power,4);await f.game.move(a,'exile');f.game.recalc();assert.equal(c.ctrl,f.b);});
 test(`${role}: The Second Doctor removes all hand limits; Nyssa only yours`,async()=>{const f=setup(role),c=card(f,'The Second Doctor');assert.equal(f.game.maximumHandSize(f.b),Infinity);await f.game.move(c,'graveyard');card(f,'Nyssa of Traken');assert.equal(f.game.maximumHandSize(f.a),Infinity);assert.equal(f.game.maximumHandSize(f.b),7);});
 test(`${role}: Timestream Navigator bottoms itself as a cost`,async()=>{const f=setup(role),c=card(f,'Timestream Navigator');f.a.cityBlessing=true;await activate(f,c);assert.equal(c.zone,'library');assert.equal(f.a.library[0],c);assert.ok(f.game._extraTurns?.length||f.game.extraTurns?.length);});
}
