// Generated by node scripts/sync-landing-counts.mjs after catalog changes.
'use strict';
var MTG = globalThis.MTG || (globalThis.MTG = {});
MTG.CATALOG_SUMMARY = Object.freeze({"decks":150,"importableCards":21541});
